CREATE TABLE plate_codes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(5) NOT NULL UNIQUE,
    region VARCHAR(100) NOT NULL
);

INSERT INTO plate_codes (code, region) VALUES
('A', 'Banten'),
('AA', 'Magelang (Jawa Tengah)'),
('AB', 'Yogyakarta (DIY)'),
('AD', 'Surakarta (Jawa Tengah)'),
('AE', 'Madiun (Jawa Timur)'),
('AG', 'Kediri (Jawa Timur)'),
('B', 'Jakarta (DKI)'),
('BA', 'Sumatera Barat'),
('BB', 'Sumatera Utara (Tebing Tinggi)'),
('BD', 'Bengkulu'),
('BE', 'Lampung'),
('BG', 'Sumatera Selatan'),
('BH', 'Jambi'),
('BK', 'Sumatera Utara (Medan)'),
('BL', 'Aceh'),
('BM', 'Riau (Pekanbaru)'),
('BN', 'Kepulauan Riau (Batam)'),
('BP', 'Bangka Belitung'),
('D', 'Bandung (Jawa Barat)'),
('DA', 'Kalimantan Selatan'),
('DB', 'Sulawesi Utara'),
('DC', 'Sulawesi Barat'),
('DD', 'Sulawesi Selatan'),
('DE', 'Maluku'),
('DG', 'Maluku Utara'),
('DK', 'Bali'),
('DM', 'Gorontalo'),
('DN', 'Sulawesi Tengah'),
('DT', 'Sulawesi Tenggara'),
('E', 'Cirebon (Jawa Barat)'),
('EA', 'Nusa Tenggara Barat'),
('EB', 'Nusa Tenggara Timur'),
('F', 'Bogor (Jawa Barat)'),
('G', 'Tegal (Jawa Tengah)'),
('H', 'Semarang (Jawa Tengah)'),
('K', 'Pati (Jawa Tengah)'),
('KB', 'Kalimantan Barat'),
('KH', 'Kalimantan Tengah'),
('KT', 'Kalimantan Timur'),
('KU', 'Kalimantan Utara'),
('L', 'Surabaya (Jawa Timur)'),
('M', 'Madura (Jawa Timur)'),
('N', 'Malang (Jawa Timur)'),
('P', 'Jember (Jawa Timur)'),
('PA', 'Papua'),
('PB', 'Papua Barat'),
('R', 'Banyumas (Jawa Tengah)'),
('S', 'Bojonegoro (Jawa Timur)'),
('W', 'Sidoarjo (Jawa Timur)');