CREATE TABLE dealers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    brand VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    city VARCHAR(100) NOT NULL,
    province VARCHAR(100) NOT NULL,
    type VARCHAR(10) NOT NULL
);

INSERT INTO dealers (brand, name, city, province, type) VALUES
('Toyota', 'Auto2000 Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Toyota', 'Auto2000 Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Toyota', 'Auto2000 Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Toyota', 'Auto2000 Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Toyota', 'Auto2000 Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Toyota', 'Auto2000 Cempaka Putih', 'Jakarta', 'DKI Jakarta', '3S'),
('Toyota', 'Auto2000 Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Toyota', 'Auto2000 Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Toyota', 'Auto2000 Depok', 'Depok', 'Jawa Barat', '3S'),
('Toyota', 'Auto2000 Tangerang', 'Tangerang', 'Banten', '3S'),
('Toyota', 'Auto2000 Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Toyota', 'Auto2000 Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Toyota', 'Auto2000 Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Toyota', 'Auto2000 Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Toyota', 'Auto2000 Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Toyota', 'Auto2000 Malang', 'Malang', 'Jawa Timur', '3S'),
('Toyota', 'Auto2000 Denpasar', 'Denpasar', 'Bali', '3S'),
('Toyota', 'Auto2000 Medan', 'Medan', 'Sumatera Utara', '3S'),
('Toyota', 'Auto2000 Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Toyota', 'Auto2000 Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Toyota', 'Auto2000 Padang', 'Padang', 'Sumatera Barat', '3S'),
('Toyota', 'Auto2000 Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Toyota', 'Auto2000 Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Toyota', 'Auto2000 Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Toyota', 'Auto2000 Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Toyota', 'Auto2000 Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Toyota', 'Auto2000 Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Toyota', 'Auto2000 Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Toyota', 'Auto2000 Jayapura', 'Jayapura', 'Papua', '3S'),
('Toyota', 'Auto2000 Ambon', 'Ambon', 'Maluku', '3S'),
('Toyota', 'Auto2000 Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Toyota', 'Auto2000 Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Toyota', 'Auto2000 Manokwari', 'Manokwari', 'Papua Barat', '3S'),
('Toyota', 'Auto2000 Sorong', 'Sorong', 'Papua Barat Daya', '3S'),
('Toyota', 'Auto2000 Ternate', 'Ternate', 'Maluku Utara', '3S'),
('Toyota', 'Auto2000 Gorontalo', 'Gorontalo', 'Gorontalo', '3S'),
('Toyota', 'Auto2000 Palu', 'Palu', 'Sulawesi Tengah', '3S'),
('Toyota', 'Auto2000 Kendari', 'Kendari', 'Sulawesi Tenggara', '3S'),
('Toyota', 'Auto2000 Mamuju', 'Mamuju', 'Sulawesi Barat', '3S'),
('Toyota', 'Auto2000 Tanjung Pinang', 'Tanjung Pinang', 'Kepulauan Riau', '3S'),
('Toyota', 'Auto2000 Batam', 'Batam', 'Kepulauan Riau', '3S'),
('Toyota', 'Auto2000 Pangkal Pinang', 'Pangkal Pinang', 'Bangka Belitung', '3S'),
('Toyota', 'Auto2000 Bengkulu', 'Bengkulu', 'Bengkulu', '3S'),
('Toyota', 'Auto2000 Jambi', 'Jambi', 'Jambi', '3S'),
('Toyota', 'Auto2000 Banda Aceh', 'Banda Aceh', 'Aceh', '3S'),
('Toyota', 'Auto2000 Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Toyota', 'Auto2000 Tasikmalaya', 'Tasikmalaya', 'Jawa Barat', '3S'),
('Toyota', 'Auto2000 Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Toyota', 'Auto2000 Purwokerto', 'Purwokerto', 'Jawa Tengah', '3S'),
('Toyota', 'Auto2000 Tegal', 'Tegal', 'Jawa Tengah', '3S'),
('Toyota', 'Auto2000 Kediri', 'Kediri', 'Jawa Timur', '3S'),
('Toyota', 'Auto2000 Jember', 'Jember', 'Jawa Timur', '3S'),
('Toyota', 'Auto2000 Sidoarjo', 'Sidoarjo', 'Jawa Timur', '3S'),
('Toyota', 'Auto2000 Gresik', 'Gresik', 'Jawa Timur', '3S'),
('Toyota', 'Auto2000 Madiun', 'Madiun', 'Jawa Timur', '3S'),
('Daihatsu', 'Astra Daihatsu Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Daihatsu', 'Astra Daihatsu Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Daihatsu', 'Astra Daihatsu Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Daihatsu', 'Astra Daihatsu Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Daihatsu', 'Astra Daihatsu Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Daihatsu', 'Astra Daihatsu Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Daihatsu', 'Astra Daihatsu Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Daihatsu', 'Astra Daihatsu Depok', 'Depok', 'Jawa Barat', '3S'),
('Daihatsu', 'Astra Daihatsu Tangerang', 'Tangerang', 'Banten', '3S'),
('Daihatsu', 'Astra Daihatsu Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Daihatsu', 'Astra Daihatsu Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Daihatsu', 'Astra Daihatsu Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Daihatsu', 'Astra Daihatsu Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Daihatsu', 'Astra Daihatsu Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Daihatsu', 'Astra Daihatsu Malang', 'Malang', 'Jawa Timur', '3S'),
('Daihatsu', 'Astra Daihatsu Denpasar', 'Denpasar', 'Bali', '3S'),
('Daihatsu', 'Astra Daihatsu Medan', 'Medan', 'Sumatera Utara', '3S'),
('Daihatsu', 'Astra Daihatsu Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Daihatsu', 'Astra Daihatsu Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Daihatsu', 'Astra Daihatsu Padang', 'Padang', 'Sumatera Barat', '3S'),
('Daihatsu', 'Astra Daihatsu Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Daihatsu', 'Astra Daihatsu Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Daihatsu', 'Astra Daihatsu Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Daihatsu', 'Astra Daihatsu Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Daihatsu', 'Astra Daihatsu Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Daihatsu', 'Astra Daihatsu Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Daihatsu', 'Astra Daihatsu Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Daihatsu', 'Astra Daihatsu Jayapura', 'Jayapura', 'Papua', '3S'),
('Daihatsu', 'Astra Daihatsu Ambon', 'Ambon', 'Maluku', '3S'),
('Daihatsu', 'Astra Daihatsu Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Daihatsu', 'Astra Daihatsu Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Daihatsu', 'Astra Daihatsu Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Daihatsu', 'Astra Daihatsu Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Daihatsu', 'Astra Daihatsu Purwokerto', 'Purwokerto', 'Jawa Tengah', '3S'),
('Daihatsu', 'Astra Daihatsu Kediri', 'Kediri', 'Jawa Timur', '3S'),
('Daihatsu', 'Astra Daihatsu Jember', 'Jember', 'Jawa Timur', '3S'),
('Daihatsu', 'Astra Daihatsu Sidoarjo', 'Sidoarjo', 'Jawa Timur', '3S'),
('Honda', 'Honda Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Honda', 'Honda Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Honda', 'Honda Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Honda', 'Honda Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Honda', 'Honda Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Honda', 'Honda Cempaka Putih', 'Jakarta', 'DKI Jakarta', '3S'),
('Honda', 'Honda Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Honda', 'Honda Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Honda', 'Honda Depok', 'Depok', 'Jawa Barat', '3S'),
('Honda', 'Honda Tangerang', 'Tangerang', 'Banten', '3S'),
('Honda', 'Honda Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Honda', 'Honda Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Honda', 'Honda Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Honda', 'Honda Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Honda', 'Honda Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Honda', 'Honda Malang', 'Malang', 'Jawa Timur', '3S'),
('Honda', 'Honda Denpasar', 'Denpasar', 'Bali', '3S'),
('Honda', 'Honda Medan', 'Medan', 'Sumatera Utara', '3S'),
('Honda', 'Honda Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Honda', 'Honda Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Honda', 'Honda Padang', 'Padang', 'Sumatera Barat', '3S'),
('Honda', 'Honda Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Honda', 'Honda Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Honda', 'Honda Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Honda', 'Honda Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Honda', 'Honda Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Honda', 'Honda Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Honda', 'Honda Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Honda', 'Honda Jayapura', 'Jayapura', 'Papua', '3S'),
('Honda', 'Honda Ambon', 'Ambon', 'Maluku', '3S'),
('Honda', 'Honda Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Honda', 'Honda Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Honda', 'Honda Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Honda', 'Honda Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Honda', 'Honda Purwokerto', 'Purwokerto', 'Jawa Tengah', '3S'),
('Honda', 'Honda Kediri', 'Kediri', 'Jawa Timur', '3S'),
('Honda', 'Honda Jember', 'Jember', 'Jawa Timur', '3S'),
('Honda', 'Honda Sidoarjo', 'Sidoarjo', 'Jawa Timur', '3S'),
('Mitsubishi', 'Mitsubishi Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Mitsubishi', 'Mitsubishi Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Mitsubishi', 'Mitsubishi Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Mitsubishi', 'Mitsubishi Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Mitsubishi', 'Mitsubishi Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Mitsubishi', 'Mitsubishi Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Mitsubishi', 'Mitsubishi Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Mitsubishi', 'Mitsubishi Depok', 'Depok', 'Jawa Barat', '3S'),
('Mitsubishi', 'Mitsubishi Tangerang', 'Tangerang', 'Banten', '3S'),
('Mitsubishi', 'Mitsubishi Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Mitsubishi', 'Mitsubishi Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Mitsubishi', 'Mitsubishi Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Mitsubishi', 'Mitsubishi Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Mitsubishi', 'Mitsubishi Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Mitsubishi', 'Mitsubishi Malang', 'Malang', 'Jawa Timur', '3S'),
('Mitsubishi', 'Mitsubishi Denpasar', 'Denpasar', 'Bali', '3S'),
('Mitsubishi', 'Mitsubishi Medan', 'Medan', 'Sumatera Utara', '3S'),
('Mitsubishi', 'Mitsubishi Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Mitsubishi', 'Mitsubishi Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Mitsubishi', 'Mitsubishi Padang', 'Padang', 'Sumatera Barat', '3S'),
('Mitsubishi', 'Mitsubishi Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Mitsubishi', 'Mitsubishi Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Mitsubishi', 'Mitsubishi Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Mitsubishi', 'Mitsubishi Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Mitsubishi', 'Mitsubishi Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Mitsubishi', 'Mitsubishi Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Mitsubishi', 'Mitsubishi Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Mitsubishi', 'Mitsubishi Jayapura', 'Jayapura', 'Papua', '3S'),
('Mitsubishi', 'Mitsubishi Ambon', 'Ambon', 'Maluku', '3S'),
('Mitsubishi', 'Mitsubishi Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Mitsubishi', 'Mitsubishi Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Mitsubishi', 'Mitsubishi Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Mitsubishi', 'Mitsubishi Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Mitsubishi', 'Mitsubishi Purwokerto', 'Purwokerto', 'Jawa Tengah', '3S'),
('Mitsubishi', 'Mitsubishi Kediri', 'Kediri', 'Jawa Timur', '3S'),
('Mitsubishi', 'Mitsubishi Jember', 'Jember', 'Jawa Timur', '3S'),
('Mitsubishi', 'Mitsubishi Sidoarjo', 'Sidoarjo', 'Jawa Timur', '3S'),
('Suzuki', 'Suzuki Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Suzuki', 'Suzuki Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Suzuki', 'Suzuki Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Suzuki', 'Suzuki Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Suzuki', 'Suzuki Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Suzuki', 'Suzuki Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Suzuki', 'Suzuki Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Suzuki', 'Suzuki Depok', 'Depok', 'Jawa Barat', '3S'),
('Suzuki', 'Suzuki Tangerang', 'Tangerang', 'Banten', '3S'),
('Suzuki', 'Suzuki Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Suzuki', 'Suzuki Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Suzuki', 'Suzuki Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Suzuki', 'Suzuki Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Suzuki', 'Suzuki Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Suzuki', 'Suzuki Malang', 'Malang', 'Jawa Timur', '3S'),
('Suzuki', 'Suzuki Denpasar', 'Denpasar', 'Bali', '3S'),
('Suzuki', 'Suzuki Medan', 'Medan', 'Sumatera Utara', '3S'),
('Suzuki', 'Suzuki Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Suzuki', 'Suzuki Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Suzuki', 'Suzuki Padang', 'Padang', 'Sumatera Barat', '3S'),
('Suzuki', 'Suzuki Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Suzuki', 'Suzuki Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Suzuki', 'Suzuki Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Suzuki', 'Suzuki Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Suzuki', 'Suzuki Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Suzuki', 'Suzuki Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Suzuki', 'Suzuki Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Suzuki', 'Suzuki Jayapura', 'Jayapura', 'Papua', '3S'),
('Suzuki', 'Suzuki Ambon', 'Ambon', 'Maluku', '3S'),
('Suzuki', 'Suzuki Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Suzuki', 'Suzuki Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Suzuki', 'Suzuki Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Suzuki', 'Suzuki Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Suzuki', 'Suzuki Purwokerto', 'Purwokerto', 'Jawa Tengah', '3S'),
('Suzuki', 'Suzuki Kediri', 'Kediri', 'Jawa Timur', '3S'),
('Suzuki', 'Suzuki Jember', 'Jember', 'Jawa Timur', '3S'),
('Suzuki', 'Suzuki Sidoarjo', 'Sidoarjo', 'Jawa Timur', '3S'),
('Nissan', 'Nissan Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Nissan', 'Nissan Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Nissan', 'Nissan Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Nissan', 'Nissan Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Nissan', 'Nissan Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Nissan', 'Nissan Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Nissan', 'Nissan Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Nissan', 'Nissan Depok', 'Depok', 'Jawa Barat', '3S'),
('Nissan', 'Nissan Tangerang', 'Tangerang', 'Banten', '3S'),
('Nissan', 'Nissan Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Nissan', 'Nissan Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Nissan', 'Nissan Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Nissan', 'Nissan Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Nissan', 'Nissan Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Nissan', 'Nissan Malang', 'Malang', 'Jawa Timur', '3S'),
('Nissan', 'Nissan Denpasar', 'Denpasar', 'Bali', '3S'),
('Nissan', 'Nissan Medan', 'Medan', 'Sumatera Utara', '3S'),
('Nissan', 'Nissan Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Nissan', 'Nissan Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Nissan', 'Nissan Padang', 'Padang', 'Sumatera Barat', '3S'),
('Nissan', 'Nissan Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Nissan', 'Nissan Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Nissan', 'Nissan Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Nissan', 'Nissan Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Nissan', 'Nissan Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Nissan', 'Nissan Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Nissan', 'Nissan Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Nissan', 'Nissan Jayapura', 'Jayapura', 'Papua', '3S'),
('Nissan', 'Nissan Ambon', 'Ambon', 'Maluku', '3S'),
('Nissan', 'Nissan Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Nissan', 'Nissan Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Nissan', 'Nissan Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Nissan', 'Nissan Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Nissan', 'Nissan Purwokerto', 'Purwokerto', 'Jawa Tengah', '3S'),
('Nissan', 'Nissan Kediri', 'Kediri', 'Jawa Timur', '3S'),
('Nissan', 'Nissan Jember', 'Jember', 'Jawa Timur', '3S'),
('Nissan', 'Nissan Sidoarjo', 'Sidoarjo', 'Jawa Timur', '3S'),
('Mazda', 'Mazda Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Mazda', 'Mazda Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Mazda', 'Mazda Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Mazda', 'Mazda Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Mazda', 'Mazda Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Mazda', 'Mazda Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Mazda', 'Mazda Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Mazda', 'Mazda Depok', 'Depok', 'Jawa Barat', '3S'),
('Mazda', 'Mazda Tangerang', 'Tangerang', 'Banten', '3S'),
('Mazda', 'Mazda Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Mazda', 'Mazda Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Mazda', 'Mazda Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Mazda', 'Mazda Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Mazda', 'Mazda Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Mazda', 'Mazda Malang', 'Malang', 'Jawa Timur', '3S'),
('Mazda', 'Mazda Denpasar', 'Denpasar', 'Bali', '3S'),
('Mazda', 'Mazda Medan', 'Medan', 'Sumatera Utara', '3S'),
('Mazda', 'Mazda Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Mazda', 'Mazda Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Mazda', 'Mazda Padang', 'Padang', 'Sumatera Barat', '3S'),
('Mazda', 'Mazda Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Mazda', 'Mazda Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Mazda', 'Mazda Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Mazda', 'Mazda Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Mazda', 'Mazda Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Mazda', 'Mazda Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Mazda', 'Mazda Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Mazda', 'Mazda Jayapura', 'Jayapura', 'Papua', '3S'),
('Mazda', 'Mazda Ambon', 'Ambon', 'Maluku', '3S'),
('Mazda', 'Mazda Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Mazda', 'Mazda Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Mazda', 'Mazda Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Mazda', 'Mazda Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Wuling', 'Wuling Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Wuling', 'Wuling Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Wuling', 'Wuling Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Wuling', 'Wuling Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Wuling', 'Wuling Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Wuling', 'Wuling Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Wuling', 'Wuling Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Wuling', 'Wuling Depok', 'Depok', 'Jawa Barat', '3S'),
('Wuling', 'Wuling Tangerang', 'Tangerang', 'Banten', '3S'),
('Wuling', 'Wuling Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Wuling', 'Wuling Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Wuling', 'Wuling Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Wuling', 'Wuling Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Wuling', 'Wuling Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Wuling', 'Wuling Malang', 'Malang', 'Jawa Timur', '3S'),
('Wuling', 'Wuling Denpasar', 'Denpasar', 'Bali', '3S'),
('Wuling', 'Wuling Medan', 'Medan', 'Sumatera Utara', '3S'),
('Wuling', 'Wuling Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Wuling', 'Wuling Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Wuling', 'Wuling Padang', 'Padang', 'Sumatera Barat', '3S'),
('Wuling', 'Wuling Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Wuling', 'Wuling Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Wuling', 'Wuling Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Wuling', 'Wuling Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Wuling', 'Wuling Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Wuling', 'Wuling Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Wuling', 'Wuling Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Wuling', 'Wuling Jayapura', 'Jayapura', 'Papua', '3S'),
('Wuling', 'Wuling Ambon', 'Ambon', 'Maluku', '3S'),
('Wuling', 'Wuling Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Wuling', 'Wuling Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Wuling', 'Wuling Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Wuling', 'Wuling Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Wuling', 'Wuling Purwokerto', 'Purwokerto', 'Jawa Tengah', '3S'),
('Wuling', 'Wuling Kediri', 'Kediri', 'Jawa Timur', '3S'),
('Wuling', 'Wuling Jember', 'Jember', 'Jawa Timur', '3S'),
('Wuling', 'Wuling Sidoarjo', 'Sidoarjo', 'Jawa Timur', '3S'),
('Hyundai', 'Hyundai Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Hyundai', 'Hyundai Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Hyundai', 'Hyundai Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Hyundai', 'Hyundai Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Hyundai', 'Hyundai Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Hyundai', 'Hyundai Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Hyundai', 'Hyundai Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Hyundai', 'Hyundai Depok', 'Depok', 'Jawa Barat', '3S'),
('Hyundai', 'Hyundai Tangerang', 'Tangerang', 'Banten', '3S'),
('Hyundai', 'Hyundai Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Hyundai', 'Hyundai Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Hyundai', 'Hyundai Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Hyundai', 'Hyundai Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Hyundai', 'Hyundai Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Hyundai', 'Hyundai Malang', 'Malang', 'Jawa Timur', '3S'),
('Hyundai', 'Hyundai Denpasar', 'Denpasar', 'Bali', '3S'),
('Hyundai', 'Hyundai Medan', 'Medan', 'Sumatera Utara', '3S'),
('Hyundai', 'Hyundai Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Hyundai', 'Hyundai Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Hyundai', 'Hyundai Padang', 'Padang', 'Sumatera Barat', '3S'),
('Hyundai', 'Hyundai Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Hyundai', 'Hyundai Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Hyundai', 'Hyundai Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Hyundai', 'Hyundai Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Hyundai', 'Hyundai Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Hyundai', 'Hyundai Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Hyundai', 'Hyundai Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Hyundai', 'Hyundai Jayapura', 'Jayapura', 'Papua', '3S'),
('Hyundai', 'Hyundai Ambon', 'Ambon', 'Maluku', '3S'),
('Hyundai', 'Hyundai Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Hyundai', 'Hyundai Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Hyundai', 'Hyundai Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Hyundai', 'Hyundai Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Hyundai', 'Hyundai Purwokerto', 'Purwokerto', 'Jawa Tengah', '3S'),
('Hyundai', 'Hyundai Kediri', 'Kediri', 'Jawa Timur', '3S'),
('Hyundai', 'Hyundai Jember', 'Jember', 'Jawa Timur', '3S'),
('Hyundai', 'Hyundai Sidoarjo', 'Sidoarjo', 'Jawa Timur', '3S'),
('Kia', 'Kia Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Kia', 'Kia Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Kia', 'Kia Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Kia', 'Kia Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Kia', 'Kia Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Kia', 'Kia Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Kia', 'Kia Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Kia', 'Kia Depok', 'Depok', 'Jawa Barat', '3S'),
('Kia', 'Kia Tangerang', 'Tangerang', 'Banten', '3S'),
('Kia', 'Kia Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Kia', 'Kia Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Kia', 'Kia Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Kia', 'Kia Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Kia', 'Kia Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Kia', 'Kia Malang', 'Malang', 'Jawa Timur', '3S'),
('Kia', 'Kia Denpasar', 'Denpasar', 'Bali', '3S'),
('Kia', 'Kia Medan', 'Medan', 'Sumatera Utara', '3S'),
('Kia', 'Kia Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Kia', 'Kia Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Kia', 'Kia Padang', 'Padang', 'Sumatera Barat', '3S'),
('Kia', 'Kia Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Kia', 'Kia Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Kia', 'Kia Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Kia', 'Kia Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Kia', 'Kia Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Kia', 'Kia Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Kia', 'Kia Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Kia', 'Kia Jayapura', 'Jayapura', 'Papua', '3S'),
('Kia', 'Kia Ambon', 'Ambon', 'Maluku', '3S'),
('Kia', 'Kia Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Kia', 'Kia Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Kia', 'Kia Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Kia', 'Kia Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('BMW', 'BMW Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('BMW', 'BMW Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('BMW', 'BMW Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('BMW', 'BMW Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('BMW', 'BMW Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('BMW', 'BMW Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('BMW', 'BMW Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('BMW', 'BMW Depok', 'Depok', 'Jawa Barat', '3S'),
('BMW', 'BMW Tangerang', 'Tangerang', 'Banten', '3S'),
('BMW', 'BMW Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('BMW', 'BMW Bandung', 'Bandung', 'Jawa Barat', '3S'),
('BMW', 'BMW Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('BMW', 'BMW Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('BMW', 'BMW Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('BMW', 'BMW Malang', 'Malang', 'Jawa Timur', '3S'),
('BMW', 'BMW Denpasar', 'Denpasar', 'Bali', '3S'),
('BMW', 'BMW Medan', 'Medan', 'Sumatera Utara', '3S'),
('BMW', 'BMW Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('BMW', 'BMW Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('BMW', 'BMW Padang', 'Padang', 'Sumatera Barat', '3S'),
('BMW', 'BMW Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('BMW', 'BMW Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('BMW', 'BMW Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('BMW', 'BMW Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('BMW', 'BMW Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('BMW', 'BMW Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('BMW', 'BMW Manado', 'Manado', 'Sulawesi Utara', '3S'),
('BMW', 'BMW Jayapura', 'Jayapura', 'Papua', '3S'),
('BMW', 'BMW Ambon', 'Ambon', 'Maluku', '3S'),
('BMW', 'BMW Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('BMW', 'BMW Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('BMW', 'BMW Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('BMW', 'BMW Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Depok', 'Depok', 'Jawa Barat', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Tangerang', 'Tangerang', 'Banten', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Malang', 'Malang', 'Jawa Timur', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Denpasar', 'Denpasar', 'Bali', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Medan', 'Medan', 'Sumatera Utara', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Padang', 'Padang', 'Sumatera Barat', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Jayapura', 'Jayapura', 'Papua', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Ambon', 'Ambon', 'Maluku', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Mercedes-Benz', 'Mercedes-Benz Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Audi', 'Audi Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Audi', 'Audi Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Audi', 'Audi Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Audi', 'Audi Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Audi', 'Audi Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Audi', 'Audi Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Audi', 'Audi Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Audi', 'Audi Depok', 'Depok', 'Jawa Barat', '3S'),
('Audi', 'Audi Tangerang', 'Tangerang', 'Banten', '3S'),
('Audi', 'Audi Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Audi', 'Audi Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Audi', 'Audi Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Audi', 'Audi Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Audi', 'Audi Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Audi', 'Audi Malang', 'Malang', 'Jawa Timur', '3S'),
('Audi', 'Audi Denpasar', 'Denpasar', 'Bali', '3S'),
('Audi', 'Audi Medan', 'Medan', 'Sumatera Utara', '3S'),
('Audi', 'Audi Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Audi', 'Audi Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Audi', 'Audi Padang', 'Padang', 'Sumatera Barat', '3S'),
('Audi', 'Audi Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Audi', 'Audi Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Audi', 'Audi Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Audi', 'Audi Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Audi', 'Audi Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Audi', 'Audi Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Audi', 'Audi Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Audi', 'Audi Jayapura', 'Jayapura', 'Papua', '3S'),
('Audi', 'Audi Ambon', 'Ambon', 'Maluku', '3S'),
('Audi', 'Audi Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Audi', 'Audi Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Audi', 'Audi Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Audi', 'Audi Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Lexus', 'Lexus Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Lexus', 'Lexus Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Lexus', 'Lexus Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Lexus', 'Lexus Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Lexus', 'Lexus Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Lexus', 'Lexus Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Lexus', 'Lexus Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Lexus', 'Lexus Depok', 'Depok', 'Jawa Barat', '3S'),
('Lexus', 'Lexus Tangerang', 'Tangerang', 'Banten', '3S'),
('Lexus', 'Lexus Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Lexus', 'Lexus Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Lexus', 'Lexus Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Lexus', 'Lexus Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Lexus', 'Lexus Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Lexus', 'Lexus Malang', 'Malang', 'Jawa Timur', '3S'),
('Lexus', 'Lexus Denpasar', 'Denpasar', 'Bali', '3S'),
('Lexus', 'Lexus Medan', 'Medan', 'Sumatera Utara', '3S'),
('Lexus', 'Lexus Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Lexus', 'Lexus Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Lexus', 'Lexus Padang', 'Padang', 'Sumatera Barat', '3S'),
('Lexus', 'Lexus Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Lexus', 'Lexus Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Lexus', 'Lexus Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Lexus', 'Lexus Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Lexus', 'Lexus Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Lexus', 'Lexus Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Lexus', 'Lexus Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Lexus', 'Lexus Jayapura', 'Jayapura', 'Papua', '3S'),
('Lexus', 'Lexus Ambon', 'Ambon', 'Maluku', '3S'),
('Lexus', 'Lexus Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Lexus', 'Lexus Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Lexus', 'Lexus Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Lexus', 'Lexus Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Volvo', 'Volvo Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Volvo', 'Volvo Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Volvo', 'Volvo Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Volvo', 'Volvo Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Volvo', 'Volvo Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Volvo', 'Volvo Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Volvo', 'Volvo Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Volvo', 'Volvo Depok', 'Depok', 'Jawa Barat', '3S'),
('Volvo', 'Volvo Tangerang', 'Tangerang', 'Banten', '3S'),
('Volvo', 'Volvo Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Volvo', 'Volvo Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Volvo', 'Volvo Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Volvo', 'Volvo Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Volvo', 'Volvo Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Volvo', 'Volvo Malang', 'Malang', 'Jawa Timur', '3S'),
('Volvo', 'Volvo Denpasar', 'Denpasar', 'Bali', '3S'),
('Volvo', 'Volvo Medan', 'Medan', 'Sumatera Utara', '3S'),
('Volvo', 'Volvo Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Volvo', 'Volvo Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Volvo', 'Volvo Padang', 'Padang', 'Sumatera Barat', '3S'),
('Volvo', 'Volvo Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Volvo', 'Volvo Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Volvo', 'Volvo Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Volvo', 'Volvo Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Volvo', 'Volvo Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Volvo', 'Volvo Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Volvo', 'Volvo Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Volvo', 'Volvo Jayapura', 'Jayapura', 'Papua', '3S'),
('Volvo', 'Volvo Ambon', 'Ambon', 'Maluku', '3S'),
('Volvo', 'Volvo Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Volvo', 'Volvo Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Volvo', 'Volvo Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Volvo', 'Volvo Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Land Rover', 'Land Rover Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Land Rover', 'Land Rover Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Land Rover', 'Land Rover Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Land Rover', 'Land Rover Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Land Rover', 'Land Rover Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Land Rover', 'Land Rover Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Land Rover', 'Land Rover Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Land Rover', 'Land Rover Depok', 'Depok', 'Jawa Barat', '3S'),
('Land Rover', 'Land Rover Tangerang', 'Tangerang', 'Banten', '3S'),
('Land Rover', 'Land Rover Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Land Rover', 'Land Rover Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Land Rover', 'Land Rover Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Land Rover', 'Land Rover Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Land Rover', 'Land Rover Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Land Rover', 'Land Rover Malang', 'Malang', 'Jawa Timur', '3S'),
('Land Rover', 'Land Rover Denpasar', 'Denpasar', 'Bali', '3S'),
('Land Rover', 'Land Rover Medan', 'Medan', 'Sumatera Utara', '3S'),
('Land Rover', 'Land Rover Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Land Rover', 'Land Rover Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Land Rover', 'Land Rover Padang', 'Padang', 'Sumatera Barat', '3S'),
('Land Rover', 'Land Rover Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Land Rover', 'Land Rover Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Land Rover', 'Land Rover Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Land Rover', 'Land Rover Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Land Rover', 'Land Rover Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Land Rover', 'Land Rover Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Land Rover', 'Land Rover Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Land Rover', 'Land Rover Jayapura', 'Jayapura', 'Papua', '3S'),
('Land Rover', 'Land Rover Ambon', 'Ambon', 'Maluku', '3S'),
('Land Rover', 'Land Rover Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Land Rover', 'Land Rover Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Land Rover', 'Land Rover Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Land Rover', 'Land Rover Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Jaguar', 'Jaguar Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Jaguar', 'Jaguar Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Jaguar', 'Jaguar Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Jaguar', 'Jaguar Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Jaguar', 'Jaguar Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Jaguar', 'Jaguar Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Jaguar', 'Jaguar Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Jaguar', 'Jaguar Depok', 'Depok', 'Jawa Barat', '3S'),
('Jaguar', 'Jaguar Tangerang', 'Tangerang', 'Banten', '3S'),
('Jaguar', 'Jaguar Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Jaguar', 'Jaguar Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Jaguar', 'Jaguar Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Jaguar', 'Jaguar Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Jaguar', 'Jaguar Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Jaguar', 'Jaguar Malang', 'Malang', 'Jawa Timur', '3S'),
('Jaguar', 'Jaguar Denpasar', 'Denpasar', 'Bali', '3S'),
('Jaguar', 'Jaguar Medan', 'Medan', 'Sumatera Utara', '3S'),
('Jaguar', 'Jaguar Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Jaguar', 'Jaguar Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Jaguar', 'Jaguar Padang', 'Padang', 'Sumatera Barat', '3S'),
('Jaguar', 'Jaguar Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Jaguar', 'Jaguar Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Jaguar', 'Jaguar Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Jaguar', 'Jaguar Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Jaguar', 'Jaguar Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Jaguar', 'Jaguar Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Jaguar', 'Jaguar Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Jaguar', 'Jaguar Jayapura', 'Jayapura', 'Papua', '3S'),
('Jaguar', 'Jaguar Ambon', 'Ambon', 'Maluku', '3S'),
('Jaguar', 'Jaguar Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Jaguar', 'Jaguar Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Jaguar', 'Jaguar Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Jaguar', 'Jaguar Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Porsche', 'Porsche Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Porsche', 'Porsche Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Porsche', 'Porsche Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Porsche', 'Porsche Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Porsche', 'Porsche Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Porsche', 'Porsche Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Porsche', 'Porsche Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Porsche', 'Porsche Depok', 'Depok', 'Jawa Barat', '3S'),
('Porsche', 'Porsche Tangerang', 'Tangerang', 'Banten', '3S'),
('Porsche', 'Porsche Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Porsche', 'Porsche Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Porsche', 'Porsche Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Porsche', 'Porsche Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Porsche', 'Porsche Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Porsche', 'Porsche Malang', 'Malang', 'Jawa Timur', '3S'),
('Porsche', 'Porsche Denpasar', 'Denpasar', 'Bali', '3S'),
('Porsche', 'Porsche Medan', 'Medan', 'Sumatera Utara', '3S'),
('Porsche', 'Porsche Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Porsche', 'Porsche Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Porsche', 'Porsche Padang', 'Padang', 'Sumatera Barat', '3S'),
('Porsche', 'Porsche Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Porsche', 'Porsche Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Porsche', 'Porsche Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Porsche', 'Porsche Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Porsche', 'Porsche Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Porsche', 'Porsche Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Porsche', 'Porsche Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Porsche', 'Porsche Jayapura', 'Jayapura', 'Papua', '3S'),
('Porsche', 'Porsche Ambon', 'Ambon', 'Maluku', '3S'),
('Porsche', 'Porsche Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Porsche', 'Porsche Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Porsche', 'Porsche Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Porsche', 'Porsche Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('MINI', 'MINI Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('MINI', 'MINI Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('MINI', 'MINI Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('MINI', 'MINI Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('MINI', 'MINI Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('MINI', 'MINI Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('MINI', 'MINI Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('MINI', 'MINI Depok', 'Depok', 'Jawa Barat', '3S'),
('MINI', 'MINI Tangerang', 'Tangerang', 'Banten', '3S'),
('MINI', 'MINI Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('MINI', 'MINI Bandung', 'Bandung', 'Jawa Barat', '3S'),
('MINI', 'MINI Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('MINI', 'MINI Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('MINI', 'MINI Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('MINI', 'MINI Malang', 'Malang', 'Jawa Timur', '3S'),
('MINI', 'MINI Denpasar', 'Denpasar', 'Bali', '3S'),
('MINI', 'MINI Medan', 'Medan', 'Sumatera Utara', '3S'),
('MINI', 'MINI Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('MINI', 'MINI Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('MINI', 'MINI Padang', 'Padang', 'Sumatera Barat', '3S'),
('MINI', 'MINI Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('MINI', 'MINI Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('MINI', 'MINI Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('MINI', 'MINI Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('MINI', 'MINI Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('MINI', 'MINI Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('MINI', 'MINI Manado', 'Manado', 'Sulawesi Utara', '3S'),
('MINI', 'MINI Jayapura', 'Jayapura', 'Papua', '3S'),
('MINI', 'MINI Ambon', 'Ambon', 'Maluku', '3S'),
('MINI', 'MINI Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('MINI', 'MINI Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('MINI', 'MINI Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('MINI', 'MINI Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Ford', 'Ford Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Ford', 'Ford Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Ford', 'Ford Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Ford', 'Ford Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Ford', 'Ford Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Ford', 'Ford Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Ford', 'Ford Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Ford', 'Ford Depok', 'Depok', 'Jawa Barat', '3S'),
('Ford', 'Ford Tangerang', 'Tangerang', 'Banten', '3S'),
('Ford', 'Ford Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Ford', 'Ford Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Ford', 'Ford Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Ford', 'Ford Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Ford', 'Ford Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Ford', 'Ford Malang', 'Malang', 'Jawa Timur', '3S'),
('Ford', 'Ford Denpasar', 'Denpasar', 'Bali', '3S'),
('Ford', 'Ford Medan', 'Medan', 'Sumatera Utara', '3S'),
('Ford', 'Ford Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Ford', 'Ford Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Ford', 'Ford Padang', 'Padang', 'Sumatera Barat', '3S'),
('Ford', 'Ford Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Ford', 'Ford Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Ford', 'Ford Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Ford', 'Ford Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Ford', 'Ford Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Ford', 'Ford Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Ford', 'Ford Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Ford', 'Ford Jayapura', 'Jayapura', 'Papua', '3S'),
('Ford', 'Ford Ambon', 'Ambon', 'Maluku', '3S'),
('Ford', 'Ford Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Ford', 'Ford Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Ford', 'Ford Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Ford', 'Ford Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Chevrolet', 'Chevrolet Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Chevrolet', 'Chevrolet Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Chevrolet', 'Chevrolet Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Chevrolet', 'Chevrolet Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Chevrolet', 'Chevrolet Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Chevrolet', 'Chevrolet Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Chevrolet', 'Chevrolet Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Chevrolet', 'Chevrolet Depok', 'Depok', 'Jawa Barat', '3S'),
('Chevrolet', 'Chevrolet Tangerang', 'Tangerang', 'Banten', '3S'),
('Chevrolet', 'Chevrolet Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Chevrolet', 'Chevrolet Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Chevrolet', 'Chevrolet Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Chevrolet', 'Chevrolet Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Chevrolet', 'Chevrolet Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Chevrolet', 'Chevrolet Malang', 'Malang', 'Jawa Timur', '3S'),
('Chevrolet', 'Chevrolet Denpasar', 'Denpasar', 'Bali', '3S'),
('Chevrolet', 'Chevrolet Medan', 'Medan', 'Sumatera Utara', '3S'),
('Chevrolet', 'Chevrolet Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Chevrolet', 'Chevrolet Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Chevrolet', 'Chevrolet Padang', 'Padang', 'Sumatera Barat', '3S'),
('Chevrolet', 'Chevrolet Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Chevrolet', 'Chevrolet Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Chevrolet', 'Chevrolet Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Chevrolet', 'Chevrolet Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Chevrolet', 'Chevrolet Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Chevrolet', 'Chevrolet Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Chevrolet', 'Chevrolet Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Chevrolet', 'Chevrolet Jayapura', 'Jayapura', 'Papua', '3S'),
('Chevrolet', 'Chevrolet Ambon', 'Ambon', 'Maluku', '3S'),
('Chevrolet', 'Chevrolet Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Chevrolet', 'Chevrolet Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Chevrolet', 'Chevrolet Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Chevrolet', 'Chevrolet Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Isuzu', 'Isuzu Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Isuzu', 'Isuzu Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Isuzu', 'Isuzu Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Isuzu', 'Isuzu Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Isuzu', 'Isuzu Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Isuzu', 'Isuzu Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Isuzu', 'Isuzu Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Isuzu', 'Isuzu Depok', 'Depok', 'Jawa Barat', '3S'),
('Isuzu', 'Isuzu Tangerang', 'Tangerang', 'Banten', '3S'),
('Isuzu', 'Isuzu Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Isuzu', 'Isuzu Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Isuzu', 'Isuzu Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Isuzu', 'Isuzu Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Isuzu', 'Isuzu Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Isuzu', 'Isuzu Malang', 'Malang', 'Jawa Timur', '3S'),
('Isuzu', 'Isuzu Denpasar', 'Denpasar', 'Bali', '3S'),
('Isuzu', 'Isuzu Medan', 'Medan', 'Sumatera Utara', '3S'),
('Isuzu', 'Isuzu Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Isuzu', 'Isuzu Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Isuzu', 'Isuzu Padang', 'Padang', 'Sumatera Barat', '3S'),
('Isuzu', 'Isuzu Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Isuzu', 'Isuzu Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Isuzu', 'Isuzu Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Isuzu', 'Isuzu Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Isuzu', 'Isuzu Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Isuzu', 'Isuzu Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Isuzu', 'Isuzu Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Isuzu', 'Isuzu Jayapura', 'Jayapura', 'Papua', '3S'),
('Isuzu', 'Isuzu Ambon', 'Ambon', 'Maluku', '3S'),
('Isuzu', 'Isuzu Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Isuzu', 'Isuzu Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Isuzu', 'Isuzu Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Isuzu', 'Isuzu Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Hino', 'Hino Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Hino', 'Hino Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Hino', 'Hino Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Hino', 'Hino Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Hino', 'Hino Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Hino', 'Hino Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Hino', 'Hino Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Hino', 'Hino Depok', 'Depok', 'Jawa Barat', '3S'),
('Hino', 'Hino Tangerang', 'Tangerang', 'Banten', '3S'),
('Hino', 'Hino Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Hino', 'Hino Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Hino', 'Hino Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Hino', 'Hino Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Hino', 'Hino Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Hino', 'Hino Malang', 'Malang', 'Jawa Timur', '3S'),
('Hino', 'Hino Denpasar', 'Denpasar', 'Bali', '3S'),
('Hino', 'Hino Medan', 'Medan', 'Sumatera Utara', '3S'),
('Hino', 'Hino Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Hino', 'Hino Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Hino', 'Hino Padang', 'Padang', 'Sumatera Barat', '3S'),
('Hino', 'Hino Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Hino', 'Hino Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Hino', 'Hino Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Hino', 'Hino Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Hino', 'Hino Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Hino', 'Hino Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Hino', 'Hino Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Hino', 'Hino Jayapura', 'Jayapura', 'Papua', '3S'),
('Hino', 'Hino Ambon', 'Ambon', 'Maluku', '3S'),
('Hino', 'Hino Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Hino', 'Hino Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Hino', 'Hino Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Hino', 'Hino Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('BYD', 'BYD Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('BYD', 'BYD Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('BYD', 'BYD Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('BYD', 'BYD Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('BYD', 'BYD Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('BYD', 'BYD Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('BYD', 'BYD Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('BYD', 'BYD Depok', 'Depok', 'Jawa Barat', '3S'),
('BYD', 'BYD Tangerang', 'Tangerang', 'Banten', '3S'),
('BYD', 'BYD Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('BYD', 'BYD Bandung', 'Bandung', 'Jawa Barat', '3S'),
('BYD', 'BYD Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('BYD', 'BYD Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('BYD', 'BYD Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('BYD', 'BYD Malang', 'Malang', 'Jawa Timur', '3S'),
('BYD', 'BYD Denpasar', 'Denpasar', 'Bali', '3S'),
('BYD', 'BYD Medan', 'Medan', 'Sumatera Utara', '3S'),
('BYD', 'BYD Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('BYD', 'BYD Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('BYD', 'BYD Padang', 'Padang', 'Sumatera Barat', '3S'),
('BYD', 'BYD Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('BYD', 'BYD Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('BYD', 'BYD Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('BYD', 'BYD Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('BYD', 'BYD Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('BYD', 'BYD Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('BYD', 'BYD Manado', 'Manado', 'Sulawesi Utara', '3S'),
('BYD', 'BYD Jayapura', 'Jayapura', 'Papua', '3S'),
('BYD', 'BYD Ambon', 'Ambon', 'Maluku', '3S'),
('BYD', 'BYD Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('BYD', 'BYD Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('BYD', 'BYD Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('BYD', 'BYD Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Tesla', 'Tesla Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Tesla', 'Tesla Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Tesla', 'Tesla Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Tesla', 'Tesla Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Tesla', 'Tesla Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Tesla', 'Tesla Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Tesla', 'Tesla Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Tesla', 'Tesla Depok', 'Depok', 'Jawa Barat', '3S'),
('Tesla', 'Tesla Tangerang', 'Tangerang', 'Banten', '3S'),
('Tesla', 'Tesla Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Tesla', 'Tesla Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Tesla', 'Tesla Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Tesla', 'Tesla Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Tesla', 'Tesla Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Tesla', 'Tesla Malang', 'Malang', 'Jawa Timur', '3S'),
('Tesla', 'Tesla Denpasar', 'Denpasar', 'Bali', '3S'),
('Tesla', 'Tesla Medan', 'Medan', 'Sumatera Utara', '3S'),
('Tesla', 'Tesla Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Tesla', 'Tesla Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Tesla', 'Tesla Padang', 'Padang', 'Sumatera Barat', '3S'),
('Tesla', 'Tesla Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Tesla', 'Tesla Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Tesla', 'Tesla Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Tesla', 'Tesla Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Tesla', 'Tesla Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Tesla', 'Tesla Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Tesla', 'Tesla Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Tesla', 'Tesla Jayapura', 'Jayapura', 'Papua', '3S'),
('Tesla', 'Tesla Ambon', 'Ambon', 'Maluku', '3S'),
('Tesla', 'Tesla Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Tesla', 'Tesla Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Tesla', 'Tesla Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Tesla', 'Tesla Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Chery', 'Chery Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Chery', 'Chery Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Chery', 'Chery Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Chery', 'Chery Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Chery', 'Chery Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Chery', 'Chery Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Chery', 'Chery Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Chery', 'Chery Depok', 'Depok', 'Jawa Barat', '3S'),
('Chery', 'Chery Tangerang', 'Tangerang', 'Banten', '3S'),
('Chery', 'Chery Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Chery', 'Chery Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Chery', 'Chery Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Chery', 'Chery Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Chery', 'Chery Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Chery', 'Chery Malang', 'Malang', 'Jawa Timur', '3S'),
('Chery', 'Chery Denpasar', 'Denpasar', 'Bali', '3S'),
('Chery', 'Chery Medan', 'Medan', 'Sumatera Utara', '3S'),
('Chery', 'Chery Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Chery', 'Chery Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Chery', 'Chery Padang', 'Padang', 'Sumatera Barat', '3S'),
('Chery', 'Chery Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Chery', 'Chery Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Chery', 'Chery Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Chery', 'Chery Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Chery', 'Chery Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Chery', 'Chery Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Chery', 'Chery Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Chery', 'Chery Jayapura', 'Jayapura', 'Papua', '3S'),
('Chery', 'Chery Ambon', 'Ambon', 'Maluku', '3S'),
('Chery', 'Chery Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Chery', 'Chery Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Chery', 'Chery Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Chery', 'Chery Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('MG', 'MG Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('MG', 'MG Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('MG', 'MG Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('MG', 'MG Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('MG', 'MG Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('MG', 'MG Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('MG', 'MG Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('MG', 'MG Depok', 'Depok', 'Jawa Barat', '3S'),
('MG', 'MG Tangerang', 'Tangerang', 'Banten', '3S'),
('MG', 'MG Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('MG', 'MG Bandung', 'Bandung', 'Jawa Barat', '3S'),
('MG', 'MG Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('MG', 'MG Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('MG', 'MG Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('MG', 'MG Malang', 'Malang', 'Jawa Timur', '3S'),
('MG', 'MG Denpasar', 'Denpasar', 'Bali', '3S'),
('MG', 'MG Medan', 'Medan', 'Sumatera Utara', '3S'),
('MG', 'MG Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('MG', 'MG Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('MG', 'MG Padang', 'Padang', 'Sumatera Barat', '3S'),
('MG', 'MG Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('MG', 'MG Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('MG', 'MG Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('MG', 'MG Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('MG', 'MG Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('MG', 'MG Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('MG', 'MG Manado', 'Manado', 'Sulawesi Utara', '3S'),
('MG', 'MG Jayapura', 'Jayapura', 'Papua', '3S'),
('MG', 'MG Ambon', 'Ambon', 'Maluku', '3S'),
('MG', 'MG Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('MG', 'MG Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('MG', 'MG Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('MG', 'MG Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Datsun', 'Datsun Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Datsun', 'Datsun Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Datsun', 'Datsun Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Datsun', 'Datsun Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Datsun', 'Datsun Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Datsun', 'Datsun Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Datsun', 'Datsun Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Datsun', 'Datsun Depok', 'Depok', 'Jawa Barat', '3S'),
('Datsun', 'Datsun Tangerang', 'Tangerang', 'Banten', '3S'),
('Datsun', 'Datsun Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Datsun', 'Datsun Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Datsun', 'Datsun Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Datsun', 'Datsun Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Datsun', 'Datsun Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Datsun', 'Datsun Malang', 'Malang', 'Jawa Timur', '3S'),
('Datsun', 'Datsun Denpasar', 'Denpasar', 'Bali', '3S'),
('Datsun', 'Datsun Medan', 'Medan', 'Sumatera Utara', '3S'),
('Datsun', 'Datsun Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Datsun', 'Datsun Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Datsun', 'Datsun Padang', 'Padang', 'Sumatera Barat', '3S'),
('Datsun', 'Datsun Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Datsun', 'Datsun Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Datsun', 'Datsun Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Datsun', 'Datsun Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Datsun', 'Datsun Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Datsun', 'Datsun Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Datsun', 'Datsun Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Datsun', 'Datsun Jayapura', 'Jayapura', 'Papua', '3S'),
('Datsun', 'Datsun Ambon', 'Ambon', 'Maluku', '3S'),
('Datsun', 'Datsun Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Datsun', 'Datsun Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Datsun', 'Datsun Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Datsun', 'Datsun Solo', 'Surakarta', 'Jawa Tengah', '3S'),
('Proton', 'Proton Cawang', 'Jakarta', 'DKI Jakarta', '3S'),
('Proton', 'Proton Sudirman', 'Jakarta', 'DKI Jakarta', '3S'),
('Proton', 'Proton Fatmawati', 'Jakarta', 'DKI Jakarta', '3S'),
('Proton', 'Proton Pluit', 'Jakarta', 'DKI Jakarta', '3S'),
('Proton', 'Proton Sunter', 'Jakarta', 'DKI Jakarta', '3S'),
('Proton', 'Proton Kalimalang', 'Jakarta', 'DKI Jakarta', '3S'),
('Proton', 'Proton Bekasi', 'Bekasi', 'Jawa Barat', '3S'),
('Proton', 'Proton Depok', 'Depok', 'Jawa Barat', '3S'),
('Proton', 'Proton Tangerang', 'Tangerang', 'Banten', '3S'),
('Proton', 'Proton Serpong', 'Tangerang Selatan', 'Banten', '3S'),
('Proton', 'Proton Bandung', 'Bandung', 'Jawa Barat', '3S'),
('Proton', 'Proton Semarang', 'Semarang', 'Jawa Tengah', '3S'),
('Proton', 'Proton Yogyakarta', 'Yogyakarta', 'DI Yogyakarta', '3S'),
('Proton', 'Proton Surabaya', 'Surabaya', 'Jawa Timur', '3S'),
('Proton', 'Proton Malang', 'Malang', 'Jawa Timur', '3S'),
('Proton', 'Proton Denpasar', 'Denpasar', 'Bali', '3S'),
('Proton', 'Proton Medan', 'Medan', 'Sumatera Utara', '3S'),
('Proton', 'Proton Palembang', 'Palembang', 'Sumatera Selatan', '3S'),
('Proton', 'Proton Pekanbaru', 'Pekanbaru', 'Riau', '3S'),
('Proton', 'Proton Padang', 'Padang', 'Sumatera Barat', '3S'),
('Proton', 'Proton Bandar Lampung', 'Bandar Lampung', 'Lampung', '3S'),
('Proton', 'Proton Pontianak', 'Pontianak', 'Kalimantan Barat', '3S'),
('Proton', 'Proton Banjarmasin', 'Banjarmasin', 'Kalimantan Selatan', '3S'),
('Proton', 'Proton Balikpapan', 'Balikpapan', 'Kalimantan Timur', '3S'),
('Proton', 'Proton Samarinda', 'Samarinda', 'Kalimantan Timur', '3S'),
('Proton', 'Proton Makassar', 'Makassar', 'Sulawesi Selatan', '3S'),
('Proton', 'Proton Manado', 'Manado', 'Sulawesi Utara', '3S'),
('Proton', 'Proton Jayapura', 'Jayapura', 'Papua', '3S'),
('Proton', 'Proton Ambon', 'Ambon', 'Maluku', '3S'),
('Proton', 'Proton Mataram', 'Mataram', 'Nusa Tenggara Barat', '3S'),
('Proton', 'Proton Kupang', 'Kupang', 'Nusa Tenggara Timur', '3S'),
('Proton', 'Proton Cirebon', 'Cirebon', 'Jawa Barat', '3S'),
('Proton', 'Proton Solo', 'Surakarta', 'Jawa Tengah', '3S');