CREATE TABLE IF NOT EXISTS bandara (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(255) NOT NULL,
  iata VARCHAR(10),
  icao VARCHAR(10),
  kota VARCHAR(100),
  provinsi VARCHAR(100),
  jenis VARCHAR(50)
);

INSERT INTO bandara (nama, iata, icao, kota, provinsi, jenis) VALUES
('Bandar Udara Internasional Soekarno-Hatta', 'CGK', 'WIII', 'Tangerang', 'Banten', 'Internasional'),
('Bandar Udara Internasional Halim Perdanakusuma', 'HLP', 'WIHH', 'Jakarta', 'DKI Jakarta', 'Internasional'),
('Bandar Udara Internasional Ngurah Rai', 'DPS', 'WADD', 'Denpasar', 'Bali', 'Internasional'),
('Bandar Udara Internasional Juanda', 'SUB', 'WARR', 'Surabaya', 'Jawa Timur', 'Internasional'),
('Bandar Udara Internasional Kualanamu', 'KNO', 'WIMM', 'Medan', 'Sumatera Utara', 'Internasional'),
('Bandar Udara Internasional Sultan Hasanuddin', 'UPG', 'WAAA', 'Makassar', 'Sulawesi Selatan', 'Internasional'),
('Bandar Udara Internasional Sultan Aji Muhammad Sulaiman Sepinggan', 'BPN', 'WALL', 'Balikpapan', 'Kalimantan Timur', 'Internasional'),
('Bandar Udara Internasional Sam Ratulangi', 'MDC', 'WAMM', 'Manado', 'Sulawesi Utara', 'Internasional'),
('Bandar Udara Internasional Yogyakarta', 'YIA', 'WAHI', 'Kulon Progo', 'DI Yogyakarta', 'Internasional'),
('Bandar Udara Internasional Adisutjipto', 'JOG', 'WARJ', 'Yogyakarta', 'DI Yogyakarta', 'Internasional'),
('Bandar Udara Internasional Ahmad Yani', 'SRG', 'WAHS', 'Semarang', 'Jawa Tengah', 'Internasional'),
('Bandar Udara Internasional Adi Soemarmo', 'SOC', 'WARQ', 'Solo', 'Jawa Tengah', 'Internasional'),
('Bandar Udara Internasional Husein Sastranegara', 'BDO', 'WICC', 'Bandung', 'Jawa Barat', 'Internasional'),
('Bandar Udara Internasional Kertajati', 'KJT', 'WICA', 'Majalengka', 'Jawa Barat', 'Internasional'),
('Bandar Udara Internasional Sultan Iskandar Muda', 'BTJ', 'WITT', 'Banda Aceh', 'Aceh', 'Internasional'),
('Bandar Udara Internasional Sultan Syarif Kasim II', 'PKU', 'WIBB', 'Pekanbaru', 'Riau', 'Internasional'),
('Bandar Udara Internasional Minangkabau', 'PDG', 'WIPT', 'Padang', 'Sumatera Barat', 'Internasional'),
('Bandar Udara Internasional Sultan Mahmud Badaruddin II', 'PLM', 'WIPP', 'Palembang', 'Sumatera Selatan', 'Internasional'),
('Bandar Udara Internasional Radin Inten II', 'TKG', 'WILL', 'Bandar Lampung', 'Lampung', 'Internasional'),
('Bandar Udara Internasional Depati Amir', 'PGK', 'WIPK', 'Pangkal Pinang', 'Bangka Belitung', 'Internasional'),
('Bandar Udara Internasional Raja Haji Fisabilillah', 'TNJ', 'WIDN', 'Tanjung Pinang', 'Kepulauan Riau', 'Internasional'),
('Bandar Udara Internasional Hang Nadim', 'BTH', 'WIDD', 'Batam', 'Kepulauan Riau', 'Internasional'),
('Bandar Udara Internasional Supadio', 'PNK', 'WIOO', 'Pontianak', 'Kalimantan Barat', 'Internasional'),
('Bandar Udara Internasional Syamsudin Noor', 'BDJ', 'WAOO', 'Banjarmasin', 'Kalimantan Selatan', 'Internasional'),
('Bandar Udara Internasional Sultan Aji Muhammad Sulaiman Sepinggan', 'BPN', 'WALL', 'Balikpapan', 'Kalimantan Timur', 'Internasional'),
('Bandar Udara Internasional Juwata', 'TRK', 'WAQQ', 'Tarakan', 'Kalimantan Utara', 'Internasional'),
('Bandar Udara Internasional Sultan Bantilan', 'TLI', 'WAMI', 'Tolitoli', 'Sulawesi Tengah', 'Internasional'),
('Bandar Udara Internasional Mutiara SIS Al-Jufrie', 'PLW', 'WAFF', 'Palu', 'Sulawesi Tengah', 'Internasional'),
('Bandar Udara Internasional Haluoleo', 'KDI', 'WAWW', 'Kendari', 'Sulawesi Tenggara', 'Internasional'),
('Bandar Udara Internasional Betoambari', 'BUW', 'WAWB', 'Bau-Bau', 'Sulawesi Tenggara', 'Internasional'),
('Bandar Udara Internasional Sultan Babullah', 'TTE', 'WAMT', 'Ternate', 'Maluku Utara', 'Internasional'),
('Bandar Udara Internasional Pattimura', 'AMQ', 'WAPP', 'Ambon', 'Maluku', 'Internasional'),
('Bandar Udara Internasional Frans Kaisiepo', 'BIK', 'WABB', 'Biak', 'Papua', 'Internasional'),
('Bandar Udara Internasional Sentani', 'DJJ', 'WAJJ', 'Jayapura', 'Papua', 'Internasional'),
('Bandar Udara Internasional El Tari', 'KOE', 'WATT', 'Kupang', 'Nusa Tenggara Timur', 'Internasional'),
('Bandar Udara Internasional Lombok', 'LOP', 'WADL', 'Praya', 'Nusa Tenggara Barat', 'Internasional'),
('Bandar Udara Internasional Sultan Muhammad Kaharuddin III', 'SWQ', 'WADS', 'Sumbawa Besar', 'Nusa Tenggara Barat', 'Internasional'),
('Bandar Udara Internasional Komodo', 'LBJ', 'WATO', 'Labuan Bajo', 'Nusa Tenggara Timur', 'Internasional'),
('Bandar Udara Internasional Tardamu', 'SAU', 'WATS', 'Sabu', 'Nusa Tenggara Timur', 'Internasional'),
('Bandar Udara Internasional Umbu Mehang Kunda', 'WGP', 'WATU', 'Waingapu', 'Nusa Tenggara Timur', 'Internasional'),
('Bandar Udara Internasional Gewayantana', 'LKA', 'WATL', 'Larantuka', 'Nusa Tenggara Timur', 'Internasional'),
('Bandar Udara Internasional Wai Oti', 'MOF', 'WATC', 'Maumere', 'Nusa Tenggara Timur', 'Internasional'),
('Bandar Udara Internasional H. Hasan Aroeboesman', 'ENE', 'WATE', 'Ende', 'Nusa Tenggara Timur', 'Internasional'),
('Bandar Udara Internasional Soa Bajawa', 'BJW', 'WATB', 'Bajawa', 'Nusa Tenggara Timur', 'Internasional'),
('Bandar Udara Internasional Frans Sales Lega', 'RTG', 'WATG', 'Ruteng', 'Nusa Tenggara Timur', 'Internasional'),
('Bandar Udara Internasional Tambolaka', 'TMC', 'WATK', 'Tambolaka', 'Nusa Tenggara Timur', 'Internasional'),
('Bandar Udara Internasional Lede Kalumbang', 'TJS', 'WALT', 'Tanjung Selor', 'Kalimantan Utara', 'Internasional'),
('Bandar Udara Internasional Kalimarau', 'BEJ', 'WAQT', 'Berau', 'Kalimantan Timur', 'Internasional'),
('Bandar Udara Internasional Sultan Aji Muhammad Sulaiman Sepinggan', 'BPN', 'WALL', 'Balikpapan', 'Kalimantan Timur', 'Internasional'),
('Bandar Udara Internasional Aji Pangeran Tumenggung Pranoto', 'AAP', 'WALS', 'Samarinda', 'Kalimantan Timur', 'Internasional'),
('Bandar Udara Internasional Tanjung Harapan', 'TJS', 'WALT', 'Tanjung Selor', 'Kalimantan Utara', 'Internasional'),
('Bandar Udara Internasional Robert Atty Bessing', 'NNX', 'WAQN', 'Nunukan', 'Kalimantan Utara', 'Internasional'),
('Bandar Udara Internasional Long Apung', 'LPU', 'WRLP', 'Long Apung', 'Kalimantan Utara', 'Internasional'),
('Bandar Udara Internasional Long Bawan', 'LBW', 'WRLB', 'Long Bawan', 'Kalimantan Utara', 'Internasional'),
('Bandar Udara Internasional Datah Dawai', 'DTD', 'WRLD', 'Datah Dawai', 'Kalimantan Timur', 'Internasional'),
('Bandar Udara Internasional Melak', 'MLK', 'WRLM', 'Melak', 'Kalimantan Timur', 'Internasional'),
('Bandar Udara Internasional Muara Wahau', 'MWW', 'WRLW', 'Muara Wahau', 'Kalimantan Timur', 'Internasional'),
('Bandar Udara Internasional Muara Teweh', 'HMS', 'WRLH', 'Muara Teweh', 'Kalimantan Tengah', 'Internasional'),
('Bandar Udara Internasional Kuala Kurun', 'KLK', 'WRLK', 'Kuala Kurun', 'Kalimantan Tengah', 'Internasional'),
('Bandar Udara Internasional Kuala Pembuang', 'KLP', 'WRLP', 'Kuala Pembuang', 'Kalimantan Tengah', 'Internasional'),
('Bandar Udara Internasional Pangkalan Bun', 'PKN', 'WAGI', 'Pangkalan Bun', 'Kalimantan Tengah', 'Internasional'),
('Bandar Udara Internasional Sampit', 'SMQ', 'WAGS', 'Sampit', 'Kalimantan Tengah', 'Internasional'),
('Bandar Udara Internasional Palangkaraya', 'PKY', 'WAGG', 'Palangkaraya', 'Kalimantan Tengah', 'Internasional'),
('Bandar Udara Internasional Buntok', 'BUN', 'WAGB', 'Buntok', 'Kalimantan Tengah', 'Internasional'),
('Bandar Udara Internasional Tumbang Samba', 'TBS', 'WAGT', 'Tumbang Samba', 'Kalimantan Tengah', 'Internasional'),
('Bandar Udara Internasional Puruk Cahu', 'PCU', 'WAGP', 'Puruk Cahu', 'Kalimantan Tengah', 'Internasional'),
('Bandar Udara Internasional Beringin', 'BRG', 'WAGB', 'Beringin', 'Kalimantan Selatan', 'Internasional'),
('Bandar Udara Internasional Gusti Syamsir Alam', 'KBU', 'WAOK', 'Kotabaru', 'Kalimantan Selatan', 'Internasional'),
('Bandar Udara Internasional Syamsudin Noor', 'BDJ', 'WAOO', 'Banjarmasin', 'Kalimantan Selatan', 'Internasional'),
('Bandar Udara Internasional Batu Licin', 'BTW', 'WAOB', 'Batu Licin', 'Kalimantan Selatan', 'Internasional'),
('Bandar Udara Internasional Warukin', 'TJG', 'WAON', 'Tanjung', 'Kalimantan Selatan', 'Internasional'),
('Bandar Udara Internasional Supadio', 'PNK', 'WIOO', 'Pontianak', 'Kalimantan Barat', 'Internasional'),
('Bandar Udara Internasional Rahadi Osman', 'KTG', 'WIOK', 'Ketapang', 'Kalimantan Barat', 'Internasional'),
('Bandar Udara Internasional Singkawang', 'SKJ', 'WIOS', 'Singkawang', 'Kalimantan Barat', 'Internasional'),
('Bandar Udara Internasional Sintang', 'SQG', 'WIOS', 'Sintang', 'Kalimantan Barat', 'Internasional'),
('Bandar Udara Internasional Putussibau', 'PSU', 'WIOP', 'Putussibau', 'Kalimantan Barat', 'Internasional'),
('Bandar Udara Internasional Kapuas Hulu', 'KHY', 'WIOH', 'Kapuas Hulu', 'Kalimantan Barat', 'Internasional'),
('Bandar Udara Internasional Bengkayang', 'BKY', 'WIOB', 'Bengkayang', 'Kalimantan Barat', 'Internasional'),
('Bandar Udara Internasional Landak', 'LDK', 'WIOL', 'Landak', 'Kalimantan Barat', 'Internasional'),
('Bandar Udara Internasional Mempawah', 'MPW', 'WIOM', 'Mempawah', 'Kalimantan Barat', 'Internasional'),
('Bandar Udara Internasional Sambas', 'SBS', 'WIOS', 'Sambas', 'Kalimantan Barat', 'Internasional'),
('Bandar Udara Internasional Sanggau', 'SGQ', 'WIOS', 'Sanggau', 'Kalimantan Barat', 'Internasional'),
('Bandar Udara Internasional Sekadau', 'SKD', 'WIOS', 'Sekadau', 'Kalimantan Barat', 'Internasional'),
('Bandar Udara Internasional Tayan', 'TYN', 'WIOT', 'Tayan', 'Kalimantan Barat', 'Internasional'),
('Bandar Udara Internasional Kuala Tungkal', 'KTL', 'WIKT', 'Kuala Tungkal', 'Jambi', 'Internasional'),
('Bandar Udara Internasional Sultan Thaha', 'DJB', 'WIPA', 'Jambi', 'Jambi', 'Internasional'),
('Bandar Udara Internasional Muara Bungo', 'BUU', 'WIPB', 'Muara Bungo', 'Jambi', 'Internasional'),
('Bandar Udara Internasional Kerinci', 'KRC', 'WIPK', 'Kerinci', 'Jambi', 'Internasional'),
('Bandar Udara Internasional Depati Parbo', 'KRC', 'WIPK', 'Kerinci', 'Jambi', 'Internasional'),
('Bandar Udara Internasional Fatmawati Soekarno', 'BKS', 'WIPL', 'Bengkulu', 'Bengkulu', 'Internasional'),
('Bandar Udara Internasional Mukomuko', 'MPC', 'WIPM', 'Mukomuko', 'Bengkulu', 'Internasional'),
('Bandar Udara Internasional Enggano', 'ENG', 'WIPE', 'Enggano', 'Bengkulu', 'Internasional'),
('Bandar Udara Internasional Sultan Mahmud Badaruddin II', 'PLM', 'WIPP', 'Palembang', 'Sumatera Selatan', 'Internasional'),
('Bandar Udara Internasional Silampari', 'LLG', 'WIPL', 'Lubuk Linggau', 'Sumatera Selatan', 'Internasional'),
('Bandar Udara Internasional Atung Bungsu', 'PXA', 'WIPX', 'Pagar Alam', 'Sumatera Selatan', 'Internasional'),
('Bandar Udara Internasional Banding Agung', 'BDA', 'WIPD', 'Banding Agung', 'Sumatera Selatan', 'Internasional'),
('Bandar Udara Internasional Radin Inten II', 'TKG', 'WILL', 'Bandar Lampung', 'Lampung', 'Internasional'),
('Bandar Udara Internasional Gusti Sjamsir Alam', 'KBU', 'WAOK', 'Kotabaru', 'Kalimantan Selatan', 'Internasional'),
('Bandar Udara Internasional Abdul Rachman Saleh', 'MLG', 'WARA', 'Malang', 'Jawa Timur', 'Internasional'),
('Bandar Udara Internasional Banyuwangi', 'BWX', 'WADY', 'Banyuwangi', 'Jawa Timur', 'Internasional'),
('Bandar Udara Internasional Notohadinegoro', 'JBB', 'WARE', 'Jember', 'Jawa Timur', 'Internasional'),
('Bandar Udara Internasional Iswahjudi', 'MDN', 'WARI', 'Madiun', 'Jawa Timur', 'Internasional'),
('Bandar Udara Internasional Dhoho', 'DHO', 'WARD', 'Kediri', 'Jawa Timur', 'Internasional'),
('Bandar Udara Internasional Juanda', 'SUB', 'WARR', 'Surabaya', 'Jawa Timur', 'Internasional'),
('Bandar Udara Internasional Bawean', 'BXW', 'WARB', 'Bawean', 'Jawa Timur', 'Internasional'),
('Bandar Udara Internasional Kangean', 'KGP', 'WARK', 'Kangean', 'Jawa Timur', 'Internasional'),
('Bandar Udara Internasional Sumenep', 'SUP', 'WARS', 'Sumenep', 'Jawa Timur', 'Internasional'),
('Bandar Udara Internasional Tuban', 'TBU', 'WART', 'Tuban', 'Jawa Timur', 'Internasional'),
('Bandar Udara Internasional Ahmad Yani', 'SRG', 'WAHS', 'Semarang', 'Jawa Tengah', 'Internasional'),
('Bandar Udara Internasional Adi Soemarmo', 'SOC', 'WARQ', 'Solo', 'Jawa Tengah', 'Internasional'),
('Bandar Udara Internasional Jenderal Ahmad Yani', 'SRG', 'WAHS', 'Semarang', 'Jawa Tengah', 'Internasional'),
('Bandar Udara Internasional Tunggul Wulung', 'CXP', 'WIHL', 'Cilacap', 'Jawa Tengah', 'Internasional'),
('Bandar Udara Internasional Dewadaru', 'KWB', 'WAHK', 'Karimunjawa', 'Jawa Tengah', 'Internasional'),
('Bandar Udara Internasional Yogyakarta', 'YIA', 'WAHI', 'Kulon Progo', 'DI Yogyakarta', 'Internasional'),
('Bandar Udara Internasional Adisutjipto', 'JOG', 'WARJ', 'Yogyakarta', 'DI Yogyakarta', 'Internasional'),
('Bandar Udara Internasional Husein Sastranegara', 'BDO', 'WICC', 'Bandung', 'Jawa Barat', 'Internasional'),
('Bandar Udara Internasional Kertajati', 'KJT', 'WICA', 'Majalengka', 'Jawa Barat', 'Internasional'),
('Bandar Udara Internasional Cakrabhuwana', 'CBN', 'WICD', 'Cirebon', 'Jawa Barat', 'Internasional'),
('Bandar Udara Internasional Nusawiru', 'CJN', 'WICN', 'Pangandaran', 'Jawa Barat', 'Internasional'),
('Bandar Udara Internasional Soekarno-Hatta', 'CGK', 'WIII', 'Tangerang', 'Banten', 'Internasional'),
('Bandar Udara Internasional Halim Perdanakusuma', 'HLP', 'WIHH', 'Jakarta', 'DKI Jakarta', 'Internasional'),
('Bandar Udara Internasional Pondok Cabe', 'PCB', 'WIHP', 'Tangerang Selatan', 'Banten', 'Domestik'),
('Bandar Udara Internasional Curug', 'CUR', 'WIIA', 'Tangerang', 'Banten', 'Domestik'),
('Bandar Udara Internasional Budiarto', 'CUR', 'WIIA', 'Tangerang', 'Banten', 'Domestik'),
('Bandar Udara Internasional Sultan Iskandar Muda', 'BTJ', 'WITT', 'Banda Aceh', 'Aceh', 'Internasional'),
('Bandar Udara Internasional Malikussaleh', 'LSW', 'WITM', 'Lhokseumawe', 'Aceh', 'Internasional'),
('Bandar Udara Internasional Sultan Syarif Kasim II', 'PKU', 'WIBB', 'Pekanbaru', 'Riau', 'Internasional'),
('Bandar Udara Internasional Hang Nadim', 'BTH', 'WIDD', 'Batam', 'Kepulauan Riau', 'Internasional'),
('Bandar Udara Internasional Raja Haji Fisabilillah', 'TNJ', 'WIDN', 'Tanjung Pinang', 'Kepulauan Riau', 'Internasional'),
('Bandar Udara Internasional Minangkabau', 'PDG', 'WIPT', 'Padang', 'Sumatera Barat', 'Internasional'),
('Bandar Udara Internasional Kualanamu', 'KNO', 'WIMM', 'Medan', 'Sumatera Utara', 'Internasional'),
('Bandar Udara Internasional Silangit', 'DTB', 'WIMN', 'Siborong-Borong', 'Sumatera Utara', 'Internasional'),
('Bandar Udara Internasional Ferdinand Lumban Tobing', 'FLZ', 'WIMS', 'Sibolga', 'Sumatera Utara', 'Internasional'),
('Bandar Udara Internasional Aek Godang', 'AEG', 'WIME', 'Padang Sidempuan', 'Sumatera Utara', 'Internasional'),
('Bandar Udara Internasional Binaka', 'GNS', 'WIMB', 'Gunungsitoli', 'Sumatera Utara', 'Internasional'),
('Bandar Udara Internasional Lasikin', 'LKI', 'WIML', 'Lasikin', 'Sumatera Utara', 'Internasional'),
('Bandar Udara Internasional Sibisa', 'SIB', 'WIMS', 'Sibisa', 'Sumatera Utara', 'Internasional'),
('Bandar Udara Internasional Dr. Ferdinand Lumban Tobing', 'FLZ', 'WIMS', 'Sibolga', 'Sumatera Utara', 'Internasional'),
('Bandar Udara Internasional Raja Haji Fisabilillah', 'TNJ', 'WIDN', 'Tanjung Pinang', 'Kepulauan Riau', 'Internasional'),
('Bandar Udara Internasional Dabo', 'SIQ', 'WIDS', 'Singkep', 'Kepulauan Riau', 'Internasional'),
('Bandar Udara Internasional Letung', 'LMU', 'WIDL', 'Letung', 'Kepulauan Riau', 'Internasional'),
('Bandar Udara Internasional Matak', 'MWK', 'WIOM', 'Matak', 'Kepulauan Riau', 'Internasional'),
('Bandar Udara Internasional Ranai', 'NTX', 'WION', 'Ranai', 'Kepulauan Riau', 'Internasional'),
('Bandar Udara Internasional Tambelan', 'TBX', 'WIDT', 'Tambelan', 'Kepulauan Riau', 'Internasional'),
('Bandar Udara Internasional Jemaja', 'LMU', 'WIDL', 'Jemaja', 'Kepulauan Riau', 'Internasional'),
('Bandar Udara Internasional Siantan', 'SIQ', 'WIDS', 'Siantan', 'Kepulauan Riau', 'Internasional'),
('Bandar Udara Internasional Tioman', 'TOD', 'WIDT', 'Tioman', 'Kepulauan Riau', 'Internasional'),
('Bandar Udara Internasional Pangkal Pinang', 'PGK', 'WIPK', 'Pangkal Pinang', 'Bangka Belitung', 'Internasional'),
('Bandar Udara Internasional H.A.S. Hanandjoeddin', 'TJQ', 'WIOD', 'Tanjung Pandan', 'Bangka Belitung', 'Internasional'),
('Bandar Udara Internasional Depati Amir', 'PGK', 'WIPK', 'Pangkal Pinang', 'Bangka Belitung', 'Internasional'),
('Bandar Udara Internasional Fatmawati Soekarno', 'BKS', 'WIPL', 'Bengkulu', 'Bengkulu', 'Internasional'),
('Bandar Udara Internasional Sultan Thaha', 'DJB', 'WIPA', 'Jambi', 'Jambi', 'Internasional'),
('Bandar Udara Internasional Sultan Mahmud Badaruddin II', 'PLM', 'WIPP', 'Palembang', 'Sumatera Selatan', 'Internasional'),
('Bandar Udara Internasional Radin Inten II', 'TKG', 'WILL', 'Bandar Lampung', 'Lampung', 'Internasional'),
('Bandar Udara Internasional Soekarno-Hatta', 'CGK', 'WIII', 'Tangerang', 'Banten', 'Internasional'),
('Bandar Udara Internasional Ngurah Rai', 'DPS', 'WADD', 'Denpasar', 'Bali', 'Internasional'),
('Bandar Udara Internasional Lombok', 'LOP', 'WADL', 'Praya', 'Nusa Tenggara Barat', 'Internasional'),
('Bandar Udara Internasional Sultan Muhammad Kaharuddin III', 'SWQ', 'WADS', 'Sumbawa Besar', 'Nusa Tenggara Barat', 'Internasional'),
('Bandar Udara Internasional Bima', 'BMU', 'WADB', 'Bima', 'Nusa Tenggara Barat', 'Internasional'),
('Bandar Udara Internasional El Tari', 'KOE', 'WATT', 'Kupang', 'Nusa Tenggara Timur', 'Internasional'),
('Bandar Udara Internasional Komodo', 'LBJ', 'WATO', 'Labuan Bajo', 'Nusa Tenggara Timur', 'Internasional'),
('Bandar Udara Internasional Frans Kaisiepo', 'BIK', 'WABB', 'Biak', 'Papua', 'Internasional'),
('Bandar Udara Internasional Sentani', 'DJJ', 'WAJJ', 'Jayapura', 'Papua', 'Internasional'),
('Bandar Udara Internasional Mozes Kilangin', 'TIM', 'WABP', 'Timika', 'Papua', 'Internasional'),
('Bandar Udara Internasional Wamena', 'WMX', 'WAJW', 'Wamena', 'Papua', 'Internasional'),
('Bandar Udara Internasional Merauke', 'MKQ', 'WAKK', 'Merauke', 'Papua', 'Internasional'),
('Bandar Udara Internasional Nabire', 'NBX', 'WABI', 'Nabire', 'Papua', 'Internasional'),
('Bandar Udara Internasional Fakfak', 'FKQ', 'WASF', 'Fakfak', 'Papua Barat', 'Internasional'),
('Bandar Udara Internasional Kaimana', 'KNG', 'WASK', 'Kaimana', 'Papua Barat', 'Internasional'),
('Bandar Udara Internasional Manokwari', 'MKW', 'WASR', 'Manokwari', 'Papua Barat', 'Internasional'),
('Bandar Udara Internasional Sorong', 'SOQ', 'WASS', 'Sorong', 'Papua Barat', 'Internasional'),
('Bandar Udara Internasional Torea', 'FKQ', 'WASF', 'Fakfak', 'Papua Barat', 'Internasional'),
('Bandar Udara Internasional Utarom', 'KNG', 'WASK', 'Kaimana', 'Papua Barat', 'Internasional'),
('Bandar Udara Internasional Rendani', 'MKW', 'WASR', 'Manokwari', 'Papua Barat', 'Internasional'),
('Bandar Udara Internasional Domine Eduard Osok', 'SOQ', 'WASS', 'Sorong', 'Papua Barat', 'Internasional'),
('Bandar Udara Internasional Pattimura', 'AMQ', 'WAPP', 'Ambon', 'Maluku', 'Internasional'),
('Bandar Udara Internasional Sultan Babullah', 'TTE', 'WAMT', 'Ternate', 'Maluku Utara', 'Internasional'),
('Bandar Udara Internasional Sam Ratulangi', 'MDC', 'WAMM', 'Manado', 'Sulawesi Utara', 'Internasional'),
('Bandar Udara Internasional Djalaluddin', 'GTO', 'WAMG', 'Gorontalo', 'Gorontalo', 'Internasional'),
('Bandar Udara Internasional Syukuran Aminuddin Amir', 'LUW', 'WAMW', 'Luwuk', 'Sulawesi Tengah', 'Internasional'),
('Bandar Udara Internasional Mutiara SIS Al-Jufrie', 'PLW', 'WAFF', 'Palu', 'Sulawesi Tengah', 'Internasional'),
('Bandar Udara Internasional Sultan Hasanuddin', 'UPG', 'WAAA', 'Makassar', 'Sulawesi Selatan', 'Internasional'),
('Bandar Udara Internasional Haluoleo', 'KDI', 'WAWW', 'Kendari', 'Sulawesi Tenggara', 'Internasional'),
('Bandar Udara Internasional Betoambari', 'BUW', 'WAWB', 'Bau-Bau', 'Sulawesi Tenggara', 'Internasional'),
('Bandar Udara Internasional Sultan Aji Muhammad Sulaiman Sepinggan', 'BPN', 'WALL', 'Balikpapan', 'Kalimantan Timur', 'Internasional'),
('Bandar Udara Internasional Aji Pangeran Tumenggung Pranoto', 'AAP', 'WALS', 'Samarinda', 'Kalimantan Timur', 'Internasional'),
('Bandar Udara Internasional Juwata', 'TRK', 'WAQQ', 'Tarakan', 'Kalimantan Utara', 'Internasional'),
('Bandar Udara Internasional Kalimarau', 'BEJ', 'WAQT', 'Berau', 'Kalimantan Timur', 'Internasional'),
('Bandar Udara Internasional Sultan Syarif Kasim II', 'PKU', 'WIBB', 'Pekanbaru', 'Riau', 'Internasional'),
('Bandar Udara Internasional Sultan Iskandar Muda', 'BTJ', 'WITT', 'Banda Aceh', 'Aceh', 'Internasional'),
('Bandar Udara Internasional Minangkabau', 'PDG', 'WIPT', 'Padang', 'Sumatera Barat', 'Internasional'),
('Bandar Udara Internasional Kualanamu', 'KNO', 'WIMM', 'Medan', 'Sumatera Utara', 'Internasional'),
('Bandar Udara Internasional Hang Nadim', 'BTH', 'WIDD', 'Batam', 'Kepulauan Riau', 'Internasional'),
('Bandar Udara Internasional Soekarno-Hatta', 'CGK', 'WIII', 'Tangerang', 'Banten', 'Internasional'),
('Bandar Udara Internasional Halim Perdanakusuma', 'HLP', 'WIHH', 'Jakarta', 'DKI Jakarta', 'Internasional'),
('Bandar Udara Internasional Juanda', 'SUB', 'WARR', 'Surabaya', 'Jawa Timur', 'Internasional'),
('Bandar Udara Internasional Ngurah Rai', 'DPS', 'WADD', 'Denpasar', 'Bali', 'Internasional'),
('Bandar Udara Internasional Sultan Hasanuddin', 'UPG', 'WAAA', 'Makassar', 'Sulawesi Selatan', 'Internasional'),
('Bandar Udara Internasional Kualanamu', 'KNO', 'WIMM', 'Medan', 'Sumatera Utara', 'Internasional'),
('Bandar Udara Internasional Sam Ratulangi', 'MDC', 'WAMM', 'Manado', 'Sulawesi Utara', 'Internasional'),
('Bandar Udara Internasional Sultan Aji Muhammad Sulaiman Sepinggan', 'BPN', 'WALL', 'Balikpapan', 'Kalimantan Timur', 'Internasional'),
('Bandar Udara Internasional Yogyakarta', 'YIA', 'WAHI', 'Kulon Progo', 'DI Yogyakarta', 'Internasional'),
('Bandar Udara Internasional Adisutjipto', 'JOG', 'WARJ', 'Yogyakarta', 'DI Yogyakarta', 'Internasional'),
('Bandar Udara Internasional Ahmad Yani', 'SRG', 'WAHS', 'Semarang', 'Jawa Tengah', 'Internasional'),
('Bandar Udara Internasional Adi Soemarmo', 'SOC', 'WARQ', 'Solo', 'Jawa Tengah', 'Internasional'),
('Bandar Udara Internasional Husein Sastranegara', 'BDO', 'WICC', 'Bandung', 'Jawa Barat', 'Internasional'),
('Bandar Udara Internasional Kertajati', 'KJT', 'WICA', 'Majalengka', 'Jawa Barat', 'Internasional'),
('Bandar Udara Internasional Sultan Iskandar Muda', 'BTJ', 'WITT', 'Banda Aceh', 'Aceh', 'Internasional'),
('Bandar Udara Internasional Sultan Syarif Kasim II', 'PKU', 'WIBB', 'Pekanbaru', 'Riau', 'Internasional'),
('Bandar Udara Internasional Minangkabau', 'PDG', 'WIPT', 'Padang', 'Sumatera Barat', 'Internasional'),
('Bandar Udara Internasional Sultan Mahmud Badaruddin II', 'PLM', 'WIPP', 'Palembang', 'Sumatera Selatan', 'Internasional'),
('Bandar Udara Internasional Radin Inten II', 'TKG', 'WILL', 'Bandar Lampung', 'Lampung', 'Internasional'),
('Bandar Udara Internasional Depati Amir', 'PGK', 'WIPK', 'Pangkal Pinang', 'Bangka Belitung', 'Internasional'),
('Bandar Udara Internasional Raja Haji Fisabilillah', 'TNJ', 'WIDN', 'Tanjung Pinang', 'Kepulauan Riau', 'Internasional'),
('Bandar Udara Internasional Hang Nadim', 'BTH', 'WIDD', 'Batam', 'Kepulauan Riau', 'Internasional'),
('Bandar Udara Internasional Supadio', 'PNK', 'WIOO', 'Pontianak', 'Kalimantan Barat', 'Internasional'),
('Bandar Udara Internasional Syamsudin Noor', 'BDJ', 'WAOO', 'Banjarmasin', 'Kalimantan Selatan', 'Internasional'),
('Bandar Udara Internasional Sultan Aji Muhammad Sulaiman Sepinggan', 'BPN', 'WALL', 'Balikpapan', 'Kalimantan Timur', 'Internasional'),
('Bandar Udara Internasional Juwata', 'TRK', 'WAQQ', 'Tarakan', 'Kalimantan Utara', 'Internasional'),
('Bandar Udara Internasional Mutiara SIS Al-Jufrie', 'PLW', 'WAFF', 'Palu', 'Sulawesi Tengah', 'Internasional'),
('Bandar Udara Internasional Haluoleo', 'KDI', 'WAWW', 'Kendari', 'Sulawesi Tenggara', 'Internasional'),
('Bandar Udara Internasional Betoambari', 'BUW', 'WAWB', 'Bau-Bau', 'Sulawesi Tenggara', 'Internasional'),
('Bandar Udara Internasional Sultan Babullah', 'TTE', 'WAMT', 'Ternate', 'Maluku Utara', 'Internasional'),
('Bandar Udara Internasional Pattimura', 'AMQ', 'WAPP', 'Ambon', 'Maluku', 'Internasional'),
('Bandar Udara Internasional Frans Kaisiepo', 'BIK', 'WABB', 'Biak', 'Papua', 'Internasional'),
('Bandar Udara Internasional Sentani', 'DJJ', 'WAJJ', 'Jayapura', 'Papua', 'Internasional'),
('Bandar Udara Internasional El Tari', 'KOE', 'WATT', 'Kupang', 'Nusa Tenggara Timur', 'Internasional'),
('Bandar Udara Internasional Lombok', 'LOP', 'WADL', 'Praya', 'Nusa Tenggara Barat', 'Internasional'),
('Bandar Udara Internasional Sultan Muhammad Kaharuddin III', 'SWQ', 'WADS', 'Sumbawa Besar', 'Nusa Tenggara Barat', 'Internasional'),
('Bandar Udara Internasional Komodo', 'LBJ', 'WATO', 'Labuan Bajo', 'Nusa Tenggara Timur', 'Internasional');

CREATE INDEX idx_bandara_iata ON bandara(iata);
CREATE INDEX idx_bandara_provinsi ON bandara(provinsi);
CREATE INDEX idx_bandara_jenis ON bandara(jenis);