const disasters = [
  // ========== BENCANA GEOLOGIS ==========
  { name: "Gempa Bumi", category: "Geologis", type: "Alam" },
  { name: "Gempa Bumi Tektonik", category: "Geologis", type: "Alam" },
  { name: "Gempa Bumi Vulkanik", category: "Geologis", type: "Alam" },
  { name: "Gempa Bumi Runtuhan", category: "Geologis", type: "Alam" },
  { name: "Gempa Bumi Buatan", category: "Geologis", type: "Alam" },
  { name: "Gempa Bumi Megathrust", category: "Geologis", type: "Alam" },
  { name: "Gempa Bumi Deep Focus", category: "Geologis", type: "Alam" },
  { name: "Gempa Bumi Shallow Focus", category: "Geologis", type: "Alam" },
  { name: "Gempa Bumi Interplate", category: "Geologis", type: "Alam" },
  { name: "Gempa Bumi Intraplate", category: "Geologis", type: "Alam" },
  { name: "Gempa Bumi Induced", category: "Geologis", type: "Alam" },
  { name: "Gempa Bumi Swarm", category: "Geologis", type: "Alam" },
  { name: "Gempa Bumi Foreshock", category: "Geologis", type: "Alam" },
  { name: "Gempa Bumi Aftershock", category: "Geologis", type: "Alam" },
  { name: "Gempa Bumi Mainshock", category: "Geologis", type: "Alam" },
  { name: "Tsunami", category: "Geologis", type: "Alam" },
  { name: "Tsunami Lokal", category: "Geologis", type: "Alam" },
  { name: "Tsunami Regional", category: "Geologis", type: "Alam" },
  { name: "Tsunami Trans-Ocean", category: "Geologis", type: "Alam" },
  { name: "Tsunami Tele-Tsunami", category: "Geologis", type: "Alam" },
  { name: "Tsunami Vulkanik", category: "Geologis", type: "Alam" },
  { name: "Tsunami Longsor", category: "Geologis", type: "Alam" },
  { name: "Tsunami Meteor", category: "Geologis", type: "Alam" },
  { name: "Letusan Gunung Berapi", category: "Geologis", type: "Alam" },
  { name: "Letusan Efusif", category: "Geologis", type: "Alam" },
  { name: "Letusan Eksplosif", category: "Geologis", type: "Alam" },
  { name: "Letusan Plinian", category: "Geologis", type: "Alam" },
  { name: "Letusan Vulcanian", category: "Geologis", type: "Alam" },
  { name: "Letusan Strombolian", category: "Geologis", type: "Alam" },
  { name: "Letusan Hawaiian", category: "Geologis", type: "Alam" },
  { name: "Letusan Pelean", category: "Geologis", type: "Alam" },
  { name: "Letusan Surtseyan", category: "Geologis", type: "Alam" },
  { name: "Letusan Subglasial", category: "Geologis", type: "Alam" },
  { name: "Letusan Freatik", category: "Geologis", type: "Alam" },
  { name: "Letusan Freatomagmatik", category: "Geologis", type: "Alam" },
  { name: "Letusan Supervolcano", category: "Geologis", type: "Alam" },
  { name: "Letusan Caldera", category: "Geologis", type: "Alam" },
  { name: "Letusan Lava Dome", category: "Geologis", type: "Alam" },
  { name: "Letusan Ash Fall", category: "Geologis", type: "Alam" },
  { name: "Letusan Pyroclastic Flow", category: "Geologis", type: "Alam" },
  { name: "Letusan Lahar", category: "Geologis", type: "Alam" },
  { name: "Letusan Gas Volcanic", category: "Geologis", type: "Alam" },
  { name: "Awan Panas Guguran", category: "Geologis", type: "Alam" },
  { name: "Hujan Abu Vulkanik", category: "Geologis", type: "Alam" },
  { name: "Lahar Panas", category: "Geologis", type: "Alam" },
  { name: "Lahar Dingin", category: "Geologis", type: "Alam" },
  { name: "Gas Beracun Vulkanik", category: "Geologis", type: "Alam" },
  { name: "Longsor", category: "Geologis", type: "Alam" },
  { name: "Longsor Tanah", category: "Geologis", type: "Alam" },
  { name: "Longsor Batuan", category: "Geologis", type: "Alam" },
  { name: "Longsor Puing", category: "Geologis", type: "Alam" },
  { name: "Longsor Lumpur", category: "Geologis", type: "Alam" },
  { name: "Longsor Bawah Laut", category: "Geologis", type: "Alam" },
  { name: "Longsor Salju", category: "Geologis", type: "Alam" },
  { name: "Avalanche", category: "Geologis", type: "Alam" },
  { name: "Rockfall", category: "Geologis", type: "Alam" },
  { name: "Debris Flow", category: "Geologis", type: "Alam" },
  { name: "Mudflow", category: "Geologis", type: "Alam" },
  { name: "Earthflow", category: "Geologis", type: "Alam" },
  { name: "Creep", category: "Geologis", type: "Alam" },
  { name: "Slump", category: "Geologis", type: "Alam" },
  { name: "Subsidence", category: "Geologis", type: "Alam" },
  { name: "Sinkhole", category: "Geologis", type: "Alam" },
  { name: "Amblesan Tanah", category: "Geologis", type: "Alam" },
  { name: "Erosi Tanah", category: "Geologis", type: "Alam" },
  { name: "Abrasi Pantai", category: "Geologis", type: "Alam" },
  { name: "Sedimentasi", category: "Geologis", type: "Alam" },
  { name: "Desertifikasi", category: "Geologis", type: "Alam" },
  { name: "Salinisasi Tanah", category: "Geologis", type: "Alam" },
  { name: "Pergerakan Tanah", category: "Geologis", type: "Alam" },
  { name: "Tanah Bergerak", category: "Geologis", type: "Alam" },
  { name: "Tanah Retak", category: "Geologis", type: "Alam" },
  { name: "Likuifaksi", category: "Geologis", type: "Alam" },
  { name: "Sesar Aktif", category: "Geologis", type: "Alam" },
  { name: "Patahan", category: "Geologis", type: "Alam" },
  { name: "Rift Valley", category: "Geologis", type: "Alam" },
  { name: "Geyser Erupsi", category: "Geologis", type: "Alam" },
  { name: "Fumarol", category: "Geologis", type: "Alam" },
  { name: "Solfatara", category: "Geologis", type: "Alam" },
  { name: "Mofet", category: "Geologis", type: "Alam" },
  { name: "Limbah Vulkanik", category: "Geologis", type: "Alam" },
  { name: "Banjir Lahar", category: "Geologis", type: "Alam" },
  { name: "Jökulhlaup", category: "Geologis", type: "Alam" },
  { name: "Glacial Lake Outburst Flood", category: "Geologis", type: "Alam" },
  { name: "Rock Avalanche", category: "Geologis", type: "Alam" },
  { name: "Debris Avalanche", category: "Geologis", type: "Alam" },
  { name: "Volcanic Bomb", category: "Geologis", type: "Alam" },
  { name: "Tephra Fall", category: "Geologis", type: "Alam" },
  { name: "Volcanic Lightning", category: "Geologis", type: "Alam" },
  { name: "Volcanic Winter", category: "Geologis", type: "Alam" },
  { name: "Impact Event", category: "Geologis", type: "Alam" },
  { name: "Meteor Jatuh", category: "Geologis", type: "Alam" },
  { name: "Meteorit", category: "Geologis", type: "Alam" },
  { name: "Asteroid Impact", category: "Geologis", type: "Alam" },
  { name: "Comet Impact", category: "Geologis", type: "Alam" },
  { name: "Airburst", category: "Geologis", type: "Alam" },

  // ========== BENCANA HIDROMETEOROLOGIS ==========
  { name: "Banjir", category: "Hidrometeorologis", type: "Alam" },
  { name: "Banjir Bandang", category: "Hidrometeorologis", type: "Alam" },
  { name: "Banjir Genangan", category: "Hidrometeorologis", type: "Alam" },
  { name: "Banjir Rob", category: "Hidrometeorologis", type: "Alam" },
  { name: "Banjir Pesisir", category: "Hidrometeorologis", type: "Alam" },
  { name: "Banjir Sungai", category: "Hidrometeorologis", type: "Alam" },
  { name: "Banjir Danau", category: "Hidrometeorologis", type: "Alam" },
  { name: "Banjir Lumpur", category: "Hidrometeorologis", type: "Alam" },
  { name: "Banjir Kilat", category: "Hidrometeorologis", type: "Alam" },
  { name: "Flash Flood", category: "Hidrometeorologis", type: "Alam" },
  { name: "Urban Flood", category: "Hidrometeorologis", type: "Alam" },
  { name: "Riverine Flood", category: "Hidrometeorologis", type: "Alam" },
  { name: "Coastal Flood", category: "Hidrometeorologis", type: "Alam" },
  { name: "Storm Surge", category: "Hidrometeorologis", type: "Alam" },
  { name: "Tidal Flood", category: "Hidrometeorologis", type: "Alam" },
  { name: "Ice Jam Flood", category: "Hidrometeorologis", type: "Alam" },
  { name: "Dam Break Flood", category: "Hidrometeorologis", type: "Alam" },
  { name: "Levee Failure", category: "Hidrometeorologis", type: "Alam" },
  { name: "Kekeringan", category: "Hidrometeorologis", type: "Alam" },
  { name: "Kekeringan Meteorologis", category: "Hidrometeorologis", type: "Alam" },
  { name: "Kekeringan Hidrologis", category: "Hidrometeorologis", type: "Alam" },
  { name: "Kekeringan Agrikultural", category: "Hidrometeorologis", type: "Alam" },
  { name: "Kekeringan Sosioekonomi", category: "Hidrometeorologis", type: "Alam" },
  { name: "El Niño", category: "Hidrometeorologis", type: "Alam" },
  { name: "La Niña", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Topan", category: "Hidrometeorologis", type: "Alam" },
  { name: "Siklon Tropis", category: "Hidrometeorologis", type: "Alam" },
  { name: "Hurikan", category: "Hidrometeorologis", type: "Alam" },
  { name: "Topan", category: "Hidrometeorologis", type: "Alam" },
  { name: "Badai Tropis", category: "Hidrometeorologis", type: "Alam" },
  { name: "Depresi Tropis", category: "Hidrometeorologis", type: "Alam" },
  { name: "Super Typhoon", category: "Hidrometeorologis", type: "Alam" },
  { name: "Super Cyclone", category: "Hidrometeorologis", type: "Alam" },
  { name: "Category 5 Hurricane", category: "Hidrometeorologis", type: "Alam" },
  { name: "Badai Ekstratropis", category: "Hidrometeorologis", type: "Alam" },
  { name: "Badai Subtropis", category: "Hidrometeorologis", type: "Alam" },
  { name: "Medicane", category: "Hidrometeorologis", type: "Alam" },
  { name: "Polar Low", category: "Hidrometeorologis", type: "Alam" },
  { name: "Badai Petir", category: "Hidrometeorologis", type: "Alam" },
  { name: "Badai Listrik", category: "Hidrometeorologis", type: "Alam" },
  { name: "Badai Es", category: "Hidrometeorologis", type: "Alam" },
  { name: "Hujan Es", category: "Hidrometeorologis", type: "Alam" },
  { name: "Hujan Batu", category: "Hidrometeorologis", type: "Alam" },
  { name: "Hujan Asam", category: "Hidrometeorologis", type: "Alam" },
  { name: "Hujan Deras", category: "Hidrometeorologis", type: "Alam" },
  { name: "Hujan Lebat", category: "Hidrometeorologis", type: "Alam" },
  { name: "Hujan Monsun", category: "Hidrometeorologis", type: "Alam" },
  { name: "Hujan Orografis", category: "Hidrometeorologis", type: "Alam" },
  { name: "Hujan Konvektif", category: "Hidrometeorologis", type: "Alam" },
  { name: "Hujan Frontal", category: "Hidrometeorologis", type: "Alam" },
  { name: "Hujan Siklonik", category: "Hidrometeorologis", type: "Alam" },
  { name: "Hujan Buatan", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Puting Beliung", category: "Hidrometeorologis", type: "Alam" },
  { name: "Tornado", category: "Hidrometeorologis", type: "Alam" },
  { name: "Waterspout", category: "Hidrometeorologis", type: "Alam" },
  { name: "Landspout", category: "Hidrometeorologis", type: "Alam" },
  { name: "Gustnado", category: "Hidrometeorologis", type: "Alam" },
  { name: "Dust Devil", category: "Hidrometeorologis", type: "Alam" },
  { name: "Fire Whirl", category: "Hidrometeorologis", type: "Alam" },
  { name: "Steam Devil", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Kencang", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Badai", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Monsun", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Darat", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Laut", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Fohn", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Chinook", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Santa Ana", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Mistral", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Bora", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Sirocco", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Harmattan", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Khamsin", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Shamal", category: "Hidrometeorologis", type: "Alam" },
  { name: "Angin Haboob", category: "Hidrometeorologis", type: "Alam" },
  { name: "Badai Debu", category: "Hidrometeorologis", type: "Alam" },
  { name: "Badai Pasir", category: "Hidrometeorologis", type: "Alam" },
  { name: "Dust Storm", category: "Hidrometeorologis", type: "Alam" },
  { name: "Sandstorm", category: "Hidrometeorologis", type: "Alam" },
  { name: "Blizzard", category: "Hidrometeorologis", type: "Alam" },
  { name: "Badai Salju", category: "Hidrometeorologis", type: "Alam" },
  { name: "Snowstorm", category: "Hidrometeorologis", type: "Alam" },
  { name: "Ground Blizzard", category: "Hidrometeorologis", type: "Alam" },
  { name: "Whiteout", category: "Hidrometeorologis", type: "Alam" },
  { name: "Ice Storm", category: "Hidrometeorologis", type: "Alam" },
  { name: "Freezing Rain", category: "Hidrometeorologis", type: "Alam" },
  { name: "Sleet", category: "Hidrometeorologis", type: "Alam" },
  { name: "Graupel", category: "Hidrometeorologis", type: "Alam" },
  { name: "Hailstorm", category: "Hidrometeorologis", type: "Alam" },
  { name: "Cold Wave", category: "Hidrometeorologis", type: "Alam" },
  { name: "Gelombang Dingin", category: "Hidrometeorologis", type: "Alam" },
  { name: "Heat Wave", category: "Hidrometeorologis", type: "Alam" },
  { name: "Gelombang Panas", category: "Hidrometeorologis", type: "Alam" },
  { name: "Heat Dome", category: "Hidrometeorologis", type: "Alam" },
  { name: "Frost", category: "Hidrometeorologis", type: "Alam" },
  { name: "Fog", category: "Hidrometeorologis", type: "Alam" },
  { name: "Kabut Tebal", category: "Hidrometeorologis", type: "Alam" },
  { name: "Smog", category: "Hidrometeorologis", type: "Alam" },
  { name: "Vog", category: "Hidrometeorologis", type: "Alam" },
  { name: "Haze", category: "Hidrometeorologis", type: "Alam" },
  { name: "Badai Matahari", category: "Hidrometeorologis", type: "Alam" },
  { name: "Solar Flare", category: "Hidrometeorologis", type: "Alam" },
  { name: "Coronal Mass Ejection", category: "Hidrometeorologis", type: "Alam" },
  { name: "Geomagnetic Storm", category: "Hidrometeorologis", type: "Alam" },
  { name: "Aurora", category: "Hidrometeorologis", type: "Alam" },
  { name: "Emp Solar", category: "Hidrometeorologis", type: "Alam" },
  { name: "Cosmic Ray", category: "Hidrometeorologis", type: "Alam" },
  { name: "Radiasi UV Ekstrem", category: "Hidrometeorologis", type: "Alam" },
  { name: "Lubang Ozon", category: "Hidrometeorologis", type: "Alam" },
  { name: "Pemanasan Global", category: "Hidrometeorologis", type: "Alam" },
  { name: "Perubahan Iklim", category: "Hidrometeorologis", type: "Alam" },
  { name: "Efek Rumah Kaca", category: "Hidrometeorologis", type: "Alam" },
  { name: "Kenaikan Permukaan Laut", category: "Hidrometeorologis", type: "Alam" },
  { name: "Intrusi Air Laut", category: "Hidrometeorologis", type: "Alam" },
  { name: "Erosi Pantai", category: "Hidrometeorologis", type: "Alam" },
  { name: "Abrasi", category: "Hidrometeorologis", type: "Alam" },
  { name: "Sedimentasi", category: "Hidrometeorologis", type: "Alam" },
  { name: "Pendangkalan", category: "Hidrometeorologis", type: "Alam" },
  { name: "Kekeringan Sungai", category: "Hidrometeorologis", type: "Alam" },
  { name: "Kekeringan Danau", category: "Hidrometeorologis", type: "Alam" },
  { name: "Kekeringan Air Tanah", category: "Hidrometeorologis", type: "Alam" },
  { name: "Kelaparan", category: "Hidrometeorologis", type: "Alam" },
  { name: "Krisis Pangan", category: "Hidrometeorologis", type: "Alam" },
  { name: "Krisis Air Bersih", category: "Hidrometeorologis", type: "Alam" },

  // ========== BENCANA BIOLOGIS ==========
  { name: "Pandemi", category: "Biologis", type: "Alam" },
  { name: "Epidemi", category: "Biologis", type: "Alam" },
  { name: "Endemi", category: "Biologis", type: "Alam" },
  { name: "Wabah Penyakit", category: "Biologis", type: "Alam" },
  { name: "Wabah Virus", category: "Biologis", type: "Alam" },
  { name: "Wabah Bakteri", category: "Biologis", type: "Alam" },
  { name: "Wabah Jamur", category: "Biologis", type: "Alam" },
  { name: "Wabah Parasit", category: "Biologis", type: "Alam" },
  { name: "Wabah Prion", category: "Biologis", type: "Alam" },
  { name: "Flu Burung", category: "Biologis", type: "Alam" },
  { name: "Flu Babi", category: "Biologis", type: "Alam" },
  { name: "Flu Spanyol", category: "Biologis", type: "Alam" },
  { name: "Flu Asia", category: "Biologis", type: "Alam" },
  { name: "Flu Hong Kong", category: "Biologis", type: "Alam" },
  { name: "SARS", category: "Biologis", type: "Alam" },
  { name: "MERS", category: "Biologis", type: "Alam" },
  { name: "COVID-19", category: "Biologis", type: "Alam" },
  { name: "Ebola", category: "Biologis", type: "Alam" },
  { name: "Marburg", category: "Biologis", type: "Alam" },
  { name: "Lassa Fever", category: "Biologis", type: "Alam" },
  { name: "Dengue", category: "Biologis", type: "Alam" },
  { name: "Malaria", category: "Biologis", type: "Alam" },
  { name: "Chikungunya", category: "Biologis", type: "Alam" },
  { name: "Zika", category: "Biologis", type: "Alam" },
  { name: "Yellow Fever", category: "Biologis", type: "Alam" },
  { name: "West Nile Fever", category: "Biologis", type: "Alam" },
  { name: "Japanese Encephalitis", category: "Biologis", type: "Alam" },
  { name: "Rabies", category: "Biologis", type: "Alam" },
  { name: "Anthrax", category: "Biologis", type: "Alam" },
  { name: "Plague", category: "Biologis", type: "Alam" },
  { name: "Cholera", category: "Biologis", type: "Alam" },
  { name: "Typhoid", category: "Biologis", type: "Alam" },
  { name: "Tuberculosis", category: "Biologis", type: "Alam" },
  { name: "HIV/AIDS", category: "Biologis", type: "Alam" },
  { name: "Hepatitis", category: "Biologis", type: "Alam" },
  { name: "Polio", category: "Biologis", type: "Alam" },
  { name: "Measles", category: "Biologis", type: "Alam" },
  { name: "Smallpox", category: "Biologis", type: "Alam" },
  { name: "Monkeypox", category: "Biologis", type: "Alam" },
  { name: "Nipah Virus", category: "Biologis", type: "Alam" },
  { name: "Hantavirus", category: "Biologis", type: "Alam" },
  { name: "Rift Valley Fever", category: "Biologis", type: "Alam" },
  { name: "Crimean-Congo Fever", category: "Biologis", type: "Alam" },
  { name: "Wabah Kolera", category: "Biologis", type: "Alam" },
  { name: "Wabah Pes", category: "Biologis", type: "Alam" },
  { name: "Black Death", category: "Biologis", type: "Alam" },
  { name: "Wabah Tifus", category: "Biologis", type: "Alam" },
  { name: "Wabah Difteri", category: "Biologis", type: "Alam" },
  { name: "Wabah Campak", category: "Biologis", type: "Alam" },
  { name: "Wabah Cacar", category: "Biologis", type: "Alam" },
  { name: "Wabah Demam Berdarah", category: "Biologis", type: "Alam" },
  { name: "Wabah Malaria", category: "Biologis", type: "Alam" },
  { name: "Wabah TBC", category: "Biologis", type: "Alam" },
  { name: "Wabah HIV", category: "Biologis", type: "Alam" },
  { name: "Wabah Hepatitis", category: "Biologis", type: "Alam" },
  { name: "Wabah Polio", category: "Biologis", type: "Alam" },
  { name: "Wabah Difteri", category: "Biologis", type: "Alam" },
  { name: "Wabah Pertusis", category: "Biologis", type: "Alam" },
  { name: "Wabah Tetanus", category: "Biologis", type: "Alam" },
  { name: "Wabah Rabies", category: "Biologis", type: "Alam" },
  { name: "Wabah Antraks", category: "Biologis", type: "Alam" },
  { name: "Wabah Leptospirosis", category: "Biologis", type: "Alam" },
  { name: "Wabah Toksoplasmosis", category: "Biologis", type: "Alam" },
  { name: "Wabah Cacingan", category: "Biologis", type: "Alam" },
  { name: "Wabah Jamur", category: "Biologis", type: "Alam" },
  { name: "Wabah Alga", category: "Biologis", type: "Alam" },
  { name: "Red Tide", category: "Biologis", type: "Alam" },
  { name: "Algal Bloom", category: "Biologis", type: "Alam" },
  { name: "Wabah Belalang", category: "Biologis", type: "Alam" },
  { name: "Wabah Tikus", category: "Biologis", type: "Alam" },
  { name: "Wabah Ulat", category: "Biologis", type: "Alam" },
  { name: "Wabah Serangga", category: "Biologis", type: "Alam" },
  { name: "Wabah Hama", category: "Biologis", type: "Alam" },
  { name: "Wabah Penyakit Tanaman", category: "Biologis", type: "Alam" },
  { name: "Wabah Penyakit Hewan", category: "Biologis", type: "Alam" },
  { name: "Wabah Penyakit Ikan", category: "Biologis", type: "Alam" },
  { name: "Wabah Penyakit Ternak", category: "Biologis", type: "Alam" },
  { name: "PMK", category: "Biologis", type: "Alam" },
  { name: "ASF", category: "Biologis", type: "Alam" },
  { name: "Avian Influenza", category: "Biologis", type: "Alam" },
  { name: "Swine Influenza", category: "Biologis", type: "Alam" },
  { name: "BSE", category: "Biologis", type: "Alam" },
  { name: "Scrapie", category: "Biologis", type: "Alam" },
  { name: "CWD", category: "Biologis", type: "Alam" },
  { name: "Invasif Spesies", category: "Biologis", type: "Alam" },
  { name: "Ledakan Populasi", category: "Biologis", type: "Alam" },
  { name: "Kepunahan Spesies", category: "Biologis", type: "Alam" },
  { name: "Krisis Biodiversitas", category: "Biologis", type: "Alam" },
  { name: "Kerusakan Ekosistem", category: "Biologis", type: "Alam" },
  { name: "Kerusakan Terumbu Karang", category: "Biologis", type: "Alam" },
  { name: "Coral Bleaching", category: "Biologis", type: "Alam" },
  { name: "Kerusakan Hutan Bakau", category: "Biologis", type: "Alam" },
  { name: "Deforestasi", category: "Biologis", type: "Alam" },
  { name: "Desertifikasi", category: "Biologis", type: "Alam" },
  { name: "Kebakaran Hutan", category: "Biologis", type: "Alam" },
  { name: "Kebakaran Lahan", category: "Biologis", type: "Alam" },
  { name: "Kebakaran Gambut", category: "Biologis", type: "Alam" },
  { name: "Kebakaran Semak", category: "Biologis", type: "Alam" },
  { name: "Kebakaran Padang Rumput", category: "Biologis", type: "Alam" },
  { name: "Wildfire", category: "Biologis", type: "Alam" },
  { name: "Bushfire", category: "Biologis", type: "Alam" },
  { name: "Forest Fire", category: "Biologis", type: "Alam" },
  { name: "Peat Fire", category: "Biologis", type: "Alam" },
  { name: "Firestorm", category: "Biologis", type: "Alam" },
  { name: "Crown Fire", category: "Biologis", type: "Alam" },
  { name: "Surface Fire", category: "Biologis", type: "Alam" },
  { name: "Ground Fire", category: "Biologis", type: "Alam" },
  { name: "Spot Fire", category: "Biologis", type: "Alam" },
  { name: "Fire Tornado", category: "Biologis", type: "Alam" },

  // ========== BENCANA TEKNOLOGI ==========
  { name: "Kecelakaan Industri", category: "Teknologi", type: "Non-Alam" },
  { name: "Kebocoran Gas", category: "Teknologi", type: "Non-Alam" },
  { name: "Ledakan Pabrik", category: "Teknologi", type: "Non-Alam" },
  { name: "Kebakaran Pabrik", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Kerja", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Tambang", category: "Teknologi", type: "Non-Alam" },
  { name: "Ledakan Tambang", category: "Teknologi", type: "Non-Alam" },
  { name: "Runtuhan Tambang", category: "Teknologi", type: "Non-Alam" },
  { name: "Kebocoran Radioaktif", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Nuklir", category: "Teknologi", type: "Non-Alam" },
  { name: "Meltdown Nuklir", category: "Teknologi", type: "Non-Alam" },
  { name: "Ledakan Nuklir", category: "Teknologi", type: "Non-Alam" },
  { name: "Perang Nuklir", category: "Teknologi", type: "Non-Alam" },
  { name: "EMP Nuklir", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Kimia", category: "Teknologi", type: "Non-Alam" },
  { name: "Kebocoran Kimia", category: "Teknologi", type: "Non-Alam" },
  { name: "Tumpahan Minyak", category: "Teknologi", type: "Non-Alam" },
  { name: "Tumpahan Gas", category: "Teknologi", type: "Non-Alam" },
  { name: "Tumpahan Bahan Bakar", category: "Teknologi", type: "Non-Alam" },
  { name: "Tumpahan Zat Beracun", category: "Teknologi", type: "Non-Alam" },
  { name: "Pencemaran Air", category: "Teknologi", type: "Non-Alam" },
  { name: "Pencemaran Udara", category: "Teknologi", type: "Non-Alam" },
  { name: "Pencemaran Tanah", category: "Teknologi", type: "Non-Alam" },
  { name: "Pencemaran Laut", category: "Teknologi", type: "Non-Alam" },
  { name: "Pencemaran Sungai", category: "Teknologi", type: "Non-Alam" },
  { name: "Pencemaran Danau", category: "Teknologi", type: "Non-Alam" },
  { name: "Pencemaran Air Tanah", category: "Teknologi", type: "Non-Alam" },
  { name: "Hujan Asam", category: "Teknologi", type: "Non-Alam" },
  { name: "Limbah B3", category: "Teknologi", type: "Non-Alam" },
  { name: "Limbah Industri", category: "Teknologi", type: "Non-Alam" },
  { name: "Limbah Medis", category: "Teknologi", type: "Non-Alam" },
  { name: "Limbah Nuklir", category: "Teknologi", type: "Non-Alam" },
  { name: "Limbah Plastik", category: "Teknologi", type: "Non-Alam" },
  { name: "Mikroplastik", category: "Teknologi", type: "Non-Alam" },
  { name: "Sampah Antariksa", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Pesawat", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Helikopter", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Kapal", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Kereta", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Bus", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Truk", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Mobil", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Motor", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Sepeda", category: "Teknologi", type: "Non-Alam" },
  { name: "Tabrakan Kapal", category: "Teknologi", type: "Non-Alam" },
  { name: "Kapal Tenggelam", category: "Teknologi", type: "Non-Alam" },
  { name: "Kapal Kandas", category: "Teknologi", type: "Non-Alam" },
  { name: "Pesawat Jatuh", category: "Teknologi", type: "Non-Alam" },
  { name: "Pesawat Hilang", category: "Teknologi", type: "Non-Alam" },
  { name: "Kereta Anjlok", category: "Teknologi", type: "Non-Alam" },
  { name: "Kereta Tabrakan", category: "Teknologi", type: "Non-Alam" },
  { name: "Jembatan Roboh", category: "Teknologi", type: "Non-Alam" },
  { name: "Gedung Roboh", category: "Teknologi", type: "Non-Alam" },
  { name: "Bendungan Jebol", category: "Teknologi", type: "Non-Alam" },
  { name: "Tanggul Jebol", category: "Teknologi", type: "Non-Alam" },
  { name: "Terowongan Runtuh", category: "Teknologi", type: "Non-Alam" },
  { name: "Jalan Runtuh", category: "Teknologi", type: "Non-Alam" },
  { name: "Tanah Longsor Jalan", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Struktur", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Sistem", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Listrik", category: "Teknologi", type: "Non-Alam" },
  { name: "Blackout", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Air", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Gas", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Telekomunikasi", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Internet", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Satelit", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Komputer", category: "Teknologi", type: "Non-Alam" },
  { name: "Serangan Siber", category: "Teknologi", type: "Non-Alam" },
  { name: "Perang Siber", category: "Teknologi", type: "Non-Alam" },
  { name: "Malware", category: "Teknologi", type: "Non-Alam" },
  { name: "Ransomware", category: "Teknologi", type: "Non-Alam" },
  { name: "Phishing", category: "Teknologi", type: "Non-Alam" },
  { name: "DDoS", category: "Teknologi", type: "Non-Alam" },
  { name: "Data Breach", category: "Teknologi", type: "Non-Alam" },
  { name: "Identity Theft", category: "Teknologi", type: "Non-Alam" },
  { name: "Deepfake", category: "Teknologi", type: "Non-Alam" },
  { name: "AI Failure", category: "Teknologi", type: "Non-Alam" },
  { name: "Robot Malfunction", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Robot", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Otonom", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Drone", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Roket", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Satelit", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Stasiun Ruang", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Laboratorium", category: "Teknologi", type: "Non-Alam" },
  { name: "Kecelakaan Biologi", category: "Teknologi", type: "Non-Alam" },
  { name: "Kebocoran Virus", category: "Teknologi", type: "Non-Alam" },
  { name: "Kebocoran Bakteri", category: "Teknologi", type: "Non-Alam" },
  { name: "Senjata Biologi", category: "Teknologi", type: "Non-Alam" },
  { name: "Senjata Kimia", category: "Teknologi", type: "Non-Alam" },
  { name: "Senjata Nuklir", category: "Teknologi", type: "Non-Alam" },
  { name: "Perang Konvensional", category: "Teknologi", type: "Non-Alam" },
  { name: "Perang Saudara", category: "Teknologi", type: "Non-Alam" },
  { name: "Genosida", category: "Teknologi", type: "Non-Alam" },
  { name: "Terorisme", category: "Teknologi", type: "Non-Alam" },
  { name: "Bom", category: "Teknologi", type: "Non-Alam" },
  { name: "Bom Bunuh Diri", category: "Teknologi", type: "Non-Alam" },
  { name: "Penembakan Massal", category: "Teknologi", type: "Non-Alam" },
  { name: "Kerusuhan", category: "Teknologi", type: "Non-Alam" },
  { name: "Demonstrasi Kekerasan", category: "Teknologi", type: "Non-Alam" },
  { name: "Kudeta", category: "Teknologi", type: "Non-Alam" },
  { name: "Revolusi", category: "Teknologi", type: "Non-Alam" },
  { name: "Invasi", category: "Teknologi", type: "Non-Alam" },
  { name: "Blokade", category: "Teknologi", type: "Non-Alam" },
  { name: "Embargo", category: "Teknologi", type: "Non-Alam" },
  { name: "Krisis Ekonomi", category: "Teknologi", type: "Non-Alam" },
  { name: "Depresi Ekonomi", category: "Teknologi", type: "Non-Alam" },
  { name: "Resesi", category: "Teknologi", type: "Non-Alam" },
  { name: "Hiperinflasi", category: "Teknologi", type: "Non-Alam" },
  { name: "Krisis Moneter", category: "Teknologi", type: "Non-Alam" },
  { name: "Krisis Perbankan", category: "Teknologi", type: "Non-Alam" },
  { name: "Krisis Utang", category: "Teknologi", type: "Non-Alam" },
  { name: "Krisis Pangan", category: "Teknologi", type: "Non-Alam" },
  { name: "Krisis Energi", category: "Teknologi", type: "Non-Alam" },
  { name: "Krisis Air", category: "Teknologi", type: "Non-Alam" },
  { name: "Krisis Perumahan", category: "Teknologi", type: "Non-Alam" },
  { name: "Krisis Pengungsi", category: "Teknologi", type: "Non-Alam" },
  { name: "Krisis Kemanusiaan", category: "Teknologi", type: "Non-Alam" },
  { name: "Kelaparan", category: "Teknologi", type: "Non-Alam" },
  { name: "Malnutrisi", category: "Teknologi", type: "Non-Alam" },
  { name: "Penyakit Sosial", category: "Teknologi", type: "Non-Alam" },
  { name: "Kemiskinan Ekstrem", category: "Teknologi", type: "Non-Alam" },
  { name: "Pengangguran Massal", category: "Teknologi", type: "Non-Alam" },
  { name: "Kejahatan Massal", category: "Teknologi", type: "Non-Alam" },
  { name: "Korupsi Massal", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Negara", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Pemerintahan", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Diplomasi", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Kebijakan", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Sistem Kesehatan", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Sistem Pendidikan", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Sistem Pangan", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Sistem Energi", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Sistem Transportasi", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Sistem Komunikasi", category: "Teknologi", type: "Non-Alam" },
  { name: "Kegagalan Sistem Keuangan", category: "Teknologi", type: "Non-Alam" },

  // ========== BENCANA LINGKUNGAN ==========
  { name: "Kerusakan Lingkungan", category: "Lingkungan", type: "Non-Alam" },
  { name: "Polusi Udara", category: "Lingkungan", type: "Non-Alam" },
  { name: "Polusi Air", category: "Lingkungan", type: "Non-Alam" },
  { name: "Polusi Tanah", category: "Lingkungan", type: "Non-Alam" },
  { name: "Polusi Suara", category: "Lingkungan", type: "Non-Alam" },
  { name: "Polusi Cahaya", category: "Lingkungan", type: "Non-Alam" },
  { name: "Polusi Termal", category: "Lingkungan", type: "Non-Alam" },
  { name: "Polusi Radioaktif", category: "Lingkungan", type: "Non-Alam" },
  { name: "Polusi Elektromagnetik", category: "Lingkungan", type: "Non-Alam" },
  { name: "Polusi Plastik", category: "Lingkungan", type: "Non-Alam" },
  { name: "Polusi Mikroplastik", category: "Lingkungan", type: "Non-Alam" },
  { name: "Polusi Kimia", category: "Lingkungan", type: "Non-Alam" },
  { name: "Polusi Logam Berat", category: "Lingkungan", type: "Non-Alam" },
  { name: "Polusi Pestisida", category: "Lingkungan", type: "Non-Alam" },
  { name: "Polusi Pupuk", category: "Lingkungan", type: "Non-Alam" },
  { name: "Eutrofikasi", category: "Lingkungan", type: "Non-Alam" },
  { name: "Algal Bloom", category: "Lingkungan", type: "Non-Alam" },
  { name: "Red Tide", category: "Lingkungan", type: "Non-Alam" },
  { name: "Dead Zone", category: "Lingkungan", type: "Non-Alam" },
  { name: "Hypoxia", category: "Lingkungan", type: "Non-Alam" },
  { name: "Acidification", category: "Lingkungan", type: "Non-Alam" },
  { name: "Ocean Acidification", category: "Lingkungan", type: "Non-Alam" },
  { name: "Coral Bleaching", category: "Lingkungan", type: "Non-Alam" },
  { name: "Deforestasi", category: "Lingkungan", type: "Non-Alam" },
  { name: "Desertifikasi", category: "Lingkungan", type: "Non-Alam" },
  { name: "Degradasi Lahan", category: "Lingkungan", type: "Non-Alam" },
  { name: "Erosi Tanah", category: "Lingkungan", type: "Non-Alam" },
  { name: "Salinisasi", category: "Lingkungan", type: "Non-Alam" },
  { name: "Waterlogging", category: "Lingkungan", type: "Non-Alam" },
  { name: "Intrusi Air Laut", category: "Lingkungan", type: "Non-Alam" },
  { name: "Penurunan Muka Tanah", category: "Lingkungan", type: "Non-Alam" },
  { name: "Subsidence", category: "Lingkungan", type: "Non-Alam" },
  { name: "Abrasi Pantai", category: "Lingkungan", type: "Non-Alam" },
  { name: "Erosi Pantai", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Terumbu Karang", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Hutan Bakau", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Padang Lamun", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Lahan Basah", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Gambut", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Hutan", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Savana", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Padang Rumput", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Gunung", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Sungai", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Danau", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Rawa", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Estuari", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Delta", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Pesisir", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Pulau", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Laut", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Samudra", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Atmosfer", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kerusakan Ozon", category: "Lingkungan", type: "Non-Alam" },
  { name: "Pemanasan Global", category: "Lingkungan", type: "Non-Alam" },
  { name: "Perubahan Iklim", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kenaikan Permukaan Laut", category: "Lingkungan", type: "Non-Alam" },
  { name: "Pencairan Es", category: "Lingkungan", type: "Non-Alam" },
  { name: "Pencairan Glasier", category: "Lingkungan", type: "Non-Alam" },
  { name: "Pencairan Permafrost", category: "Lingkungan", type: "Non-Alam" },
  { name: "Pencairan Lapisan Es", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kenaikan Suhu Laut", category: "Lingkungan", type: "Non-Alam" },
  { name: "Marine Heatwave", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kenaikan Suhu Udara", category: "Lingkungan", type: "Non-Alam" },
  { name: "Urban Heat Island", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kekeringan", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kelangkaan Air", category: "Lingkungan", type: "Non-Alam" },
  { name: "Krisis Air Bersih", category: "Lingkungan", type: "Non-Alam" },
  { name: "Krisis Pangan", category: "Lingkungan", type: "Non-Alam" },
  { name: "Krisis Energi", category: "Lingkungan", type: "Non-Alam" },
  { name: "Krisis Ekosistem", category: "Lingkungan", type: "Non-Alam" },
  { name: "Krisis Biodiversitas", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kepunahan Massal", category: "Lingkungan", type: "Non-Alam" },
  { name: "Kepunahan Spesies", category: "Lingkungan", type: "Non-Alam" },
  { name: "Invasi Spesies Asing", category: "Lingkungan", type: "Non-Alam" },
  { name: "Ledakan Populasi", category: "Lingkungan", type: "Non-Alam" },
  { name: "Overpopulasi", category: "Lingkungan", type: "Non-Alam" },
  { name: "Overeksploitasi", category: "Lingkungan", type: "Non-Alam" },
  { name: "Overfishing", category: "Lingkungan", type: "Non-Alam" },
  { name: "Overhunting", category: "Lingkungan", type: "Non-Alam" },
  { name: "Overlogging", category: "Lingkungan", type: "Non-Alam" },
  { name: "Overgrazing", category: "Lingkungan", type: "Non-Alam" },
  { name: "Overirigasi", category: "Lingkungan", type: "Non-Alam" },
  { name: "Overfertilisasi", category: "Lingkungan", type: "Non-Alam" },
  { name: "Overurbanisasi", category: "Lingkungan", type: "Non-Alam" },
  { name: "Urbanisasi Cepat", category: "Lingkungan", type: "Non-Alam" },
  { name: "Slum", category: "Lingkungan", type: "Non-Alam" },
  { name: "Sanitasi Buruk", category: "Lingkungan", type: "Non-Alam" },
  { name: "Air Kotor", category: "Lingkungan", type: "Non-Alam" },
  { name: "Limbah Padat", category: "Lingkungan", type: "Non-Alam" },
  { name: "Limbah Cair", category: "Lingkungan", type: "Non-Alam" },
  { name: "Limbah Gas", category: "Lingkungan", type: "Non-Alam" },
  { name: "Limbah B3", category: "Lingkungan", type: "Non-Alam" },
  { name: "Limbah Medis", category: "Lingkungan", type: "Non-Alam" },
  { name: "Limbah Nuklir", category: "Lingkungan", type: "Non-Alam" },
  { name: "Limbah Elektronik", category: "Lingkungan", type: "Non-Alam" },
  { name: "Limbah Plastik", category: "Lingkungan", type: "Non-Alam" },
  { name: "Sampah Antariksa", category: "Lingkungan", type: "Non-Alam" },

  // ========== BENCANA SOSIAL ==========
  { name: "Perang", category: "Sosial", type: "Non-Alam" },
  { name: "Perang Dunia", category: "Sosial", type: "Non-Alam" },
  { name: "Perang Saudara", category: "Sosial", type: "Non-Alam" },
  { name: "Perang Proxy", category: "Sosial", type: "Non-Alam" },
  { name: "Perang Dingin", category: "Sosial", type: "Non-Alam" },
  { name: "Perang Nuklir", category: "Sosial", type: "Non-Alam" },
  { name: "Perang Biologi", category: "Sosial", type: "Non-Alam" },
  { name: "Perang Kimia", category: "Sosial", type: "Non-Alam" },
  { name: "Perang Siber", category: "Sosial", type: "Non-Alam" },
  { name: "Perang Informasi", category: "Sosial", type: "Non-Alam" },
  { name: "Perang Ekonomi", category: "Sosial", type: "Non-Alam" },
  { name: "Perang Dagang", category: "Sosial", type: "Non-Alam" },
  { name: "Perang Mata Uang", category: "Sosial", type: "Non-Alam" },
  { name: "Perang Teknologi", category: "Sosial", type: "Non-Alam" },
  { name: "Perang Antariksa", category: "Sosial", type: "Non-Alam" },
  { name: "Genosida", category: "Sosial", type: "Non-Alam" },
  { name: "Etnis Cleansing", category: "Sosial", type: "Non-Alam" },
  { name: "Holocaust", category: "Sosial", type: "Non-Alam" },
  { name: "Pogrom", category: "Sosial", type: "Non-Alam" },
  { name: "Massacre", category: "Sosial", type: "Non-Alam" },
  { name: "Terorisme", category: "Sosial", type: "Non-Alam" },
  { name: "Terorisme Negara", category: "Sosial", type: "Non-Alam" },
  { name: "Terorisme Agama", category: "Sosial", type: "Non-Alam" },
  { name: "Terorisme Politik", category: "Sosial", type: "Non-Alam" },
  { name: "Terorisme Siber", category: "Sosial", type: "Non-Alam" },
  { name: "Bom Bunuh Diri", category: "Sosial", type: "Non-Alam" },
  { name: "Penembakan Massal", category: "Sosial", type: "Non-Alam" },
  { name: "Pembantaian", category: "Sosial", type: "Non-Alam" },
  { name: "Kerusuhan", category: "Sosial", type: "Non-Alam" },
  { name: "Demonstrasi Kekerasan", category: "Sosial", type: "Non-Alam" },
  { name: "Revolusi", category: "Sosial", type: "Non-Alam" },
  { name: "Kudeta", category: "Sosial", type: "Non-Alam" },
  { name: "Invasi", category: "Sosial", type: "Non-Alam" },
  { name: "Aneksasi", category: "Sosial", type: "Non-Alam" },
  { name: "Kolonialisme", category: "Sosial", type: "Non-Alam" },
  { name: "Imperialisme", category: "Sosial", type: "Non-Alam" },
  { name: "Apartheid", category: "Sosial", type: "Non-Alam" },
  { name: "Diskriminasi", category: "Sosial", type: "Non-Alam" },
  { name: "Rasisme", category: "Sosial", type: "Non-Alam" },
  { name: "Xenophobia", category: "Sosial", type: "Non-Alam" },
  { name: "Islamophobia", category: "Sosial", type: "Non-Alam" },
  { name: "Anti-Semitisme", category: "Sosial", type: "Non-Alam" },
  { name: "Homophobia", category: "Sosial", type: "Non-Alam" },
  { name: "Gender Discrimination", category: "Sosial", type: "Non-Alam" },
  { name: "Perbudakan", category: "Sosial", type: "Non-Alam" },
  { name: "Human Trafficking", category: "Sosial", type: "Non-Alam" },
  { name: "Child Labor", category: "Sosial", type: "Non-Alam" },
  { name: "Forced Labor", category: "Sosial", type: "Non-Alam" },
  { name: "Refugee Crisis", category: "Sosial", type: "Non-Alam" },
  { name: "IDP Crisis", category: "Sosial", type: "Non-Alam" },
  { name: "Statelessness", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kemanusiaan", category: "Sosial", type: "Non-Alam" },
  { name: "Kelaparan", category: "Sosial", type: "Non-Alam" },
  { name: "Malnutrisi", category: "Sosial", type: "Non-Alam" },
  { name: "Kemiskinan Ekstrem", category: "Sosial", type: "Non-Alam" },
  { name: "Kesenjangan Sosial", category: "Sosial", type: "Non-Alam" },
  { name: "Pengangguran Massal", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Perumahan", category: "Sosial", type: "Non-Alam" },
  { name: "Homelessness", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pendidikan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kesehatan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Moral", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kepercayaan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Demokrasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis HAM", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Hukum", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Korupsi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Tata Kelola", category: "Sosial", type: "Non-Alam" },
  { name: "Kegagalan Negara", category: "Sosial", type: "Non-Alam" },
  { name: "Failed State", category: "Sosial", type: "Non-Alam" },
  { name: "Fragile State", category: "Sosial", type: "Non-Alam" },
  { name: "Rogue State", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Diplomatik", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Politik", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Konstitusi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pemilu", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pemerintahan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kabinet", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Koalisi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Parlemen", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Yudisial", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Militer", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Keamanan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Ketertiban", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Sosial", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Budaya", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Identitas", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Agama", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Etnis", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Ras", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Gender", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Generasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Keluarga", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Anak", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Remaja", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Lansia", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Disabilitas", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Minoritas", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Masyarakat Adat", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Buruh", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Petani", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Nelayan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pedagang", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis UMKM", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Industri", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pertanian", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Perikanan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Peternakan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kehutanan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pertambangan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Energi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Transportasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Logistik", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Rantai Pasok", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pangan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Air", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Sanitasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kesehatan Mental", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Narkoba", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Alkohol", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Rokok", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Judi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Prostitusi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kriminalitas", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kekerasan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kejahatan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Korupsi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kolusi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Nepotisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Oligarki", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kleptokrasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Autokrasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Totaliterisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Fasisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Komunisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kapitalisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Sosialisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Demokrasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Liberalisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Konservatisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Nasionalisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Globalisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Populisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Fundamentalisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Ekstremisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Radikalisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Separatisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Nasionalisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Integrasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Disintegrasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Federalisme", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Otonomi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Desentralisasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Sentralisasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Birokrasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Regulasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Deregulasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Privatisasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Nasionalisasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Subsidi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pajak", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Fiskal", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Moneter", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Perbankan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Utang", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Inflasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Deflasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Stagflasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Resesi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Depresi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Ekonomi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Keuangan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pasar", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Bursa", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Properti", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Komoditas", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Minyak", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Gas", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Batu Bara", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Listrik", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis BBM", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pupuk", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pangan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Air", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Sandang", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Papan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kesehatan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pendidikan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Lapangan Kerja", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Upah", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kesejahteraan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Jaminan Sosial", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pensiun", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kesehatan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Demografi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Populasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Migrasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Urbanisasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Perkotaan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pedesaan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pertanian", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Industri", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Jasa", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Perdagangan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Investasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Produksi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Distribusi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Konsumsi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Permintaan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Penawaran", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Rantai Pasok", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Logistik", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Transportasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Komunikasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Informasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Data", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Privasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Keamanan Siber", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Energi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Lingkungan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Iklim", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Ekologi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Biodiversitas", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Sumber Daya", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Air", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pangan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Energi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Mineral", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Logam", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Tanah", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Hutan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Laut", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Perikanan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pertanian", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Peternakan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kesehatan Hewan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kesehatan Tanaman", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pangan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Gizi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kesehatan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Obat", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Vaksin", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Rumah Sakit", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Tenaga Medis", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kesehatan Mental", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pendidikan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Guru", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Sekolah", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Universitas", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Riset", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Inovasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Teknologi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Digital", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis AI", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Robot", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Otomasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Lapangan Kerja", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Upah", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kesejahteraan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pensiun", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Jaminan Sosial", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Kesehatan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Demografi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Populasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Migrasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Urbanisasi", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Perkotaan", category: "Sosial", type: "Non-Alam" },
  { name: "Krisis Pedesaan", category: "Sosial", type: "Non-Alam" }
];