-- ============================================================
-- DATABASE: LAGU TRENDING SPOTIFY
-- File: lagu_trending_spotify.sql
-- Konversi lengkap dari php.txt
-- ============================================================

DROP TABLE IF EXISTS lagu_trending_spotify;

CREATE TABLE lagu_trending_spotify (
    id INT AUTO_INCREMENT PRIMARY KEY,
    judul VARCHAR(255) NOT NULL,
    artis VARCHAR(255),
    genre VARCHAR(100),
    tahun YEAR,
    negara VARCHAR(100),
    INDEX idx_judul (judul),
    INDEX idx_artis (artis),
    INDEX idx_genre (genre),
    INDEX idx_tahun (tahun),
    INDEX idx_negara (negara)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==================== POP INTERNASIONAL ====================
INSERT INTO lagu_trending_spotify (judul, artis, genre, tahun, negara) VALUES
('Blinding Lights', 'The Weeknd', 'Pop', 2019, 'Kanada'),
('Save Your Tears', 'The Weeknd', 'Pop', 2020, 'Kanada'),
('Starboy', 'The Weeknd', 'Pop', 2016, 'Kanada'),
('Die For You', 'The Weeknd', 'Pop', 2016, 'Kanada'),
('Shape of You', 'Ed Sheeran', 'Pop', 2017, 'Inggris'),
('Perfect', 'Ed Sheeran', 'Pop', 2017, 'Inggris'),
('Photograph', 'Ed Sheeran', 'Pop', 2014, 'Inggris'),
('Thinking Out Loud', 'Ed Sheeran', 'Pop', 2014, 'Inggris'),
('Bad Habits', 'Ed Sheeran', 'Pop', 2021, 'Inggris'),
('Shivers', 'Ed Sheeran', 'Pop', 2021, 'Inggris'),
('Castle on the Hill', 'Ed Sheeran', 'Pop', 2017, 'Inggris'),
('Happier', 'Ed Sheeran', 'Pop', 2017, 'Inggris'),
('Anti-Hero', 'Taylor Swift', 'Pop', 2022, 'Amerika'),
('Cruel Summer', 'Taylor Swift', 'Pop', 2019, 'Amerika'),
('Blank Space', 'Taylor Swift', 'Pop', 2014, 'Amerika'),
('Shake It Off', 'Taylor Swift', 'Pop', 2014, 'Amerika'),
('Love Story', 'Taylor Swift', 'Pop', 2008, 'Amerika'),
('You Belong With Me', 'Taylor Swift', 'Pop', 2008, 'Amerika'),
('Wildest Dreams', 'Taylor Swift', 'Pop', 2014, 'Amerika'),
('Style', 'Taylor Swift', 'Pop', 2014, 'Amerika'),
('Cardigan', 'Taylor Swift', 'Pop', 2020, 'Amerika'),
('Willow', 'Taylor Swift', 'Pop', 2020, 'Amerika'),
('Lavender Haze', 'Taylor Swift', 'Pop', 2022, 'Amerika'),
('Karma', 'Taylor Swift', 'Pop', 2022, 'Amerika'),
('As It Was', 'Harry Styles', 'Pop', 2022, 'Inggris'),
('Watermelon Sugar', 'Harry Styles', 'Pop', 2019, 'Inggris'),
('Adore You', 'Harry Styles', 'Pop', 2019, 'Inggris'),
('Sign of the Times', 'Harry Styles', 'Pop', 2017, 'Inggris'),
('Late Night Talking', 'Harry Styles', 'Pop', 2022, 'Inggris'),
('Levitating', 'Dua Lipa', 'Pop', 2020, 'Inggris'),
('Don''t Start Now', 'Dua Lipa', 'Pop', 2019, 'Inggris'),
('New Rules', 'Dua Lipa', 'Pop', 2017, 'Inggris'),
('One Kiss', 'Calvin Harris, Dua Lipa', 'Pop', 2018, 'Inggris'),
('Cold Heart', 'Elton John, Dua Lipa', 'Pop', 2021, 'Inggris'),
('Dance Monkey', 'Tones and I', 'Pop', 2019, 'Australia'),
('Someone You Loved', 'Lewis Capaldi', 'Pop', 2018, 'Skotlandia'),
('Before You Go', 'Lewis Capaldi', 'Pop', 2019, 'Skotlandia'),
('Hold Me While You Wait', 'Lewis Capaldi', 'Pop', 2019, 'Skotlandia'),
('Bad Guy', 'Billie Eilish', 'Pop', 2019, 'Amerika'),
('Happier Than Ever', 'Billie Eilish', 'Pop', 2021, 'Amerika'),
('Ocean Eyes', 'Billie Eilish', 'Pop', 2016, 'Amerika'),
('Lovely', 'Billie Eilish, Khalid', 'Pop', 2018, 'Amerika'),
('What Was I Made For?', 'Billie Eilish', 'Pop', 2023, 'Amerika'),
('Flowers', 'Miley Cyrus', 'Pop', 2023, 'Amerika'),
('Wrecking Ball', 'Miley Cyrus', 'Pop', 2013, 'Amerika'),
('Party in the U.S.A.', 'Miley Cyrus', 'Pop', 2009, 'Amerika'),
('Midnight Sky', 'Miley Cyrus', 'Pop', 2020, 'Amerika'),
('Shallow', 'Lady Gaga, Bradley Cooper', 'Pop', 2018, 'Amerika'),
('Bad Romance', 'Lady Gaga', 'Pop', 2009, 'Amerika'),
('Poker Face', 'Lady Gaga', 'Pop', 2008, 'Amerika'),
('Just Dance', 'Lady Gaga', 'Pop', 2008, 'Amerika'),
('Always Remember Us This Way', 'Lady Gaga', 'Pop', 2018, 'Amerika'),
('Rain On Me', 'Lady Gaga, Ariana Grande', 'Pop', 2020, 'Amerika'),
('7 Rings', 'Ariana Grande', 'Pop', 2019, 'Amerika'),
('Thank U, Next', 'Ariana Grande', 'Pop', 2018, 'Amerika'),
('Into You', 'Ariana Grande', 'Pop', 2016, 'Amerika'),
('Side to Side', 'Ariana Grande', 'Pop', 2016, 'Amerika'),
('Positions', 'Ariana Grande', 'Pop', 2020, 'Amerika'),
('Save Your Tears Remix', 'The Weeknd, Ariana Grande', 'Pop', 2021, 'Amerika'),
('We Can''t Be Friends', 'Ariana Grande', 'Pop', 2024, 'Amerika'),
('Sunflower', 'Post Malone, Swae Lee', 'Pop', 2018, 'Amerika'),
('Circles', 'Post Malone', 'Pop', 2019, 'Amerika'),
('Rockstar', 'Post Malone, 21 Savage', 'Hip-Hop', 2017, 'Amerika'),
('Better Now', 'Post Malone', 'Pop', 2018, 'Amerika'),
('I Fall Apart', 'Post Malone', 'Pop', 2016, 'Amerika'),
('Congratulations', 'Post Malone', 'Hip-Hop', 2016, 'Amerika'),
('Ghost', 'Justin Bieber', 'Pop', 2021, 'Kanada'),
('Peaches', 'Justin Bieber', 'Pop', 2021, 'Kanada'),
('Sorry', 'Justin Bieber', 'Pop', 2015, 'Kanada'),
('Love Yourself', 'Justin Bieber', 'Pop', 2015, 'Kanada'),
('What Do You Mean?', 'Justin Bieber', 'Pop', 2015, 'Kanada'),
('Baby', 'Justin Bieber', 'Pop', 2010, 'Kanada'),
('Stay', 'Kid LAROI, Justin Bieber', 'Pop', 2021, 'Australia'),
('Intentions', 'Justin Bieber', 'Pop', 2020, 'Kanada'),
('Yummy', 'Justin Bieber', 'Pop', 2020, 'Kanada'),
('Uptown Funk', 'Mark Ronson, Bruno Mars', 'Pop', 2014, 'Inggris'),
('Just the Way You Are', 'Bruno Mars', 'Pop', 2010, 'Amerika'),
('Grenade', 'Bruno Mars', 'Pop', 2010, 'Amerika'),
('Locked Out of Heaven', 'Bruno Mars', 'Pop', 2012, 'Amerika'),
('When I Was Your Man', 'Bruno Mars', 'Pop', 2012, 'Amerika'),
('Talking to the Moon', 'Bruno Mars', 'Pop', 2010, 'Amerika'),
('That''s What I Like', 'Bruno Mars', 'Pop', 2016, 'Amerika'),
('The Lazy Song', 'Bruno Mars', 'Pop', 2010, 'Amerika'),
('Count on Me', 'Bruno Mars', 'Pop', 2010, 'Amerika'),
('Leave the Door Open', 'Silk Sonic', 'R&B', 2021, 'Amerika'),
('Die With A Smile', 'Lady Gaga, Bruno Mars', 'Pop', 2024, 'Amerika'),
('Stay With Me', 'Sam Smith', 'Pop', 2014, 'Inggris'),
('Too Good at Goodbyes', 'Sam Smith', 'Pop', 2017, 'Inggris'),
('Unholy', 'Sam Smith, Kim Petras', 'Pop', 2022, 'Inggris'),
('I''m Not the Only One', 'Sam Smith', 'Pop', 2014, 'Inggris'),
('All of Me', 'John Legend', 'R&B', 2013, 'Amerika'),
('Ordinary People', 'John Legend', 'R&B', 2004, 'Amerika'),
('Perfect Duet', 'Ed Sheeran, Beyoncé', 'Pop', 2017, 'Inggris'),
('Halo', 'Beyoncé', 'Pop', 2008, 'Amerika'),
('Crazy in Love', 'Beyoncé', 'Pop', 2003, 'Amerika'),
('Single Ladies', 'Beyoncé', 'Pop', 2008, 'Amerika'),
('Love On Top', 'Beyoncé', 'Pop', 2011, 'Amerika'),
('Drunk in Love', 'Beyoncé', 'R&B', 2013, 'Amerika'),
('Texas Hold ''Em', 'Beyoncé', 'Country', 2024, 'Amerika'),
('Rolling in the Deep', 'Adele', 'Pop', 2010, 'Inggris'),
('Someone Like You', 'Adele', 'Pop', 2011, 'Inggris'),
('Hello', 'Adele', 'Pop', 2015, 'Inggris'),
('Easy On Me', 'Adele', 'Pop', 2021, 'Inggris'),
('Set Fire to the Rain', 'Adele', 'Pop', 2011, 'Inggris'),
('When We Were Young', 'Adele', 'Pop', 2015, 'Inggris'),
('Skyfall', 'Adele', 'Pop', 2012, 'Inggris'),
('Make You Feel My Love', 'Adele', 'Pop', 2008, 'Inggris'),
('Rumour Has It', 'Adele', 'Pop', 2011, 'Inggris'),
('Send My Love', 'Adele', 'Pop', 2015, 'Inggris'),
('Iris', 'Goo Goo Dolls', 'Rock', 1998, 'Amerika'),
('Yellow', 'Coldplay', 'Rock', 2000, 'Inggris'),
('The Scientist', 'Coldplay', 'Rock', 2002, 'Inggris'),
('Fix You', 'Coldplay', 'Rock', 2005, 'Inggris'),
('Viva La Vida', 'Coldplay', 'Rock', 2008, 'Inggris'),
('Paradise', 'Coldplay', 'Rock', 2011, 'Inggris'),
('Adventure of a Lifetime', 'Coldplay', 'Rock', 2015, 'Inggris'),
('Hymn for the Weekend', 'Coldplay', 'Rock', 2015, 'Inggris'),
('Something Just Like This', 'Coldplay, Chainsmokers', 'Pop', 2017, 'Inggris'),
('A Sky Full of Stars', 'Coldplay', 'Rock', 2014, 'Inggris'),
('My Universe', 'Coldplay, BTS', 'Pop', 2021, 'Inggris'),
('Radioactive', 'Imagine Dragons', 'Rock', 2012, 'Amerika'),
('Demons', 'Imagine Dragons', 'Rock', 2012, 'Amerika'),
('Believer', 'Imagine Dragons', 'Rock', 2017, 'Amerika'),
('Thunder', 'Imagine Dragons', 'Rock', 2017, 'Amerika'),
('Whatever It Takes', 'Imagine Dragons', 'Rock', 2017, 'Amerika'),
('Bad Liar', 'Imagine Dragons', 'Rock', 2018, 'Amerika'),
('Enemy', 'Imagine Dragons, JID', 'Rock', 2021, 'Amerika'),
('Bones', 'Imagine Dragons', 'Rock', 2022, 'Amerika'),
('Sharks', 'Imagine Dragons', 'Rock', 2022, 'Amerika'),
('Natural', 'Imagine Dragons', 'Rock', 2018, 'Amerika'),
('High Hopes', 'Panic! At The Disco', 'Rock', 2018, 'Amerika'),
('House of Memories', 'Panic! At The Disco', 'Rock', 2016, 'Amerika'),
('Heathens', 'Twenty One Pilots', 'Rock', 2016, 'Amerika'),
('Stressed Out', 'Twenty One Pilots', 'Rock', 2015, 'Amerika'),
('Ride', 'Twenty One Pilots', 'Rock', 2015, 'Amerika'),
('Chlorine', 'Twenty One Pilots', 'Rock', 2018, 'Amerika'),
('Mr. Brightside', 'The Killers', 'Rock', 2004, 'Amerika'),
('Somebody Told Me', 'The Killers', 'Rock', 2004, 'Amerika'),
('Do I Wanna Know?', 'Arctic Monkeys', 'Rock', 2013, 'Inggris'),
('505', 'Arctic Monkeys', 'Rock', 2007, 'Inggris'),
('I Wanna Be Yours', 'Arctic Monkeys', 'Rock', 2013, 'Inggris'),
('R U Mine?', 'Arctic Monkeys', 'Rock', 2013, 'Inggris'),
('Why''d You Only Call Me When You''re High?', 'Arctic Monkeys', 'Rock', 2013, 'Inggris'),
('Sweater Weather', 'The Neighbourhood', 'Rock', 2012, 'Amerika'),
('Daddy Issues', 'The Neighbourhood', 'Rock', 2015, 'Amerika'),
('Softcore', 'The Neighbourhood', 'Rock', 2018, 'Amerika'),
('The Less I Know The Better', 'Tame Impala', 'Rock', 2015, 'Australia'),
('Let It Happen', 'Tame Impala', 'Rock', 2015, 'Australia'),
('Borderline', 'Tame Impala', 'Rock', 2019, 'Australia'),
('Another One Bites the Dust', 'Queen', 'Rock', 1980, 'Inggris'),
('Bohemian Rhapsody', 'Queen', 'Rock', 1975, 'Inggris'),
('Don''t Stop Me Now', 'Queen', 'Rock', 1978, 'Inggris'),
('We Will Rock You', 'Queen', 'Rock', 1977, 'Inggris'),
('We Are The Champions', 'Queen', 'Rock', 1977, 'Inggris'),
('Love of My Life', 'Queen', 'Rock', 1975, 'Inggris'),
('Under Pressure', 'Queen, David Bowie', 'Rock', 1981, 'Inggris'),
('Radio Ga Ga', 'Queen', 'Rock', 1984, 'Inggris'),
('Somebody to Love', 'Queen', 'Rock', 1976, 'Inggris'),
('I Want to Break Free', 'Queen', 'Rock', 1984, 'Inggris'),
('Hotel California', 'Eagles', 'Rock', 1976, 'Amerika'),
('Sweet Child O'' Mine', 'Guns N'' Roses', 'Rock', 1987, 'Amerika'),
('November Rain', 'Guns N'' Roses', 'Rock', 1991, 'Amerika'),
('Welcome to the Jungle', 'Guns N'' Roses', 'Rock', 1987, 'Amerika'),
('Smells Like Teen Spirit', 'Nirvana', 'Rock', 1991, 'Amerika'),
('Come As You Are', 'Nirvana', 'Rock', 1991, 'Amerika'),
('In Bloom', 'Nirvana', 'Rock', 1991, 'Amerika'),
('Losing My Religion', 'R.E.M.', 'Rock', 1991, 'Amerika'),
('Wonderwall', 'Oasis', 'Rock', 1995, 'Inggris'),
('Don''t Look Back in Anger', 'Oasis', 'Rock', 1995, 'Inggris'),
('Champagne Supernova', 'Oasis', 'Rock', 1995, 'Inggris'),
('Iris', 'Goo Goo Dolls', 'Rock', 1998, 'Amerika'),
('How You Remind Me', 'Nickelback', 'Rock', 2001, 'Kanada'),
('In the End', 'Linkin Park', 'Rock', 2000, 'Amerika'),
('Numb', 'Linkin Park', 'Rock', 2003, 'Amerika'),
('Faint', 'Linkin Park', 'Rock', 2003, 'Amerika'),
('Crawling', 'Linkin Park', 'Rock', 2000, 'Amerika'),
('Somewhere I Belong', 'Linkin Park', 'Rock', 2003, 'Amerika'),
('Breaking the Habit', 'Linkin Park', 'Rock', 2003, 'Amerika'),
('What I''ve Done', 'Linkin Park', 'Rock', 2007, 'Amerika'),
('New Divide', 'Linkin Park', 'Rock', 2009, 'Amerika'),
('Castle of Glass', 'Linkin Park', 'Rock', 2012, 'Amerika'),
('Heavy', 'Linkin Park, Kiiara', 'Rock', 2017, 'Amerika'),
('Lost', 'Linkin Park', 'Rock', 2023, 'Amerika'),
('Vampire', 'Olivia Rodrigo', 'Pop', 2023, 'Amerika'),
('Drivers License', 'Olivia Rodrigo', 'Pop', 2021, 'Amerika'),
('Good 4 U', 'Olivia Rodrigo', 'Pop', 2021, 'Amerika'),
('Traitor', 'Olivia Rodrigo', 'Pop', 2021, 'Amerika'),
('Deja Vu', 'Olivia Rodrigo', 'Pop', 2021, 'Amerika'),
('Happier', 'Olivia Rodrigo', 'Pop', 2021, 'Amerika'),
('Brutal', 'Olivia Rodrigo', 'Pop', 2021, 'Amerika'),
('Get Him Back!', 'Olivia Rodrigo', 'Pop', 2023, 'Amerika'),
('Bad Idea Right?', 'Olivia Rodrigo', 'Pop', 2023, 'Amerika'),
('Espresso', 'Sabrina Carpenter', 'Pop', 2024, 'Amerika'),
('Please Please Please', 'Sabrina Carpenter', 'Pop', 2024, 'Amerika'),
('Nonsense', 'Sabrina Carpenter', 'Pop', 2022, 'Amerika'),
('Feather', 'Sabrina Carpenter', 'Pop', 2023, 'Amerika'),
('Taste', 'Sabrina Carpenter', 'Pop', 2024, 'Amerika'),
('Paint The Town Red', 'Doja Cat', 'Hip-Hop', 2023, 'Amerika'),
('Say So', 'Doja Cat', 'Pop', 2019, 'Amerika'),
('Kiss Me More', 'Doja Cat, SZA', 'Pop', 2021, 'Amerika'),
('Woman', 'Doja Cat', 'Pop', 2021, 'Amerika'),
('Need to Know', 'Doja Cat', 'Pop', 2021, 'Amerika'),
('Agora Hills', 'Doja Cat', 'Hip-Hop', 2023, 'Amerika'),
('Streets', 'Doja Cat', 'Pop', 2019, 'Amerika'),
('Levitating Remix', 'Dua Lipa, DaBaby', 'Pop', 2020, 'Inggris'),
('Kill Bill', 'SZA', 'R&B', 2022, 'Amerika'),
('Snooze', 'SZA', 'R&B', 2022, 'Amerika'),
('Good Days', 'SZA', 'R&B', 2020, 'Amerika'),
('Nobody Gets Me', 'SZA', 'R&B', 2022, 'Amerika'),
('Saturn', 'SZA', 'R&B', 2024, 'Amerika'),
('Kill Bill Remix', 'SZA, Doja Cat', 'R&B', 2023, 'Amerika'),
('Heat Waves', 'Glass Animals', 'Pop', 2020, 'Inggris'),
('Dreamland', 'Glass Animals', 'Pop', 2020, 'Inggris'),
('Space Ghost Coast to Coast', 'Glass Animals', 'Pop', 2020, 'Inggris'),
('Industry Baby', 'Lil Nas X, Jack Harlow', 'Hip-Hop', 2021, 'Amerika'),
('Montero', 'Lil Nas X', 'Hip-Hop', 2021, 'Amerika'),
('Old Town Road', 'Lil Nas X, Billy Ray Cyrus', 'Hip-Hop', 2019, 'Amerika'),
('That''s What I Want', 'Lil Nas X', 'Pop', 2021, 'Amerika'),
('Panini', 'Lil Nas X', 'Hip-Hop', 2019, 'Amerika'),
('Holiday', 'Lil Nas X', 'Pop', 2020, 'Amerika'),
('Sunflower', 'Post Malone, Swae Lee', 'Pop', 2018, 'Amerika'),
('Wow.', 'Post Malone', 'Hip-Hop', 2018, 'Amerika'),
('Goodbyes', 'Post Malone, Young Thug', 'Hip-Hop', 2019, 'Amerika'),
('Chemical', 'Post Malone', 'Pop', 2023, 'Amerika'),
('I Had Some Help', 'Post Malone, Morgan Wallen', 'Country', 2024, 'Amerika'),

-- ==================== HIP-HOP / RAP ====================
('Lose Yourself', 'Eminem', 'Hip-Hop', 2002, 'Amerika'),
('Without Me', 'Eminem', 'Hip-Hop', 2002, 'Amerika'),
('Stan', 'Eminem, Dido', 'Hip-Hop', 2000, 'Amerika'),
('Mockingbird', 'Eminem', 'Hip-Hop', 2004, 'Amerika'),
('Rap God', 'Eminem', 'Hip-Hop', 2013, 'Amerika'),
('Not Afraid', 'Eminem', 'Hip-Hop', 2010, 'Amerika'),
('Love The Way You Lie', 'Eminem, Rihanna', 'Hip-Hop', 2010, 'Amerika'),
('The Real Slim Shady', 'Eminem', 'Hip-Hop', 2000, 'Amerika'),
('Superman', 'Eminem, Dina Rae', 'Hip-Hop', 2002, 'Amerika'),
('Till I Collapse', 'Eminem, Nate Dogg', 'Hip-Hop', 2002, 'Amerika'),
('Venom', 'Eminem', 'Hip-Hop', 2018, 'Amerika'),
('Godzilla', 'Eminem, Juice WRLD', 'Hip-Hop', 2020, 'Amerika'),
('Houdini', 'Eminem', 'Hip-Hop', 2024, 'Amerika'),
('Sicko Mode', 'Travis Scott', 'Hip-Hop', 2018, 'Amerika'),
('Goosebumps', 'Travis Scott', 'Hip-Hop', 2016, 'Amerika'),
('Antidote', 'Travis Scott', 'Hip-Hop', 2015, 'Amerika'),
('Highest in the Room', 'Travis Scott', 'Hip-Hop', 2019, 'Amerika'),
('Butterfly Effect', 'Travis Scott', 'Hip-Hop', 2017, 'Amerika'),
('Stargazing', 'Travis Scott', 'Hip-Hop', 2018, 'Amerika'),
('FE!N', 'Travis Scott, Playboi Carti', 'Hip-Hop', 2023, 'Amerika'),
('I Know ?', 'Travis Scott', 'Hip-Hop', 2023, 'Amerika'),
('God''s Plan', 'Drake', 'Hip-Hop', 2018, 'Kanada'),
('Hotline Bling', 'Drake', 'Hip-Hop', 2015, 'Kanada'),
('One Dance', 'Drake, Wizkid, Kyla', 'Hip-Hop', 2016, 'Kanada'),
('In My Feelings', 'Drake', 'Hip-Hop', 2018, 'Kanada'),
('Nice for What', 'Drake', 'Hip-Hop', 2018, 'Kanada'),
('Passionfruit', 'Drake', 'R&B', 2017, 'Kanada'),
('Started from the Bottom', 'Drake', 'Hip-Hop', 2013, 'Kanada'),
('Controlla', 'Drake', 'Hip-Hop', 2016, 'Kanada'),
('Jimmy Cooks', 'Drake, 21 Savage', 'Hip-Hop', 2022, 'Kanada'),
('Rich Flex', 'Drake, 21 Savage', 'Hip-Hop', 2022, 'Kanada'),
('Sicko Mode', 'Travis Scott', 'Hip-Hop', 2018, 'Amerika'),
('Humble', 'Kendrick Lamar', 'Hip-Hop', 2017, 'Amerika'),
('Alright', 'Kendrick Lamar', 'Hip-Hop', 2015, 'Amerika'),
('Money Trees', 'Kendrick Lamar', 'Hip-Hop', 2012, 'Amerika'),
('DNA.', 'Kendrick Lamar', 'Hip-Hop', 2017, 'Amerika'),
('Swimming Pools', 'Kendrick Lamar', 'Hip-Hop', 2012, 'Amerika'),
('Not Like Us', 'Kendrick Lamar', 'Hip-Hop', 2024, 'Amerika'),
('Like That', 'Future, Metro Boomin, Kendrick Lamar', 'Hip-Hop', 2024, 'Amerika'),
('All The Stars', 'Kendrick Lamar, SZA', 'Hip-Hop', 2018, 'Amerika'),
('Bad Habit', 'Steve Lacy', 'R&B', 2022, 'Amerika'),
('Dark Red', 'Steve Lacy', 'R&B', 2017, 'Amerika'),
('N Side', 'Steve Lacy', 'R&B', 2017, 'Amerika'),
('Flamingo', 'Kanye West', 'Hip-Hop', 2018, 'Amerika'),
('Gold Digger', 'Kanye West, Jamie Foxx', 'Hip-Hop', 2005, 'Amerika'),
('Stronger', 'Kanye West', 'Hip-Hop', 2007, 'Amerika'),
('Heartless', 'Kanye West', 'Hip-Hop', 2008, 'Amerika'),
('Power', 'Kanye West', 'Hip-Hop', 2010, 'Amerika'),
('Runaway', 'Kanye West, Pusha T', 'Hip-Hop', 2010, 'Amerika'),
('Flashing Lights', 'Kanye West', 'Hip-Hop', 2007, 'Amerika'),
('Bound 2', 'Kanye West', 'Hip-Hop', 2013, 'Amerika'),
('Carnival', 'Kanye West, Ty Dolla $ign', 'Hip-Hop', 2024, 'Amerika'),
('Lucid Dreams', 'Juice WRLD', 'Hip-Hop', 2018, 'Amerika'),
('All Girls Are The Same', 'Juice WRLD', 'Hip-Hop', 2018, 'Amerika'),
('Robbery', 'Juice WRLD', 'Hip-Hop', 2019, 'Amerika'),
('Come & Go', 'Juice WRLD, Marshmello', 'Hip-Hop', 2020, 'Amerika'),
('Wishing Well', 'Juice WRLD', 'Hip-Hop', 2020, 'Amerika'),
('Sunflower', 'Post Malone, Swae Lee', 'Hip-Hop', 2018, 'Amerika'),
('Sicko Mode', 'Travis Scott', 'Hip-Hop', 2018, 'Amerika'),
('Rockstar', 'Post Malone, 21 Savage', 'Hip-Hop', 2017, 'Amerika'),
('Psycho', 'Post Malone, Ty Dolla $ign', 'Hip-Hop', 2018, 'Amerika'),
('Congratulations', 'Post Malone, Quavo', 'Hip-Hop', 2016, 'Amerika'),
('White Iverson', 'Post Malone', 'Hip-Hop', 2015, 'Amerika'),
('Candy Paint', 'Post Malone', 'Hip-Hop', 2017, 'Amerika'),
('Wow. Remix', 'Post Malone, Tyga, Roddy Ricch', 'Hip-Hop', 2019, 'Amerika'),
('The Box', 'Roddy Ricch', 'Hip-Hop', 2019, 'Amerika'),
('High Fashion', 'Roddy Ricch, Mustard', 'Hip-Hop', 2019, 'Amerika'),
('Ballin''', 'Mustard, Roddy Ricch', 'Hip-Hop', 2019, 'Amerika'),
('Ransom', 'Lil Tecca', 'Hip-Hop', 2019, 'Amerika'),
('Lucid Dreams', 'Juice WRLD', 'Hip-Hop', 2018, 'Amerika'),
('Mood', '24kGoldn, iann dior', 'Hip-Hop', 2020, 'Amerika'),
('Roses Remix', 'Saint Jhn, Future', 'Hip-Hop', 2020, 'Amerika'),
('Whats Poppin', 'Jack Harlow', 'Hip-Hop', 2020, 'Amerika'),
('First Class', 'Jack Harlow', 'Hip-Hop', 2022, 'Amerika'),
('Churchill Downs', 'Jack Harlow, Drake', 'Hip-Hop', 2022, 'Amerika'),
('Nail Tech', 'Jack Harlow', 'Hip-Hop', 2022, 'Amerika'),
('Industry Baby', 'Lil Nas X, Jack Harlow', 'Hip-Hop', 2021, 'Amerika'),
('Dior', 'Pop Smoke', 'Hip-Hop', 2019, 'Amerika'),
('Mood Swings', 'Pop Smoke, Lil Tjay', 'Hip-Hop', 2020, 'Amerika'),
('For The Night', 'Pop Smoke, Lil Baby, DaBaby', 'Hip-Hop', 2020, 'Amerika'),
('What You Know Bout Love', 'Pop Smoke', 'Hip-Hop', 2020, 'Amerika'),
('Hello', 'Pop Smoke, A Boogie Wit da Hoodie', 'Hip-Hop', 2020, 'Amerika'),
('Sunflower', 'Post Malone, Swae Lee', 'Hip-Hop', 2018, 'Amerika'),
('Way 2 Sexy', 'Drake, Future, Young Thug', 'Hip-Hop', 2021, 'Kanada'),
('Fair Trade', 'Drake, Travis Scott', 'Hip-Hop', 2021, 'Kanada'),
('Knife Talk', 'Drake, 21 Savage, Project Pat', 'Hip-Hop', 2021, 'Kanada'),
('Girls Want Girls', 'Drake, Lil Baby', 'Hip-Hop', 2021, 'Kanada'),
('Champagne Poetry', 'Drake', 'Hip-Hop', 2021, 'Kanada'),
('Wait for U', 'Future, Drake, Tems', 'Hip-Hop', 2022, 'Amerika'),
('Puffin on Zootiez', 'Future', 'Hip-Hop', 2022, 'Amerika'),
('Mask Off', 'Future', 'Hip-Hop', 2017, 'Amerika'),
('Life Is Good', 'Future, Drake', 'Hip-Hop', 2020, 'Amerika'),
('Low Life', 'Future, The Weeknd', 'Hip-Hop', 2016, 'Amerika'),
('Jumpman', 'Drake, Future', 'Hip-Hop', 2015, 'Kanada'),
('March Madness', 'Future', 'Hip-Hop', 2015, 'Amerika'),
('Codeine Crazy', 'Future', 'Hip-Hop', 2014, 'Amerika'),
('Drankin N Smokin', 'Future, Lil Uzi Vert', 'Hip-Hop', 2020, 'Amerika'),
('XO Tour Llif3', 'Lil Uzi Vert', 'Hip-Hop', 2017, 'Amerika'),
('Money Longer', 'Lil Uzi Vert', 'Hip-Hop', 2016, 'Amerika'),
('Just Wanna Rock', 'Lil Uzi Vert', 'Hip-Hop', 2022, 'Amerika'),
('Futsal Shuffle 2020', 'Lil Uzi Vert', 'Hip-Hop', 2019, 'Amerika'),
('Sanguine Paradise', 'Lil Uzi Vert', 'Hip-Hop', 2019, 'Amerika'),
('Baby Pluto', 'Lil Uzi Vert', 'Hip-Hop', 2020, 'Amerika'),
('Lo Mein', 'Lil Uzi Vert', 'Hip-Hop', 2020, 'Amerika'),
('Homecoming', 'Lil Uzi Vert', 'Hip-Hop', 2020, 'Amerika'),
('Rockstar Made', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('Magnolia', 'Playboi Carti', 'Hip-Hop', 2017, 'Amerika'),
('Shoota', 'Playboi Carti, Lil Uzi Vert', 'Hip-Hop', 2018, 'Amerika'),
('Sky', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('Vamp Anthem', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('New Tank', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('On That Time', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('Beno!', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('ILoveUIHateU', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('Die4Guy', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('Slay!', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('Not Playing', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('F33l Lik3 Dyin', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('Control', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('Punk Monk', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('Place', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('King Vamp', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('Teen X', 'Playboi Carti, Future', 'Hip-Hop', 2020, 'Amerika'),
('Meh', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('Metamorphosis', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('No Sl33p', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),
('Vampire Hour', 'Playboi Carti', 'Hip-Hop', 2020, 'Amerika'),

-- ==================== R&B / SOUL ====================
('Blinding Lights', 'The Weeknd', 'R&B', 2019, 'Kanada'),
('Save Your Tears', 'The Weeknd', 'R&B', 2020, 'Kanada'),
('Starboy', 'The Weeknd, Daft Punk', 'R&B', 2016, 'Kanada'),
('Die For You', 'The Weeknd', 'R&B', 2016, 'Kanada'),
('Call Out My Name', 'The Weeknd', 'R&B', 2018, 'Kanada'),
('Earned It', 'The Weeknd', 'R&B', 2015, 'Kanada'),
('The Hills', 'The Weeknd', 'R&B', 2015, 'Kanada'),
('Can''t Feel My Face', 'The Weeknd', 'R&B', 2015, 'Kanada'),
('Often', 'The Weeknd', 'R&B', 2014, 'Kanada'),
('I Feel It Coming', 'The Weeknd, Daft Punk', 'R&B', 2016, 'Kanada'),
('After Hours', 'The Weeknd', 'R&B', 2020, 'Kanada'),
('Take My Breath', 'The Weeknd', 'R&B', 2021, 'Kanada'),
('Sacrifice', 'The Weeknd', 'R&B', 2022, 'Kanada'),
('Out of Time', 'The Weeknd', 'R&B', 2022, 'Kanada'),
('Is There Someone Else?', 'The Weeknd', 'R&B', 2022, 'Kanada'),
('Less Than Zero', 'The Weeknd', 'R&B', 2022, 'Kanada'),
('Creepin', 'Metro Boomin, The Weeknd, 21 Savage', 'R&B', 2022, 'Amerika'),
('Popular', 'The Weeknd, Playboi Carti, Madonna', 'R&B', 2023, 'Kanada'),
('One Of The Girls', 'The Weeknd, JENNIE, Lily-Rose Depp', 'R&B', 2023, 'Kanada'),
('Timeless', 'The Weeknd, Playboi Carti', 'R&B', 2024, 'Kanada'),
('Snooze', 'SZA', 'R&B', 2022, 'Amerika'),
('Kill Bill', 'SZA', 'R&B', 2022, 'Amerika'),
('Nobody Gets Me', 'SZA', 'R&B', 2022, 'Amerika'),
('Good Days', 'SZA', 'R&B', 2020, 'Amerika'),
('Saturn', 'SZA', 'R&B', 2024, 'Amerika'),
('Open Arms', 'SZA, Travis Scott', 'R&B', 2022, 'Amerika'),
('I Hate U', 'SZA', 'R&B', 2021, 'Amerika'),
('Shirt', 'SZA', 'R&B', 2022, 'Amerika'),
('Blind', 'SZA', 'R&B', 2022, 'Amerika'),
('Used', 'SZA, Don Toliver', 'R&B', 2022, 'Amerika'),
('Low', 'SZA', 'R&B', 2022, 'Amerika'),
('Love Language', 'SZA', 'R&B', 2022, 'Amerika'),
('Notice Me', 'SZA', 'R&B', 2022, 'Amerika'),
('Gone Girl', 'SZA', 'R&B', 2022, 'Amerika'),
('Smoking on My Ex Pack', 'SZA', 'R&B', 2022, 'Amerika'),
('Conceited', 'SZA', 'R&B', 2022, 'Amerika'),
('Special', 'SZA', 'R&B', 2022, 'Amerika'),
('Too Late', 'SZA', 'R&B', 2022, 'Amerika'),
('Far', 'SZA', 'R&B', 2022, 'Amerika'),
('F2F', 'SZA', 'R&B', 2022, 'Amerika'),
('Nobody', 'SZA', 'R&B', 2022, 'Amerika'),
('Ghost in the Machine', 'SZA, Phoebe Bridgers', 'R&B', 2022, 'Amerika'),
('Leave Me Lonely', 'Ariana Grande, Macy Gray', 'R&B', 2016, 'Amerika'),
('Adorn', 'Miguel', 'R&B', 2012, 'Amerika'),
('Sure Thing', 'Miguel', 'R&B', 2010, 'Amerika'),
('Coffee', 'Miguel', 'R&B', 2015, 'Amerika'),
('Come Through', 'H.E.R., Chris Brown', 'R&B', 2021, 'Amerika'),
('Focus', 'H.E.R.', 'R&B', 2016, 'Amerika'),
('Best Part', 'Daniel Caesar, H.E.R.', 'R&B', 2017, 'Kanada'),
('Get You', 'Daniel Caesar, Kali Uchis', 'R&B', 2016, 'Kanada'),
('Japanese Denim', 'Daniel Caesar', 'R&B', 2016, 'Kanada'),
('Always', 'Daniel Caesar', 'R&B', 2017, 'Kanada'),
('Superpowers', 'Daniel Caesar', 'R&B', 2023, 'Kanada'),
('Telepatía', 'Kali Uchis', 'R&B', 2020, 'Kolombia'),
('After the Storm', 'Kali Uchis, Tyler, The Creator, Bootsy Collins', 'R&B', 2018, 'Kolombia'),
('Moonlight', 'Kali Uchis', 'R&B', 2023, 'Kolombia'),
('Igual Que Un Ángel', 'Kali Uchis, Peso Pluma', 'R&B', 2024, 'Kolombia'),
('Peaches', 'Justin Bieber, Daniel Caesar, Giveon', 'R&B', 2021, 'Kanada'),
('Heartbreak Anniversary', 'Giveon', 'R&B', 2020, 'Amerika'),
('Like I Want You', 'Giveon', 'R&B', 2020, 'Amerika'),
('For Tonight', 'Giveon', 'R&B', 2021, 'Amerika'),
('All to Me', 'Giveon', 'R&B', 2022, 'Amerika'),
('Lost Me', 'Giveon', 'R&B', 2022, 'Amerika'),
('Lie Again', 'Giveon', 'R&B', 2022, 'Amerika'),
('The Beach', 'The Neighbourhood', 'R&B', 2015, 'Amerika'),
('Pink + White', 'Frank Ocean', 'R&B', 2016, 'Amerika'),
('Ivy', 'Frank Ocean', 'R&B', 2016, 'Amerika'),
('Thinkin Bout You', 'Frank Ocean', 'R&B', 2012, 'Amerika'),
('Chanel', 'Frank Ocean', 'R&B', 2017, 'Amerika'),
('Nikes', 'Frank Ocean', 'R&B', 2016, 'Amerika'),
('Self Control', 'Frank Ocean', 'R&B', 2016, 'Amerika'),
('Nights', 'Frank Ocean', 'R&B', 2016, 'Amerika'),
('Pyramids', 'Frank Ocean', 'R&B', 2012, 'Amerika'),
('Novacane', 'Frank Ocean', 'R&B', 2011, 'Amerika'),
('Super Rich Kids', 'Frank Ocean, Earl Sweatshirt', 'R&B', 2012, 'Amerika'),
('Lost', 'Frank Ocean', 'R&B', 2012, 'Amerika'),
('Seigfried', 'Frank Ocean', 'R&B', 2016, 'Amerika'),
('Godspeed', 'Frank Ocean', 'R&B', 2016, 'Amerika'),
('White Ferrari', 'Frank Ocean', 'R&B', 2016, 'Amerika'),
('Pink Matter', 'Frank Ocean, André 3000', 'R&B', 2012, 'Amerika'),
('Bad Religion', 'Frank Ocean', 'R&B', 2012, 'Amerika'),

-- ==================== EDM / ELECTRONIC ====================
('Wake Me Up', 'Avicii', 'EDM', 2013, 'Swedia'),
('Hey Brother', 'Avicii', 'EDM', 2013, 'Swedia'),
('Levels', 'Avicii', 'EDM', 2011, 'Swedia'),
('The Nights', 'Avicii', 'EDM', 2014, 'Swedia'),
('Waiting for Love', 'Avicii', 'EDM', 2015, 'Swedia'),
('Without You', 'Avicii, Sandro Cavazza', 'EDM', 2017, 'Swedia'),
('Lonely Together', 'Avicii, Rita Ora', 'EDM', 2017, 'Swedia'),
('SOS', 'Avicii, Aloe Blacc', 'EDM', 2019, 'Swedia'),
('Heaven', 'Avicii, Chris Martin', 'EDM', 2019, 'Swedia'),
('Titanium', 'David Guetta, Sia', 'EDM', 2011, 'Prancis'),
('Without You', 'David Guetta, Usher', 'EDM', 2011, 'Prancis'),
('Play Hard', 'David Guetta, Ne-Yo, Akon', 'EDM', 2013, 'Prancis'),
('Hey Mama', 'David Guetta, Nicki Minaj, Bebe Rexha', 'EDM', 2014, 'Prancis'),
('2U', 'David Guetta, Justin Bieber', 'EDM', 2017, 'Prancis'),
('Flames', 'David Guetta, Sia', 'EDM', 2018, 'Prancis'),
('I''m Good (Blue)', 'David Guetta, Bebe Rexha', 'EDM', 2022, 'Prancis'),
('Closer', 'The Chainsmokers, Halsey', 'EDM', 2016, 'Amerika'),
('Don''t Let Me Down', 'The Chainsmokers, Daya', 'EDM', 2016, 'Amerika'),
('Something Just Like This', 'The Chainsmokers, Coldplay', 'EDM', 2017, 'Amerika'),
('Roses', 'The Chainsmokers, ROZES', 'EDM', 2015, 'Amerika'),
('Paris', 'The Chainsmokers', 'EDM', 2017, 'Amerika'),
('Selfie', 'The Chainsmokers', 'EDM', 2014, 'Amerika'),
('Sick Boy', 'The Chainsmokers', 'EDM', 2018, 'Amerika'),
('Who Do You Love', 'The Chainsmokers, 5 Seconds of Summer', 'EDM', 2019, 'Amerika'),
('Summer', 'Calvin Harris', 'EDM', 2014, 'Skotlandia'),
('Feel So Close', 'Calvin Harris', 'EDM', 2011, 'Skotlandia'),
('This Is What You Came For', 'Calvin Harris, Rihanna', 'EDM', 2016, 'Skotlandia'),
('Outside', 'Calvin Harris, Ellie Goulding', 'EDM', 2014, 'Skotlandia'),
('Slide', 'Calvin Harris, Frank Ocean, Migos', 'EDM', 2017, 'Skotlandia'),
('Feels', 'Calvin Harris, Pharrell Williams, Katy Perry, Big Sean', 'EDM', 2017, 'Skotlandia'),
('One Kiss', 'Calvin Harris, Dua Lipa', 'EDM', 2018, 'Skotlandia'),
('Giant', 'Calvin Harris, Rag''n''Bone Man', 'EDM', 2019, 'Skotlandia'),
('By Your Side', 'Calvin Harris, Tom Grennan', 'EDM', 2021, 'Skotlandia'),
('Faded', 'Alan Walker', 'EDM', 2015, 'Norwegia'),
('Sing Me to Sleep', 'Alan Walker', 'EDM', 2016, 'Norwegia'),
('Alone', 'Alan Walker', 'EDM', 2016, 'Norwegia'),
('On My Way', 'Alan Walker, Sabrina Carpenter, Farruko', 'EDM', 2019, 'Norwegia'),
('Darkside', 'Alan Walker, Au/Ra, Tomine Harket', 'EDM', 2018, 'Norwegia'),
('Play', 'Alan Walker, K-391, Tungevaag, Mangoo', 'EDM', 2019, 'Norwegia'),
('The Spectre', 'Alan Walker', 'EDM', 2017, 'Norwegia'),
('Animals', 'Martin Garrix', 'EDM', 2013, 'Belanda'),
('In the Name of Love', 'Martin Garrix, Bebe Rexha', 'EDM', 2016, 'Belanda'),
('Scared to Be Lonely', 'Martin Garrix, Dua Lipa', 'EDM', 2017, 'Belanda'),
('There for You', 'Martin Garrix, Troye Sivan', 'EDM', 2017, 'Belanda'),
('Ocean', 'Martin Garrix, Khalid', 'EDM', 2018, 'Belanda'),
('High on Life', 'Martin Garrix, Bonn', 'EDM', 2018, 'Belanda'),
('Summer Days', 'Martin Garrix, Macklemore, Patrick Stump', 'EDM', 2019, 'Belanda'),
('Tremor', 'Dimitri Vegas, Like Mike, Martin Garrix', 'EDM', 2014, 'Belgia'),
('Don''t You Worry Child', 'Swedish House Mafia', 'EDM', 2012, 'Swedia'),
('Save the World', 'Swedish House Mafia', 'EDM', 2011, 'Swedia'),
('One', 'Swedish House Mafia', 'EDM', 2010, 'Swedia'),
('Greyhound', 'Swedish House Mafia', 'EDM', 2012, 'Swedia'),
('Moth to a Flame', 'Swedish House Mafia, The Weeknd', 'EDM', 2021, 'Swedia'),
('Redlight', 'Swedish House Mafia, Sting', 'EDM', 2022, 'Swedia'),
('Heaven Takes You Home', 'Swedish House Mafia, Connie Constance', 'EDM', 2022, 'Swedia'),
('Turn On the Lights again', 'Fred again.., Swedish House Mafia, Future', 'EDM', 2022, 'Inggris'),
('Where Are Ü Now', 'Jack Ü, Justin Bieber', 'EDM', 2015, 'Amerika'),
('Lean On', 'Major Lazer, DJ Snake, MØ', 'EDM', 2015, 'Amerika'),
('Cold Water', 'Major Lazer, Justin Bieber, MØ', 'EDM', 2016, 'Amerika'),
('Light It Up', 'Major Lazer, Nyla, Fuse ODG', 'EDM', 2015, 'Amerika'),
('Run Up', 'Major Lazer, PARTYNEXTDOOR, Nicki Minaj', 'EDM', 2017, 'Amerika'),
('Particula', 'Major Lazer, DJ Maphorisa, Nasty C, Ice Prince', 'EDM', 2017, 'Amerika'),
('Taki Taki', 'DJ Snake, Selena Gomez, Ozuna, Cardi B', 'EDM', 2018, 'Prancis'),
('Let Me Love You', 'DJ Snake, Justin Bieber', 'EDM', 2016, 'Prancis'),
('Middle', 'DJ Snake, Bipolar Sunshine', 'EDM', 2015, 'Prancis'),
('Magenta Riddim', 'DJ Snake', 'EDM', 2018, 'Prancis'),
('Loco Contigo', 'DJ Snake, J Balvin, Tyga', 'EDM', 2019, 'Prancis'),
('A Different Way', 'DJ Snake, Lauv', 'EDM', 2017, 'Prancis'),
('Clarity', 'Zedd, Foxes', 'EDM', 2012, 'Rusia'),
('Stay', 'Zedd, Alessia Cara', 'EDM', 2017, 'Rusia'),
('The Middle', 'Zedd, Maren Morris, Grey', 'EDM', 2018, 'Rusia'),
('Beautiful Now', 'Zedd, Jon Bellion', 'EDM', 2015, 'Rusia'),
('I Want You to Know', 'Zedd, Selena Gomez', 'EDM', 2015, 'Rusia'),
('Break Free', 'Ariana Grande, Zedd', 'EDM', 2014, 'Amerika'),
('Happy Now', 'Zedd, Elley Duhé', 'EDM', 2018, 'Rusia'),
('365', 'Zedd, Katy Perry', 'EDM', 2019, 'Rusia'),
('Good Thing', 'Zedd, Kehlani', 'EDM', 2019, 'Rusia'),
('Roses', 'Saint Jhn', 'EDM', 2016, 'Amerika'),
('Lose Control', 'Meduza, Becky Hill, Goodboys', 'EDM', 2019, 'Italia'),
('Piece of Your Heart', 'Meduza, Goodboys', 'EDM', 2019, 'Italia'),
('Head & Heart', 'Joel Corry, MNEK', 'EDM', 2020, 'Inggris'),
('Sorry', 'Joel Corry', 'EDM', 2019, 'Inggris'),
('Lonely', 'Joel Corry', 'EDM', 2020, 'Inggris'),
('Bed', 'Joel Corry, RAYE, David Guetta', 'EDM', 2021, 'Inggris'),
('OUT OUT', 'Joel Corry, Jax Jones, Charli XCX, Saweetie', 'EDM', 2021, 'Inggris'),
('I Wish', 'Joel Corry, Mabel', 'EDM', 2021, 'Inggris'),
('Where Did You Go?', 'Jax Jones, MNEK', 'EDM', 2022, 'Inggris'),
('You Don''t Know Me', 'Jax Jones, RAYE', 'EDM', 2016, 'Inggris'),
('Instruction', 'Jax Jones, Demi Lovato, Stefflon Don', 'EDM', 2017, 'Inggris'),
('Breathe', 'Jax Jones, Ina Wroldsen', 'EDM', 2017, 'Inggris'),
('Ring Ring', 'Jax Jones, Mabel, Rich the Kid', 'EDM', 2018, 'Inggris'),
('One Touch', 'Jess Glynne, Jax Jones', 'EDM', 2019, 'Inggris'),
('This Is Real', 'Jax Jones, Ella Henderson', 'EDM', 2019, 'Inggris'),
('Tequila', 'Dan + Shay', 'Country', 2018, 'Amerika'),
('Speechless', 'Dan + Shay', 'Country', 2018, 'Amerika'),
('10,000 Hours', 'Dan + Shay, Justin Bieber', 'Country', 2019, 'Amerika'),
('I Hope', 'Gabby Barrett', 'Country', 2019, 'Amerika'),
('The Good Ones', 'Gabby Barrett', 'Country', 2019, 'Amerika'),
('Before He Cheats', 'Carrie Underwood', 'Country', 2005, 'Amerika'),
('Jesus, Take the Wheel', 'Carrie Underwood', 'Country', 2005, 'Amerika'),
('Blown Away', 'Carrie Underwood', 'Country', 2012, 'Amerika'),
('Love Story', 'Taylor Swift', 'Country', 2008, 'Amerika'),
('You Belong With Me', 'Taylor Swift', 'Country', 2008, 'Amerika'),
('Mean', 'Taylor Swift', 'Country', 2010, 'Amerika'),
('Fifteen', 'Taylor Swift', 'Country', 2008, 'Amerika'),
('Tim McGraw', 'Taylor Swift', 'Country', 2006, 'Amerika'),
('Our Song', 'Taylor Swift', 'Country', 2006, 'Amerika'),
('Teardrops on My Guitar', 'Taylor Swift', 'Country', 2006, 'Amerika'),
('White Horse', 'Taylor Swift', 'Country', 2008, 'Amerika'),
('Back to December', 'Taylor Swift', 'Country', 2010, 'Amerika'),
('Dear John', 'Taylor Swift', 'Country', 2010, 'Amerika'),
('Enchanted', 'Taylor Swift', 'Country', 2010, 'Amerika'),
('Last Kiss', 'Taylor Swift', 'Country', 2010, 'Amerika'),
('Sparks Fly', 'Taylor Swift', 'Country', 2010, 'Amerika'),
('Mine', 'Taylor Swift', 'Country', 2010, 'Amerika'),
('Ours', 'Taylor Swift', 'Country', 2010, 'Amerika'),
('Safe & Sound', 'Taylor Swift, The Civil Wars', 'Country', 2011, 'Amerika'),
('Red', 'Taylor Swift', 'Country', 2012, 'Amerika'),
('Begin Again', 'Taylor Swift', 'Country', 2012, 'Amerika'),
('Everything Has Changed', 'Taylor Swift, Ed Sheeran', 'Country', 2012, 'Amerika'),
('I Knew You Were Trouble', 'Taylor Swift', 'Country', 2012, 'Amerika'),
('22', 'Taylor Swift', 'Country', 2012, 'Amerika'),
('We Are Never Ever Getting Back Together', 'Taylor Swift', 'Country', 2012, 'Amerika'),
('All Too Well', 'Taylor Swift', 'Country', 2012, 'Amerika'),
('All Too Well (10 Minute Version)', 'Taylor Swift', 'Country', 2021, 'Amerika'),
('Cruel Summer', 'Taylor Swift', 'Pop', 2019, 'Amerika'),
('Lover', 'Taylor Swift', 'Pop', 2019, 'Amerika'),
('The Man', 'Taylor Swift', 'Pop', 2019, 'Amerika'),
('You Need to Calm Down', 'Taylor Swift', 'Pop', 2019, 'Amerika'),
('ME!', 'Taylor Swift, Brendon Urie', 'Pop', 2019, 'Amerika'),
('Exile', 'Taylor Swift, Bon Iver', 'Folk', 2020, 'Amerika'),
('Betty', 'Taylor Swift', 'Folk', 2020, 'Amerika'),
('The 1', 'Taylor Swift', 'Folk', 2020, 'Amerika'),
('August', 'Taylor Swift', 'Folk', 2020, 'Amerika'),
('Mirrorball', 'Taylor Swift', 'Folk', 2020, 'Amerika'),
('My Tears Ricochet', 'Taylor Swift', 'Folk', 2020, 'Amerika'),
('Illicit Affairs', 'Taylor Swift', 'Folk', 2020, 'Amerika'),
('Invisible String', 'Taylor Swift', 'Folk', 2020, 'Amerika'),
('Mad Woman', 'Taylor Swift', 'Folk', 2020, 'Amerika'),
('Epiphany', 'Taylor Swift', 'Folk', 2020, 'Amerika'),
('Peace', 'Taylor Swift', 'Folk', 2020, 'Amerika'),
('Hoax', 'Taylor Swift', 'Folk', 2020, 'Amerika'),
('The Lakes', 'Taylor Swift', 'Folk', 2020, 'Amerika'),
('Coney Island', 'Taylor Swift, The National', 'Folk', 2020, 'Amerika'),
('No Body, No Crime', 'Taylor Swift, HAIM', 'Country', 2020, 'Amerika'),
('Dorothea', 'Taylor Swift', 'Folk', 2020, 'Amerika'),
('Closure', 'Taylor Swift', 'Folk', 2020, 'Amerika'),
('Marjorie', 'Taylor Swift', 'Folk', 2020, 'Amerika'),
('Right Where You Left Me', 'Taylor Swift', 'Folk', 2020, 'Amerika'),
('It''s Time to Go', 'Taylor Swift', 'Folk', 2020, 'Amerika'),

-- ==================== K-POP ====================
('Dynamite', 'BTS', 'K-Pop', 2020, 'Korea Selatan'),
('Butter', 'BTS', 'K-Pop', 2021, 'Korea Selatan'),
('Permission to Dance', 'BTS', 'K-Pop', 2021, 'Korea Selatan'),
('Boy With Luv', 'BTS, Halsey', 'K-Pop', 2019, 'Korea Selatan'),
('DNA', 'BTS', 'K-Pop', 2017, 'Korea Selatan'),
('Fake Love', 'BTS', 'K-Pop', 2018, 'Korea Selatan'),
('Idol', 'BTS', 'K-Pop', 2018, 'Korea Selatan'),
('Mic Drop', 'BTS, Steve Aoki', 'K-Pop', 2017, 'Korea Selatan'),
('Spring Day', 'BTS', 'K-Pop', 2017, 'Korea Selatan'),
('Black Swan', 'BTS', 'K-Pop', 2020, 'Korea Selatan'),
('Life Goes On', 'BTS', 'K-Pop', 2020, 'Korea Selatan'),
('On', 'BTS', 'K-Pop', 2020, 'Korea Selatan'),
('My Universe', 'Coldplay, BTS', 'K-Pop', 2021, 'Korea Selatan'),
('Run BTS', 'BTS', 'K-Pop', 2022, 'Korea Selatan'),
('Yet to Come', 'BTS', 'K-Pop', 2022, 'Korea Selatan'),
('Take Two', 'BTS', 'K-Pop', 2023, 'Korea Selatan'),
('The Astronaut', 'Jin', 'K-Pop', 2022, 'Korea Selatan'),
('Left and Right', 'Charlie Puth, Jung Kook', 'K-Pop', 2022, 'Korea Selatan'),
('Dreamers', 'Jung Kook, Fahad Al Kubaisi', 'K-Pop', 2022, 'Korea Selatan'),
('Seven', 'Jung Kook, Latto', 'K-Pop', 2023, 'Korea Selatan'),
('3D', 'Jung Kook, Jack Harlow', 'K-Pop', 2023, 'Korea Selatan'),
('Standing Next to You', 'Jung Kook', 'K-Pop', 2023, 'Korea Selatan'),
('Like Crazy', 'Jimin', 'K-Pop', 2023, 'Korea Selatan'),
('Set Me Free Pt.2', 'Jimin', 'K-Pop', 2023, 'Korea Selatan'),
('Who', 'Jimin', 'K-Pop', 2024, 'Korea Selatan'),
('Vibe', 'Taeyang, Jimin', 'K-Pop', 2023, 'Korea Selatan'),
('Layover', 'V', 'K-Pop', 2023, 'Korea Selatan'),
('Slow Dancing', 'V', 'K-Pop', 2023, 'Korea Selatan'),
('Rainy Days', 'V', 'K-Pop', 2023, 'Korea Selatan'),
('Love Me Again', 'V', 'K-Pop', 2023, 'Korea Selatan'),
('Christmas Tree', 'V', 'K-Pop', 2021, 'Korea Selatan'),
('Indigo', 'RM', 'K-Pop', 2022, 'Korea Selatan'),
('Wild Flower', 'RM, youjeen', 'K-Pop', 2022, 'Korea Selatan'),
('Closer', 'RM, Paul Blanco, Mahalia', 'K-Pop', 2022, 'Korea Selatan'),
('Arson', 'j-hope', 'K-Pop', 2022, 'Korea Selatan'),
('More', 'j-hope', 'K-Pop', 2022, 'Korea Selatan'),
('Neuron', 'j-hope, Gaeko, yoon mirae', 'K-Pop', 2022, 'Korea Selatan'),
('On the Street', 'j-hope, J. Cole', 'K-Pop', 2023, 'Korea Selatan'),
('Haegeum', 'Agust D', 'K-Pop', 2023, 'Korea Selatan'),
('People Pt.2', 'Agust D, IU', 'K-Pop', 2023, 'Korea Selatan'),
('Amygdala', 'Agust D', 'K-Pop', 2023, 'Korea Selatan'),
('D-Day', 'Agust D', 'K-Pop', 2023, 'Korea Selatan'),
('Kill This Love', 'BLACKPINK', 'K-Pop', 2019, 'Korea Selatan'),
('DDU-DU DDU-DU', 'BLACKPINK', 'K-Pop', 2018, 'Korea Selatan'),
('How You Like That', 'BLACKPINK', 'K-Pop', 2020, 'Korea Selatan'),
('Ice Cream', 'BLACKPINK, Selena Gomez', 'K-Pop', 2020, 'Korea Selatan'),
('Lovesick Girls', 'BLACKPINK', 'K-Pop', 2020, 'Korea Selatan'),
('Pretty Savage', 'BLACKPINK', 'K-Pop', 2020, 'Korea Selatan'),
('Bet You Wanna', 'BLACKPINK, Cardi B', 'K-Pop', 2020, 'Korea Selatan'),
('Pink Venom', 'BLACKPINK', 'K-Pop', 2022, 'Korea Selatan'),
('Shut Down', 'BLACKPINK', 'K-Pop', 2022, 'Korea Selatan'),
('Typa Girl', 'BLACKPINK', 'K-Pop', 2022, 'Korea Selatan'),
('Yeah Yeah Yeah', 'BLACKPINK', 'K-Pop', 2022, 'Korea Selatan'),
('Hard to Love', 'BLACKPINK', 'K-Pop', 2022, 'Korea Selatan'),
('The Happiest Girl', 'BLACKPINK', 'K-Pop', 2022, 'Korea Selatan'),
('Tally', 'BLACKPINK', 'K-Pop', 2022, 'Korea Selatan'),
('Ready For Love', 'BLACKPINK', 'K-Pop', 2022, 'Korea Selatan'),
('Solo', 'Jennie', 'K-Pop', 2018, 'Korea Selatan'),
('You & Me', 'Jennie', 'K-Pop', 2023, 'Korea Selatan'),
('One of the Girls', 'The Weeknd, JENNIE, Lily-Rose Depp', 'K-Pop', 2023, 'Korea Selatan'),
('Mantra', 'Jennie', 'K-Pop', 2024, 'Korea Selatan'),
('On The Ground', 'Rosé', 'K-Pop', 2021, 'Korea Selatan'),
('Gone', 'Rosé', 'K-Pop', 2021, 'Korea Selatan'),
('APT.', 'Rosé, Bruno Mars', 'K-Pop', 2024, 'Korea Selatan'),
('Number One Girl', 'Rosé', 'K-Pop', 2024, 'Korea Selatan'),
('LALISA', 'Lisa', 'K-Pop', 2021, 'Korea Selatan'),
('Money', 'Lisa', 'K-Pop', 2021, 'Korea Selatan'),
('Rockstar', 'Lisa', 'K-Pop', 2024, 'Korea Selatan'),
('New Woman', 'Lisa, Rosalía', 'K-Pop', 2024, 'Korea Selatan'),
('Moonlit Floor', 'Lisa', 'K-Pop', 2024, 'Korea Selatan'),
('FLOWER', 'Jisoo', 'K-Pop', 2023, 'Korea Selatan'),
('All Eyes On Me', 'Jisoo', 'K-Pop', 2023, 'Korea Selatan'),
('Super Shy', 'NewJeans', 'K-Pop', 2023, 'Korea Selatan'),
('Ditto', 'NewJeans', 'K-Pop', 2022, 'Korea Selatan'),
('OMG', 'NewJeans', 'K-Pop', 2023, 'Korea Selatan'),
('Hype Boy', 'NewJeans', 'K-Pop', 2022, 'Korea Selatan'),
('Attention', 'NewJeans', 'K-Pop', 2022, 'Korea Selatan'),
('Cookie', 'NewJeans', 'K-Pop', 2022, 'Korea Selatan'),
('Hurt', 'NewJeans', 'K-Pop', 2022, 'Korea Selatan'),
('Cool With You', 'NewJeans', 'K-Pop', 2023, 'Korea Selatan'),
('ETA', 'NewJeans', 'K-Pop', 2023, 'Korea Selatan'),
('ASAP', 'NewJeans', 'K-Pop', 2023, 'Korea Selatan'),
('Get Up', 'NewJeans', 'K-Pop', 2023, 'Korea Selatan'),
('How Sweet', 'NewJeans', 'K-Pop', 2024, 'Korea Selatan'),
('Supernatural', 'NewJeans', 'K-Pop', 2024, 'Korea Selatan'),
('Fancy', 'TWICE', 'K-Pop', 2019, 'Korea Selatan'),
('Feel Special', 'TWICE', 'K-Pop', 2019, 'Korea Selatan'),
('TT', 'TWICE', 'K-Pop', 2016, 'Korea Selatan'),
('Like Ooh-Ahh', 'TWICE', 'K-Pop', 2015, 'Korea Selatan'),
('Cheer Up', 'TWICE', 'K-Pop', 2016, 'Korea Selatan'),
('What Is Love?', 'TWICE', 'K-Pop', 2018, 'Korea Selatan'),
('Yes or Yes', 'TWICE', 'K-Pop', 2018, 'Korea Selatan'),
('I Can''t Stop Me', 'TWICE', 'K-Pop', 2020, 'Korea Selatan'),
('Cry for Me', 'TWICE', 'K-Pop', 2020, 'Korea Selatan'),
('The Feels', 'TWICE', 'K-Pop', 2021, 'Korea Selatan'),
('Scientist', 'TWICE', 'K-Pop', 2021, 'Korea Selatan'),
('Talk that Talk', 'TWICE', 'K-Pop', 2022, 'Korea Selatan'),
('Set Me Free', 'TWICE', 'K-Pop', 2023, 'Korea Selatan'),
('Moonlight Sunrise', 'TWICE', 'K-Pop', 2023, 'Korea Selatan'),
('One Spark', 'TWICE', 'K-Pop', 2024, 'Korea Selatan'),
('God Menu', 'Stray Kids', 'K-Pop', 2023, 'Korea Selatan'),
('S-Class', 'Stray Kids', 'K-Pop', 2023, 'Korea Selatan'),
('Maniac', 'Stray Kids', 'K-Pop', 2022, 'Korea Selatan'),
('Thunderous', 'Stray Kids', 'K-Pop', 2021, 'Korea Selatan'),
('Case 143', 'Stray Kids', 'K-Pop', 2022, 'Korea Selatan'),
('LALALALA', 'Stray Kids', 'K-Pop', 2023, 'Korea Selatan'),
('Chk Chk Boom', 'Stray Kids', 'K-Pop', 2024, 'Korea Selatan'),
('Back Door', 'Stray Kids', 'K-Pop', 2020, 'Korea Selatan'),
('Red Lights', 'Stray Kids', 'K-Pop', 2021, 'Korea Selatan'),
('Christmas EveL', 'Stray Kids', 'K-Pop', 2021, 'Korea Selatan'),
('Venom', 'Stray Kids', 'K-Pop', 2022, 'Korea Selatan'),
('Freeze', 'Stray Kids', 'K-Pop', 2022, 'Korea Selatan'),
('Charmer', 'Stray Kids', 'K-Pop', 2022, 'Korea Selatan'),
('Lonely St.', 'Stray Kids', 'K-Pop', 2022, 'Korea Selatan'),
('Super Board', 'Stray Kids', 'K-Pop', 2022, 'Korea Selatan'),
('3RACHA', 'Stray Kids', 'K-Pop', 2022, 'Korea Selatan'),
('Taste', 'Stray Kids', 'K-Pop', 2022, 'Korea Selatan'),
('Give Me Your TMI', 'Stray Kids', 'K-Pop', 2022, 'Korea Selatan'),
('Circus', 'Stray Kids', 'K-Pop', 2022, 'Korea Selatan'),
('FAM', 'Stray Kids', 'K-Pop', 2022, 'Korea Selatan'),
('HOT', 'SEVENTEEN', 'K-Pop', 2022, 'Korea Selatan'),
('Darl+ing', 'SEVENTEEN', 'K-Pop', 2022, 'Korea Selatan'),
('Rock with you', 'SEVENTEEN', 'K-Pop', 2021, 'Korea Selatan'),
('Left & Right', 'SEVENTEEN', 'K-Pop', 2020, 'Korea Selatan'),
('Very Nice', 'SEVENTEEN', 'K-Pop', 2016, 'Korea Selatan'),
('Don''t Wanna Cry', 'SEVENTEEN', 'K-Pop', 2017, 'Korea Selatan'),
('Thanks', 'SEVENTEEN', 'K-Pop', 2018, 'Korea Selatan'),
('Home', 'SEVENTEEN', 'K-Pop', 2019, 'Korea Selatan'),
('Fear', 'SEVENTEEN', 'K-Pop', 2019, 'Korea Selatan'),
('Ready to Love', 'SEVENTEEN', 'K-Pop', 2021, 'Korea Selatan'),
('_World', 'SEVENTEEN', 'K-Pop', 2022, 'Korea Selatan'),
('F*ck My Life', 'SEVENTEEN', 'K-Pop', 2023, 'Korea Selatan'),
('Super', 'SEVENTEEN', 'K-Pop', 2023, 'Korea Selatan'),
('I Don''t Understand But I Luv U', 'SEVENTEEN', 'K-Pop', 2023, 'Korea Selatan'),
('God of Music', 'SEVENTEEN', 'K-Pop', 2023, 'Korea Selatan'),
('Spell', 'SEVENTEEN', 'K-Pop', 2024, 'Korea Selatan'),
('Maestro', 'SEVENTEEN', 'K-Pop', 2024, 'Korea Selatan'),
('Love, Money, Fame', 'SEVENTEEN, DJ Khaled', 'K-Pop', 2024, 'Korea Selatan'),
('Next Level', 'aespa', 'K-Pop', 2021, 'Korea Selatan'),
('Savage', 'aespa', 'K-Pop', 2021, 'Korea Selatan'),
('Black Mamba', 'aespa', 'K-Pop', 2020, 'Korea Selatan'),
('Girls', 'aespa', 'K-Pop', 2022, 'Korea Selatan'),
('Illusion', 'aespa', 'K-Pop', 2022, 'Korea Selatan'),
('Spicy', 'aespa', 'K-Pop', 2023, 'Korea Selatan'),
('Drama', 'aespa', 'K-Pop', 2023, 'Korea Selatan'),
('Supernova', 'aespa', 'K-Pop', 2024, 'Korea Selatan'),
('Armageddon', 'aespa', 'K-Pop', 2024, 'Korea Selatan'),
('Whiplash', 'aespa', 'K-Pop', 2024, 'Korea Selatan'),
('Love Dive', 'IVE', 'K-Pop', 2022, 'Korea Selatan'),
('Eleven', 'IVE', 'K-Pop', 2021, 'Korea Selatan'),
('After Like', 'IVE', 'K-Pop', 2022, 'Korea Selatan'),
('I Am', 'IVE', 'K-Pop', 2023, 'Korea Selatan'),
('Kitsch', 'IVE', 'K-Pop', 2023, 'Korea Selatan'),
('Baddie', 'IVE', 'K-Pop', 2023, 'Korea Selatan'),
('Either Way', 'IVE', 'K-Pop', 2023, 'Korea Selatan'),
('Off the Record', 'IVE', 'K-Pop', 2023, 'Korea Selatan'),
('Heya', 'IVE', 'K-Pop', 2024, 'Korea Selatan'),
('Accendio', 'IVE', 'K-Pop', 2024, 'Korea Selatan'),
('Hype Boy', 'NewJeans', 'K-Pop', 2022, 'Korea Selatan'),
('ANTIFRAGILE', 'LE SSERAFIM', 'K-Pop', 2022, 'Korea Selatan'),
('FEARLESS', 'LE SSERAFIM', 'K-Pop', 2022, 'Korea Selatan'),
('UNFORGIVEN', 'LE SSERAFIM, Nile Rodgers', 'K-Pop', 2023, 'Korea Selatan'),
('Eve, Psyche & The Bluebeard''s Wife', 'LE SSERAFIM', 'K-Pop', 2023, 'Korea Selatan'),
('Perfect Night', 'LE SSERAFIM', 'K-Pop', 2023, 'Korea Selatan'),
('Smart', 'LE SSERAFIM', 'K-Pop', 2024, 'Korea Selatan'),
('Easy', 'LE SSERAFIM', 'K-Pop', 2024, 'Korea Selatan'),
('Crazy', 'LE SSERAFIM', 'K-Pop', 2024, 'Korea Selatan'),
('1-800-hot-n-fun', 'LE SSERAFIM', 'K-Pop', 2024, 'Korea Selatan'),
('Cupid', 'FIFTY FIFTY', 'K-Pop', 2023, 'Korea Selatan'),
('Cupid (Twin Version)', 'FIFTY FIFTY', 'K-Pop', 2023, 'Korea Selatan'),
('Lovesick', 'FIFTY FIFTY', 'K-Pop', 2022, 'Korea Selatan'),
('Higher', 'FIFTY FIFTY', 'K-Pop', 2022, 'Korea Selatan'),
('Tell Me', 'FIFTY FIFTY', 'K-Pop', 2022, 'Korea Selatan'),
('Ditto', 'NewJeans', 'K-Pop', 2022, 'Korea Selatan'),
('OMG', 'NewJeans', 'K-Pop', 2023, 'Korea Selatan'),
('Left Right', 'XG', 'K-Pop', 2023, 'Jepang'),
('Shooting Star', 'XG', 'K-Pop', 2023, 'Jepang'),
('Puppet Show', 'XG', 'K-Pop', 2023, 'Jepang'),
('Tippy Toes', 'XG', 'K-Pop', 2022, 'Jepang'),
('Mascara', 'XG', 'K-Pop', 2022, 'Jepang'),
('Something Ain''t Right', 'XG', 'K-Pop', 2024, 'Jepang'),
('Woke Up', 'XG', 'K-Pop', 2024, 'Jepang'),
('Drama', 'aespa', 'K-Pop', 2023, 'Korea Selatan'),
('Regret of the Times', 'aespa', 'K-Pop', 2024, 'Korea Selatan'),

-- ==================== LATIN ====================
('Despacito', 'Luis Fonsi, Daddy Yankee', 'Latin', 2017, 'Puerto Riko'),
('Despacito Remix', 'Luis Fonsi, Daddy Yankee, Justin Bieber', 'Latin', 2017, 'Puerto Riko'),
('Bailando', 'Enrique Iglesias', 'Latin', 2014, 'Spanyol'),
('Hero', 'Enrique Iglesias', 'Latin', 2001, 'Spanyol'),
('Taki Taki', 'DJ Snake, Selena Gomez, Ozuna, Cardi B', 'Latin', 2018, 'Prancis'),
('Con Calma', 'Daddy Yankee, Snow', 'Latin', 2019, 'Puerto Riko'),
('Gasolina', 'Daddy Yankee', 'Latin', 2004, 'Puerto Riko'),
('Dura', 'Daddy Yankee', 'Latin', 2018, 'Puerto Riko'),
('La Gasolina', 'Daddy Yankee', 'Latin', 2004, 'Puerto Riko'),
('Hips Don''t Lie', 'Shakira, Wyclef Jean', 'Latin', 2006, 'Kolombia'),
('Waka Waka', 'Shakira', 'Latin', 2010, 'Kolombia'),
('La Tortura', 'Shakira, Alejandro Sanz', 'Latin', 2005, 'Kolombia'),
('Chantaje', 'Shakira, Maluma', 'Latin', 2016, 'Kolombia'),
('Bzrp Music Sessions #53', 'Bizarrap, Shakira', 'Latin', 2023, 'Argentina'),
('TQG', 'Karol G, Shakira', 'Latin', 2023, 'Kolombia'),
('Whenever, Wherever', 'Shakira', 'Latin', 2001, 'Kolombia'),
('Vivir Mi Vida', 'Marc Anthony', 'Latin', 2013, 'Amerika'),
('Flor Pálida', 'Marc Anthony', 'Latin', 2013, 'Amerika'),
('Felices los 4', 'Maluma', 'Latin', 2017, 'Kolombia'),
('Hawái', 'Maluma', 'Latin', 2020, 'Kolombia'),
('Borro Cassette', 'Maluma', 'Latin', 2015, 'Kolombia'),
('Sin Contrato', 'Maluma', 'Latin', 2016, 'Kolombia'),
('Sobrio', 'Maluma', 'Latin', 2021, 'Kolombia'),
('Canoa', 'Maluma', 'Latin', 2021, 'Kolombia'),
('Mamaíta', 'Maluma', 'Latin', 2022, 'Kolombia'),
('Junio', 'Maluma', 'Latin', 2023, 'Kolombia'),
('Según Quién', 'Maluma, Carin Leon', 'Latin', 2023, 'Kolombia'),
('Tusa', 'Karol G, Nicki Minaj', 'Latin', 2019, 'Kolombia'),
('Bichota', 'Karol G', 'Latin', 2020, 'Kolombia'),
('Provenza', 'Karol G', 'Latin', 2022, 'Kolombia'),
('MAMIII', 'Becky G, Karol G', 'Latin', 2022, 'Amerika'),
('Cairo', 'Karol G, Ovy On The Drums', 'Latin', 2022, 'Kolombia'),
('Gatúbela', 'Karol G, Maldy', 'Latin', 2022, 'Kolombia'),
('X Si Volvemos', 'Karol G, Romeo Santos', 'Latin', 2023, 'Kolombia'),
('Amargura', 'Karol G', 'Latin', 2023, 'Kolombia'),
('MIENTRAS ME CURO DEL CORA', 'Karol G', 'Latin', 2023, 'Kolombia'),
('Si Antes Te Hubiera Conocido', 'Karol G', 'Latin', 2024, 'Kolombia'),
('MI EX TENÍA RAZÓN', 'Karol G', 'Latin', 2023, 'Kolombia'),
('QLONA', 'Karol G, Peso Pluma', 'Latin', 2023, 'Kolombia'),
('La Bebe Remix', 'Yng Lvcas, Peso Pluma', 'Latin', 2023, 'Meksiko'),
('Ella Baila Sola', 'Eslabon Armado, Peso Pluma', 'Latin', 2023, 'Meksiko'),
('Lady Gaga', 'Peso Pluma, Gabito Ballesteros, Junior H', 'Latin', 2023, 'Meksiko'),
('PRC', 'Peso Pluma, Natanael Cano', 'Latin', 2023, 'Meksiko'),
('BZRP Music Sessions #55', 'Bizarrap, Peso Pluma', 'Latin', 2023, 'Argentina'),
('El Azul', 'Junior H, Peso Pluma', 'Latin', 2023, 'Meksiko'),
('AMG', 'Natanael Cano, Peso Pluma, Gabito Ballesteros', 'Latin', 2023, 'Meksiko'),
('Bye', 'Peso Pluma', 'Latin', 2023, 'Meksiko'),
('Luna', 'Peso Pluma, Junior H', 'Latin', 2023, 'Meksiko'),
('Tulum', 'Peso Pluma, Grupo Frontera', 'Latin', 2023, 'Meksiko'),
('Rompe Corazones', 'Peso Pluma, Natanael Cano', 'Latin', 2023, 'Meksiko'),
('Nueva Vida', 'Peso Pluma', 'Latin', 2023, 'Meksiko'),
('Rubicon', 'Peso Pluma', 'Latin', 2023, 'Meksiko'),
('Carnal', 'Peso Pluma, Natanael Cano', 'Latin', 2023, 'Meksiko'),
('VVS', 'Peso Pluma, Edgardo Nuñez, Los Dareyes De La Sierra', 'Latin', 2023, 'Meksiko'),
('La People', 'Peso Pluma, Tito Double P', 'Latin', 2023, 'Meksiko'),
('Bipolar', 'Peso Pluma, Jasiel Nuñez, Junior H', 'Latin', 2023, 'Meksiko'),
('Chanel', 'Becky G, Peso Pluma', 'Latin', 2023, 'Amerika'),
('La Bebe', 'Yng Lvcas', 'Latin', 2023, 'Meksiko'),
('Feria', 'Kali Uchis', 'Latin', 2023, 'Kolombia'),
('Muñekita', 'Kali Uchis, El Alfa, JT', 'Latin', 2023, 'Kolombia'),
('Labios Mordidos', 'Kali Uchis, Karol G', 'Latin', 2023, 'Kolombia'),
('No Hay Ley', 'Kali Uchis', 'Latin', 2022, 'Kolombia'),
('Me Pongo Loca', 'Kali Uchis', 'Latin', 2024, 'Kolombia'),
('Young Miko: Bzrp Music Sessions #58', 'Bizarrap, Young Miko', 'Latin', 2024, 'Argentina'),
('Classy 101', 'Feid, Young Miko', 'Latin', 2023, 'Kolombia'),
('Lisa', 'Young Miko', 'Latin', 2023, 'Puerto Riko'),
('Riri', 'Young Miko', 'Latin', 2023, 'Puerto Riko'),
('Wiggy', 'Young Miko', 'Latin', 2023, 'Puerto Riko'),
('Offline', 'Young Miko, Feid', 'Latin', 2024, 'Puerto Riko'),
('FINA', 'Bad Bunny, Young Miko', 'Latin', 2024, 'Puerto Riko'),
('Tití Me Preguntó', 'Bad Bunny', 'Latin', 2022, 'Puerto Riko'),
('Ojitos Lindos', 'Bad Bunny, Bomba Estéreo', 'Latin', 2022, 'Puerto Riko'),
('Me Porto Bonito', 'Bad Bunny, Chencho Corleone', 'Latin', 2022, 'Puerto Riko'),
('Moscow Mule', 'Bad Bunny', 'Latin', 2022, 'Puerto Riko'),
('Efecto', 'Bad Bunny', 'Latin', 2022, 'Puerto Riko'),
('Party', 'Bad Bunny, Rauw Alejandro', 'Latin', 2022, 'Puerto Riko'),
('Un Coco', 'Bad Bunny', 'Latin', 2022, 'Puerto Riko'),
('Neverita', 'Bad Bunny', 'Latin', 2022, 'Puerto Riko'),
('La Corriente', 'Bad Bunny, Tony Dize', 'Latin', 2022, 'Puerto Riko'),
('El Apagón', 'Bad Bunny', 'Latin', 2022, 'Puerto Riko'),
('Después de la Playa', 'Bad Bunny', 'Latin', 2022, 'Puerto Riko'),
('Yo No Soy Celoso', 'Bad Bunny', 'Latin', 2022, 'Puerto Riko'),
('Tarot', 'Bad Bunny, Jhayco', 'Latin', 2022, 'Puerto Riko'),
('Andrea', 'Bad Bunny, Buscabulla', 'Latin', 2022, 'Puerto Riko'),
('Callaíta', 'Bad Bunny, Tainy', 'Latin', 2019, 'Puerto Riko'),
('Dakiti', 'Bad Bunny, Jhayco', 'Latin', 2020, 'Puerto Riko'),
('Yonaguni', 'Bad Bunny', 'Latin', 2021, 'Puerto Riko'),
('AM Remix', 'Nio Garcia, J Balvin, Bad Bunny', 'Latin', 2021, 'Puerto Riko'),
('Booker T', 'Bad Bunny', 'Latin', 2020, 'Puerto Riko'),
('La Noche de Anoche', 'Bad Bunny, Rosalía', 'Latin', 2020, 'Puerto Riko'),
('Te Deseo Lo Mejor', 'Bad Bunny', 'Latin', 2020, 'Puerto Riko'),
('Yo Perreo Sola', 'Bad Bunny', 'Latin', 2020, 'Puerto Riko'),
('Safaera', 'Bad Bunny, Jowell & Randy, Ñengo Flow', 'Latin', 2020, 'Puerto Riko'),
('Si Veo a Tu Mamá', 'Bad Bunny', 'Latin', 2020, 'Puerto Riko'),
('Bichiyal', 'Bad Bunny, Yaviah', 'Latin', 2020, 'Puerto Riko'),
('Está Cabrón Ser Yo', 'Bad Bunny, Anuel AA', 'Latin', 2020, 'Puerto Riko'),
('La Santa', 'Bad Bunny, Daddy Yankee', 'Latin', 2020, 'Puerto Riko'),
('A Tu Merced', 'Bad Bunny', 'Latin', 2020, 'Puerto Riko'),
('Una Vez', 'Bad Bunny, Mora', 'Latin', 2020, 'Puerto Riko'),
('Haciendo Que Me Amas', 'Bad Bunny', 'Latin', 2020, 'Puerto Riko'),
('Soliá', 'Bad Bunny', 'Latin', 2020, 'Puerto Riko'),
('Pero Ya No', 'Bad Bunny', 'Latin', 2020, 'Puerto Riko'),
('Hablamos Mañana', 'Bad Bunny, Duki, Pablo Chill-E', 'Latin', 2020, 'Puerto Riko'),

-- ==================== AFROBEATS / AFROPOP ====================
('Last Last', 'Burna Boy', 'Afrobeats', 2022, 'Nigeria'),
('City Boys', 'Burna Boy', 'Afrobeats', 2023, 'Nigeria'),
('Ye', 'Burna Boy', 'Afrobeats', 2018, 'Nigeria'),
('On the Low', 'Burna Boy', 'Afrobeats', 2019, 'Nigeria'),
('Anybody', 'Burna Boy', 'Afrobeats', 2019, 'Nigeria'),
('Kilometre', 'Burna Boy', 'Afrobeats', 2021, 'Nigeria'),
('It''s Plenty', 'Burna Boy', 'Afrobeats', 2022, 'Nigeria'),
('Common Person', 'Burna Boy', 'Afrobeats', 2022, 'Nigeria'),
('For My Hand', 'Burna Boy, Ed Sheeran', 'Afrobeats', 2022, 'Nigeria'),
('Sungba Remix', 'Asake, Burna Boy', 'Afrobeats', 2022, 'Nigeria'),
('Sittin'' on Top of the World', 'Burna Boy, 21 Savage', 'Afrobeats', 2023, 'Nigeria'),
('Big 7', 'Burna Boy', 'Afrobeats', 2023, 'Nigeria'),
('Dey Play', 'Burna Boy', 'Afrobeats', 2023, 'Nigeria'),
('Tested, Approved & Trusted', 'Burna Boy', 'Afrobeats', 2024, 'Nigeria'),
('Higher', 'Burna Boy', 'Afrobeats', 2024, 'Nigeria'),
('Calm Down', 'Rema', 'Afrobeats', 2022, 'Nigeria'),
('Calm Down Remix', 'Rema, Selena Gomez', 'Afrobeats', 2022, 'Nigeria'),
('Dumebi', 'Rema', 'Afrobeats', 2019, 'Nigeria'),
('Lady', 'Rema', 'Afrobeats', 2020, 'Nigeria'),
('Soundgasm', 'Rema', 'Afrobeats', 2021, 'Nigeria'),
('Bounce', 'Rema', 'Afrobeats', 2021, 'Nigeria'),
('FYN', 'Rema', 'Afrobeats', 2022, 'Nigeria'),
('Holiday', 'Rema', 'Afrobeats', 2023, 'Nigeria'),
('Benin Boys', 'Rema, Shallipopi', 'Afrobeats', 2024, 'Nigeria'),
('Ozeba', 'Rema', 'Afrobeats', 2024, 'Nigeria'),
('Woman', 'Rema', 'Afrobeats', 2020, 'Nigeria'),
('Essence', 'Wizkid, Tems', 'Afrobeats', 2020, 'Nigeria'),
('Essence Remix', 'Wizkid, Justin Bieber, Tems', 'Afrobeats', 2021, 'Nigeria'),
('Ojuelegba', 'Wizkid', 'Afrobeats', 2014, 'Nigeria'),
('Come Closer', 'Wizkid, Drake', 'Afrobeats', 2017, 'Nigeria'),
('Soco', 'Wizkid', 'Afrobeats', 2018, 'Nigeria'),
('Joro', 'Wizkid', 'Afrobeats', 2019, 'Nigeria'),
('Ginger', 'Wizkid, Burna Boy', 'Afrobeats', 2020, 'Nigeria'),
('No Stress', 'Wizkid', 'Afrobeats', 2020, 'Nigeria'),
('True Love', 'Wizkid, Tay Iwar, Projexx', 'Afrobeats', 2021, 'Nigeria'),
('Bad To Me', 'Wizkid', 'Afrobeats', 2022, 'Nigeria'),
('Money & Love', 'Wizkid', 'Afrobeats', 2022, 'Nigeria'),
('Piece of My Heart', 'Wizkid, Brent Faiyaz', 'Afrobeats', 2024, 'Nigeria'),
('Free Fall', 'Tems', 'Afrobeats', 2024, 'Nigeria'),
('Love Me JeJe', 'Tems', 'Afrobeats', 2024, 'Nigeria'),
('Burning', 'Tems', 'Afrobeats', 2024, 'Nigeria'),
('Ready', 'Tems', 'Afrobeats', 2024, 'Nigeria'),
('Me & U', 'Tems', 'Afrobeats', 2023, 'Nigeria'),
('Not an Angel', 'Tems', 'Afrobeats', 2023, 'Nigeria'),
('Damages', 'Tems', 'Afrobeats', 2022, 'Nigeria'),
('Crazy Tings', 'Tems', 'Afrobeats', 2021, 'Nigeria'),
('Higher', 'Tems', 'Afrobeats', 2020, 'Nigeria'),
('Try Me', 'Tems', 'Afrobeats', 2020, 'Nigeria'),
('Free Mind', 'Tems', 'Afrobeats', 2020, 'Nigeria'),
('Water', 'Tyla', 'Afrobeats', 2023, 'Afrika Selatan'),
('Truth or Dare', 'Tyla', 'Afrobeats', 2024, 'Afrika Selatan'),
('Art', 'Tyla', 'Afrobeats', 2024, 'Afrika Selatan'),
('Jump', 'Tyla, Gunna, Skillibeng', 'Afrobeats', 2024, 'Afrika Selatan'),
('Getting Late', 'Tyla, Kooldrink', 'Afrobeats', 2021, 'Afrika Selatan'),
('Unavailable', 'Davido, Musa Keys', 'Afrobeats', 2023, 'Nigeria'),
('Feel', 'Davido', 'Afrobeats', 2023, 'Nigeria'),
('Fall', 'Davido', 'Afrobeats', 2017, 'Nigeria'),
('If', 'Davido', 'Afrobeats', 2017, 'Nigeria'),
('Fia', 'Davido', 'Afrobeats', 2018, 'Nigeria'),
('Assurance', 'Davido', 'Afrobeats', 2018, 'Nigeria'),
('Jowo', 'Davido', 'Afrobeats', 2020, 'Nigeria'),
('Holy Ground', 'Davido, Nicki Minaj', 'Afrobeats', 2020, 'Nigeria'),
('La La', 'Davido, CKay', 'Afrobeats', 2022, 'Nigeria'),
('Over Dem', 'Davido', 'Afrobeats', 2023, 'Nigeria'),
('No Competition', 'Davido, Asake', 'Afrobeats', 2023, 'Nigeria'),
('Bandana', 'Fireboy DML, Asake', 'Afrobeats', 2022, 'Nigeria'),
('Peru', 'Fireboy DML', 'Afrobeats', 2021, 'Nigeria'),
('Peru Remix', 'Fireboy DML, Ed Sheeran', 'Afrobeats', 2021, 'Nigeria'),
('Champion', 'Fireboy DML, D Smoke', 'Afrobeats', 2020, 'Nigeria'),
('Vibration', 'Fireboy DML', 'Afrobeats', 2019, 'Nigeria'),
('What If I Say', 'Fireboy DML', 'Afrobeats', 2019, 'Nigeria'),
('Like I Do', 'Fireboy DML', 'Afrobeats', 2020, 'Nigeria'),
('Tattoo', 'Fireboy DML', 'Afrobeats', 2022, 'Nigeria'),
('Soweto', 'Victony, Don Toliver, Rema', 'Afrobeats', 2022, 'Nigeria'),
('Holy Father', 'Victony, Mayorkun', 'Afrobeats', 2022, 'Nigeria'),
('Ohema', 'Victony, Cina Soul', 'Afrobeats', 2022, 'Nigeria'),
('Apollo', 'Victony', 'Afrobeats', 2023, 'Nigeria'),
('Lonely', 'Victony', 'Afrobeats', 2024, 'Nigeria'),
('Stubborn', 'Victony, Asake', 'Afrobeats', 2024, 'Nigeria'),
('OHEMA', 'Victony, Cina Soul', 'Afrobeats', 2024, 'Nigeria'),
('Lonely At The Top', 'Asake', 'Afrobeats', 2023, 'Nigeria'),
('Joha', 'Asake', 'Afrobeats', 2022, 'Nigeria'),
('Organise', 'Asake', 'Afrobeats', 2022, 'Nigeria'),
('Sungba', 'Asake', 'Afrobeats', 2022, 'Nigeria'),
('Palliative', 'Asake', 'Afrobeats', 2022, 'Nigeria'),
('Terminator', 'Asake', 'Afrobeats', 2023, 'Nigeria'),
('2:30', 'Asake', 'Afrobeats', 2023, 'Nigeria'),
('Amapiano', 'Asake, Olamide', 'Afrobeats', 2023, 'Nigeria'),
('Awodi', 'Asake', 'Afrobeats', 2023, 'Nigeria'),
('Sunshine', 'Asake', 'Afrobeats', 2024, 'Nigeria'),
('Active', 'Asake, Travis Scott', 'Afrobeats', 2024, 'Nigeria'),
('MMS', 'Asake, Wizkid', 'Afrobeats', 2024, 'Nigeria'),
('Wave', 'Asake, Central Cee', 'Afrobeats', 2024, 'Nigeria'),
('Who Is U', 'Asake', 'Afrobeats', 2024, 'Nigeria'),
('Reason', 'Omah Lay', 'Afrobeats', 2020, 'Nigeria'),
('Bad Influence', 'Omah Lay', 'Afrobeats', 2020, 'Nigeria'),
('You', 'Omah Lay', 'Afrobeats', 2020, 'Nigeria'),
('Understand', 'Omah Lay', 'Afrobeats', 2021, 'Nigeria'),
('Free My Mind', 'Omah Lay', 'Afrobeats', 2022, 'Nigeria'),
('Soso', 'Omah Lay', 'Afrobeats', 2022, 'Nigeria'),
('I''m a Mess', 'Omah Lay', 'Afrobeats', 2022, 'Nigeria'),
('Holy Ghost', 'Omah Lay', 'Afrobeats', 2023, 'Nigeria'),
('Moving', 'Omah Lay', 'Afrobeats', 2024, 'Nigeria'),
('Tanzania', 'Uncle Waffles, Tony Duardo, Sino Msolo, Boibizza', 'Amapiano', 2022, 'Eswatini'),
('Sponono', 'Uncle Waffles, Kabza De Small, DJ Maphorisa', 'Amapiano', 2022, 'Eswatini'),
('Yahyuppiyah', 'Uncle Waffles, Tony Duardo, Justin99, Pcee', 'Amapiano', 2023, 'Eswatini'),
('Peacock Revisit', 'Uncle Waffles, Ice Beats Slide', 'Amapiano', 2023, 'Eswatini'),
('Wadibusa', 'Uncle Waffles, Royal MusiQ, Ohp Sage', 'Amapiano', 2023, 'Eswatini'),
('Mnike', 'Tyler ICU, Tumelo.za, DJ Maphorisa', 'Amapiano', 2023, 'Afrika Selatan'),
('Dalie', 'Tyler ICU, Uncle Waffles', 'Amapiano', 2023, 'Afrika Selatan'),
('Banyana', 'DJ Maphorisa, Tyler ICU, Sir Trill', 'Amapiano', 2021, 'Afrika Selatan'),
('Izolo', 'DJ Maphorisa, Tyler ICU, Mpura, Daliwonga', 'Amapiano', 2021, 'Afrika Selatan'),
('Abalele', 'Kabza De Small, DJ Maphorisa, Ami Faku', 'Amapiano', 2021, 'Afrika Selatan'),

-- ==================== INDONESIA ====================
('Komang', 'Raim Laode', 'Pop Indonesia', 2023, 'Indonesia'),
('Sial', 'Mahalini', 'Pop Indonesia', 2023, 'Indonesia'),
('Bawa Dia Kembali', 'Mahalini', 'Pop Indonesia', 2023, 'Indonesia'),
('Kisah Sempurna', 'Mahalini', 'Pop Indonesia', 2024, 'Indonesia'),
('Melawan Restu', 'Mahalini', 'Pop Indonesia', 2023, 'Indonesia'),
('Bohongi Hati', 'Mahalini', 'Pop Indonesia', 2023, 'Indonesia'),
('Intuisi', 'Yura Yunita', 'Pop Indonesia', 2022, 'Indonesia'),
('Tutur Batin', 'Yura Yunita', 'Pop Indonesia', 2022, 'Indonesia'),
('Dunia Tipu-Tipu', 'Yura Yunita', 'Pop Indonesia', 2022, 'Indonesia'),
('Hoolala', 'Yura Yunita', 'Pop Indonesia', 2022, 'Indonesia'),
('Cinta dan Rahasia', 'Yura Yunita, Glenn Fredly', 'Pop Indonesia', 2014, 'Indonesia'),
('Harus Bahagia', 'Yura Yunita', 'Pop Indonesia', 2020, 'Indonesia'),
('Monokrom', 'Tulus', 'Pop Indonesia', 2016, 'Indonesia'),
('Pamit', 'Tulus', 'Pop Indonesia', 2016, 'Indonesia'),
('Ruang Sendiri', 'Tulus', 'Pop Indonesia', 2016, 'Indonesia'),
('Manusia Kuat', 'Tulus', 'Pop Indonesia', 2016, 'Indonesia'),
('Hati-Hati di Jalan', 'Tulus', 'Pop Indonesia', 2022, 'Indonesia'),
('Diri', 'Tulus', 'Pop Indonesia', 2022, 'Indonesia'),
('Ingkar', 'Tulus', 'Pop Indonesia', 2022, 'Indonesia'),
('Jatuh Suka', 'Tulus', 'Pop Indonesia', 2022, 'Indonesia'),
('Sewindu', 'Tulus', 'Pop Indonesia', 2014, 'Indonesia'),
('Gajah', 'Tulus', 'Pop Indonesia', 2014, 'Indonesia'),
('Baru', 'Tulus', 'Pop Indonesia', 2014, 'Indonesia'),
('Pupus', 'Dewa 19', 'Rock Indonesia', 2004, 'Indonesia'),
('Kangen', 'Dewa 19', 'Rock Indonesia', 1992, 'Indonesia'),
('Separuh Nafas', 'Dewa 19', 'Rock Indonesia', 2000, 'Indonesia'),
('Risalah Hati', 'Dewa 19', 'Rock Indonesia', 2000, 'Indonesia'),
('Cinta Kan Membawamu Kembali', 'Dewa 19', 'Rock Indonesia', 1997, 'Indonesia'),
('Kamulah Satu-Satunya', 'Dewa 19', 'Rock Indonesia', 1997, 'Indonesia'),
('Kosong', 'Dewa 19', 'Rock Indonesia', 1997, 'Indonesia'),
('Satu', 'Dewa 19', 'Rock Indonesia', 1997, 'Indonesia'),
('Sedang Ingin Bercinta', 'Dewa 19', 'Rock Indonesia', 2006, 'Indonesia'),
('Laskar Pelangi', 'Nidji', 'Pop Indonesia', 2008, 'Indonesia'),
('Hapus Aku', 'Nidji', 'Pop Indonesia', 2007, 'Indonesia'),
('Bila Aku Jatuh Cinta', 'Nidji', 'Pop Indonesia', 2013, 'Indonesia'),
('Ku Tak Bisa', 'Slank', 'Rock Indonesia', 2005, 'Indonesia'),
('Terlalu Manis', 'Slank', 'Rock Indonesia', 1997, 'Indonesia'),
('Balikin', 'Slank', 'Rock Indonesia', 1997, 'Indonesia'),
('Mawar Merah', 'Slank', 'Rock Indonesia', 2000, 'Indonesia'),
('Kamu Harus Pulang', 'Slank', 'Rock Indonesia', 2000, 'Indonesia'),
('Virus', 'Slank', 'Rock Indonesia', 2001, 'Indonesia'),
('Punk Rock Jalanan', 'Slank', 'Rock Indonesia', 1997, 'Indonesia'),
('Bento', 'Iwan Fals', 'Folk Indonesia', 1989, 'Indonesia'),
('Bongkar', 'Iwan Fals', 'Folk Indonesia', 1989, 'Indonesia'),
('Ibu', 'Iwan Fals', 'Folk Indonesia', 1988, 'Indonesia'),
('Bento', 'Iwan Fals', 'Folk Indonesia', 1989, 'Indonesia'),
('Negara Beringin', 'Iwan Fals', 'Folk Indonesia', 1989, 'Indonesia'),
('Sumbang', 'Iwan Fals', 'Folk Indonesia', 1989, 'Indonesia'),
('Surat Buat Wakil Rakyat', 'Iwan Fals', 'Folk Indonesia', 1989, 'Indonesia'),
('Antara Aku, Kau, dan Bekas Pacarmu', 'Iwan Fals', 'Folk Indonesia', 1989, 'Indonesia'),
('Aku Bukan Pilihan', 'Iwan Fals', 'Folk Indonesia', 1989, 'Indonesia'),
('Kemesraan', 'Iwan Fals', 'Folk Indonesia', 1988, 'Indonesia'),
('Hujan Bulan Juni', 'Dian HP', 'Pop Indonesia', 2024, 'Indonesia'),
('Duka', 'Last Child', 'Rock Indonesia', 2018, 'Indonesia'),
('Pedih', 'Last Child', 'Rock Indonesia', 2012, 'Indonesia'),
('Seluruh Nafas Ini', 'Last Child', 'Rock Indonesia', 2012, 'Indonesia'),
('Tak Pernah Ternilai', 'Last Child', 'Rock Indonesia', 2012, 'Indonesia'),
('Diary Depresiku', 'Last Child', 'Rock Indonesia', 2007, 'Indonesia'),
('Kidung', 'Last Child', 'Rock Indonesia', 2022, 'Indonesia'),
('Dunia yang Terluka', 'Last Child', 'Rock Indonesia', 2020, 'Indonesia'),
('Bintang di Surga', 'Peterpan', 'Pop Indonesia', 2004, 'Indonesia'),
('Ada Apa Denganmu', 'Peterpan', 'Pop Indonesia', 2004, 'Indonesia'),
('Ku Katakan Dengan Indah', 'Peterpan', 'Pop Indonesia', 2004, 'Indonesia'),
('Mungkin Nanti', 'Peterpan', 'Pop Indonesia', 2004, 'Indonesia'),
('Menghapus Jejakmu', 'Peterpan', 'Pop Indonesia', 2007, 'Indonesia'),
('Tak Bisakah', 'Peterpan', 'Pop Indonesia', 2004, 'Indonesia'),
('Diatas Normal', 'Peterpan', 'Pop Indonesia', 2004, 'Indonesia'),
('Kukatakan Dengan Indah', 'Peterpan', 'Pop Indonesia', 2004, 'Indonesia'),
('Walau Habis Terang', 'Peterpan', 'Pop Indonesia', 2007, 'Indonesia'),
('Separuh Aku', 'Noah', 'Pop Indonesia', 2012, 'Indonesia'),
('Hero', 'Noah', 'Pop Indonesia', 2014, 'Indonesia'),
('Terbaik', 'Noah', 'Pop Indonesia', 2016, 'Indonesia'),
('Yang Terdalam', 'Noah', 'Pop Indonesia', 2015, 'Indonesia'),
('Kau Udara Bagiku', 'Noah', 'Pop Indonesia', 2016, 'Indonesia'),
('Wanitaku', 'Noah', 'Pop Indonesia', 2016, 'Indonesia'),
('Jalani Mimpi', 'Noah', 'Pop Indonesia', 2016, 'Indonesia'),
('Menunggumu', 'Noah, Chrisye', 'Pop Indonesia', 2016, 'Indonesia'),
('Kupu-Kupu Malam', 'Titiek Puspa', 'Pop Indonesia', 1977, 'Indonesia'),
('Bing', 'Titiek Puspa', 'Pop Indonesia', 1973, 'Indonesia'),
('Cinta', 'Vina Panduwinata', 'Pop Indonesia', 1980, 'Indonesia'),
('Burung Camar', 'Vina Panduwinata', 'Pop Indonesia', 1985, 'Indonesia'),
('Kumpul Bocah', 'Vina Panduwinata', 'Pop Indonesia', 1985, 'Indonesia'),
('Badai Pasti Berlalu', 'Chrisye', 'Pop Indonesia', 1977, 'Indonesia'),
('Kala Cinta Menggoda', 'Chrisye', 'Pop Indonesia', 1997, 'Indonesia'),
('Pergilah Kasih', 'Chrisye', 'Pop Indonesia', 1991, 'Indonesia'),
('Kidung Abadi', 'Chrisye', 'Pop Indonesia', 2004, 'Indonesia'),
('Seperti Yang Kau Minta', 'Chrisye', 'Pop Indonesia', 2004, 'Indonesia'),
('Cintaku', 'Chrisye', 'Pop Indonesia', 1996, 'Indonesia'),
('Andai Aku Bisa', 'Chrisye', 'Pop Indonesia', 2004, 'Indonesia'),
('Panjang Umur', 'Chrisye', 'Pop Indonesia', 2004, 'Indonesia'),
('Damai Bersamamu', 'Chrisye', 'Pop Indonesia', 2004, 'Indonesia'),
('Aku Cinta Dia', 'Chrisye', 'Pop Indonesia', 1985, 'Indonesia'),
('Hening', 'Chrisye', 'Pop Indonesia', 1993, 'Indonesia'),
('Mimpi', 'Anggun', 'Pop Indonesia', 1989, 'Indonesia'),
('Snow on the Sahara', 'Anggun', 'Pop Internasional', 1997, 'Indonesia'),
('Bayang-Bayang Ilusi', 'Anggun', 'Pop Indonesia', 1990, 'Indonesia'),
('Tua Tua Keladi', 'Anggun', 'Pop Indonesia', 1990, 'Indonesia'),
('Yang Perdana', 'Rossa', 'Pop Indonesia', 1996, 'Indonesia'),
('Hati Yang Kau Sakiti', 'Rossa', 'Pop Indonesia', 2011, 'Indonesia'),
('Tak Sanggup Lagi', 'Rossa', 'Pop Indonesia', 2015, 'Indonesia'),
('Pudar', 'Rossa', 'Pop Indonesia', 2015, 'Indonesia'),
('Terlanjur Cinta', 'Rossa, Pasha Ungu', 'Pop Indonesia', 2009, 'Indonesia'),
('Ayat-Ayat Cinta', 'Rossa', 'Pop Indonesia', 2008, 'Indonesia'),
('Jangan Bilang Cinta', 'Rossa', 'Pop Indonesia', 2020, 'Indonesia'),
('Bukan Cinta Biasa', 'Afgan', 'Pop Indonesia', 2008, 'Indonesia'),
('Terima Kasih Cinta', 'Afgan', 'Pop Indonesia', 2008, 'Indonesia'),
('Sadis', 'Afgan', 'Pop Indonesia', 2010, 'Indonesia'),
('Pada-Mu Kuberserah', 'Afgan', 'Pop Indonesia', 2011, 'Indonesia'),
('Cinta Dua Hati', 'Afgan', 'Pop Indonesia', 2010, 'Indonesia'),
('Pesan Cinta', 'Afgan', 'Pop Indonesia', 2012, 'Indonesia'),
('Jodoh Pasti Bertemu', 'Afgan', 'Pop Indonesia', 2015, 'Indonesia'),
('Kunci Hati', 'Afgan', 'Pop Indonesia', 2017, 'Indonesia'),
('Sudah', 'Afgan', 'Pop Indonesia', 2019, 'Indonesia'),
('Cinta Luar Biasa', 'Andmesh Kamaleng', 'Pop Indonesia', 2019, 'Indonesia'),
('Hanya Rindu', 'Andmesh Kamaleng', 'Pop Indonesia', 2019, 'Indonesia'),
('Jangan Rubah Takdirku', 'Andmesh Kamaleng', 'Pop Indonesia', 2019, 'Indonesia'),
('Nyaman', 'Andmesh Kamaleng', 'Pop Indonesia', 2021, 'Indonesia'),
('Tuhan Bisa', 'Andmesh Kamaleng', 'Pop Indonesia', 2020, 'Indonesia'),
('Jangan Sampai Pasrah', 'Andmesh Kamaleng', 'Pop Indonesia', 2022, 'Indonesia'),
('Titik Akhir', 'Andmesh Kamaleng', 'Pop Indonesia', 2023, 'Indonesia'),
('Pesan Terakhir', 'Lyodra', 'Pop Indonesia', 2021, 'Indonesia'),
('Kalau Bosan', 'Lyodra', 'Pop Indonesia', 2021, 'Indonesia'),
('Sang Dewi', 'Lyodra', 'Pop Indonesia', 2022, 'Indonesia'),
('Dibalas dengan Dusta', 'Lyodra', 'Pop Indonesia', 2022, 'Indonesia'),
('Ego', 'Lyodra', 'Pop Indonesia', 2023, 'Indonesia'),
('Ada', 'Lyodra', 'Pop Indonesia', 2024, 'Indonesia'),
('Tak Dianggap', 'Lyodra', 'Pop Indonesia', 2024, 'Indonesia'),
('Cuek', 'Lyodra', 'Pop Indonesia', 2024, 'Indonesia'),
('Mengejar Matahari', 'Ari Lasso', 'Pop Indonesia', 2013, 'Indonesia'),
('Cinta Terlarang', 'Ari Lasso', 'Pop Indonesia', 2004, 'Indonesia'),
('Hampa', 'Ari Lasso', 'Pop Indonesia', 2004, 'Indonesia'),
('Arti Cinta', 'Ari Lasso', 'Pop Indonesia', 2007, 'Indonesia'),
('Aku Bukan Pilihan', 'Iwan Fals', 'Folk Indonesia', 1989, 'Indonesia'),
('Ijinkan Aku Menyayangimu', 'Iwan Fals', 'Folk Indonesia', 2002, 'Indonesia'),
('Kumenanti Seorang Kekasih', 'Iwan Fals', 'Folk Indonesia', 1989, 'Indonesia'),
('Bento', 'Iwan Fals', 'Folk Indonesia', 1989, 'Indonesia'),
('Puing', 'Iwan Fals', 'Folk Indonesia', 1988, 'Indonesia'),
('Sarjana Muda', 'Iwan Fals', 'Folk Indonesia', 1981, 'Indonesia'),
('Si Udin Bertanya', 'Iwan Fals', 'Folk Indonesia', 1983, 'Indonesia'),
('Tikus-Tikus Kantor', 'Iwan Fals', 'Folk Indonesia', 1983, 'Indonesia'),
('Yang Terlupakan', 'Iwan Fals', 'Folk Indonesia', 1983, 'Indonesia'),
('Untukmu', 'Iwan Fals', 'Folk Indonesia', 1988, 'Indonesia'),
('Alusi Au', 'Nahum Situmorang', 'Folk Indonesia', 1960, 'Indonesia'),
('Anju Ahu', 'Nahum Situmorang', 'Folk Indonesia', 1960, 'Indonesia'),
('O Tano Batak', 'Nahum Situmorang', 'Folk Indonesia', 1960, 'Indonesia'),
('Sinanggar Tulo', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Butet', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Rambadia', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Sik Sik Sibatumanikam', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Ampar-Ampar Pisang', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Yamko Rambe Yamko', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Apuse', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Manuk Dadali', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Bubuy Bulan', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Es Lilin', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Cublak-Cublak Suweng', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Gundul Pacul', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Suwe Ora Jamu', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Lir Ilir', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Jaranan', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Pitik Tukung', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Soleram', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Zapin Melayu', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Ayam Den Lapeh', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Kampuang Nan Jauh di Mato', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Bareh Solok', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Indang Sungai Garinggiang', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Tak Tong Pe', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Rasa Sayange', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Ayo Mama', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Burung Kakatua', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Sio Mama', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Gandong', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Buka Pintu', 'Lagu Tradisional', 'Folk Indonesia', 1950, 'Indonesia'),
('Tanah Airku', 'Ibu Sud', 'Nasional Indonesia', 1940, 'Indonesia'),
('Indonesia Pusaka', 'Ismail Marzuki', 'Nasional Indonesia', 1949, 'Indonesia'),
('Rayuan Pulau Kelapa', 'Ismail Marzuki', 'Nasional Indonesia', 1950, 'Indonesia'),
('Halo-Halo Bandung', 'Ismail Marzuki', 'Nasional Indonesia', 1946, 'Indonesia'),
('Sepasang Mata Bola', 'Ismail Marzuki', 'Nasional Indonesia', 1946, 'Indonesia'),
('Juwita Malam', 'Ismail Marzuki', 'Nasional Indonesia', 1950, 'Indonesia'),
('Bandung Selatan di Waktu Malam', 'Ismail Marzuki', 'Nasional Indonesia', 1946, 'Indonesia'),
('Gugur Bunga', 'Ismail Marzuki', 'Nasional Indonesia', 1945, 'Indonesia'),
('Melati di Tapal Batas', 'Ismail Marzuki', 'Nasional Indonesia', 1947, 'Indonesia'),
('Indonesia Raya', 'W.R. Supratman', 'Nasional Indonesia', 1924, 'Indonesia'),
('Ibu Kita Kartini', 'W.R. Supratman', 'Nasional Indonesia', 1929, 'Indonesia'),
('Di Timur Matahari', 'W.R. Supratman', 'Nasional Indonesia', 1931, 'Indonesia'),
('Matahari Terbit', 'W.R. Supratman', 'Nasional Indonesia', 1938, 'Indonesia'),
('Bendera Kita', 'R. Dirman Sasmokoadi', 'Nasional Indonesia', 1950, 'Indonesia'),
('Berkibarlah Benderaku', 'Ibu Sud', 'Nasional Indonesia', 1947, 'Indonesia'),
('Bagimu Negeri', 'Kusbini', 'Nasional Indonesia', 1942, 'Indonesia'),
('Garuda Pancasila', 'Sudharnoto', 'Nasional Indonesia', 1956, 'Indonesia'),
('Mars Pancasila', 'Sudharnoto', 'Nasional Indonesia', 1956, 'Indonesia'),
('Dari Sabang Sampai Merauke', 'R. Suharjo', 'Nasional Indonesia', 1947, 'Indonesia'),
('Hari Merdeka', 'H. Mutahar', 'Nasional Indonesia', 1946, 'Indonesia'),
('Syukur', 'H. Mutahar', 'Nasional Indonesia', 1945, 'Indonesia'),
('Jangan Menyerah', 'D''Masiv', 'Pop Indonesia', 2010, 'Indonesia'),
('Cinta Ini Membunuhku', 'D''Masiv', 'Pop Indonesia', 2007, 'Indonesia'),
('Rindu Setengah Mati', 'D''Masiv', 'Pop Indonesia', 2007, 'Indonesia'),
('Merindukanmu', 'D''Masiv', 'Pop Indonesia', 2007, 'Indonesia'),
('Diam Tanpa Kata', 'D''Masiv', 'Pop Indonesia', 2010, 'Indonesia'),
('Sudah Ku Bilang', 'D''Masiv', 'Pop Indonesia', 2014, 'Indonesia'),
('Esok Kan Bahagia', 'D''Masiv', 'Pop Indonesia', 2013, 'Indonesia'),
('Natural', 'D''Masiv', 'Pop Indonesia', 2014, 'Indonesia'),
('Aku Percaya', 'D''Masiv', 'Pop Indonesia', 2016, 'Indonesia'),
('Ingin Bercinta', 'D''Masiv', 'Pop Indonesia', 2012, 'Indonesia'),
('Cinta Sampai Disini', 'D''Masiv', 'Pop Indonesia', 2012, 'Indonesia'),
('Pergilah', 'D''Masiv', 'Pop Indonesia', 2015, 'Indonesia'),
('Sungguh Aku Tak Mengerti', 'D''Masiv', 'Pop Indonesia', 2017, 'Indonesia'),
('Kau Yang Ku Sayang', 'D''Masiv', 'Pop Indonesia', 2018, 'Indonesia'),
('Fatamorgana', 'D''Masiv', 'Pop Indonesia', 2020, 'Indonesia'),
('Lelaki Pantang Menyerah', 'D''Masiv', 'Pop Indonesia', 2016, 'Indonesia'),
('Kau Masih Kekasihku', 'D''Masiv', 'Pop Indonesia', 2016, 'Indonesia'),
('Apa Salahku', 'D''Masiv', 'Pop Indonesia', 2019, 'Indonesia'),
('Aku Tak Sanggup', 'D''Masiv', 'Pop Indonesia', 2020, 'Indonesia'),
('Semakin', 'D''Masiv', 'Pop Indonesia', 2021, 'Indonesia'),
('Duri', 'D''Masiv', 'Pop Indonesia', 2022, 'Indonesia'),
('Waktu Yang Salah', 'D''Masiv', 'Pop Indonesia', 2023, 'Indonesia'),
('Cinta Terbaik', 'Cassandra', 'Pop Indonesia', 2015, 'Indonesia'),
('Kamu Terlalu Berarti', 'Cassandra', 'Pop Indonesia', 2017, 'Indonesia'),
('Cinta Terlarang', 'The Virgin', 'Pop Indonesia', 2008, 'Indonesia'),
('Cinta Terlarang', 'The Virgin', 'Pop Indonesia', 2008, 'Indonesia'),
('Belahan Jiwa', 'The Virgin', 'Pop Indonesia', 2010, 'Indonesia'),
('Demi Nama Cinta', 'The Virgin', 'Pop Indonesia', 2012, 'Indonesia'),
('Tak Setia', 'The Virgin', 'Pop Indonesia', 2014, 'Indonesia'),
('Cinta Gila', 'The Virgin', 'Pop Indonesia', 2016, 'Indonesia'),
('Sakit Sakit Hatiku', 'The Virgin', 'Pop Indonesia', 2018, 'Indonesia'),
('Cinta Terlarang', 'The Virgin', 'Pop Indonesia', 2008, 'Indonesia'),
('Ku Tak Bisa', 'Slank', 'Rock Indonesia', 2005, 'Indonesia'),
('Terlalu Manis', 'Slank', 'Rock Indonesia', 1997, 'Indonesia'),
('Balikin', 'Slank', 'Rock Indonesia', 1997, 'Indonesia'),
('Mawar Merah', 'Slank', 'Rock Indonesia', 2000, 'Indonesia'),
('Kamu Harus Pulang', 'Slank', 'Rock Indonesia', 2000, 'Indonesia'),
('Virus', 'Slank', 'Rock Indonesia', 2001, 'Indonesia'),
('Punk Rock Jalanan', 'Slank', 'Rock Indonesia', 1997, 'Indonesia'),
('Terbata-Bata', 'Slank', 'Rock Indonesia', 2010, 'Indonesia'),
('I Miss You But I Hate You', 'Slank', 'Rock Indonesia', 2007, 'Indonesia'),
('Anyer 10 Maret', 'Slank', 'Rock Indonesia', 2010, 'Indonesia'),
('Kosong', 'Slank', 'Rock Indonesia', 2012, 'Indonesia'),
('Firasat', 'Slank', 'Rock Indonesia', 2015, 'Indonesia'),
('Mimpi Terindah', 'Slank', 'Rock Indonesia', 2016, 'Indonesia'),
('Too Sweet', 'Hozier', 'Folk', 2024, 'Irlandia'),
('Take Me to Church', 'Hozier', 'Folk', 2013, 'Irlandia'),
('Someone New', 'Hozier', 'Folk', 2014, 'Irlandia'),
('Cherry Wine', 'Hozier', 'Folk', 2014, 'Irlandia'),
('Work Song', 'Hozier', 'Folk', 2014, 'Irlandia'),
('From Eden', 'Hozier', 'Folk', 2014, 'Irlandia'),
('Like Real People Do', 'Hozier', 'Folk', 2014, 'Irlandia'),
('Angel of Small Death and the Codeine Scene', 'Hozier', 'Folk', 2014, 'Irlandia'),
('Jackie and Wilson', 'Hozier', 'Folk', 2014, 'Irlandia'),
('Sedated', 'Hozier', 'Folk', 2014, 'Irlandia'),
('Almost (Sweet Music)', 'Hozier', 'Folk', 2019, 'Irlandia'),
('Movement', 'Hozier', 'Folk', 2018, 'Irlandia'),
('Nina Cried Power', 'Hozier, Mavis Staples', 'Folk', 2018, 'Irlandia'),
('Dinner & Diatribes', 'Hozier', 'Folk', 2019, 'Irlandia'),
('Would That I', 'Hozier', 'Folk', 2019, 'Irlandia'),
('Shrike', 'Hozier', 'Folk', 2019, 'Irlandia'),
('Talk', 'Hozier', 'Folk', 2019, 'Irlandia'),
('Nobody''s Soldier', 'Hozier', 'Folk', 2023, 'Irlandia'),
('De Selby Part 1', 'Hozier', 'Folk', 2023, 'Irlandia'),
('De Selby Part 2', 'Hozier', 'Folk', 2023, 'Irlandia'),
('First Light', 'Hozier', 'Folk', 2023, 'Irlandia'),
('Francesca', 'Hozier', 'Folk', 2023, 'Irlandia'),
('I, Carrion (Icarian)', 'Hozier', 'Folk', 2023, 'Irlandia'),
('Eat Your Young', 'Hozier', 'Folk', 2023, 'Irlandia'),
('Damage Gets Done', 'Hozier, Brandi Carlile', 'Folk', 2023, 'Irlandia'),
('Who We Are', 'Hozier', 'Folk', 2023, 'Irlandia'),
('Son of Nyx', 'Hozier', 'Folk', 2023, 'Irlandia'),
('All Things End', 'Hozier', 'Folk', 2023, 'Irlandia'),
('To Someone From A Warm Climate', 'Hozier', 'Folk', 2023, 'Irlandia'),
('Butchered Tongue', 'Hozier', 'Folk', 2023, 'Irlandia'),
('Anything But', 'Hozier', 'Folk', 2023, 'Irlandia'),
('Abstract (Psychopomp)', 'Hozier', 'Folk', 2023, 'Irlandia'),
('Unknown / Nth', 'Hozier', 'Folk', 2023, 'Irlandia'),
('First Time', 'Hozier', 'Folk', 2023, 'Irlandia'),
('Too Sweet', 'Hozier', 'Folk', 2024, 'Irlandia'),
('Empire Now', 'Hozier', 'Folk', 2024, 'Irlandia'),
('Fare Well', 'Hozier', 'Folk', 2024, 'Irlandia'),
('Wildflower', 'Billie Eilish', 'Pop', 2024, 'Amerika'),
('Birds of a Feather', 'Billie Eilish', 'Pop', 2024, 'Amerika'),
('Lunch', 'Billie Eilish', 'Pop', 2024, 'Amerika'),
('Chihiro', 'Billie Eilish', 'Pop', 2024, 'Amerika'),
('The Greatest', 'Billie Eilish', 'Pop', 2024, 'Amerika'),
('L''Amour de Ma Vie', 'Billie Eilish', 'Pop', 2024, 'Amerika'),
('The Diner', 'Billie Eilish', 'Pop', 2024, 'Amerika'),
('Bittersuite', 'Billie Eilish', 'Pop', 2024, 'Amerika'),
('Blue', 'Billie Eilish', 'Pop', 2024, 'Amerika'),
('Skinny', 'Billie Eilish', 'Pop', 2024, 'Amerika'),
('Happier Than Ever', 'Billie Eilish', 'Pop', 2021, 'Amerika'),
('Therefore I Am', 'Billie Eilish', 'Pop', 2020, 'Amerika'),
('Your Power', 'Billie Eilish', 'Pop', 2021, 'Amerika'),
('NDA', 'Billie Eilish', 'Pop', 2021, 'Amerika'),
('Lost Cause', 'Billie Eilish', 'Pop', 2021, 'Amerika'),
('Oxytocin', 'Billie Eilish', 'Pop', 2021, 'Amerika'),
('GOLDWING', 'Billie Eilish', 'Pop', 2021, 'Amerika'),
('I Didn''t Change My Number', 'Billie Eilish', 'Pop', 2021, 'Amerika'),
('Billie Bossa Nova', 'Billie Eilish', 'Pop', 2021, 'Amerika'),
('my future', 'Billie Eilish', 'Pop', 2020, 'Amerika'),
('Everything I Wanted', 'Billie Eilish', 'Pop', 2019, 'Amerika'),
('No Time To Die', 'Billie Eilish', 'Pop', 2020, 'Amerika'),
('Sixteen', 'Billie Eilish', 'Pop', 2019, 'Amerika'),
('I Love You', 'Billie Eilish', 'Pop', 2019, 'Amerika'),
('Bury a Friend', 'Billie Eilish', 'Pop', 2019, 'Amerika'),
('Wish You Were Gay', 'Billie Eilish', 'Pop', 2019, 'Amerika'),
('When the Party''s Over', 'Billie Eilish', 'Pop', 2018, 'Amerika'),
('You Should See Me in a Crown', 'Billie Eilish', 'Pop', 2018, 'Amerika'),
('Bellyache', 'Billie Eilish', 'Pop', 2017, 'Amerika'),
('Idontwannabeyouanymore', 'Billie Eilish', 'Pop', 2017, 'Amerika'),
('Copycat', 'Billie Eilish', 'Pop', 2017, 'Amerika'),
('My Boy', 'Billie Eilish', 'Pop', 2017, 'Amerika'),
('Watch', 'Billie Eilish', 'Pop', 2017, 'Amerika'),
('Party Favor', 'Billie Eilish', 'Pop', 2017, 'Amerika'),
('Hostage', 'Billie Eilish', 'Pop', 2017, 'Amerika'),
('&Burn', 'Billie Eilish, Vince Staples', 'Pop', 2017, 'Amerika'),
('Come Out and Play', 'Billie Eilish', 'Pop', 2018, 'Amerika'),
('Lovely', 'Billie Eilish, Khalid', 'Pop', 2018, 'Amerika'),
('Bitches Broken Hearts', 'Billie Eilish', 'Pop', 2017, 'Amerika'),
('Bad Guy', 'Billie Eilish', 'Pop', 2019, 'Amerika'),
('Xanny', 'Billie Eilish', 'Pop', 2019, 'Amerika'),
('All the Good Girls Go to Hell', 'Billie Eilish', 'Pop', 2019, 'Amerika'),
('8', 'Billie Eilish', 'Pop', 2019, 'Amerika'),
('Ilomilo', 'Billie Eilish', 'Pop', 2019, 'Amerika'),
('Listen Before I Go', 'Billie Eilish', 'Pop', 2019, 'Amerika'),
('Goodbye', 'Billie Eilish', 'Pop', 2019, 'Amerika'),
('Gone, Gone, Gone', 'Phillip Phillips', 'Pop', 2012, 'Amerika'),
('Home', 'Phillip Phillips', 'Pop', 2012, 'Amerika'),
('Raging Fire', 'Phillip Phillips', 'Pop', 2014, 'Amerika'),
('Into the Wild', 'Phillip Phillips', 'Pop', 2014, 'Amerika'),
('Unpack Your Heart', 'Phillip Phillips', 'Pop', 2014, 'Amerika'),
('Magnetic', 'Phillip Phillips', 'Pop', 2018, 'Amerika'),
('Dance With Me', 'Phillip Phillips', 'Pop', 2018, 'Amerika'),
('So Strong', 'Phillip Phillips', 'Pop', 2018, 'Amerika'),
('Thrill of It All', 'Phillip Phillips', 'Pop', 2018, 'Amerika'),
('What Will Become of Us', 'Phillip Phillips', 'Pop', 2022, 'Amerika'),
('Love Like That', 'Phillip Phillips', 'Pop', 2022, 'Amerika'),
('Vampire', 'Olivia Rodrigo', 'Pop', 2023, 'Amerika'),
('Bad Idea Right?', 'Olivia Rodrigo', 'Pop', 2023, 'Amerika'),
('Get Him Back!', 'Olivia Rodrigo', 'Pop', 2023, 'Amerika'),
('All-American Bitch', 'Olivia Rodrigo', 'Pop', 2023, 'Amerika'),
('Lacy', 'Olivia Rodrigo', 'Pop', 2023, 'Amerika'),
('Ballad of a Homeschooled Girl', 'Olivia Rodrigo', 'Pop', 2023, 'Amerika'),
('Making the Bed', 'Olivia Rodrigo', 'Pop', 2023, 'Amerika'),
('Logical', 'Olivia Rodrigo', 'Pop', 2023, 'Amerika'),
('Love Is Embarrassing', 'Olivia Rodrigo', 'Pop', 2023, 'Amerika'),
('The Grudge', 'Olivia Rodrigo', 'Pop', 2023, 'Amerika'),
('Pretty Isn''t Pretty', 'Olivia Rodrigo', 'Pop', 2023, 'Amerika'),
('Teenage Dream', 'Olivia Rodrigo', 'Pop', 2023, 'Amerika'),
('Obsessed', 'Olivia Rodrigo', 'Pop', 2024, 'Amerika'),
('So American', 'Olivia Rodrigo', 'Pop', 2024, 'Amerika'),
('Stranger', 'Olivia Rodrigo', 'Pop', 2024, 'Amerika'),
('Scared of My Guitar', 'Olivia Rodrigo', 'Pop', 2024, 'Amerika'),
('Girl I''ve Always Been', 'Olivia Rodrigo', 'Pop', 2024, 'Amerika'),
('Birds of a Feather', 'Billie Eilish', 'Pop', 2024, 'Amerika'),
('Taste', 'Sabrina Carpenter', 'Pop', 2024, 'Amerika'),
('Bed Chem', 'Sabrina Carpenter', 'Pop', 2024, 'Amerika'),
('Good Graces', 'Sabrina Carpenter', 'Pop', 2024, 'Amerika'),
('Sharpest Tool', 'Sabrina Carpenter', 'Pop', 2024, 'Amerika'),
('Coincidence', 'Sabrina Carpenter', 'Pop', 2024, 'Amerika'),
('Dumb & Poetic', 'Sabrina Carpenter', 'Pop', 2024, 'Amerika'),
('Slim Pickins', 'Sabrina Carpenter', 'Pop', 2024, 'Amerika'),
('Juno', 'Sabrina Carpenter', 'Pop', 2024, 'Amerika'),
('Lie to Girls', 'Sabrina Carpenter', 'Pop', 2024, 'Amerika'),
('Don''t Smile', 'Sabrina Carpenter', 'Pop', 2024, 'Amerika'),
('Please Please Please', 'Sabrina Carpenter', 'Pop', 2024, 'Amerika'),
('Espresso', 'Sabrina Carpenter', 'Pop', 2024, 'Amerika'),
('Nonsense', 'Sabrina Carpenter', 'Pop', 2022, 'Amerika'),
('Feather', 'Sabrina Carpenter', 'Pop', 2023, 'Amerika'),
('Fast Times', 'Sabrina Carpenter', 'Pop', 2022, 'Amerika'),
('Vicious', 'Sabrina Carpenter', 'Pop', 2022, 'Amerika'),
('Because I Liked a Boy', 'Sabrina Carpenter', 'Pop', 2022, 'Amerika'),
('Already Over', 'Sabrina Carpenter', 'Pop', 2022, 'Amerika'),
('Read Your Mind', 'Sabrina Carpenter', 'Pop', 2022, 'Amerika'),
('Tornado Warnings', 'Sabrina Carpenter', 'Pop', 2022, 'Amerika'),
('Opposite', 'Sabrina Carpenter', 'Pop', 2022, 'Amerika'),
('Skinny Dipping', 'Sabrina Carpenter', 'Pop', 2022, 'Amerika'),
('Bad for Business', 'Sabrina Carpenter', 'Pop', 2022, 'Amerika'),
('Decode', 'Sabrina Carpenter', 'Pop', 2022, 'Amerika'),
('Bet U Wanna', 'Sabrina Carpenter', 'Pop', 2022, 'Amerika'),
('How Many Things', 'Sabrina Carpenter', 'Pop', 2022, 'Amerika'),
('Cindy Lou Who', 'Sabrina Carpenter', 'Pop', 2023, 'Amerika'),
('Is It New Years Yet?', 'Sabrina Carpenter', 'Pop', 2023, 'Amerika'),
('Buy Me Presents', 'Sabrina Carpenter', 'Pop', 2023, 'Amerika'),
('Santa Doesn''t Know You Like I Do', 'Sabrina Carpenter', 'Pop', 2023, 'Amerika'),
('A Nonsense Christmas', 'Sabrina Carpenter', 'Pop', 2023, 'Amerika'),
('Manchild', 'Sabrina Carpenter', 'Pop', 2025, 'Amerika'),
('Golden', 'HUNTR/X, EJAE, Audrey Nuna, Rei Ami', 'K-Pop', 2025, 'Korea Selatan'),
('Soda Pop', 'Saja Boys, Andrew Choi, Neckwav, Danny Chung, Kevin Woo, samUIL Lee', 'K-Pop', 2025, 'Korea Selatan'),
('Your Idol', 'Saja Boys, Andrew Choi, Neckwav, Danny Chung, Kevin Woo, samUIL Lee', 'K-Pop', 2025, 'Korea Selatan'),
('How It''s Done', 'HUNTR/X, EJAE, Audrey Nuna, Rei Ami', 'K-Pop', 2025, 'Korea Selatan'),
('What It Sounds Like', 'HUNTR/X, EJAE, Audrey Nuna, Rei Nuna', 'K-Pop', 2025, 'Korea Selatan'),
('Free', 'Rumi, Jinu', 'K-Pop', 2025, 'Korea Selatan'),
('Takedown', 'HUNTR/X, EJAE, Audrey Nuna, Rei Ami', 'K-Pop', 2025, 'Korea Selatan'),
('Dynamite', 'HUNTR/X, EJAE, Audrey Nuna, Rei Ami', 'K-Pop', 2025, 'Korea Selatan'),
('Strategy', 'HUNTR/X, EJAE, Audrey Nuna, Rei Ami', 'K-Pop', 2025, 'Korea Selatan'),
('Path', 'HUNTR/X, EJAE, Audrey Nuna, Rei Ami', 'K-Pop', 2025, 'Korea Selatan');