-- ============================================================
-- DATABASE: DAFTAR OBAT
-- File: daftar_obat.sql
-- Konversi lengkap dari php.txt
-- ============================================================

DROP TABLE IF EXISTS daftar_obat;

CREATE TABLE daftar_obat (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    kategori VARCHAR(150),
    golongan VARCHAR(50),
    kegunaan TEXT,
    INDEX idx_nama (nama),
    INDEX idx_kategori (kategori),
    INDEX idx_golongan (golongan)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==================== ANALGESIK & ANTIPIRETIK ====================
INSERT INTO daftar_obat (nama, kategori, golongan, kegunaan) VALUES
('Paracetamol', 'Analgesik & Antipiretik', 'Bebas', 'Meredakan nyeri ringan-sedang dan menurunkan demam'),
('Acetaminophen', 'Analgesik & Antipiretik', 'Bebas', 'Nama lain Paracetamol, nyeri dan demam'),
('Ibuprofen', 'NSAID', 'Bebas Terbatas', 'Nyeri, demam, peradangan'),
('Aspirin', 'NSAID', 'Bebas Terbatas', 'Nyeri, demam, antiplatelet'),
('Diclofenac', 'NSAID', 'Resep', 'Nyeri dan peradangan sendi'),
('Naproxen', 'NSAID', 'Resep', 'Nyeri dan peradangan'),
('Ketoprofen', 'NSAID', 'Resep', 'Nyeri dan peradangan'),
('Piroxicam', 'NSAID', 'Resep', 'Nyeri sendi dan artritis'),
('Meloxicam', 'NSAID', 'Resep', 'Artritis dan nyeri'),
('Celecoxib', 'NSAID Selective', 'Resep', 'Artritis, nyeri'),
('Etoricoxib', 'NSAID Selective', 'Resep', 'Artritis, nyeri'),
('Mefenamic Acid', 'NSAID', 'Resep', 'Nyeri, dismenore'),
('Ketorolac', 'NSAID', 'Resep', 'Nyeri sedang-berat'),
('Tramadol', 'Analgesik Opioid', 'Resep', 'Nyeri sedang-berat'),
('Morphine', 'Analgesik Opioid', 'Narkotika', 'Nyeri berat'),
('Fentanyl', 'Analgesik Opioid', 'Narkotika', 'Nyeri berat, anestesi'),
('Oxycodone', 'Analgesik Opioid', 'Narkotika', 'Nyeri berat'),
('Hydrocodone', 'Analgesik Opioid', 'Narkotika', 'Nyeri berat'),
('Codeine', 'Analgesik Opioid', 'Narkotika', 'Nyeri ringan-sedang, batuk'),
('Methadone', 'Analgesik Opioid', 'Narkotika', 'Nyeri berat, terapi adiksi'),
('Buprenorphine', 'Analgesik Opioid', 'Narkotika', 'Nyeri, terapi adiksi'),
('Pethidine', 'Analgesik Opioid', 'Narkotika', 'Nyeri berat'),
('Antalgin', 'Analgesik', 'Bebas Terbatas', 'Nyeri dan demam'),
('Metamizole', 'Analgesik', 'Resep', 'Nyeri dan demam'),
('Paracetamol + Ibuprofen', 'Analgesik Kombinasi', 'Bebas Terbatas', 'Nyeri dan demam'),
('Paracetamol + Tramadol', 'Analgesik Kombinasi', 'Resep', 'Nyeri sedang-berat'),

-- ==================== ANTIBIOTIK ====================
('Amoxicillin', 'Antibiotik Penisilin', 'Resep', 'Infeksi bakteri saluran napas, telinga, saluran kemih'),
('Amoxicillin + Clavulanate', 'Antibiotik Penisilin', 'Resep', 'Infeksi bakteri resisten'),
('Ampicillin', 'Antibiotik Penisilin', 'Resep', 'Infeksi bakteri'),
('Benzylpenicillin', 'Antibiotik Penisilin', 'Resep', 'Infeksi bakteri'),
('Phenoxymethylpenicillin', 'Antibiotik Penisilin', 'Resep', 'Infeksi bakteri'),
('Cloxacillin', 'Antibiotik Penisilin', 'Resep', 'Infeksi Staphylococcus'),
('Cephalexin', 'Antibiotik Sefalosporin', 'Resep', 'Infeksi bakteri'),
('Cefadroxil', 'Antibiotik Sefalosporin', 'Resep', 'Infeksi bakteri'),
('Cefuroxime', 'Antibiotik Sefalosporin', 'Resep', 'Infeksi bakteri'),
('Cefixime', 'Antibiotik Sefalosporin', 'Resep', 'Infeksi bakteri'),
('Ceftriaxone', 'Antibiotik Sefalosporin', 'Resep', 'Infeksi bakteri berat'),
('Cefotaxime', 'Antibiotik Sefalosporin', 'Resep', 'Infeksi bakteri berat'),
('Ceftazidime', 'Antibiotik Sefalosporin', 'Resep', 'Infeksi Pseudomonas'),
('Cefepime', 'Antibiotik Sefalosporin', 'Resep', 'Infeksi bakteri berat'),
('Ceftaroline', 'Antibiotik Sefalosporin', 'Resep', 'Infeksi MRSA'),
('Meropenem', 'Antibiotik Karbapenem', 'Resep', 'Infeksi bakteri berat'),
('Imipenem', 'Antibiotik Karbapenem', 'Resep', 'Infeksi bakteri berat'),
('Ertapenem', 'Antibiotik Karbapenem', 'Resep', 'Infeksi bakteri berat'),
('Doripenem', 'Antibiotik Karbapenem', 'Resep', 'Infeksi bakteri berat'),
('Azithromycin', 'Antibiotik Makrolida', 'Resep', 'Infeksi saluran napas'),
('Erythromycin', 'Antibiotik Makrolida', 'Resep', 'Infeksi bakteri'),
('Clarithromycin', 'Antibiotik Makrolida', 'Resep', 'Infeksi bakteri'),
('Roxithromycin', 'Antibiotik Makrolida', 'Resep', 'Infeksi bakteri'),
('Spiramycin', 'Antibiotik Makrolida', 'Resep', 'Toksoplasmosis'),
('Doxycycline', 'Antibiotik Tetrasiklin', 'Resep', 'Infeksi bakteri, malaria'),
('Tetracycline', 'Antibiotik Tetrasiklin', 'Resep', 'Infeksi bakteri'),
('Minocycline', 'Antibiotik Tetrasiklin', 'Resep', 'Akne, infeksi bakteri'),
('Tigecycline', 'Antibiotik Tetrasiklin', 'Resep', 'Infeksi bakteri resisten'),
('Gentamicin', 'Antibiotik Aminoglikosida', 'Resep', 'Infeksi bakteri gram negatif'),
('Amikacin', 'Antibiotik Aminoglikosida', 'Resep', 'Infeksi bakteri berat'),
('Tobramycin', 'Antibiotik Aminoglikosida', 'Resep', 'Infeksi Pseudomonas'),
('Streptomycin', 'Antibiotik Aminoglikosida', 'Resep', 'Tuberkulosis'),
('Neomycin', 'Antibiotik Aminoglikosida', 'Resep', 'Infeksi kulit'),
('Ciprofloxacin', 'Antibiotik Kuinolon', 'Resep', 'Infeksi saluran kemih, saluran cerna'),
('Levofloxacin', 'Antibiotik Kuinolon', 'Resep', 'Infeksi saluran napas'),
('Moxifloxacin', 'Antibiotik Kuinolon', 'Resep', 'Infeksi saluran napas'),
('Ofloxacin', 'Antibiotik Kuinolon', 'Resep', 'Infeksi bakteri'),
('Norfloxacin', 'Antibiotik Kuinolon', 'Resep', 'Infeksi saluran kemih'),
('Gatifloxacin', 'Antibiotik Kuinolon', 'Resep', 'Infeksi mata'),
('Metronidazole', 'Antibiotik Nitroimidazole', 'Resep', 'Infeksi anaerob, amebiasis'),
('Tinidazole', 'Antibiotik Nitroimidazole', 'Resep', 'Infeksi anaerob, amebiasis'),
('Ornidazole', 'Antibiotik Nitroimidazole', 'Resep', 'Infeksi anaerob'),
('Vancomycin', 'Antibiotik Glikopeptida', 'Resep', 'Infeksi MRSA'),
('Teicoplanin', 'Antibiotik Glikopeptida', 'Resep', 'Infeksi MRSA'),
('Linezolid', 'Antibiotik Oxazolidinone', 'Resep', 'Infeksi MRSA, VRE'),
('Daptomycin', 'Antibiotik Lipopeptida', 'Resep', 'Infeksi gram positif'),
('Colistin', 'Antibiotik Polimiksin', 'Resep', 'Infeksi gram negatif resisten'),
('Polymyxin B', 'Antibiotik Polimiksin', 'Resep', 'Infeksi gram negatif'),
('Chloramphenicol', 'Antibiotik', 'Resep', 'Infeksi bakteri, tifoid'),
('Clindamycin', 'Antibiotik Lincosamide', 'Resep', 'Infeksi anaerob, kulit'),
('Lincomycin', 'Antibiotik Lincosamide', 'Resep', 'Infeksi bakteri'),
('Fusidic Acid', 'Antibiotik', 'Resep', 'Infeksi kulit'),
('Mupirocin', 'Antibiotik Topikal', 'Resep', 'Infeksi kulit'),
('Bacitracin', 'Antibiotik Topikal', 'Bebas Terbatas', 'Infeksi kulit'),
('Neomycin + Bacitracin', 'Antibiotik Topikal', 'Bebas Terbatas', 'Infeksi kulit'),
('Rifampicin', 'Antibiotik', 'Resep', 'Tuberkulosis, lepra'),
('Isoniazid', 'Antituberkulosis', 'Resep', 'Tuberkulosis'),
('Pyrazinamide', 'Antituberkulosis', 'Resep', 'Tuberkulosis'),
('Ethambutol', 'Antituberkulosis', 'Resep', 'Tuberkulosis'),
('Streptomycin', 'Antituberkulosis', 'Resep', 'Tuberkulosis'),
('Dapsone', 'Antilepra', 'Resep', 'Lepra'),
('Clofazimine', 'Antilepra', 'Resep', 'Lepra'),

-- ==================== ANTIVIRAL ====================
('Acyclovir', 'Antiviral', 'Resep', 'Herpes, cacar air'),
('Valacyclovir', 'Antiviral', 'Resep', 'Herpes, cacar air'),
('Famciclovir', 'Antiviral', 'Resep', 'Herpes zoster'),
('Ganciclovir', 'Antiviral', 'Resep', 'Sitomegalovirus'),
('Valganciclovir', 'Antiviral', 'Resep', 'Sitomegalovirus'),
('Oseltamivir', 'Antiviral', 'Resep', 'Influenza'),
('Zanamivir', 'Antiviral', 'Resep', 'Influenza'),
('Peramivir', 'Antiviral', 'Resep', 'Influenza'),
('Baloxavir', 'Antiviral', 'Resep', 'Influenza'),
('Remdesivir', 'Antiviral', 'Resep', 'COVID-19, Ebola'),
('Favipiravir', 'Antiviral', 'Resep', 'COVID-19, influenza'),
('Molnupiravir', 'Antiviral', 'Resep', 'COVID-19'),
('Nirmatrelvir + Ritonavir', 'Antiviral', 'Resep', 'COVID-19'),
('Ribavirin', 'Antiviral', 'Resep', 'Hepatitis C, RSV'),
('Sofosbuvir', 'Antiviral', 'Resep', 'Hepatitis C'),
('Daclatasvir', 'Antiviral', 'Resep', 'Hepatitis C'),
('Ledipasvir', 'Antiviral', 'Resep', 'Hepatitis C'),
('Velpatasvir', 'Antiviral', 'Resep', 'Hepatitis C'),
('Glecaprevir', 'Antiviral', 'Resep', 'Hepatitis C'),
('Pibrentasvir', 'Antiviral', 'Resep', 'Hepatitis C'),
('Tenofovir', 'Antiviral', 'Resep', 'HIV, hepatitis B'),
('Entecavir', 'Antiviral', 'Resep', 'Hepatitis B'),
('Lamivudine', 'Antiviral', 'Resep', 'HIV, hepatitis B'),
('Zidovudine', 'Antiviral', 'Resep', 'HIV'),
('Efavirenz', 'Antiviral', 'Resep', 'HIV'),
('Nevirapine', 'Antiviral', 'Resep', 'HIV'),
('Ritonavir', 'Antiviral', 'Resep', 'HIV'),
('Lopinavir', 'Antiviral', 'Resep', 'HIV'),
('Atazanavir', 'Antiviral', 'Resep', 'HIV'),
('Darunavir', 'Antiviral', 'Resep', 'HIV'),
('Dolutegravir', 'Antiviral', 'Resep', 'HIV'),
('Raltegravir', 'Antiviral', 'Resep', 'HIV'),
('Bictegravir', 'Antiviral', 'Resep', 'HIV'),
('Emtricitabine', 'Antiviral', 'Resep', 'HIV'),
('Abacavir', 'Antiviral', 'Resep', 'HIV'),
('Stavudine', 'Antiviral', 'Resep', 'HIV'),
('Didanosine', 'Antiviral', 'Resep', 'HIV'),
('Enfuvirtide', 'Antiviral', 'Resep', 'HIV'),
('Maraviroc', 'Antiviral', 'Resep', 'HIV'),

-- ==================== ANTIJAMUR ====================
('Fluconazole', 'Antijamur', 'Resep', 'Kandidiasis, kriptokokosis'),
('Itraconazole', 'Antijamur', 'Resep', 'Kandidiasis, aspergillosis'),
('Voriconazole', 'Antijamur', 'Resep', 'Aspergillosis'),
('Posaconazole', 'Antijamur', 'Resep', 'Aspergillosis, kandidiasis'),
('Ketoconazole', 'Antijamur', 'Resep', 'Infeksi jamur kulit'),
('Miconazole', 'Antijamur', 'Bebas Terbatas', 'Infeksi jamur kulit'),
('Clotrimazole', 'Antijamur', 'Bebas Terbatas', 'Infeksi jamur kulit, kandidiasis'),
('Econazole', 'Antijamur', 'Bebas Terbatas', 'Infeksi jamur kulit'),
('Terbinafine', 'Antijamur', 'Resep', 'Infeksi jamur kulit, kuku'),
('Nystatin', 'Antijamur', 'Resep', 'Kandidiasis oral'),
('Amphotericin B', 'Antijamur', 'Resep', 'Infeksi jamur sistemik'),
('Griseofulvin', 'Antijamur', 'Resep', 'Infeksi jamur kulit, kuku'),
('Caspofungin', 'Antijamur', 'Resep', 'Aspergillosis, kandidiasis'),
('Micafungin', 'Antijamur', 'Resep', 'Kandidiasis'),
('Anidulafungin', 'Antijamur', 'Resep', 'Kandidiasis'),
('Flucytosine', 'Antijamur', 'Resep', 'Kriptokokosis'),

-- ==================== ANTIPARASIT ====================
('Chloroquine', 'Antimalaria', 'Resep', 'Malaria'),
('Hydroxychloroquine', 'Antimalaria', 'Resep', 'Malaria, lupus, artritis'),
('Mefloquine', 'Antimalaria', 'Resep', 'Malaria'),
('Artemether', 'Antimalaria', 'Resep', 'Malaria'),
('Artesunate', 'Antimalaria', 'Resep', 'Malaria berat'),
('Dihydroartemisinin', 'Antimalaria', 'Resep', 'Malaria'),
('Primaquine', 'Antimalaria', 'Resep', 'Malaria relaps'),
('Quinine', 'Antimalaria', 'Resep', 'Malaria'),
('Pyrimethamine', 'Antimalaria', 'Resep', 'Malaria, toksoplasmosis'),
('Sulfadoxine', 'Antimalaria', 'Resep', 'Malaria'),
('Albendazole', 'Antiparasit', 'Resep', 'Cacingan'),
('Mebendazole', 'Antiparasit', 'Bebas Terbatas', 'Cacingan'),
('Pyrantel Pamoate', 'Antiparasit', 'Bebas Terbatas', 'Cacingan'),
('Piperazine', 'Antiparasit', 'Resep', 'Cacingan'),
('Levamisole', 'Antiparasit', 'Resep', 'Cacingan'),
('Ivermectin', 'Antiparasit', 'Resep', 'Strongiloidiasis, skabies'),
('Praziquantel', 'Antiparasit', 'Resep', 'Schistosomiasis, taeniasis'),
('Niclosamide', 'Antiparasit', 'Resep', 'Taeniasis'),
('Metronidazole', 'Antiparasit', 'Resep', 'Amebiasis, giardiasis, trikomoniasis'),
('Tinidazole', 'Antiparasit', 'Resep', 'Amebiasis, giardiasis'),
('Paromomycin', 'Antiparasit', 'Resep', 'Amebiasis'),
('Diloxanide Furoate', 'Antiparasit', 'Resep', 'Amebiasis'),
('Sodium Stibogluconate', 'Antiparasit', 'Resep', 'Leishmaniasis'),
('Miltefosine', 'Antiparasit', 'Resep', 'Leishmaniasis'),
('Benznidazole', 'Antiparasit', 'Resep', 'Penyakit Chagas'),
('Nifurtimox', 'Antiparasit', 'Resep', 'Penyakit Chagas'),
('Suramin', 'Antiparasit', 'Resep', 'Trypanosomiasis Afrika'),
('Eflornithine', 'Antiparasit', 'Resep', 'Trypanosomiasis Afrika'),
('Diethylcarbamazine', 'Antiparasit', 'Resep', 'Filariasis'),
('Doxycycline', 'Antiparasit', 'Resep', 'Filariasis, malaria'),
('Permethrin', 'Antiparasit Topikal', 'Resep', 'Skabies, pedikulosis'),
('Benzyl Benzoate', 'Antiparasit Topikal', 'Bebas Terbatas', 'Skabies'),
('Sulfur Salicylate', 'Antiparasit Topikal', 'Bebas Terbatas', 'Skabies'),

-- ==================== ANTIHISTAMIN & ANTIALLERGI ====================
('Cetirizine', 'Antihistamin', 'Bebas Terbatas', 'Alergi, rhinitis'),
('Levocetirizine', 'Antihistamin', 'Resep', 'Alergi, rhinitis'),
('Loratadine', 'Antihistamin', 'Bebas Terbatas', 'Alergi'),
('Desloratadine', 'Antihistamin', 'Resep', 'Alergi'),
('Fexofenadine', 'Antihistamin', 'Resep', 'Alergi'),
('Chlorpheniramine', 'Antihistamin', 'Bebas Terbatas', 'Alergi, gatal'),
('Diphenhydramine', 'Antihistamin', 'Bebas Terbatas', 'Alergi, insomnia'),
('Promethazine', 'Antihistamin', 'Resep', 'Alergi, mual'),
('Hydroxyzine', 'Antihistamin', 'Resep', 'Alergi, cemas'),
('Cyproheptadine', 'Antihistamin', 'Resep', 'Alergi, migrain'),
('Ketotifen', 'Antihistamin', 'Resep', 'Alergi, asma'),
('Azelastine', 'Antihistamin', 'Resep', 'Rhinitis alergi'),
('Olopatadine', 'Antihistamin', 'Resep', 'Konjungtivitis alergi'),
('Epinastine', 'Antihistamin', 'Resep', 'Konjungtivitis alergi'),
('Bilastine', 'Antihistamin', 'Resep', 'Alergi'),
('Rupatadine', 'Antihistamin', 'Resep', 'Alergi'),
('Ebastine', 'Antihistamin', 'Resep', 'Alergi'),
('Mizolastine', 'Antihistamin', 'Resep', 'Alergi'),
('Prednisone', 'Kortikosteroid', 'Resep', 'Alergi berat, autoimun'),
('Prednisolone', 'Kortikosteroid', 'Resep', 'Alergi, autoimun'),
('Methylprednisolone', 'Kortikosteroid', 'Resep', 'Alergi berat, autoimun'),
('Dexamethasone', 'Kortikosteroid', 'Resep', 'Alergi, peradangan'),
('Betamethasone', 'Kortikosteroid', 'Resep', 'Peradangan, alergi'),
('Hydrocortisone', 'Kortikosteroid', 'Bebas Terbatas', 'Peradangan kulit'),
('Triamcinolone', 'Kortikosteroid', 'Resep', 'Peradangan, alergi'),
('Beclomethasone', 'Kortikosteroid', 'Resep', 'Asma, rhinitis'),
('Budesonide', 'Kortikosteroid', 'Resep', 'Asma, rhinitis, IBD'),
('Fluticasone', 'Kortikosteroid', 'Resep', 'Asma, rhinitis'),
('Mometasone', 'Kortikosteroid', 'Resep', 'Asma, rhinitis'),
('Ciclesonide', 'Kortikosteroid', 'Resep', 'Asma, rhinitis'),
('Flunisolide', 'Kortikosteroid', 'Resep', 'Rhinitis'),

-- ==================== OBAT SALURAN NAPAS ====================
('Salbutamol', 'Bronkodilator', 'Resep', 'Asma, PPOK'),
('Terbutaline', 'Bronkodilator', 'Resep', 'Asma, PPOK'),
('Fenoterol', 'Bronkodilator', 'Resep', 'Asma'),
('Salmeterol', 'Bronkodilator', 'Resep', 'Asma, PPOK'),
('Formoterol', 'Bronkodilator', 'Resep', 'Asma, PPOK'),
('Indacaterol', 'Bronkodilator', 'Resep', 'PPOK'),
('Ipratropium', 'Bronkodilator', 'Resep', 'Asma, PPOK'),
('Tiotropium', 'Bronkodilator', 'Resep', 'PPOK'),
('Aclidinium', 'Bronkodilator', 'Resep', 'PPOK'),
('Glycopyrronium', 'Bronkodilator', 'Resep', 'PPOK'),
('Umeclidinium', 'Bronkodilator', 'Resep', 'PPOK'),
('Theophylline', 'Bronkodilator', 'Resep', 'Asma, PPOK'),
('Aminophylline', 'Bronkodilator', 'Resep', 'Asma berat'),
('Montelukast', 'Antileukotrien', 'Resep', 'Asma, alergi'),
('Zafirlukast', 'Antileukotrien', 'Resep', 'Asma'),
('Pranlukast', 'Antileukotrien', 'Resep', 'Asma'),
('Omalizumab', 'Antibodi Monoklonal', 'Resep', 'Asma alergi berat'),
('Mepolizumab', 'Antibodi Monoklonal', 'Resep', 'Asma eosinofilik'),
('Benralizumab', 'Antibodi Monoklonal', 'Resep', 'Asma eosinofilik'),
('Reslizumab', 'Antibodi Monoklonal', 'Resep', 'Asma eosinofilik'),
('Dupilumab', 'Antibodi Monoklonal', 'Resep', 'Asma, dermatitis atopik'),
('Dextromethorphan', 'Antitusif', 'Bebas Terbatas', 'Batuk kering'),
('Codeine', 'Antitusif', 'Narkotika', 'Batuk kering'),
('Guaifenesin', 'Ekspektoran', 'Bebas Terbatas', 'Batuk berdahak'),
('Bromhexine', 'Mukolitik', 'Bebas Terbatas', 'Batuk berdahak'),
('Ambroxol', 'Mukolitik', 'Bebas Terbatas', 'Batuk berdahak'),
('Acetylcysteine', 'Mukolitik', 'Resep', 'Batuk berdahak, keracunan paracetamol'),
('Carbocisteine', 'Mukolitik', 'Bebas Terbatas', 'Batuk berdahak'),
('Erdosteine', 'Mukolitik', 'Resep', 'Batuk berdahak'),
('Oxymetazoline', 'Dekongestan', 'Bebas Terbatas', 'Hidung tersumbat'),
('Xylometazoline', 'Dekongestan', 'Bebas Terbatas', 'Hidung tersumbat'),
('Pseudoephedrine', 'Dekongestan', 'Bebas Terbatas', 'Hidung tersumbat'),
('Phenylephrine', 'Dekongestan', 'Bebas Terbatas', 'Hidung tersumbat'),
('Ephedrine', 'Dekongestan', 'Resep', 'Hipotensi, dekongestan'),

-- ==================== OBAT SALURAN CERNA ====================
('Omeprazole', 'PPI', 'Resep', 'Ulkus, GERD'),
('Esomeprazole', 'PPI', 'Resep', 'Ulkus, GERD'),
('Lansoprazole', 'PPI', 'Resep', 'Ulkus, GERD'),
('Pantoprazole', 'PPI', 'Resep', 'Ulkus, GERD'),
('Rabeprazole', 'PPI', 'Resep', 'Ulkus, GERD'),
('Dexlansoprazole', 'PPI', 'Resep', 'GERD'),
('Ranitidine', 'H2 Blocker', 'Bebas Terbatas', 'Ulkus, GERD'),
('Famotidine', 'H2 Blocker', 'Bebas Terbatas', 'Ulkus, GERD'),
('Cimetidine', 'H2 Blocker', 'Bebas Terbatas', 'Ulkus, GERD'),
('Nizatidine', 'H2 Blocker', 'Resep', 'Ulkus, GERD'),
('Antasida', 'Antasida', 'Bebas', 'Maag, asam lambung'),
('Aluminium Hidroksida', 'Antasida', 'Bebas', 'Maag'),
('Magnesium Hidroksida', 'Antasida', 'Bebas', 'Maag, konstipasi'),
('Calcium Carbonate', 'Antasida', 'Bebas', 'Maag, kalsium'),
('Sodium Bicarbonate', 'Antasida', 'Bebas', 'Maag'),
('Sucralfate', 'Gastroprotektif', 'Resep', 'Ulkus'),
('Bismuth Subsalicylate', 'Gastroprotektif', 'Bebas Terbatas', 'Diare, maag'),
('Misoprostol', 'Gastroprotektif', 'Resep', 'Ulkus akibat NSAID'),
('Metoclopramide', 'Antiemetik', 'Resep', 'Mual, muntah'),
('Domperidone', 'Antiemetik', 'Resep', 'Mual, muntah'),
('Ondansetron', 'Antiemetik', 'Resep', 'Mual, muntah kemoterapi'),
('Granisetron', 'Antiemetik', 'Resep', 'Mual, muntah kemoterapi'),
('Palonosetron', 'Antiemetik', 'Resep', 'Mual, muntah kemoterapi'),
('Dolasetron', 'Antiemetik', 'Resep', 'Mual, muntah'),
('Tropisetron', 'Antiemetik', 'Resep', 'Mual, muntah'),
('Prochlorperazine', 'Antiemetik', 'Resep', 'Mual, muntah'),
('Chlorpromazine', 'Antiemetik', 'Resep', 'Mual, muntah, psikosis'),
('Promethazine', 'Antiemetik', 'Resep', 'Mual, muntah, alergi'),
('Dimenhydrinate', 'Antiemetik', 'Bebas Terbatas', 'Mabuk perjalanan'),
('Scopolamine', 'Antiemetik', 'Resep', 'Mabuk perjalanan'),
('Loperamide', 'Antidiare', 'Bebas Terbatas', 'Diare'),
('Diphenoxylate', 'Antidiare', 'Resep', 'Diare'),
('Attapulgite', 'Antidiare', 'Bebas', 'Diare'),
('Kaolin + Pectin', 'Antidiare', 'Bebas', 'Diare'),
('Bismuth Subsalicylate', 'Antidiare', 'Bebas Terbatas', 'Diare'),
('Probiotik', 'Antidiare', 'Bebas', 'Diare, kesehatan pencernaan'),
('Lactobacillus', 'Probiotik', 'Bebas', 'Diare, kesehatan pencernaan'),
('Bifidobacterium', 'Probiotik', 'Bebas', 'Diare, kesehatan pencernaan'),
('Saccharomyces boulardii', 'Probiotik', 'Bebas', 'Diare'),
('Oralit', 'Rehidrasi', 'Bebas', 'Dehidrasi, diare'),
('Bisacodyl', 'Laksatif', 'Bebas Terbatas', 'Konstipasi'),
('Senna', 'Laksatif', 'Bebas', 'Konstipasi'),
('Lactulose', 'Laksatif', 'Resep', 'Konstipasi, ensefalopati hepatik'),
('Polyethylene Glycol', 'Laksatif', 'Resep', 'Konstipasi, persiapan kolonoskopi'),
('Glycerin', 'Laksatif', 'Bebas', 'Konstipasi'),
('Mineral Oil', 'Laksatif', 'Bebas', 'Konstipasi'),
('Magnesium Sulfate', 'Laksatif', 'Bebas', 'Konstipasi'),
('Psyllium', 'Laksatif Bulk', 'Bebas', 'Konstipasi'),
('Ispaghula', 'Laksatif Bulk', 'Bebas', 'Konstipasi'),
('Methylcellulose', 'Laksatif Bulk', 'Bebas', 'Konstipasi'),
('Docusate', 'Laksatif Emolien', 'Bebas', 'Konstipasi'),
('Simethicone', 'Antiflatulen', 'Bebas', 'Kembung'),
('Dimethicone', 'Antiflatulen', 'Bebas', 'Kembung'),
('Activated Charcoal', 'Antiflatulen', 'Bebas', 'Kembung, keracunan'),
('Hyoscine', 'Antispasmodik', 'Resep', 'Kram perut'),
('Dicyclomine', 'Antispasmodik', 'Resep', 'Kram perut, IBS'),
('Mebeverine', 'Antispasmodik', 'Resep', 'IBS'),
('Peppermint Oil', 'Antispasmodik', 'Bebas', 'IBS, kembung'),
('Ursodeoxycholic Acid', 'Obat Hati', 'Resep', 'Batu empedu, kolestasis'),
('Chenodeoxycholic Acid', 'Obat Hati', 'Resep', 'Batu empedu'),
('Silymarin', 'Hepatoprotektif', 'Bebas', 'Pelindung hati'),
('Curcumin', 'Hepatoprotektif', 'Bebas', 'Pelindung hati'),
('Lactulose', 'Obat Hati', 'Resep', 'Ensefalopati hepatik'),
('Rifaximin', 'Antibiotik', 'Resep', 'Ensefalopati hepatik, diare traveler'),

-- ==================== OBAT KARDIOVASKULAR ====================
('Amlodipine', 'Antihipertensi CCB', 'Resep', 'Hipertensi, angina'),
('Nifedipine', 'Antihipertensi CCB', 'Resep', 'Hipertensi, angina'),
('Felodipine', 'Antihipertensi CCB', 'Resep', 'Hipertensi'),
('Nicardipine', 'Antihipertensi CCB', 'Resep', 'Hipertensi'),
('Verapamil', 'Antihipertensi CCB', 'Resep', 'Hipertensi, aritmia'),
('Diltiazem', 'Antihipertensi CCB', 'Resep', 'Hipertensi, angina'),
('Captopril', 'ACE Inhibitor', 'Resep', 'Hipertensi, gagal jantung'),
('Enalapril', 'ACE Inhibitor', 'Resep', 'Hipertensi, gagal jantung'),
('Lisinopril', 'ACE Inhibitor', 'Resep', 'Hipertensi, gagal jantung'),
('Ramipril', 'ACE Inhibitor', 'Resep', 'Hipertensi, gagal jantung'),
('Perindopril', 'ACE Inhibitor', 'Resep', 'Hipertensi, gagal jantung'),
('Losartan', 'ARB', 'Resep', 'Hipertensi'),
('Valsartan', 'ARB', 'Resep', 'Hipertensi, gagal jantung'),
('Candesartan', 'ARB', 'Resep', 'Hipertensi'),
('Irbesartan', 'ARB', 'Resep', 'Hipertensi'),
('Telmisartan', 'ARB', 'Resep', 'Hipertensi'),
('Olmesartan', 'ARB', 'Resep', 'Hipertensi'),
('Bisoprolol', 'Beta Blocker', 'Resep', 'Hipertensi, gagal jantung'),
('Metoprolol', 'Beta Blocker', 'Resep', 'Hipertensi, angina'),
('Atenolol', 'Beta Blocker', 'Resep', 'Hipertensi, angina'),
('Propranolol', 'Beta Blocker', 'Resep', 'Hipertensi, aritmia, migrain'),
('Carvedilol', 'Beta Blocker', 'Resep', 'Gagal jantung, hipertensi'),
('Nebivolol', 'Beta Blocker', 'Resep', 'Hipertensi, gagal jantung'),
('Labetalol', 'Beta Blocker', 'Resep', 'Hipertensi'),
('Hydrochlorothiazide', 'Diuretik', 'Resep', 'Hipertensi, edema'),
('Furosemide', 'Diuretik', 'Resep', 'Edema, gagal jantung'),
('Spironolactone', 'Diuretik', 'Resep', 'Gagal jantung, sirosis'),
('Eplerenone', 'Diuretik', 'Resep', 'Gagal jantung'),
('Chlorthalidone', 'Diuretik', 'Resep', 'Hipertensi'),
('Indapamide', 'Diuretik', 'Resep', 'Hipertensi'),
('Bumetanide', 'Diuretik', 'Resep', 'Edema'),
('Torsemide', 'Diuretik', 'Resep', 'Edema, hipertensi'),
('Mannitol', 'Diuretik Osmotik', 'Resep', 'Edema serebral'),
('Acetazolamide', 'Diuretik', 'Resep', 'Glaukoma, altitude sickness'),
('Atorvastatin', 'Statin', 'Resep', 'Kolesterol tinggi'),
('Simvastatin', 'Statin', 'Resep', 'Kolesterol tinggi'),
('Rosuvastatin', 'Statin', 'Resep', 'Kolesterol tinggi'),
('Pravastatin', 'Statin', 'Resep', 'Kolesterol tinggi'),
('Lovastatin', 'Statin', 'Resep', 'Kolesterol tinggi'),
('Pitavastatin', 'Statin', 'Resep', 'Kolesterol tinggi'),
('Fluvastatin', 'Statin', 'Resep', 'Kolesterol tinggi'),
('Ezetimibe', 'Antilipid', 'Resep', 'Kolesterol tinggi'),
('Fenofibrate', 'Fibrat', 'Resep', 'Trigliserida tinggi'),
('Gemfibrozil', 'Fibrat', 'Resep', 'Trigliserida tinggi'),
('Niacin', 'Antilipid', 'Resep', 'Kolesterol tinggi'),
('Omega-3', 'Antilipid', 'Bebas', 'Trigliserida tinggi'),
('Aspirin', 'Antiplatelet', 'Bebas Terbatas', 'Pencegahan stroke, serangan jantung'),
('Clopidogrel', 'Antiplatelet', 'Resep', 'Pencegahan stroke, serangan jantung'),
('Ticagrelor', 'Antiplatelet', 'Resep', 'Sindrom koroner akut'),
('Prasugrel', 'Antiplatelet', 'Resep', 'Sindrom koroner akut'),
('Dipyridamole', 'Antiplatelet', 'Resep', 'Pencegahan stroke'),
('Warfarin', 'Antikoagulan', 'Resep', 'Antikoagulan'),
('Heparin', 'Antikoagulan', 'Resep', 'Antikoagulan'),
('Enoxaparin', 'Antikoagulan', 'Resep', 'Antikoagulan'),
('Dalteparin', 'Antikoagulan', 'Resep', 'Antikoagulan'),
('Fondaparinux', 'Antikoagulan', 'Resep', 'Antikoagulan'),
('Rivaroxaban', 'Antikoagulan', 'Resep', 'Antikoagulan'),
('Apixaban', 'Antikoagulan', 'Resep', 'Antikoagulan'),
('Edoxaban', 'Antikoagulan', 'Resep', 'Antikoagulan'),
('Dabigatran', 'Antikoagulan', 'Resep', 'Antikoagulan'),
('Digoxin', 'Inotropik', 'Resep', 'Gagal jantung, aritmia'),
('Digitoxin', 'Inotropik', 'Resep', 'Gagal jantung'),
('Dobutamine', 'Inotropik', 'Resep', 'Gagal jantung akut'),
('Dopamine', 'Inotropik', 'Resep', 'Syok, hipotensi'),
('Epinephrine', 'Vasopresor', 'Resep', 'Anafilaksis, henti jantung'),
('Norepinephrine', 'Vasopresor', 'Resep', 'Syok, hipotensi'),
('Vasopressin', 'Vasopresor', 'Resep', 'Syok, diabetes insipidus'),
('Phenylephrine', 'Vasopresor', 'Resep', 'Hipotensi'),
('Milrinone', 'Inotropik', 'Resep', 'Gagal jantung'),
('Nitroglycerin', 'Vasodilator', 'Resep', 'Angina'),
('Isosorbide Dinitrate', 'Vasodilator', 'Resep', 'Angina'),
('Isosorbide Mononitrate', 'Vasodilator', 'Resep', 'Angina'),
('Hydralazine', 'Vasodilator', 'Resep', 'Hipertensi'),
('Minoxidil', 'Vasodilator', 'Resep', 'Hipertensi, rambut rontok'),
('Sildenafil', 'PDE5 Inhibitor', 'Resep', 'Disfungsi ereksi, hipertensi pulmonal'),
('Tadalafil', 'PDE5 Inhibitor', 'Resep', 'Disfungsi ereksi, hipertensi pulmonal'),
('Vardenafil', 'PDE5 Inhibitor', 'Resep', 'Disfungsi ereksi'),
('Avanafil', 'PDE5 Inhibitor', 'Resep', 'Disfungsi ereksi'),

-- ==================== OBAT DIABETES ====================
('Metformin', 'Antidiabetes', 'Resep', 'Diabetes tipe 2'),
('Glibenclamide', 'Sulfonilurea', 'Resep', 'Diabetes tipe 2'),
('Glimepiride', 'Sulfonilurea', 'Resep', 'Diabetes tipe 2'),
('Glipizide', 'Sulfonilurea', 'Resep', 'Diabetes tipe 2'),
('Gliclazide', 'Sulfonilurea', 'Resep', 'Diabetes tipe 2'),
('Tolbutamide', 'Sulfonilurea', 'Resep', 'Diabetes tipe 2'),
('Acarbose', 'Antidiabetes', 'Resep', 'Diabetes tipe 2'),
('Miglitol', 'Antidiabetes', 'Resep', 'Diabetes tipe 2'),
('Pioglitazone', 'TZD', 'Resep', 'Diabetes tipe 2'),
('Rosiglitazone', 'TZD', 'Resep', 'Diabetes tipe 2'),
('Sitagliptin', 'DPP-4 Inhibitor', 'Resep', 'Diabetes tipe 2'),
('Saxagliptin', 'DPP-4 Inhibitor', 'Resep', 'Diabetes tipe 2'),
('Linagliptin', 'DPP-4 Inhibitor', 'Resep', 'Diabetes tipe 2'),
('Vildagliptin', 'DPP-4 Inhibitor', 'Resep', 'Diabetes tipe 2'),
('Alogliptin', 'DPP-4 Inhibitor', 'Resep', 'Diabetes tipe 2'),
('Exenatide', 'GLP-1 Agonist', 'Resep', 'Diabetes tipe 2'),
('Liraglutide', 'GLP-1 Agonist', 'Resep', 'Diabetes tipe 2, obesitas'),
('Dulaglutide', 'GLP-1 Agonist', 'Resep', 'Diabetes tipe 2'),
('Semaglutide', 'GLP-1 Agonist', 'Resep', 'Diabetes tipe 2, obesitas'),
('Tirzepatide', 'GIP/GLP-1 Agonist', 'Resep', 'Diabetes tipe 2, obesitas'),
('Dapagliflozin', 'SGLT2 Inhibitor', 'Resep', 'Diabetes tipe 2, gagal jantung'),
('Empagliflozin', 'SGLT2 Inhibitor', 'Resep', 'Diabetes tipe 2, gagal jantung'),
('Canagliflozin', 'SGLT2 Inhibitor', 'Resep', 'Diabetes tipe 2'),
('Ertugliflozin', 'SGLT2 Inhibitor', 'Resep', 'Diabetes tipe 2'),
('Insulin Regular', 'Insulin', 'Resep', 'Diabetes tipe 1 & 2'),
('Insulin NPH', 'Insulin', 'Resep', 'Diabetes tipe 1 & 2'),
('Insulin Glargine', 'Insulin', 'Resep', 'Diabetes tipe 1 & 2'),
('Insulin Detemir', 'Insulin', 'Resep', 'Diabetes tipe 1 & 2'),
('Insulin Degludec', 'Insulin', 'Resep', 'Diabetes tipe 1 & 2'),
('Insulin Aspart', 'Insulin', 'Resep', 'Diabetes tipe 1 & 2'),
('Insulin Lispro', 'Insulin', 'Resep', 'Diabetes tipe 1 & 2'),
('Insulin Glulisine', 'Insulin', 'Resep', 'Diabetes tipe 1 & 2'),
('Insulin Premix', 'Insulin', 'Resep', 'Diabetes tipe 1 & 2'),
('Glucagon', 'Hormon', 'Resep', 'Hipoglikemia berat'),

-- ==================== OBAT TIROID ====================
('Levothyroxine', 'Hormon Tiroid', 'Resep', 'Hipotiroidisme'),
('Liothyronine', 'Hormon Tiroid', 'Resep', 'Hipotiroidisme'),
('Methimazole', 'Antitiroid', 'Resep', 'Hipertiroidisme'),
('Propylthiouracil', 'Antitiroid', 'Resep', 'Hipertiroidisme'),
('Carbimazole', 'Antitiroid', 'Resep', 'Hipertiroidisme'),
('Potassium Iodide', 'Antitiroid', 'Resep', 'Hipertiroidisme, proteksi radiasi'),

-- ==================== OBAT PSIKIATRI ====================
('Fluoxetine', 'SSRI', 'Resep', 'Depresi, OCD, bulimia'),
('Sertraline', 'SSRI', 'Resep', 'Depresi, OCD, PTSD'),
('Paroxetine', 'SSRI', 'Resep', 'Depresi, cemas, OCD'),
('Citalopram', 'SSRI', 'Resep', 'Depresi'),
('Escitalopram', 'SSRI', 'Resep', 'Depresi, cemas'),
('Fluvoxamine', 'SSRI', 'Resep', 'OCD, depresi'),
('Venlafaxine', 'SNRI', 'Resep', 'Depresi, cemas'),
('Duloxetine', 'SNRI', 'Resep', 'Depresi, nyeri neuropati'),
('Desvenlafaxine', 'SNRI', 'Resep', 'Depresi'),
('Milnacipran', 'SNRI', 'Resep', 'Depresi, fibromialgia'),
('Bupropion', 'Antidepresan', 'Resep', 'Depresi, berhenti merokok'),
('Mirtazapine', 'Antidepresan', 'Resep', 'Depresi'),
('Trazodone', 'Antidepresan', 'Resep', 'Depresi, insomnia'),
('Vortioxetine', 'Antidepresan', 'Resep', 'Depresi'),
('Vilazodone', 'Antidepresan', 'Resep', 'Depresi'),
('Amitriptyline', 'TCA', 'Resep', 'Depresi, nyeri neuropati'),
('Nortriptyline', 'TCA', 'Resep', 'Depresi, nyeri neuropati'),
('Imipramine', 'TCA', 'Resep', 'Depresi, enuresis'),
('Clomipramine', 'TCA', 'Resep', 'OCD, depresi'),
('Doxepin', 'TCA', 'Resep', 'Depresi, insomnia'),
('Phenelzine', 'MAOI', 'Resep', 'Depresi'),
('Tranylcypromine', 'MAOI', 'Resep', 'Depresi'),
('Moclobemide', 'MAOI', 'Resep', 'Depresi'),
('Selegiline', 'MAOI', 'Resep', 'Parkinson, depresi'),
('Haloperidol', 'Antipsikotik', 'Resep', 'Skizofrenia, agitasi'),
('Chlorpromazine', 'Antipsikotik', 'Resep', 'Skizofrenia'),
('Risperidone', 'Antipsikotik', 'Resep', 'Skizofrenia, bipolar'),
('Olanzapine', 'Antipsikotik', 'Resep', 'Skizofrenia, bipolar'),
('Quetiapine', 'Antipsikotik', 'Resep', 'Skizofrenia, bipolar'),
('Aripiprazole', 'Antipsikotik', 'Resep', 'Skizofrenia, bipolar'),
('Ziprasidone', 'Antipsikotik', 'Resep', 'Skizofrenia'),
('Paliperidone', 'Antipsikotik', 'Resep', 'Skizofrenia'),
('Amisulpride', 'Antipsikotik', 'Resep', 'Skizofrenia'),
('Clozapine', 'Antipsikotik', 'Resep', 'Skizofrenia resisten'),
('Lithium', 'Mood Stabilizer', 'Resep', 'Bipolar'),
('Valproic Acid', 'Mood Stabilizer', 'Resep', 'Bipolar, epilepsi'),
('Carbamazepine', 'Mood Stabilizer', 'Resep', 'Bipolar, epilepsi'),
('Lamotrigine', 'Mood Stabilizer', 'Resep', 'Bipolar, epilepsi'),
('Divalproex', 'Mood Stabilizer', 'Resep', 'Bipolar, epilepsi'),
('Diazepam', 'Benzodiazepin', 'Resep', 'Cemas, kejang, relaksasi otot'),
('Lorazepam', 'Benzodiazepin', 'Resep', 'Cemas, insomnia'),
('Alprazolam', 'Benzodiazepin', 'Resep', 'Cemas, panik'),
('Clonazepam', 'Benzodiazepin', 'Resep', 'Panik, kejang'),
('Midazolam', 'Benzodiazepin', 'Resep', 'Sedasi, anestesi'),
('Oxazepam', 'Benzodiazepin', 'Resep', 'Cemas, insomnia'),
('Temazepam', 'Benzodiazepin', 'Resep', 'Insomnia'),
('Nitrazepam', 'Benzodiazepin', 'Resep', 'Insomnia'),
('Flurazepam', 'Benzodiazepin', 'Resep', 'Insomnia'),
('Triazolam', 'Benzodiazepin', 'Resep', 'Insomnia'),
('Buspirone', 'Anksiolitik', 'Resep', 'Cemas'),
('Hydroxyzine', 'Anksiolitik', 'Resep', 'Cemas, alergi'),
('Pregabalin', 'Anksiolitik', 'Resep', 'Cemas, nyeri neuropati, epilepsi'),
('Gabapentin', 'Antikonvulsan', 'Resep', 'Epilepsi, nyeri neuropati'),
('Zolpidem', 'Hipnotik', 'Resep', 'Insomnia'),
('Zaleplon', 'Hipnotik', 'Resep', 'Insomnia'),
('Eszopiclone', 'Hipnotik', 'Resep', 'Insomnia'),
('Ramelteon', 'Hipnotik', 'Resep', 'Insomnia'),
('Melatonin', 'Hipnotik', 'Bebas', 'Insomnia, jet lag'),
('Diphenhydramine', 'Hipnotik', 'Bebas Terbatas', 'Insomnia, alergi'),
('Doxylamine', 'Hipnotik', 'Bebas Terbatas', 'Insomnia, mual'),

-- ==================== OBAT NYERI & MUSKULOSKELETAL ====================
('Paracetamol', 'Analgesik', 'Bebas', 'Nyeri, demam'),
('Ibuprofen', 'NSAID', 'Bebas Terbatas', 'Nyeri, demam, peradangan'),
('Diclofenac', 'NSAID', 'Resep', 'Nyeri sendi, artritis'),
('Ketoprofen', 'NSAID', 'Resep', 'Nyeri, artritis'),
('Piroxicam', 'NSAID', 'Resep', 'Artritis'),
('Meloxicam', 'NSAID', 'Resep', 'Artritis'),
('Celecoxib', 'NSAID Selective', 'Resep', 'Artritis'),
('Etoricoxib', 'NSAID Selective', 'Resep', 'Artritis'),
('Mefenamic Acid', 'NSAID', 'Resep', 'Nyeri, dismenore'),
('Ketorolac', 'NSAID', 'Resep', 'Nyeri sedang-berat'),
('Tramadol', 'Opioid', 'Resep', 'Nyeri sedang-berat'),
('Morphine', 'Opioid', 'Narkotika', 'Nyeri berat'),
('Fentanyl', 'Opioid', 'Narkotika', 'Nyeri berat, anestesi'),
('Oxycodone', 'Opioid', 'Narkotika', 'Nyeri berat'),
('Codeine', 'Opioid', 'Narkotika', 'Nyeri, batuk'),
('Methocarbamol', 'Relaksan Otot', 'Resep', 'Spasme otot'),
('Carisoprodol', 'Relaksan Otot', 'Resep', 'Spasme otot'),
('Cyclobenzaprine', 'Relaksan Otot', 'Resep', 'Spasme otot'),
('Baclofen', 'Relaksan Otot', 'Resep', 'Spasme otot, MS'),
('Tizanidine', 'Relaksan Otot', 'Resep', 'Spasme otot'),
('Dantrolene', 'Relaksan Otot', 'Resep', 'Spasme otot, malignant hyperthermia'),
('Orphenadrine', 'Relaksan Otot', 'Resep', 'Spasme otot'),
('Chlorzoxazone', 'Relaksan Otot', 'Resep', 'Spasme otot'),
('Allopurinol', 'Antigout', 'Resep', 'Gout'),
('Febuxostat', 'Antigout', 'Resep', 'Gout'),
('Colchicine', 'Antigout', 'Resep', 'Gout akut'),
('Probenecid', 'Antigout', 'Resep', 'Gout'),
('Sulfinpyrazone', 'Antigout', 'Resep', 'Gout'),
('Hydroxychloroquine', 'DMARD', 'Resep', 'Artritis reumatoid, lupus'),
('Methotrexate', 'DMARD', 'Resep', 'Artritis reumatoid, kanker'),
('Sulfasalazine', 'DMARD', 'Resep', 'Artritis reumatoid, IBD'),
('Leflunomide', 'DMARD', 'Resep', 'Artritis reumatoid'),
('Azathioprine', 'Imunosupresan', 'Resep', 'Autoimun, transplantasi'),
('Cyclosporine', 'Imunosupresan', 'Resep', 'Autoimun, transplantasi'),
('Tacrolimus', 'Imunosupresan', 'Resep', 'Autoimun, transplantasi'),
('Mycophenolate', 'Imunosupresan', 'Resep', 'Autoimun, transplantasi'),
('Adalimumab', 'Biologik', 'Resep', 'Artritis reumatoid, Crohn'),
('Infliximab', 'Biologik', 'Resep', 'Artritis reumatoid, Crohn'),
('Etanercept', 'Biologik', 'Resep', 'Artritis reumatoid'),
('Golimumab', 'Biologik', 'Resep', 'Artritis reumatoid'),
('Certolizumab', 'Biologik', 'Resep', 'Artritis reumatoid, Crohn'),
('Rituximab', 'Biologik', 'Resep', 'Artritis reumatoid, limfoma'),
('Tocilizumab', 'Biologik', 'Resep', 'Artritis reumatoid'),
('Abatacept', 'Biologik', 'Resep', 'Artritis reumatoid'),
('Secukinumab', 'Biologik', 'Resep', 'Psoriasis, artritis psoriatik'),
('Ustekinumab', 'Biologik', 'Resep', 'Psoriasis, Crohn'),
('Vedolizumab', 'Biologik', 'Resep', 'Kolitis ulseratif, Crohn'),

-- ==================== OBAT MATA & TELINGA ====================
('Timolol', 'Obat Glaukoma', 'Resep', 'Glaukoma'),
('Latanoprost', 'Obat Glaukoma', 'Resep', 'Glaukoma'),
('Travoprost', 'Obat Glaukoma', 'Resep', 'Glaukoma'),
('Bimatoprost', 'Obat Glaukoma', 'Resep', 'Glaukoma, bulu mata'),
('Dorzolamide', 'Obat Glaukoma', 'Resep', 'Glaukoma'),
('Brinzolamide', 'Obat Glaukoma', 'Resep', 'Glaukoma'),
('Pilocarpine', 'Obat Glaukoma', 'Resep', 'Glaukoma'),
('Tropicamide', 'Midriatik', 'Resep', 'Dilatasi pupil'),
('Atropine', 'Midriatik', 'Resep', 'Dilatasi pupil, keracunan organofosfat'),
('Cyclopentolate', 'Midriatik', 'Resep', 'Dilatasi pupil'),
('Phenylephrine', 'Midriatik', 'Resep', 'Dilatasi pupil'),
('Olopatadine', 'Obat Mata Alergi', 'Resep', 'Konjungtivitis alergi'),
('Ketotifen', 'Obat Mata Alergi', 'Resep', 'Konjungtivitis alergi'),
('Azelastine', 'Obat Mata Alergi', 'Resep', 'Konjungtivitis alergi'),
('Cromolyn', 'Obat Mata Alergi', 'Resep', 'Konjungtivitis alergi'),
('Artificial Tears', 'Obat Mata', 'Bebas', 'Mata kering'),
('Hyaluronic Acid', 'Obat Mata', 'Bebas', 'Mata kering'),
('Chloramphenicol', 'Antibiotik Mata', 'Resep', 'Infeksi mata'),
('Tobramycin', 'Antibiotik Mata', 'Resep', 'Infeksi mata'),
('Gentamicin', 'Antibiotik Mata', 'Resep', 'Infeksi mata'),
('Ciprofloxacin', 'Antibiotik Mata', 'Resep', 'Infeksi mata'),
('Ofloxacin', 'Antibiotik Mata', 'Resep', 'Infeksi mata'),
('Moxifloxacin', 'Antibiotik Mata', 'Resep', 'Infeksi mata'),
('Acyclovir', 'Antiviral Mata', 'Resep', 'Herpes mata'),
('Ganciclovir', 'Antiviral Mata', 'Resep', 'Herpes mata'),
('Natamycin', 'Antijamur Mata', 'Resep', 'Infeksi jamur mata'),
('Amphotericin B', 'Antijamur Mata', 'Resep', 'Infeksi jamur mata'),
('Fluconazole', 'Antijamur Mata', 'Resep', 'Infeksi jamur mata'),
('Prednisolone', 'Steroid Mata', 'Resep', 'Peradangan mata'),
('Dexamethasone', 'Steroid Mata', 'Resep', 'Peradangan mata'),
('Fluorometholone', 'Steroid Mata', 'Resep', 'Peradangan mata'),
('Loteprednol', 'Steroid Mata', 'Resep', 'Peradangan mata'),
('Diclofenac', 'NSAID Mata', 'Resep', 'Peradangan mata'),
('Ketorolac', 'NSAID Mata', 'Resep', 'Peradangan mata'),
('Bromfenac', 'NSAID Mata', 'Resep', 'Peradangan mata'),
('Nepafenac', 'NSAID Mata', 'Resep', 'Peradangan mata'),
('Ciprofloxacin', 'Antibiotik Telinga', 'Resep', 'Infeksi telinga'),
('Ofloxacin', 'Antibiotik Telinga', 'Resep', 'Infeksi telinga'),
('Neomycin', 'Antibiotik Telinga', 'Resep', 'Infeksi telinga'),
('Polymyxin B', 'Antibiotik Telinga', 'Resep', 'Infeksi telinga'),
('Hydrocortisone', 'Steroid Telinga', 'Resep', 'Peradangan telinga'),
('Dexamethasone', 'Steroid Telinga', 'Resep', 'Peradangan telinga'),
('Clotrimazole', 'Antijamur Telinga', 'Resep', 'Infeksi jamur telinga'),
('Miconazole', 'Antijamur Telinga', 'Resep', 'Infeksi jamur telinga'),

-- ==================== OBAT KULIT ====================
('Hydrocortisone', 'Steroid Topikal', 'Bebas Terbatas', 'Peradangan kulit, alergi'),
('Betamethasone', 'Steroid Topikal', 'Resep', 'Peradangan kulit'),
('Dexamethasone', 'Steroid Topikal', 'Resep', 'Peradangan kulit'),
('Clobetasol', 'Steroid Topikal', 'Resep', 'Peradangan kulit berat'),
('Mometasone', 'Steroid Topikal', 'Resep', 'Peradangan kulit'),
('Triamcinolone', 'Steroid Topikal', 'Resep', 'Peradangan kulit'),
('Fluocinolone', 'Steroid Topikal', 'Resep', 'Peradangan kulit'),
('Clotrimazole', 'Antijamur Topikal', 'Bebas Terbatas', 'Infeksi jamur kulit'),
('Miconazole', 'Antijamur Topikal', 'Bebas Terbatas', 'Infeksi jamur kulit'),
('Ketoconazole', 'Antijamur Topikal', 'Resep', 'Infeksi jamur kulit'),
('Terbinafine', 'Antijamur Topikal', 'Resep', 'Infeksi jamur kulit, kuku'),
('Nystatin', 'Antijamur Topikal', 'Resep', 'Kandidiasis kulit'),
('Econazole', 'Antijamur Topikal', 'Bebas Terbatas', 'Infeksi jamur kulit'),
('Griseofulvin', 'Antijamur Oral', 'Resep', 'Infeksi jamur kulit, kuku'),
('Mupirocin', 'Antibiotik Topikal', 'Resep', 'Infeksi kulit'),
('Fusidic Acid', 'Antibiotik Topikal', 'Resep', 'Infeksi kulit'),
('Neomycin', 'Antibiotik Topikal', 'Bebas Terbatas', 'Infeksi kulit'),
('Bacitracin', 'Antibiotik Topikal', 'Bebas Terbatas', 'Infeksi kulit'),
('Retapamulin', 'Antibiotik Topikal', 'Resep', 'Infeksi kulit'),
('Benzoyl Peroxide', 'Antiakne', 'Bebas Terbatas', 'Akne'),
('Salicylic Acid', 'Antiakne', 'Bebas', 'Akne, kutil'),
('Adapalene', 'Antiakne', 'Resep', 'Akne'),
('Tretinoin', 'Antiakne', 'Resep', 'Akne, kerutan'),
('Isotretinoin', 'Antiakne', 'Resep', 'Akne berat'),
('Clindamycin', 'Antiakne', 'Resep', 'Akne'),
('Erythromycin', 'Antiakne', 'Resep', 'Akne'),
('Azelaic Acid', 'Antiakne', 'Resep', 'Akne, rosacea'),
('Metronidazole', 'Antiakne', 'Resep', 'Rosacea'),
('Ivermectin', 'Antiakne', 'Resep', 'Rosacea'),
('Permethrin', 'Antiparasit Topikal', 'Resep', 'Skabies, pedikulosis'),
('Benzyl Benzoate', 'Antiparasit Topikal', 'Bebas Terbatas', 'Skabies'),
('Sulfur', 'Antiparasit Topikal', 'Bebas', 'Skabies, akne'),
('Calamine', 'Obat Kulit', 'Bebas', 'Gatal, iritasi kulit'),
('Zinc Oxide', 'Obat Kulit', 'Bebas', 'Ruam, pelindung kulit'),
('Petroleum Jelly', 'Obat Kulit', 'Bebas', 'Pelembap, luka bakar'),
('Urea', 'Obat Kulit', 'Bebas', 'Kulit kering, keratosis'),
('Lactic Acid', 'Obat Kulit', 'Bebas', 'Kulit kering'),
('Ammonium Lactate', 'Obat Kulit', 'Bebas', 'Kulit kering'),
('Coal Tar', 'Obat Kulit', 'Resep', 'Psoriasis'),
('Calcipotriol', 'Obat Kulit', 'Resep', 'Psoriasis'),
('Tazarotene', 'Obat Kulit', 'Resep', 'Psoriasis, akne'),
('Methoxsalen', 'Obat Kulit', 'Resep', 'Psoriasis, vitiligo'),
('Hydroquinone', 'Obat Kulit', 'Resep', 'Hiperpigmentasi'),
('Tretinoin', 'Obat Kulit', 'Resep', 'Hiperpigmentasi, akne'),
('Fluocinolone', 'Obat Kulit', 'Resep', 'Hiperpigmentasi'),
('Minoxidil', 'Obat Rambut', 'Resep', 'Rambut rontok'),
('Finasteride', 'Obat Rambut', 'Resep', 'Rambut rontok, BPH'),
('Dutasteride', 'Obat Rambut', 'Resep', 'Rambut rontok, BPH'),

-- ==================== OBAT UROLOGI ====================
('Tamsulosin', 'Alpha Blocker', 'Resep', 'BPH'),
('Alfuzosin', 'Alpha Blocker', 'Resep', 'BPH'),
('Doxazosin', 'Alpha Blocker', 'Resep', 'BPH, hipertensi'),
('Terazosin', 'Alpha Blocker', 'Resep', 'BPH, hipertensi'),
('Silodosin', 'Alpha Blocker', 'Resep', 'BPH'),
('Finasteride', '5-Alpha Reductase Inhibitor', 'Resep', 'BPH, rambut rontok'),
('Dutasteride', '5-Alpha Reductase Inhibitor', 'Resep', 'BPH, rambut rontok'),
('Oxybutynin', 'Antimuskarinik', 'Resep', 'Inkontinensia urin'),
('Tolterodine', 'Antimuskarinik', 'Resep', 'Inkontinensia urin'),
('Solifenacin', 'Antimuskarinik', 'Resep', 'Inkontinensia urin'),
('Darifenacin', 'Antimuskarinik', 'Resep', 'Inkontinensia urin'),
('Trospium', 'Antimuskarinik', 'Resep', 'Inkontinensia urin'),
('Mirabegron', 'Beta-3 Agonist', 'Resep', 'Inkontinensia urin'),
('Sildenafil', 'PDE5 Inhibitor', 'Resep', 'Disfungsi ereksi'),
('Tadalafil', 'PDE5 Inhibitor', 'Resep', 'Disfungsi ereksi, BPH'),
('Vardenafil', 'PDE5 Inhibitor', 'Resep', 'Disfungsi ereksi'),
('Avanafil', 'PDE5 Inhibitor', 'Resep', 'Disfungsi ereksi'),
('Alprostadil', 'Vasodilator', 'Resep', 'Disfungsi ereksi'),
('Testosterone', 'Hormon', 'Resep', 'Hipogonadisme'),
('Estrogen', 'Hormon', 'Resep', 'Menopause, kontrasepsi'),
('Progesterone', 'Hormon', 'Resep', 'Menopause, kontrasepsi'),
('Combined Oral Contraceptive', 'Kontrasepsi', 'Resep', 'Kontrasepsi'),
('Progestin Only Pill', 'Kontrasepsi', 'Resep', 'Kontrasepsi'),
('Levonorgestrel', 'Kontrasepsi', 'Resep', 'Kontrasepsi darurat'),
('Mifepristone', 'Kontrasepsi', 'Resep', 'Abortus, kontrasepsi darurat'),
('Misoprostol', 'Obat Kandungan', 'Resep', 'Abortus, ulkus'),
('Oxytocin', 'Hormon', 'Resep', 'Induksi persalinan'),
('Methylergonovine', 'Hormon', 'Resep', 'Perdarahan postpartum'),
('Dinoprostone', 'Hormon', 'Resep', 'Induksi persalinan'),
('Clomiphene', 'Fertilitas', 'Resep', 'Infertilitas'),
('Letrozole', 'Fertilitas', 'Resep', 'Infertilitas, kanker payudara'),
('Gonadotropin', 'Fertilitas', 'Resep', 'Infertilitas'),
('Human Chorionic Gonadotropin', 'Fertilitas', 'Resep', 'Infertilitas'),
('Menotropin', 'Fertilitas', 'Resep', 'Infertilitas'),
('Follitropin', 'Fertilitas', 'Resep', 'Infertilitas'),
('Ganirelix', 'Fertilitas', 'Resep', 'Infertilitas'),
('Cetrorelix', 'Fertilitas', 'Resep', 'Infertilitas'),

-- ==================== VITAMIN & SUPLEMEN ====================
('Vitamin A', 'Vitamin', 'Bebas', 'Defisiensi vitamin A, mata'),
('Vitamin B1 (Thiamine)', 'Vitamin', 'Bebas', 'Defisiensi B1, beri-beri'),
('Vitamin B2 (Riboflavin)', 'Vitamin', 'Bebas', 'Defisiensi B2'),
('Vitamin B3 (Niacin)', 'Vitamin', 'Bebas', 'Defisiensi B3, kolesterol'),
('Vitamin B5 (Pantothenic Acid)', 'Vitamin', 'Bebas', 'Defisiensi B5'),
('Vitamin B6 (Pyridoxine)', 'Vitamin', 'Bebas', 'Defisiensi B6, mual'),
('Vitamin B7 (Biotin)', 'Vitamin', 'Bebas', 'Defisiensi biotin'),
('Vitamin B9 (Folic Acid)', 'Vitamin', 'Bebas', 'Defisiensi folat, kehamilan'),
('Vitamin B12 (Cobalamin)', 'Vitamin', 'Bebas', 'Defisiensi B12, anemia'),
('Vitamin C (Ascorbic Acid)', 'Vitamin', 'Bebas', 'Defisiensi vitamin C, skorbut'),
('Vitamin D2 (Ergocalciferol)', 'Vitamin', 'Bebas', 'Defisiensi vitamin D'),
('Vitamin D3 (Cholecalciferol)', 'Vitamin', 'Bebas', 'Defisiensi vitamin D'),
('Vitamin E (Tocopherol)', 'Vitamin', 'Bebas', 'Defisiensi vitamin E'),
('Vitamin K', 'Vitamin', 'Bebas', 'Defisiensi vitamin K, perdarahan'),
('Multivitamin', 'Vitamin', 'Bebas', 'Suplemen vitamin'),
('Calcium', 'Mineral', 'Bebas', 'Defisiensi kalsium, osteoporosis'),
('Magnesium', 'Mineral', 'Bebas', 'Defisiensi magnesium'),
('Zinc', 'Mineral', 'Bebas', 'Defisiensi zinc, diare'),
('Iron (Ferrous Sulfate)', 'Mineral', 'Bebas', 'Anemia defisiensi besi'),
('Iron (Ferrous Fumarate)', 'Mineral', 'Bebas', 'Anemia defisiensi besi'),
('Iron (Ferrous Gluconate)', 'Mineral', 'Bebas', 'Anemia defisiensi besi'),
('Iodine', 'Mineral', 'Bebas', 'Defisiensi iodin'),
('Selenium', 'Mineral', 'Bebas', 'Defisiensi selenium'),
('Copper', 'Mineral', 'Bebas', 'Defisiensi tembaga'),
('Manganese', 'Mineral', 'Bebas', 'Defisiensi mangan'),
('Chromium', 'Mineral', 'Bebas', 'Defisiensi kromium'),
('Omega-3', 'Suplemen', 'Bebas', 'Kesehatan jantung, otak'),
('Omega-6', 'Suplemen', 'Bebas', 'Kesehatan kulit'),
('Cod Liver Oil', 'Suplemen', 'Bebas', 'Vitamin A & D'),
('Fish Oil', 'Suplemen', 'Bebas', 'Omega-3'),
('Glucosamine', 'Suplemen', 'Bebas', 'Kesehatan sendi'),
('Chondroitin', 'Suplemen', 'Bebas', 'Kesehatan sendi'),
('Collagen', 'Suplemen', 'Bebas', 'Kesehatan kulit, sendi'),
('Coenzyme Q10', 'Suplemen', 'Bebas', 'Kesehatan jantung'),
('Probiotik', 'Suplemen', 'Bebas', 'Kesehatan pencernaan'),
('Prebiotik', 'Suplemen', 'Bebas', 'Kesehatan pencernaan'),
('Spirulina', 'Suplemen', 'Bebas', 'Suplemen gizi'),
('Moringa', 'Suplemen', 'Bebas', 'Suplemen gizi'),
('Ginseng', 'Herbal', 'Bebas', 'Stamina, energi'),
('Echinacea', 'Herbal', 'Bebas', 'Imunitas'),
('Ginkgo Biloba', 'Herbal', 'Bebas', 'Sirkulasi, memori'),
('St. John''s Wort', 'Herbal', 'Bebas', 'Depresi ringan'),
('Valerian', 'Herbal', 'Bebas', 'Insomnia, cemas'),
('Chamomile', 'Herbal', 'Bebas', 'Cemas, insomnia'),
('Peppermint', 'Herbal', 'Bebas', 'Pencernaan, kembung'),
('Ginger', 'Herbal', 'Bebas', 'Mual, muntah'),
('Turmeric', 'Herbal', 'Bebas', 'Peradangan, antioksidan'),
('Garlic', 'Herbal', 'Bebas', 'Kolesterol, tekanan darah'),
('Aloe Vera', 'Herbal', 'Bebas', 'Kulit, pencernaan'),
('Sambiloto', 'Herbal', 'Bebas', 'Imunitas, diabetes'),
('Temulawak', 'Herbal', 'Bebas', 'Hati, pencernaan'),
('Jahe', 'Herbal', 'Bebas', 'Mual, masuk angin'),
('Kunyit', 'Herbal', 'Bebas', 'Peradangan, antioksidan'),
('Kencur', 'Herbal', 'Bebas', 'Batuk, masuk angin'),
('Lidah Buaya', 'Herbal', 'Bebas', 'Kulit, pencernaan'),
('Daun Sirih', 'Herbal', 'Bebas', 'Antiseptik, kewanitaan'),
('Kayu Manis', 'Herbal', 'Bebas', 'Diabetes, kolesterol'),
('Cengkeh', 'Herbal', 'Bebas', 'Sakit gigi, antiseptik'),
('Pegagan', 'Herbal', 'Bebas', 'Memori, sirkulasi'),
('Meniran', 'Herbal', 'Bebas', 'Imunitas'),
('Kumis Kucing', 'Herbal', 'Bebas', 'Saluran kemih, ginjal'),
('Sambiloto', 'Herbal', 'Bebas', 'Imunitas, diabetes'),
('Mahkota Dewa', 'Herbal', 'Bebas', 'Imunitas, antioksidan'),
('Mengkudu', 'Herbal', 'Bebas', 'Hipertensi, pencernaan'),
('Sirsak', 'Herbal', 'Bebas', 'Imunitas, antioksidan'),

-- ==================== OBAT DARAH ====================
('Ferrous Sulfate', 'Antianemia', 'Bebas', 'Anemia defisiensi besi'),
('Ferrous Fumarate', 'Antianemia', 'Bebas', 'Anemia defisiensi besi'),
('Ferrous Gluconate', 'Antianemia', 'Bebas', 'Anemia defisiensi besi'),
('Iron Sucrose', 'Antianemia', 'Resep', 'Anemia defisiensi besi'),
('Iron Dextran', 'Antianemia', 'Resep', 'Anemia defisiensi besi'),
('Erythropoietin', 'Antianemia', 'Resep', 'Anemia gagal ginjal'),
('Darbepoetin', 'Antianemia', 'Resep', 'Anemia gagal ginjal'),
('Folic Acid', 'Antianemia', 'Bebas', 'Anemia megaloblastik'),
('Vitamin B12', 'Antianemia', 'Bebas', 'Anemia pernisiosa'),
('Filgrastim', 'Koloni Stimulan', 'Resep', 'Neutropenia'),
('Pegfilgrastim', 'Koloni Stimulan', 'Resep', 'Neutropenia'),
('Sargramostim', 'Koloni Stimulan', 'Resep', 'Neutropenia'),
('Oprelvekin', 'Koloni Stimulan', 'Resep', 'Trombositopenia'),
('Eltrombopag', 'Koloni Stimulan', 'Resep', 'Trombositopenia'),
('Romiplostim', 'Koloni Stimulan', 'Resep', 'Trombositopenia'),
('Heparin', 'Antikoagulan', 'Resep', 'Antikoagulan'),
('Warfarin', 'Antikoagulan', 'Resep', 'Antikoagulan'),
('Enoxaparin', 'Antikoagulan', 'Resep', 'Antikoagulan'),
('Rivaroxaban', 'Antikoagulan', 'Resep', 'Antikoagulan'),
('Apixaban', 'Antikoagulan', 'Resep', 'Antikoagulan'),
('Dabigatran', 'Antikoagulan', 'Resep', 'Antikoagulan'),
('Protamine', 'Antidot', 'Resep', 'Antidot heparin'),
('Vitamin K', 'Antidot', 'Resep', 'Antidot warfarin'),
('Tranexamic Acid', 'Antifibrinolitik', 'Resep', 'Perdarahan'),
('Aminocaproic Acid', 'Antifibrinolitik', 'Resep', 'Perdarahan'),
('Desmopressin', 'Hemostatik', 'Resep', 'Hemofilia, diabetes insipidus'),
('Factor VIII', 'Hemostatik', 'Resep', 'Hemofilia A'),
('Factor IX', 'Hemostatik', 'Resep', 'Hemofilia B'),
('Factor VIIa', 'Hemostatik', 'Resep', 'Hemofilia dengan inhibitor'),
('Von Willebrand Factor', 'Hemostatik', 'Resep', 'Penyakit Von Willebrand'),
('Hydroxyurea', 'Antisickling', 'Resep', 'Anemia sel sabit'),
('L-Glutamine', 'Antisickling', 'Resep', 'Anemia sel sabit'),
('Deferoxamine', 'Kelasi Besi', 'Resep', 'Kelebihan besi'),
('Deferasirox', 'Kelasi Besi', 'Resep', 'Kelebihan besi'),
('Deferiprone', 'Kelasi Besi', 'Resep', 'Kelebihan besi'),
('Penicillamine', 'Kelasi Tembaga', 'Resep', 'Penyakit Wilson'),
('Trientine', 'Kelasi Tembaga', 'Resep', 'Penyakit Wilson'),

-- ==================== OBAT KANKER ====================
('Methotrexate', 'Kemoterapi', 'Resep', 'Kanker, autoimun'),
('Cisplatin', 'Kemoterapi', 'Resep', 'Kanker'),
('Carboplatin', 'Kemoterapi', 'Resep', 'Kanker'),
('Oxaliplatin', 'Kemoterapi', 'Resep', 'Kanker kolorektal'),
('Doxorubicin', 'Kemoterapi', 'Resep', 'Kanker'),
('Daunorubicin', 'Kemoterapi', 'Resep', 'Leukemia'),
('Epirubicin', 'Kemoterapi', 'Resep', 'Kanker payudara'),
('Idarubicin', 'Kemoterapi', 'Resep', 'Leukemia'),
('Mitoxantrone', 'Kemoterapi', 'Resep', 'Kanker, MS'),
('Bleomycin', 'Kemoterapi', 'Resep', 'Kanker'),
('Vinblastine', 'Kemoterapi', 'Resep', 'Kanker'),
('Vincristine', 'Kemoterapi', 'Resep', 'Leukemia, limfoma'),
('Vinorelbine', 'Kemoterapi', 'Resep', 'Kanker paru, payudara'),
('Paclitaxel', 'Kemoterapi', 'Resep', 'Kanker payudara, ovarium'),
('Docetaxel', 'Kemoterapi', 'Resep', 'Kanker payudara, prostat'),
('Cabazitaxel', 'Kemoterapi', 'Resep', 'Kanker prostat'),
('Etoposide', 'Kemoterapi', 'Resep', 'Kanker paru, testis'),
('Teniposide', 'Kemoterapi', 'Resep', 'Leukemia'),
('Irinotecan', 'Kemoterapi', 'Resep', 'Kanker kolorektal'),
('Topotecan', 'Kemoterapi', 'Resep', 'Kanker ovarium, paru'),
('Cyclophosphamide', 'Kemoterapi', 'Resep', 'Kanker, autoimun'),
('Ifosfamide', 'Kemoterapi', 'Resep', 'Kanker'),
('Chlorambucil', 'Kemoterapi', 'Resep', 'Leukemia, limfoma'),
('Melphalan', 'Kemoterapi', 'Resep', 'Mieloma multipel'),
('Busulfan', 'Kemoterapi', 'Resep', 'Leukemia'),
('Temozolomide', 'Kemoterapi', 'Resep', 'Glioblastoma'),
('Dacarbazine', 'Kemoterapi', 'Resep', 'Melanoma, limfoma'),
('Procarbazine', 'Kemoterapi', 'Resep', 'Limfoma Hodgkin'),
('Fluorouracil', 'Kemoterapi', 'Resep', 'Kanker kolorektal, payudara'),
('Capecitabine', 'Kemoterapi', 'Resep', 'Kanker kolorektal, payudara'),
('Gemcitabine', 'Kemoterapi', 'Resep', 'Kanker pankreas, paru'),
('Cytarabine', 'Kemoterapi', 'Resep', 'Leukemia'),
('Fludarabine', 'Kemoterapi', 'Resep', 'Leukemia limfositik kronis'),
('Cladribine', 'Kemoterapi', 'Resep', 'Leukemia hairy cell'),
('Pentostatin', 'Kemoterapi', 'Resep', 'Leukemia hairy cell'),
('Mercaptopurine', 'Kemoterapi', 'Resep', 'Leukemia'),
('Thioguanine', 'Kemoterapi', 'Resep', 'Leukemia'),
('Hydroxyurea', 'Kemoterapi', 'Resep', 'Leukemia, anemia sel sabit'),
('L-Asparaginase', 'Kemoterapi', 'Resep', 'Leukemia limfoblastik akut'),
('Pegaspargase', 'Kemoterapi', 'Resep', 'Leukemia limfoblastik akut'),
('Rituximab', 'Kemoterapi Biologik', 'Resep', 'Limfoma, leukemia'),
('Trastuzumab', 'Kemoterapi Biologik', 'Resep', 'Kanker payudara HER2+'),
('Bevacizumab', 'Kemoterapi Biologik', 'Resep', 'Kanker kolorektal, paru'),
('Cetuximab', 'Kemoterapi Biologik', 'Resep', 'Kanker kolorektal, kepala leher'),
('Panitumumab', 'Kemoterapi Biologik', 'Resep', 'Kanker kolorektal'),
('Pertuzumab', 'Kemoterapi Biologik', 'Resep', 'Kanker payudara HER2+'),
('Nivolumab', 'Imunoterapi', 'Resep', 'Melanoma, kanker paru'),
('Pembrolizumab', 'Imunoterapi', 'Resep', 'Melanoma, kanker paru'),
('Atezolizumab', 'Imunoterapi', 'Resep', 'Kanker paru, kandung kemih'),
('Durvalumab', 'Imunoterapi', 'Resep', 'Kanker paru'),
('Avelumab', 'Imunoterapi', 'Resep', 'Kanker Merkel'),
('Ipilimumab', 'Imunoterapi', 'Resep', 'Melanoma'),
('Imatinib', 'Targeted Therapy', 'Resep', 'Leukemia mieloid kronis, GIST'),
('Dasatinib', 'Targeted Therapy', 'Resep', 'Leukemia mieloid kronis'),
('Nilotinib', 'Targeted Therapy', 'Resep', 'Leukemia mieloid kronis'),
('Bosutinib', 'Targeted Therapy', 'Resep', 'Leukemia mieloid kronis'),
('Ponatinib', 'Targeted Therapy', 'Resep', 'Leukemia mieloid kronis'),
('Erlotinib', 'Targeted Therapy', 'Resep', 'Kanker paru'),
('Gefitinib', 'Targeted Therapy', 'Resep', 'Kanker paru'),
('Afatinib', 'Targeted Therapy', 'Resep', 'Kanker paru'),
('Osimertinib', 'Targeted Therapy', 'Resep', 'Kanker paru'),
('Crizotinib', 'Targeted Therapy', 'Resep', 'Kanker paru'),
('Ceritinib', 'Targeted Therapy', 'Resep', 'Kanker paru'),
('Alectinib', 'Targeted Therapy', 'Resep', 'Kanker paru'),
('Lorlatinib', 'Targeted Therapy', 'Resep', 'Kanker paru'),
('Lapatinib', 'Targeted Therapy', 'Resep', 'Kanker payudara HER2+'),
('Sorafenib', 'Targeted Therapy', 'Resep', 'Kanker hati, ginjal'),
('Sunitinib', 'Targeted Therapy', 'Resep', 'Kanker ginjal, GIST'),
('Pazopanib', 'Targeted Therapy', 'Resep', 'Kanker ginjal, sarkoma'),
('Cabozantinib', 'Targeted Therapy', 'Resep', 'Kanker ginjal, tiroid'),
('Lenvatinib', 'Targeted Therapy', 'Resep', 'Kanker tiroid, hati'),
('Regorafenib', 'Targeted Therapy', 'Resep', 'Kanker kolorektal, GIST'),
('Vemurafenib', 'Targeted Therapy', 'Resep', 'Melanoma BRAF+'),
('Dabrafenib', 'Targeted Therapy', 'Resep', 'Melanoma BRAF+'),
('Trametinib', 'Targeted Therapy', 'Resep', 'Melanoma BRAF+'),
('Cobimetinib', 'Targeted Therapy', 'Resep', 'Melanoma BRAF+'),
('Olaparib', 'Targeted Therapy', 'Resep', 'Kanker ovarium, payudara'),
('Rucaparib', 'Targeted Therapy', 'Resep', 'Kanker ovarium, prostat'),
('Niraparib', 'Targeted Therapy', 'Resep', 'Kanker ovarium'),
('Talazoparib', 'Targeted Therapy', 'Resep', 'Kanker payudara BRCA+'),
('Palbociclib', 'Targeted Therapy', 'Resep', 'Kanker payudara HR+'),
('Ribociclib', 'Targeted Therapy', 'Resep', 'Kanker payudara HR+'),
('Abemaciclib', 'Targeted Therapy', 'Resep', 'Kanker payudara HR+'),
('Everolimus', 'Targeted Therapy', 'Resep', 'Kanker payudara, ginjal'),
('Temsirolimus', 'Targeted Therapy', 'Resep', 'Kanker ginjal'),
('Bortezomib', 'Targeted Therapy', 'Resep', 'Mieloma multipel'),
('Carfilzomib', 'Targeted Therapy', 'Resep', 'Mieloma multipel'),
('Ixazomib', 'Targeted Therapy', 'Resep', 'Mieloma multipel'),
('Lenalidomide', 'Targeted Therapy', 'Resep', 'Mieloma multipel'),
('Thalidomide', 'Targeted Therapy', 'Resep', 'Mieloma multipel'),
('Pomalidomide', 'Targeted Therapy', 'Resep', 'Mieloma multipel'),
('Venetoclax', 'Targeted Therapy', 'Resep', 'Leukemia limfositik kronis'),
('Ibrutinib', 'Targeted Therapy', 'Resep', 'Leukemia, limfoma'),
('Acalabrutinib', 'Targeted Therapy', 'Resep', 'Leukemia, limfoma'),
('Idelalisib', 'Targeted Therapy', 'Resep', 'Leukemia, limfoma'),
('Duvelisib', 'Targeted Therapy', 'Resep', 'Leukemia, limfoma'),

-- ==================== OBAT LAIN-LAIN ====================
('Epinephrine', 'Emergency', 'Resep', 'Anafilaksis, henti jantung'),
('Atropine', 'Emergency', 'Resep', 'Bradikardia, keracunan organofosfat'),
('Amiodarone', 'Antiarrhythmic', 'Resep', 'Aritmia'),
('Adenosine', 'Antiarrhythmic', 'Resep', 'Aritmia supraventrikular'),
('Lidocaine', 'Antiarrhythmic', 'Resep', 'Aritmia, anestesi lokal'),
('Procainamide', 'Antiarrhythmic', 'Resep', 'Aritmia'),
('Flecainide', 'Antiarrhythmic', 'Resep', 'Aritmia'),
('Propafenone', 'Antiarrhythmic', 'Resep', 'Aritmia'),
('Sotalol', 'Antiarrhythmic', 'Resep', 'Aritmia'),
('Ibutilide', 'Antiarrhythmic', 'Resep', 'Aritmia'),
('Dronedarone', 'Antiarrhythmic', 'Resep', 'Fibrilasi atrium'),
('Digoxin', 'Antiarrhythmic', 'Resep', 'Gagal jantung, aritmia'),
('Magnesium Sulfate', 'Emergency', 'Resep', 'Aritmia, eklampsia, asma'),
('Calcium Gluconate', 'Emergency', 'Resep', 'Hipokalsemia, hiperkalemia'),
('Sodium Bicarbonate', 'Emergency', 'Resep', 'Asidosis metabolik'),
('Naloxone', 'Antidot', 'Resep', 'Overdosis opioid'),
('Flumazenil', 'Antidot', 'Resep', 'Overdosis benzodiazepin'),
('N-Acetylcysteine', 'Antidot', 'Resep', 'Keracunan paracetamol'),
('Deferoxamine', 'Antidot', 'Resep', 'Keracunan besi'),
('Dimercaprol', 'Antidot', 'Resep', 'Keracunan logam berat'),
('Penicillamine', 'Antidot', 'Resep', 'Keracunan logam berat'),
('Pralidoxime', 'Antidot', 'Resep', 'Keracunan organofosfat'),
('Methylene Blue', 'Antidot', 'Resep', 'Methemoglobinemia'),
('Ethanol', 'Antidot', 'Resep', 'Keracunan metanol'),
('Fomepizole', 'Antidot', 'Resep', 'Keracunan metanol, etilen glikol'),
('Glucagon', 'Antidot', 'Resep', 'Hipoglikemia, overdosis beta blocker'),
('Octreotide', 'Hormon', 'Resep', 'Akromegali, perdarahan varises'),
('Desmopressin', 'Hormon', 'Resep', 'Diabetes insipidus, hemofilia'),
('Vasopressin', 'Hormon', 'Resep', 'Syok, diabetes insipidus'),
('Oxytocin', 'Hormon', 'Resep', 'Induksi persalinan'),
('Methylergonovine', 'Hormon', 'Resep', 'Perdarahan postpartum'),
('Dinoprostone', 'Hormon', 'Resep', 'Induksi persalinan'),
('Carbetocin', 'Hormon', 'Resep', 'Perdarahan postpartum'),
('Terlipressin', 'Hormon', 'Resep', 'Perdarahan varises esofagus'),
('Somatostatin', 'Hormon', 'Resep', 'Perdarahan varises'),
('Lanreotide', 'Hormon', 'Resep', 'Akromegali'),
('Pasireotide', 'Hormon', 'Resep', 'Cushing, akromegali'),
('Pegvisomant', 'Hormon', 'Resep', 'Akromegali'),
('Bromocriptine', 'Hormon', 'Resep', 'Prolaktinoma, Parkinson'),
('Cabergoline', 'Hormon', 'Resep', 'Prolaktinoma, Parkinson'),
('Quinagolide', 'Hormon', 'Resep', 'Prolaktinoma'),
('Mifepristone', 'Hormon', 'Resep', 'Cushing, abortus'),
('Ketoconazole', 'Hormon', 'Resep', 'Cushing'),
('Metyrapone', 'Hormon', 'Resep', 'Cushing'),
('Mitotane', 'Hormon', 'Resep', 'Kanker adrenal, Cushing'),
('Aminoglutethimide', 'Hormon', 'Resep', 'Cushing, kanker payudara'),
('Fludrocortisone', 'Hormon', 'Resep', 'Penyakit Addison'),
('Hydrocortisone', 'Hormon', 'Resep', 'Penyakit Addison, alergi'),
('Prednisone', 'Hormon', 'Resep', 'Autoimun, alergi'),
('Dexamethasone', 'Hormon', 'Resep', 'Autoimun, alergi, COVID-19'),
('Methylprednisolone', 'Hormon', 'Resep', 'Autoimun, alergi'),
('Betamethasone', 'Hormon', 'Resep', 'Autoimun, pematangan paru janin'),
('Triamcinolone', 'Hormon', 'Resep', 'Autoimun, alergi'),
('Budesonide', 'Hormon', 'Resep', 'Asma, IBD'),
('Fluticasone', 'Hormon', 'Resep', 'Asma, rhinitis'),
('Beclomethasone', 'Hormon', 'Resep', 'Asma, rhinitis'),
('Mometasone', 'Hormon', 'Resep', 'Asma, rhinitis'),
('Ciclesonide', 'Hormon', 'Resep', 'Asma, rhinitis'),
('Flunisolide', 'Hormon', 'Resep', 'Rhinitis');