-- ============================================================
-- DATABASE: TENAGA KESEHATAN
-- File: tenaga_kesehatan.sql
-- Konversi lengkap dari php.txt
-- ============================================================

DROP TABLE IF EXISTS tenaga_kesehatan;

CREATE TABLE tenaga_kesehatan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    kategori VARCHAR(100),
    pendidikan VARCHAR(255),
    tugas TEXT,
    INDEX idx_nama (nama),
    INDEX idx_kategori (kategori)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==================== TENAGA MEDIS ====================
INSERT INTO tenaga_kesehatan (nama, kategori, pendidikan, tugas) VALUES
('Dokter Umum', 'Tenaga Medis', 'S1 Kedokteran + Profesi Dokter', 'Melakukan pemeriksaan, diagnosis, pengobatan pasien umum, merujuk ke spesialis, menjaga rekam medis'),
('Dokter Spesialis Penyakit Dalam', 'Tenaga Medis', 'Spesialis Penyakit Dalam', 'Menangani penyakit organ dalam, diabetes, hipertensi, infeksi, autoimun'),
('Dokter Spesialis Anak', 'Tenaga Medis', 'Spesialis Anak', 'Menangani kesehatan bayi, anak, imunisasi, tumbuh kembang'),
('Dokter Spesialis Bedah', 'Tenaga Medis', 'Spesialis Bedah', 'Melakukan operasi umum, bedah digestif, bedah onkologi'),
('Dokter Spesialis Bedah Orthopedi', 'Tenaga Medis', 'Spesialis Orthopedi', 'Menangani cedera tulang, sendi, fraktur, sports injury'),
('Dokter Spesialis Bedah Saraf', 'Tenaga Medis', 'Spesialis Bedah Saraf', 'Operasi otak, sumsum tulang belakang, saraf'),
('Dokter Spesialis Bedah Plastik', 'Tenaga Medis', 'Spesialis Bedah Plastik', 'Rekonstruksi, estetika, luka bakar, cangkok kulit'),
('Dokter Spesialis Bedah Toraks Kardiovaskular', 'Tenaga Medis', 'Spesialis Bedah Toraks Kardiovaskular', 'Operasi jantung, paru, pembuluh darah'),
('Dokter Spesialis Bedah Digestif', 'Tenaga Medis', 'Spesialis Bedah Digestif', 'Operasi saluran cerna, hati, empedu'),
('Dokter Spesialis Bedah Urologi', 'Tenaga Medis', 'Spesialis Urologi', 'Menangani saluran kemih, ginjal, prostat'),
('Dokter Spesialis Obstetri & Ginekologi', 'Tenaga Medis', 'Spesialis Obstetri & Ginekologi', 'Menangani kehamilan, persalinan, kandungan, operasi caesar'),
('Dokter Spesialis Mata', 'Tenaga Medis', 'Spesialis Mata', 'Menangani gangguan mata, operasi katarak, glaukoma, retina'),
('Dokter Spesialis THT-KL', 'Tenaga Medis', 'Spesialis THT-KL', 'Menangani telinga, hidung, tenggorokan, kepala leher'),
('Dokter Spesialis Kulit & Kelamin', 'Tenaga Medis', 'Spesialis Dermatologi & Venereologi', 'Menangani penyakit kulit, kelamin, estetika'),
('Dokter Spesialis Saraf', 'Tenaga Medis', 'Spesialis Neurologi', 'Menangani stroke, epilepsi, Parkinson, nyeri saraf'),
('Dokter Spesialis Jiwa', 'Tenaga Medis', 'Spesialis Psikiatri', 'Menangani gangguan mental, depresi, skizofrenia, adiksi'),
('Dokter Spesialis Jantung', 'Tenaga Medis', 'Spesialis Jantung & Pembuluh Darah', 'Menangani penyakit jantung, hipertensi, aritmia, kateterisasi'),
('Dokter Spesialis Paru', 'Tenaga Medis', 'Spesialis Pulmonologi', 'Menangani asma, TBC, PPOK, kanker paru'),
('Dokter Spesialis Radiologi', 'Tenaga Medis', 'Spesialis Radiologi', 'Membaca hasil rontgen, CT scan, MRI, USG'),
('Dokter Spesialis Patologi Klinik', 'Tenaga Medis', 'Spesialis Patologi Klinik', 'Menganalisis hasil laboratorium, diagnosis penyakit'),
('Dokter Spesialis Patologi Anatomi', 'Tenaga Medis', 'Spesialis Patologi Anatomi', 'Menganalisis jaringan biopsi, diagnosis kanker'),
('Dokter Spesialis Anestesi', 'Tenaga Medis', 'Spesialis Anestesiologi', 'Melakukan anestesi operasi, manajemen nyeri, ICU'),
('Dokter Spesialis Rehabilitasi Medik', 'Tenaga Medis', 'Spesialis Kedokteran Fisik & Rehabilitasi', 'Rehabilitasi pasien stroke, cedera, disabilitas'),
('Dokter Spesialis Forensik', 'Tenaga Medis', 'Spesialis Forensik & Medikolegal', 'Autopsi, visum et repertum, forensik'),
('Dokter Spesialis Gizi Klinik', 'Tenaga Medis', 'Spesialis Gizi Klinik', 'Menangani gizi pasien, diet khusus, obesitas'),
('Dokter Spesialis Mikrobiologi Klinik', 'Tenaga Medis', 'Spesialis Mikrobiologi Klinik', 'Menganalisis infeksi, resistensi antibiotik'),
('Dokter Spesialis Kedokteran Olahraga', 'Tenaga Medis', 'Spesialis Kedokteran Olahraga', 'Menangani cedera olahraga, performa atlet'),
('Dokter Spesialis Kedokteran Nuklir', 'Tenaga Medis', 'Spesialis Kedokteran Nuklir', 'Diagnosis dan terapi dengan radioisotop'),
('Dokter Spesialis Onkologi Radiasi', 'Tenaga Medis', 'Spesialis Onkologi Radiasi', 'Radioterapi kanker'),
('Dokter Spesialis Onkologi Medik', 'Tenaga Medis', 'Spesialis Onkologi Medik', 'Kemoterapi, imunoterapi kanker'),
('Dokter Gigi', 'Tenaga Medis', 'S1 Kedokteran Gigi + Profesi Dokter Gigi', 'Memeriksa gigi, menambal, mencabut, membersihkan karang gigi'),
('Dokter Gigi Spesialis Orthodonti', 'Tenaga Medis', 'Spesialis Ortodonti', 'Merapikan gigi dengan behel, ortodonti'),
('Dokter Gigi Spesialis Bedah Mulut', 'Tenaga Medis', 'Spesialis Bedah Mulut & Maksilofasial', 'Operasi mulut, rahang, wajah'),
('Dokter Gigi Spesialis Konservasi Gigi', 'Tenaga Medis', 'Spesialis Konservasi Gigi', 'Perawatan saluran akar, restorasi gigi'),
('Dokter Gigi Spesialis Periodonsi', 'Tenaga Medis', 'Spesialis Periodonsi', 'Menangani penyakit gusi, jaringan pendukung gigi'),
('Dokter Gigi Spesialis Prosthodonsi', 'Tenaga Medis', 'Spesialis Prosthodonsi', 'Membuat gigi palsu, mahkota, jembatan'),
('Dokter Gigi Spesialis Pedodonti', 'Tenaga Medis', 'Spesialis Kedokteran Gigi Anak', 'Menangani gigi anak'),
('Dokter Gigi Spesialis Radiologi Kedokteran Gigi', 'Tenaga Medis', 'Spesialis Radiologi Kedokteran Gigi', 'Rontgen gigi, panoramik, CBCT'),

-- ==================== TENAGA KEPERAWATAN ====================
('Perawat', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan + Profesi Ners', 'Merawat pasien, memberikan obat, monitoring tanda vital, asuhan keperawatan'),
('Perawat ICU', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan + Pelatihan ICU', 'Merawat pasien kritis, ventilator, monitoring intensif'),
('Perawat Bedah', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan + Pelatihan Bedah', 'Membantu operasi, instrumen bedah, perawatan luka'),
('Perawat Anak', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan + Pelatihan Anak', 'Merawat bayi dan anak, imunisasi, tumbuh kembang'),
('Perawat Maternitas', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan + Pelatihan Maternitas', 'Merawat ibu hamil, bersalin, nifas, bayi baru lahir'),
('Perawat Jiwa', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan + Pelatihan Jiwa', 'Merawat pasien gangguan jiwa, terapi aktivitas kelompok'),
('Perawat Komunitas', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan + Pelatihan Komunitas', 'Perawatan kesehatan masyarakat, puskesmas, home care'),
('Perawat Gerontik', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan + Pelatihan Gerontik', 'Merawat lansia, panti jompo, home care lansia'),
('Perawat Medikal Bedah', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan + Pelatihan Medikal Bedah', 'Merawat pasien dewasa dengan penyakit medis dan bedah'),
('Perawat Gawat Darurat', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan + Pelatihan Emergency', 'Menangani pasien gawat darurat, triase, resusitasi'),
('Perawat Hemodialisis', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan + Pelatihan Hemodialisis', 'Menangani pasien cuci darah, mesin dialisis'),
('Perawat Kamar Operasi', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan + Pelatihan OK', 'Menyiapkan instrumen operasi, membantu dokter bedah'),
('Perawat Recovery Room', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan + Pelatihan RR', 'Merawat pasien pasca operasi'),
('Perawat Poliklinik', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan', 'Melayani pasien rawat jalan, asisten dokter'),
('Perawat Home Care', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan', 'Merawat pasien di rumah, perawatan luka, kateter'),
('Perawat Sekolah', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan', 'UKS, kesehatan sekolah, pertolongan pertama'),
('Perawat Perusahaan', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan', 'Klinik perusahaan, kesehatan kerja, P3K'),
('Bidan', 'Tenaga Keperawatan', 'D3/D4/S1 Kebidanan + Profesi Bidan', 'Menangani kehamilan, persalinan normal, nifas, bayi baru lahir, KB'),
('Bidan Delima', 'Tenaga Keperawatan', 'D3 Kebidanan + Sertifikasi', 'Praktik mandiri bidan, pelayanan KB, ANC, PNC'),
('Bidan Desa', 'Tenaga Keperawatan', 'D3 Kebidanan', 'Melayani kesehatan ibu dan anak di desa, posyandu'),
('Bidan Puskesmas', 'Tenaga Keperawatan', 'D3/D4 Kebidanan', 'KIA di puskesmas, imunisasi, KB, persalinan'),
('Bidan Rumah Sakit', 'Tenaga Keperawatan', 'D3/D4 Kebidanan', 'Persalinan di RS, kamar bersalin, perawatan maternitas'),
('Bidan Klinik', 'Tenaga Keperawatan', 'D3 Kebidanan', 'Pelayanan KB, ANC, PNC, imunisasi'),
('Bidan Komunitas', 'Tenaga Keperawatan', 'D3/D4 Kebidanan', 'Pelayanan kesehatan ibu dan anak di komunitas'),
('Perawat Anestesi', 'Tenaga Keperawatan', 'D4 Keperawatan Anestesi', 'Membantu anestesi, monitoring pasien operasi'),
('Perawat Penanggung Jawab Asuhan', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan', 'Mengelola asuhan keperawatan pasien'),
('Kepala Ruangan', 'Tenaga Keperawatan', 'D3/D4/S1 Keperawatan + Manajemen', 'Mengelola ruangan, jadwal perawat, mutu asuhan'),
('Perawat Pendidikan', 'Tenaga Keperawatan', 'S1/S2 Keperawatan', 'Mengajar, melatih perawat, pendidikan keperawatan'),
('Perawat Peneliti', 'Tenaga Keperawatan', 'S2/S3 Keperawatan', 'Penelitian keperawatan, publikasi ilmiah'),
('Perawat Konsultan', 'Tenaga Keperawatan', 'S2/S3 Keperawatan', 'Konsultasi keperawatan, manajemen kasus'),

-- ==================== TENAGA KEFARMASIAN ====================
('Apoteker', 'Tenaga Kefarmasian', 'S1 Farmasi + Profesi Apoteker', 'Menyiapkan obat, pelayanan resep, konseling obat, manajemen apotek'),
('Apoteker Penanggung Jawab', 'Tenaga Kefarmasian', 'S1 Farmasi + Profesi Apoteker', 'Penanggung jawab apotek, legalitas, mutu obat'),
('Apoteker Industri', 'Tenaga Kefarmasian', 'S1 Farmasi + Profesi Apoteker', 'Produksi obat, QC, QA, registrasi obat'),
('Apoteker Rumah Sakit', 'Tenaga Kefarmasian', 'S1 Farmasi + Profesi Apoteker', 'Pelayanan farmasi RS, PFT, steril, obat kanker'),
('Apoteker Puskesmas', 'Tenaga Kefarmasian', 'S1 Farmasi + Profesi Apoteker', 'Pengelolaan obat puskesmas, pelayanan resep'),
('Apoteker Klinik', 'Tenaga Kefarmasian', 'S1 Farmasi + Profesi Apoteker', 'Pelayanan farmasi klinik, konseling pasien'),
('Tenaga Teknis Kefarmasian', 'Tenaga Kefarmasian', 'D3 Farmasi', 'Menyiapkan obat, meracik, melayani resep'),
('Asisten Apoteker', 'Tenaga Kefarmasian', 'D3 Farmasi', 'Membantu apoteker, menyiapkan obat, melayani resep'),
('Farmasis', 'Tenaga Kefarmasian', 'S1 Farmasi', 'Penelitian, pengembangan obat, QC'),
('Apoteker Komunitas', 'Tenaga Kefarmasian', 'S1 Farmasi + Profesi Apoteker', 'Apotek komunitas, pelayanan swamedikasi'),
('Apoteker Regulatory', 'Tenaga Kefarmasian', 'S1 Farmasi + Profesi Apoteker', 'Registrasi obat, izin edar, BPOM'),
('Apoteker Quality Control', 'Tenaga Kefarmasian', 'S1 Farmasi + Profesi Apoteker', 'Kontrol kualitas obat, uji laboratorium'),
('Apoteker Quality Assurance', 'Tenaga Kefarmasian', 'S1 Farmasi + Profesi Apoteker', 'Jaminan mutu obat, audit, dokumentasi'),
('Apoteker Produksi', 'Tenaga Kefarmasian', 'S1 Farmasi + Profesi Apoteker', 'Produksi obat, formulasi, scale-up'),
('Apoteker Riset', 'Tenaga Kefarmasian', 'S1 Farmasi + Profesi Apoteker', 'Riset obat baru, formulasi, uji klinis'),
('Apoteker Kosmetik', 'Tenaga Kefarmasian', 'S1 Farmasi + Profesi Apoteker', 'Formulasi kosmetik, uji stabilitas, registrasi'),
('Apoteker Makanan', 'Tenaga Kefarmasian', 'S1 Farmasi + Profesi Apoteker', 'Pengawasan makanan, BPOM, keamanan pangan'),

-- ==================== TENAGA KESEHATAN MASYARAKAT ====================
('Epidemiolog', 'Kesehatan Masyarakat', 'S1/S2 Epidemiologi', 'Investigasi wabah, surveilans penyakit, analisis data kesehatan'),
('Ahli Kesehatan Masyarakat', 'Kesehatan Masyarakat', 'S1/S2 Kesehatan Masyarakat', 'Program kesehatan, promosi kesehatan, pemberdayaan masyarakat'),
('Penyuluh Kesehatan', 'Kesehatan Masyarakat', 'D3/S1 Kesehatan Masyarakat', 'Penyuluhan kesehatan, edukasi masyarakat, kampanye kesehatan'),
('Administrator Kesehatan', 'Kesehatan Masyarakat', 'S1 Administrasi Kesehatan', 'Manajemen RS, puskesmas, klaim BPJS, administrasi'),
('Ahli Gizi', 'Kesehatan Masyarakat', 'D3/D4/S1 Gizi', 'Menyusun diet pasien, konseling gizi, asuhan gizi'),
('Dietisien', 'Kesehatan Masyarakat', 'D3/D4/S1 Gizi + Profesi Dietisien', 'Terapi diet, asuhan gizi klinik, monitoring gizi'),
('Nutrisionis', 'Kesehatan Masyarakat', 'D3 Gizi', 'Menyiapkan makanan pasien, penyuluhan gizi'),
('Ahli Kesehatan Lingkungan', 'Kesehatan Lingkungan', 'D3/D4/S1 Kesehatan Lingkungan', 'Sanitasi, pengendalian vektor, kualitas air, limbah'),
('Sanitarian', 'Kesehatan Lingkungan', 'D3 Kesehatan Lingkungan', 'Inspeksi sanitasi, pengendalian vektor, penyuluhan lingkungan'),
('Ahli Kesehatan Kerja', 'Kesehatan Kerja', 'S1/S2 Kesehatan Kerja', 'Kesehatan kerja, ergonomi, keselamatan kerja, higiene industri'),
('Ahli Keselamatan Kerja', 'Kesehatan Kerja', 'S1/S2 K3', 'Manajemen K3, audit keselamatan, investigasi kecelakaan'),
('Hygienist Industri', 'Kesehatan Kerja', 'S1/S2 Higiene Industri', 'Pengukuran paparan, monitoring lingkungan kerja'),
('Ergonom', 'Kesehatan Kerja', 'S1/S2 Ergonomi', 'Desain kerja, postur, pencegahan cedera kerja'),
('Ahli Promosi Kesehatan', 'Kesehatan Masyarakat', 'S1/S2 Promosi Kesehatan', 'Kampanye kesehatan, media edukasi, pemberdayaan'),
('Ahli Biostatistik', 'Kesehatan Masyarakat', 'S1/S2 Biostatistik', 'Analisis data kesehatan, penelitian, statistik'),
('Ahli Kesehatan Reproduksi', 'Kesehatan Masyarakat', 'S1/S2 Kesehatan Reproduksi', 'Program KB, kesehatan ibu, kespro remaja'),
('Ahli Kesehatan Ibu dan Anak', 'Kesehatan Masyarakat', 'S1/S2 KIA', 'Program KIA, posyandu, imunisasi, gizi ibu anak'),
('Ahli Surveilans', 'Kesehatan Masyarakat', 'S1/S2 Surveilans', 'Pemantauan penyakit, deteksi dini wabah, pelaporan'),
('Ahli Kesehatan Global', 'Kesehatan Masyarakat', 'S1/S2 Kesehatan Global', 'Kerjasama internasional, kebijakan kesehatan global'),
('Ahli Kebijakan Kesehatan', 'Kesehatan Masyarakat', 'S1/S2 Kebijakan Kesehatan', 'Analisis kebijakan, advokasi, regulasi kesehatan'),

-- ==================== TENAGA KETERAPIAN FISIK ====================
('Fisioterapis', 'Keterapian Fisik', 'D3/D4/S1 Fisioterapi + Profesi', 'Rehabilitasi gerak, terapi latihan, modalitas fisik'),
('Okupasi Terapis', 'Keterapian Fisik', 'D3/D4/S1 Okupasi Terapi + Profesi', 'Terapi aktivitas sehari-hari, rehabilitasi vokasional'),
('Terapis Wicara', 'Keterapian Fisik', 'D3/D4/S1 Terapi Wicara + Profesi', 'Terapi bicara, bahasa, menelan, komunikasi'),
('Ortotis Prostetis', 'Keterapian Fisik', 'D3/D4/S1 Ortotik Prostetik + Profesi', 'Membuat alat bantu ortotik, prostetik, sepatu orthopedi'),
('Terapis Okupasi', 'Keterapian Fisik', 'D3/D4/S1 Okupasi Terapi', 'Rehabilitasi pasien stroke, cedera, disabilitas'),
('Terapis Fisik Olahraga', 'Keterapian Fisik', 'S1 Fisioterapi + Spesialisasi', 'Rehabilitasi atlet, cedera olahraga, performa'),
('Terapis Pediatri', 'Keterapian Fisik', 'S1 Fisioterapi + Spesialisasi', 'Fisioterapi anak, tumbuh kembang, cerebral palsy'),
('Terapis Geriatri', 'Keterapian Fisik', 'S1 Fisioterapi + Spesialisasi', 'Fisioterapi lansia, jatuh, mobilitas'),
('Terapis Kardiovaskular', 'Keterapian Fisik', 'S1 Fisioterapi + Spesialisasi', 'Rehabilitasi jantung, pasca operasi jantung'),
('Terapis Pernapasan', 'Keterapian Fisik', 'S1 Fisioterapi + Spesialisasi', 'Fisioterapi dada, bersih jalan napas, ventilator'),
('Terapis Neurologi', 'Keterapian Fisik', 'S1 Fisioterapi + Spesialisasi', 'Rehabilitasi stroke, saraf, keseimbangan'),

-- ==================== TENAGA KETEKNISIAN MEDIS ====================
('Radiografer', 'Keteknisian Medis', 'D3/D4 Radiologi', 'Mengoperasikan X-Ray, CT, MRI, USG, mammografi'),
('Teknisi Radiologi', 'Keteknisian Medis', 'D3 Teknik Radiologi', 'Pencitraan medis, processing film, QC alat'),
('Terapis Radiasi', 'Keteknisian Medis', 'D3/D4 Radioterapi', 'Radioterapi kanker, linear accelerator'),
('Teknisi Laboratorium Medis', 'Keteknisian Medis', 'D3/D4 Teknologi Laboratorium Medis', 'Pemeriksaan laboratorium, sampling, analisis'),
('Analis Laboratorium', 'Keteknisian Medis', 'D3 Analis Kesehatan', 'Analisis darah, urin, mikrobiologi, kimia'),
('Teknisi Bank Darah', 'Keteknisian Medis', 'D3 Teknologi Bank Darah', 'Pengelolaan darah, crossmatch, penyimpanan'),
('Teknisi Elektromedik', 'Keteknisian Medis', 'D3/D4 Teknik Elektromedik', 'Pemeliharaan alat medis, kalibrasi, perbaikan'),
('Teknisi Gigi', 'Keteknisian Medis', 'D3 Teknik Gigi', 'Membuat gigi palsu, mahkota, jembatan, ortodonti'),
('Teknisi Ortodonti', 'Keteknisian Medis', 'D3 Teknik Ortodonti', 'Membuat alat ortodonti, retainer, behel'),
('Teknisi Kardiovaskular', 'Keteknisian Medis', 'D3 Teknologi Kardiovaskular', 'EKG, treadmill, holter, echokardiografi'),
('Perfusionist', 'Keteknisian Medis', 'D3/D4 Perfusion', 'Mengoperasikan mesin heart-lung bypass operasi jantung'),
('Teknisi Nuklir Medis', 'Keteknisian Medis', 'D3 Teknologi Nuklir Medis', 'Pencitraan nuklir, PET, SPECT, radioisotop'),
('Teknisi Ortotik Prostetik', 'Keteknisian Medis', 'D3 Ortotik Prostetik', 'Membuat dan memasang alat bantu ortotik prostetik'),
('Teknisi Anestesi', 'Keteknisian Medis', 'D3 Teknik Anestesi', 'Membantu anestesi, mesin anestesi, monitoring'),
('Teknisi Elektrokardiografi', 'Keteknisian Medis', 'D3 Teknik EKG', 'Perekaman EKG, treadmill, holter'),
('Teknisi Endoskopi', 'Keteknisian Medis', 'D3 Teknik Endoskopi', 'Mengoperasikan endoskop, sterilisasi, perawatan alat'),
('Teknisi Dialisis', 'Keteknisian Medis', 'D3 Teknik Dialisis', 'Mengoperasikan mesin dialisis, perawatan akses vaskular'),
('Teknisi Rekam Medis', 'Keteknisian Medis', 'D3 Rekam Medis & Informasi Kesehatan', 'Mengelola rekam medis, koding ICD, statistik RS'),
('Perekam Medis', 'Keteknisian Medis', 'D3 Rekam Medis', 'Rekam medis, koding, klaim BPJS, arsip'),
('Koder Medis', 'Keteknisian Medis', 'D3 Rekam Medis + Sertifikasi Koder', 'Koding diagnosis ICD-10, prosedur ICD-9-CM, klaim'),
('Teknisi Sterilisasi', 'Keteknisian Medis', 'D3 Teknik Sterilisasi', 'Sterilisasi alat medis, autoclave, CSSD'),
('Teknisi Forensik', 'Keteknisian Medis', 'D3 Teknik Forensik', 'Membantu autopsi, pengambilan sampel forensik'),
('Teknisi Histologi', 'Keteknisian Medis', 'D3 Teknologi Histologi', 'Membuat sediaan jaringan, pewarnaan, mikroskop'),
('Teknisi Sitologi', 'Keteknisian Medis', 'D3 Teknologi Sitologi', 'Pemeriksaan sel, Pap smear, sitologi'),
('Teknisi Imunologi', 'Keteknisian Medis', 'D3 Teknologi Imunologi', 'Pemeriksaan imunologi, ELISA, flow cytometry'),
('Teknisi Mikrobiologi', 'Keteknisian Medis', 'D3 Teknologi Mikrobiologi', 'Kultur bakteri, identifikasi, uji resistensi'),
('Teknisi Biologi Molekuler', 'Keteknisian Medis', 'D3 Teknologi Biologi Molekuler', 'PCR, DNA sequencing, diagnostik molekuler'),
('Teknisi Toksikologi', 'Keteknisian Medis', 'D3 Teknologi Toksikologi', 'Pemeriksaan toksikologi, deteksi racun, doping'),
('Teknisi Genetika', 'Keteknisian Medis', 'D3 Teknologi Genetika', 'Pemeriksaan genetik, kromosom, DNA'),
('Teknisi Patologi', 'Keteknisian Medis', 'D3 Teknologi Patologi', 'Pemeriksaan patologi klinik dan anatomi'),
('Teknisi Parasitologi', 'Keteknisian Medis', 'D3 Teknologi Parasitologi', 'Pemeriksaan parasit, malaria, cacing'),
('Teknisi Hematologi', 'Keteknisian Medis', 'D3 Teknologi Hematologi', 'Pemeriksaan darah, koagulasi, hematologi'),
('Teknisi Kimia Klinik', 'Keteknisian Medis', 'D3 Teknologi Kimia Klinik', 'Pemeriksaan kimia darah, enzim, elektrolit'),
('Teknisi Urinalisis', 'Keteknisian Medis', 'D3 Teknologi Urinalisis', 'Pemeriksaan urin, sedimen, kimia urin'),
('Teknisi Serologi', 'Keteknisian Medis', 'D3 Teknologi Serologi', 'Pemeriksaan serologi, antibodi, antigen'),
('Teknisi Virologi', 'Keteknisian Medis', 'D3 Teknologi Virologi', 'Pemeriksaan virus, kultur virus, PCR virus'),

-- ==================== TENAGA KESEHATAN TRADISIONAL ====================
('Pengobat Tradisional', 'Kesehatan Tradisional', 'Pelatihan/Kursus', 'Pengobatan tradisional, jamu, akupunktur'),
('Akupunkturis', 'Kesehatan Tradisional', 'Pendidikan Akupunktur', 'Terapi akupunktur, titik meridian, jarum'),
('Terapis Pijat', 'Kesehatan Tradisional', 'Pelatihan Pijat', 'Pijat terapi, refleksi, relaksasi'),
('Refleksi', 'Kesehatan Tradisional', 'Pelatihan Refleksi', 'Terapi refleksi kaki, tangan, telinga'),
('Herbalis', 'Kesehatan Tradisional', 'Pelatihan Herbal', 'Meracik jamu, herbal, pengobatan alami'),
('Tabib', 'Kesehatan Tradisional', 'Pengalaman/Tradisi', 'Pengobatan tradisional, spiritual, herbal'),
('Dukun Bayi', 'Kesehatan Tradisional', 'Pengalaman/Tradisi', 'Menolong persalinan tradisional, perawatan bayi'),
('Sinse', 'Kesehatan Tradisional', 'Pendidikan Sinse', 'Pengobatan tradisional Tionghoa, akupunktur, herbal'),
('Terapis Bekam', 'Kesehatan Tradisional', 'Pelatihan Bekam', 'Terapi bekam, hijamah, detoksifikasi'),
('Terapis Gua Sha', 'Kesehatan Tradisional', 'Pelatihan Gua Sha', 'Terapi gua sha, kerokan, sirkulasi darah'),
('Terapis Chiropractic', 'Kesehatan Tradisional', 'Pendidikan Chiropractic', 'Manipulasi tulang belakang, sendi, nyeri punggung'),
('Terapis Osteopati', 'Kesehatan Tradisional', 'Pendidikan Osteopati', 'Manipulasi osteopati, mobilitas sendi, nyeri'),
('Terapis Shiatsu', 'Kesehatan Tradisional', 'Pelatihan Shiatsu', 'Tekanan jari shiatsu, meridian, relaksasi'),
('Terapis Aromaterapi', 'Kesehatan Tradisional', 'Pelatihan Aromaterapi', 'Terapi minyak esensial, relaksasi, pijat aroma'),
('Terapis Hidroterapi', 'Kesehatan Tradisional', 'Pelatihan Hidroterapi', 'Terapi air, hidroterapi, kolam, sauna'),

-- ==================== TENAGA PSIKOLOGI KLINIS ====================
('Psikolog Klinis', 'Psikologi Klinis', 'S1 + S2 Psikologi Klinis + Profesi', 'Asesmen psikologi, terapi psikologi, konseling'),
('Psikolog Anak', 'Psikologi Klinis', 'S1 + S2 Psikologi Klinis Anak', 'Asesmen dan terapi anak, tumbuh kembang, autisme'),
('Psikolog Pendidikan', 'Psikologi Klinis', 'S1 + S2 Psikologi Pendidikan', 'Asesmen belajar, konseling pendidikan, kesulitan belajar'),
('Psikolog Industri', 'Psikologi Klinis', 'S1 + S2 Psikologi Industri', 'Asesmen karyawan, rekrutmen, pengembangan SDM'),
('Psikolog Forensik', 'Psikologi Klinis', 'S1 + S2 Psikologi Forensik', 'Asesmen forensik, psikologi hukum, saksi ahli'),
('Psikolog Olahraga', 'Psikologi Klinis', 'S1 + S2 Psikologi Olahraga', 'Psikologi atlet, motivasi, performa mental'),
('Psikolog Kesehatan', 'Psikologi Klinis', 'S1 + S2 Psikologi Kesehatan', 'Psikologi kesehatan, perilaku sehat, penyakit kronis'),
('Psikolog Neuropsikologi', 'Psikologi Klinis', 'S1 + S2 Neuropsikologi', 'Asesmen fungsi otak, rehabilitasi kognitif'),
('Konselor', 'Psikologi Klinis', 'S1 Bimbingan Konseling', 'Konseling individu, kelompok, keluarga'),
('Konselor Adiksi', 'Psikologi Klinis', 'S1 + Pelatihan Adiksi', 'Konseling pecandu narkoba, alkohol, rokok'),
('Konselor HIV/AIDS', 'Psikologi Klinis', 'S1 + Pelatihan HIV', 'Konseling HIV, tes, dukungan psikososial'),
('Konselor Genetik', 'Psikologi Klinis', 'S1 + Pelatihan Genetik', 'Konseling genetik, risiko penyakit, keluarga'),
('Terapis Perilaku', 'Psikologi Klinis', 'S1 + Pelatihan CBT', 'Terapi perilaku kognitif, fobia, OCD'),
('Terapis Keluarga', 'Psikologi Klinis', 'S1 + Pelatihan Terapi Keluarga', 'Terapi keluarga, komunikasi, konflik'),
('Terapis Anak', 'Psikologi Klinis', 'S1 + Pelatihan Terapi Anak', 'Terapi bermain, anak, autisme, ADHD'),
('Terapis Trauma', 'Psikologi Klinis', 'S1 + Pelatihan Trauma', 'Terapi trauma, PTSD, EMDR'),
('Hipnoterapis', 'Psikologi Klinis', 'S1 + Pelatihan Hipnoterapi', 'Hipnoterapi, sugesti, relaksasi, nyeri'),
('Psikoterapis', 'Psikologi Klinis', 'S1 + S2 Psikoterapi', 'Psikoterapi, psikoanalisis, humanistik'),

-- ==================== TENAGA KESEHATAN LAINNYA ====================
('Administrator Rumah Sakit', 'Manajemen Kesehatan', 'S1/S2 Administrasi RS', 'Manajemen RS, keuangan, SDM, mutu, akreditasi'),
('Manajer Klinik', 'Manajemen Kesehatan', 'S1/S2 Manajemen Kesehatan', 'Mengelola klinik, operasional, keuangan, SDM'),
('Manajer Puskesmas', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Masyarakat', 'Mengelola puskesmas, program kesehatan, SDM'),
('Kepala Dinas Kesehatan', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Masyarakat', 'Kebijakan kesehatan daerah, program, anggaran'),
('Menteri Kesehatan', 'Manajemen Kesehatan', 'S1/S2/S3 Kesehatan', 'Kebijakan kesehatan nasional, regulasi, program'),
('Direktur Rumah Sakit', 'Manajemen Kesehatan', 'S1/S2 Manajemen RS', 'Memimpin RS, kebijakan, mutu, akreditasi'),
('Konsultan Kesehatan', 'Manajemen Kesehatan', 'S1/S2 Kesehatan', 'Konsultasi manajemen kesehatan, mutu, akreditasi'),
('Auditor Kesehatan', 'Manajemen Kesehatan', 'S1/S2 Kesehatan', 'Audit mutu, audit klaim, audit keuangan kesehatan'),
('Asuransi Kesehatan', 'Manajemen Kesehatan', 'S1 Asuransi/Kesehatan', 'Verifikasi klaim, underwriting, manajemen risiko'),
('Case Manager', 'Manajemen Kesehatan', 'S1 Keperawatan/Kesehatan', 'Manajemen kasus pasien, koordinasi perawatan, discharge planning'),
('Community Health Worker', 'Manajemen Kesehatan', 'Pelatihan Kader', 'Kader kesehatan, posyandu, penyuluhan, rujukan'),
('Kader Posyandu', 'Manajemen Kesehatan', 'Pelatihan Kader', 'Penimbangan balita, imunisasi, penyuluhan gizi'),
('Kader Kesehatan', 'Manajemen Kesehatan', 'Pelatihan Kader', 'Pemberdayaan masyarakat, penyuluhan, deteksi dini'),
('Pemandu Kesehatan', 'Manajemen Kesehatan', 'Pelatihan', 'Pemandu program kesehatan, edukasi, motivasi'),
('Health Coach', 'Manajemen Kesehatan', 'Sertifikasi Health Coach', 'Coaching kesehatan, gaya hidup, motivasi pasien'),
('Health Educator', 'Manajemen Kesehatan', 'S1 Kesehatan Masyarakat', 'Edukasi kesehatan, pengembangan media, pelatihan'),
('Patient Navigator', 'Manajemen Kesehatan', 'S1 Kesehatan', 'Membantu pasien navigasi sistem kesehatan, akses layanan'),
('Medical Scribe', 'Manajemen Kesehatan', 'D3/S1 Kesehatan', 'Dokumentasi medis, mencatat dokter, rekam medis'),
('Medical Translator', 'Manajemen Kesehatan', 'S1 Bahasa + Kesehatan', 'Menerjemahkan medis, komunikasi pasien asing'),
('Medical Interpreter', 'Manajemen Kesehatan', 'S1 Bahasa + Kesehatan', 'Interpretasi medis, komunikasi dokter-pasien'),
('Medical Writer', 'Manajemen Kesehatan', 'S1 Kesehatan + Menulis', 'Menulis artikel medis, edukasi, publikasi'),
('Medical Representative', 'Manajemen Kesehatan', 'S1 Kesehatan/Farmasi', 'Pemasaran obat, edukasi dokter, produk farmasi'),
('Product Specialist', 'Manajemen Kesehatan', 'S1 Kesehatan/Farmasi', 'Spesialis produk medis, alat kesehatan, edukasi'),
('Clinical Research Associate', 'Manajemen Kesehatan', 'S1 Kesehatan', 'Monitoring uji klinis, data, kepatuhan protokol'),
('Clinical Research Coordinator', 'Manajemen Kesehatan', 'S1 Kesehatan', 'Koordinasi uji klinis, rekrutmen subjek, data'),
('Regulatory Affairs', 'Manajemen Kesehatan', 'S1 Farmasi/Kesehatan', 'Registrasi obat/alat kesehatan, BPOM, izin edar'),
('Pharmacovigilance', 'Manajemen Kesehatan', 'S1 Farmasi/Kesehatan', 'Monitoring efek samping obat, pelaporan, keamanan obat'),
('Medical Affairs', 'Manajemen Kesehatan', 'S1/S2 Kesehatan', 'Edukasi medis, hubungan dokter, strategi medis'),
('Market Access', 'Manajemen Kesehatan', 'S1/S2 Kesehatan', 'Akses pasar obat, reimbursement, BPJS'),
('Health Economist', 'Manajemen Kesehatan', 'S1/S2 Ekonomi Kesehatan', 'Analisis ekonomi kesehatan, cost-effectiveness, anggaran'),
('Health Policy Analyst', 'Manajemen Kesehatan', 'S1/S2 Kebijakan Kesehatan', 'Analisis kebijakan kesehatan, advokasi, rekomendasi'),
('Health Informatics', 'Manajemen Kesehatan', 'S1/S2 Informatika Kesehatan', 'Sistem informasi kesehatan, rekam medis elektronik, data'),
('Health Data Analyst', 'Manajemen Kesehatan', 'S1/S2 Data Kesehatan', 'Analisis data kesehatan, big data, visualisasi'),
('Telemedicine Specialist', 'Manajemen Kesehatan', 'S1 Kesehatan + Teknologi', 'Layanan telemedicine, konsultasi online, monitoring jarak jauh'),
('Digital Health Specialist', 'Manajemen Kesehatan', 'S1 Kesehatan + Teknologi', 'Pengembangan aplikasi kesehatan, wearable, IoT kesehatan'),
('Artificial Intelligence in Health', 'Manajemen Kesehatan', 'S1/S2 AI + Kesehatan', 'AI diagnosis, machine learning, imaging AI'),
('Bioinformatika', 'Manajemen Kesehatan', 'S1/S2 Bioinformatika', 'Analisis data genom, sekuensing, biologi komputasi'),
('Genetika Klinis', 'Manajemen Kesehatan', 'S1/S2 Genetika Klinis', 'Konseling genetik, diagnosis genetik, tes DNA'),
('Konselor Genetik', 'Manajemen Kesehatan', 'S1/S2 Konseling Genetik', 'Konseling genetik, risiko keluarga, tes genetik'),
('Ahli Gizi Olahraga', 'Manajemen Kesehatan', 'S1/S2 Gizi Olahraga', 'Gizi atlet, performa, suplemen, hidrasi'),
('Ahli Gizi Klinik', 'Manajemen Kesehatan', 'S1/S2 Gizi Klinik', 'Terapi gizi pasien, diabetes, ginjal, kanker'),
('Ahli Gizi Masyarakat', 'Manajemen Kesehatan', 'S1/S2 Gizi Masyarakat', 'Program gizi masyarakat, stunting, anemia, posyandu'),
('Ahli Gizi Industri', 'Manajemen Kesehatan', 'S1/S2 Gizi Industri', 'Gizi karyawan, katering industri, produktivitas'),
('Ahli Gizi Food Service', 'Manajemen Kesehatan', 'S1/S2 Gizi', 'Manajemen penyelenggaraan makanan, menu, mutu'),
('Ahli Teknologi Pangan', 'Manajemen Kesehatan', 'S1/S2 Teknologi Pangan', 'Pengembangan produk pangan, keamanan pangan, gizi'),
('Ahli Keamanan Pangan', 'Manajemen Kesehatan', 'S1/S2 Keamanan Pangan', 'Pengawasan pangan, HACCP, BPOM, keamanan konsumen'),
('Ahli Kesehatan Hewan', 'Manajemen Kesehatan', 'S1 Kedokteran Hewan', 'Kesehatan hewan, zoonosis, vaksin hewan, karantina'),
('Dokter Hewan', 'Manajemen Kesehatan', 'S1 Kedokteran Hewan + Profesi', 'Mengobati hewan, operasi hewan, vaksinasi, zoonosis'),
('Paramedik Veteriner', 'Manajemen Kesehatan', 'D3 Kesehatan Hewan', 'Membantu dokter hewan, perawatan hewan, laboratorium'),
('Ahli Kesehatan Masyarakat Veteriner', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Masyarakat Veteriner', 'Zoonosis, keamanan pangan asal hewan, surveilans'),
('Ahli Kesehatan Tumbuhan', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Tumbuhan', 'Kesehatan tanaman, hama, penyakit tanaman, karantina'),
('Ahli Kesehatan Lingkungan Industri', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Lingkungan', 'Limbah industri, pencemaran, AMDAL, kesehatan lingkungan'),
('Ahli Kesehatan Radiasi', 'Manajemen Kesehatan', 'S1/S2 Fisika Medis', 'Proteksi radiasi, dosimetri, keselamatan radiasi'),
('Fisikawan Medis', 'Manajemen Kesehatan', 'S1/S2 Fisika Medis', 'Radioterapi, dosimetri, kalibrasi alat radiasi, QC'),
('Ahli Kesehatan Nuklir', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Nuklir', 'Kedokteran nuklir, radiofarmasi, proteksi radiasi'),
('Ahli Kesehatan Penerbangan', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Penerbangan', 'Kesehatan pilot, awak kabin, aviation medicine'),
('Ahli Kesehatan Kelautan', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Kelautan', 'Kesehatan pelaut, hiperbarik, diving medicine'),
('Ahli Kesehatan Bencana', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Bencana', 'Manajemen bencana, triase, bantuan darurat, logistik'),
('Ahli Kesehatan Militer', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Militer', 'Kesehatan tentara, medan perang, evakuasi, trauma'),
('Ahli Kesehatan Olahraga', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Olahraga', 'Kesehatan atlet, cedera olahraga, doping, performa'),
('Ahli Kesehatan Reproduksi', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Reproduksi', 'Kesehatan reproduksi, KB, kespro remaja, infertilitas'),
('Ahli Kesehatan Seksual', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Seksual', 'Kesehatan seksual, IMS, HIV, konseling'),
('Ahli Kesehatan Lansia', 'Manajemen Kesehatan', 'S1/S2 Gerontologi', 'Kesehatan lansia, panti, home care, penyakit degeneratif'),
('Ahli Kesehatan Anak', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Anak', 'Kesehatan anak, tumbuh kembang, imunisasi, gizi anak'),
('Ahli Kesehatan Remaja', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Remaja', 'Kesehatan remaja, kespro, NAPZA, mental health'),
('Ahli Kesehatan Perempuan', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Perempuan', 'Kesehatan perempuan, menopause, kanker serviks, payudara'),
('Ahli Kesehatan Pria', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Pria', 'Kesehatan pria, prostat, disfungsi ereksi, testosteron'),
('Ahli Kesehatan Keluarga', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Keluarga', 'Kesehatan keluarga, dokter keluarga, home care'),
('Ahli Kesehatan Komunitas', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Komunitas', 'Kesehatan komunitas, puskesmas, posyandu, UKBM'),
('Ahli Kesehatan Sekolah', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Sekolah', 'UKS, kesehatan sekolah, skrining, penyuluhan'),
('Ahli Kesehatan Kerja', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Kerja', 'Kesehatan kerja, ergonomi, K3, penyakit akibat kerja'),
('Ahli Kesehatan Lingkungan', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Lingkungan', 'Sanitasi, air bersih, limbah, vektor, pencemaran'),
('Ahli Kesehatan Global', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Global', 'Kesehatan global, pandemi, kerjasama internasional, WHO'),
('Ahli Kesehatan Digital', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Digital', 'Kesehatan digital, telemedicine, AI, wearable, big data'),
('Ahli Kesehatan Presisi', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Presisi', 'Kedokteran presisi, genomik, personalized medicine'),
('Ahli Kesehatan Regeneratif', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Regeneratif', 'Kedokteran regeneratif, stem cell, tissue engineering'),
('Ahli Kesehatan Anti-Aging', 'Manajemen Kesehatan', 'S1/S2 Anti-Aging', 'Anti-aging, longevity, hormon, nutrisi, estetika'),
('Ahli Kesehatan Estetika', 'Manajemen Kesehatan', 'S1/S2 Estetika', 'Estetika medis, botox, filler, laser, skincare'),
('Ahli Kesehatan Kulit', 'Manajemen Kesehatan', 'S1/S2 Dermatologi', 'Kesehatan kulit, kosmetik, dermatologi estetika'),
('Ahli Kesehatan Rambut', 'Manajemen Kesehatan', 'S1/S2 Trichology', 'Kesehatan rambut, kerontokan, transplantasi rambut'),
('Ahli Kesehatan Kuku', 'Manajemen Kesehatan', 'S1/S2 Podiatri', 'Kesehatan kuku, kaki, podiatri, diabetes foot care'),
('Ahli Kesehatan Kaki', 'Manajemen Kesehatan', 'S1/S2 Podiatri', 'Kesehatan kaki, sepatu orthopedi, diabetes foot'),
('Ahli Kesehatan Mulut', 'Manajemen Kesehatan', 'S1/S2 Kedokteran Gigi', 'Kesehatan mulut, gigi, gusi, preventif, promotif'),
('Ahli Kesehatan Gigi Masyarakat', 'Manajemen Kesehatan', 'S1/S2 Kesehatan Gigi Masyarakat', 'Kesehatan gigi masyarakat, sikat gigi massal, fluoridasi'),
('Ahli Kesehatan Gigi Anak', 'Manajemen Kesehatan', 'S1/S2 Kedokteran Gigi Anak', 'Kesehatan gigi anak, pencegahan karies, edukasi'),
('Ahli Kesehatan Gigi Keluarga', 'Manajemen Kesehatan', 'S1/S2 Kedokteran Gigi Keluarga', 'Kesehatan gigi keluarga, preventif, promotif'),
('Ahli Kesehatan Gigi Lansia', 'Manajemen Kesehatan', 'S1/S2 Kedokteran Gigi Lansia', 'Kesehatan gigi lansia, gigi palsu, perawatan mulut'),
('Ahli Kesehatan Gigi Disabilitas', 'Manajemen Kesehatan', 'S1/S2 Kedokteran Gigi Disabilitas', 'Kesehatan gigi disabilitas, perawatan khusus, sedasi'),
('Ahli Kesehatan Gigi Ibu Hamil', 'Manajemen Kesehatan', 'S1/S2 Kedokteran Gigi', 'Kesehatan gigi ibu hamil, gingivitis kehamilan, edukasi'),
('Ahli Kesehatan Gigi Diabetes', 'Manajemen Kesehatan', 'S1/S2 Kedokteran Gigi', 'Kesehatan gigi diabetes, periodontitis, penyembuhan luka'),
('Ahli Kesehatan Gigi Kanker', 'Manajemen Kesehatan', 'S1/S2 Kedokteran Gigi', 'Kesehatan gigi pasien kanker, mukositis, xerostomia'),
('Ahli Kesehatan Gigi Kardiovaskular', 'Manajemen Kesehatan', 'S1/S2 Kedokteran Gigi', 'Kesehatan gigi pasien jantung, endokarditis, antikoagulan'),
('Ahli Kesehatan Gigi HIV', 'Manajemen Kesehatan', 'S1/S2 Kedokteran Gigi', 'Kesehatan gigi pasien HIV, kandidiasis, infeksi oportunistik');