<?php

$bandaraIndonesia = [
  ["nama" => "Bandar Udara Internasional Soekarno-Hatta", "iata" => "CGK", "icao" => "WIII", "kota" => "Tangerang", "provinsi" => "Banten", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Halim Perdanakusuma", "iata" => "HLP", "icao" => "WIHH", "kota" => "Jakarta", "provinsi" => "DKI Jakarta", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Ngurah Rai", "iata" => "DPS", "icao" => "WADD", "kota" => "Denpasar", "provinsi" => "Bali", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Juanda", "iata" => "SUB", "icao" => "WARR", "kota" => "Surabaya", "provinsi" => "Jawa Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Kualanamu", "iata" => "KNO", "icao" => "WIMM", "kota" => "Medan", "provinsi" => "Sumatera Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Hasanuddin", "iata" => "UPG", "icao" => "WAAA", "kota" => "Makassar", "provinsi" => "Sulawesi Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Aji Muhammad Sulaiman Sepinggan", "iata" => "BPN", "icao" => "WALL", "kota" => "Balikpapan", "provinsi" => "Kalimantan Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sam Ratulangi", "iata" => "MDC", "icao" => "WAMM", "kota" => "Manado", "provinsi" => "Sulawesi Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Yogyakarta", "iata" => "YIA", "icao" => "WAHI", "kota" => "Kulon Progo", "provinsi" => "DI Yogyakarta", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Adisutjipto", "iata" => "JOG", "icao" => "WARJ", "kota" => "Yogyakarta", "provinsi" => "DI Yogyakarta", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Ahmad Yani", "iata" => "SRG", "icao" => "WAHS", "kota" => "Semarang", "provinsi" => "Jawa Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Adi Soemarmo", "iata" => "SOC", "icao" => "WARQ", "kota" => "Solo", "provinsi" => "Jawa Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Husein Sastranegara", "iata" => "BDO", "icao" => "WICC", "kota" => "Bandung", "provinsi" => "Jawa Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Kertajati", "iata" => "KJT", "icao" => "WICA", "kota" => "Majalengka", "provinsi" => "Jawa Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Iskandar Muda", "iata" => "BTJ", "icao" => "WITT", "kota" => "Banda Aceh", "provinsi" => "Aceh", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Syarif Kasim II", "iata" => "PKU", "icao" => "WIBB", "kota" => "Pekanbaru", "provinsi" => "Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Minangkabau", "iata" => "PDG", "icao" => "WIPT", "kota" => "Padang", "provinsi" => "Sumatera Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Mahmud Badaruddin II", "iata" => "PLM", "icao" => "WIPP", "kota" => "Palembang", "provinsi" => "Sumatera Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Radin Inten II", "iata" => "TKG", "icao" => "WILL", "kota" => "Bandar Lampung", "provinsi" => "Lampung", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Depati Amir", "iata" => "PGK", "icao" => "WIPK", "kota" => "Pangkal Pinang", "provinsi" => "Bangka Belitung", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Raja Haji Fisabilillah", "iata" => "TNJ", "icao" => "WIDN", "kota" => "Tanjung Pinang", "provinsi" => "Kepulauan Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Hang Nadim", "iata" => "BTH", "icao" => "WIDD", "kota" => "Batam", "provinsi" => "Kepulauan Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Supadio", "iata" => "PNK", "icao" => "WIOO", "kota" => "Pontianak", "provinsi" => "Kalimantan Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Syamsudin Noor", "iata" => "BDJ", "icao" => "WAOO", "kota" => "Banjarmasin", "provinsi" => "Kalimantan Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Aji Muhammad Sulaiman Sepinggan", "iata" => "BPN", "icao" => "WALL", "kota" => "Balikpapan", "provinsi" => "Kalimantan Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Juwata", "iata" => "TRK", "icao" => "WAQQ", "kota" => "Tarakan", "provinsi" => "Kalimantan Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Bantilan", "iata" => "TLI", "icao" => "WAMI", "kota" => "Tolitoli", "provinsi" => "Sulawesi Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Mutiara SIS Al-Jufrie", "iata" => "PLW", "icao" => "WAFF", "kota" => "Palu", "provinsi" => "Sulawesi Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Haluoleo", "iata" => "KDI", "icao" => "WAWW", "kota" => "Kendari", "provinsi" => "Sulawesi Tenggara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Betoambari", "iata" => "BUW", "icao" => "WAWB", "kota" => "Bau-Bau", "provinsi" => "Sulawesi Tenggara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Babullah", "iata" => "TTE", "icao" => "WAMT", "kota" => "Ternate", "provinsi" => "Maluku Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Pattimura", "iata" => "AMQ", "icao" => "WAPP", "kota" => "Ambon", "provinsi" => "Maluku", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Frans Kaisiepo", "iata" => "BIK", "icao" => "WABB", "kota" => "Biak", "provinsi" => "Papua", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sentani", "iata" => "DJJ", "icao" => "WAJJ", "kota" => "Jayapura", "provinsi" => "Papua", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional El Tari", "iata" => "KOE", "icao" => "WATT", "kota" => "Kupang", "provinsi" => "Nusa Tenggara Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Lombok", "iata" => "LOP", "icao" => "WADL", "kota" => "Praya", "provinsi" => "Nusa Tenggara Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Muhammad Kaharuddin III", "iata" => "SWQ", "icao" => "WADS", "kota" => "Sumbawa Besar", "provinsi" => "Nusa Tenggara Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Komodo", "iata" => "LBJ", "icao" => "WATO", "kota" => "Labuan Bajo", "provinsi" => "Nusa Tenggara Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Tardamu", "iata" => "SAU", "icao" => "WATS", "kota" => "Sabu", "provinsi" => "Nusa Tenggara Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Umbu Mehang Kunda", "iata" => "WGP", "icao" => "WATU", "kota" => "Waingapu", "provinsi" => "Nusa Tenggara Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Gewayantana", "iata" => "LKA", "icao" => "WATL", "kota" => "Larantuka", "provinsi" => "Nusa Tenggara Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Wai Oti", "iata" => "MOF", "icao" => "WATC", "kota" => "Maumere", "provinsi" => "Nusa Tenggara Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional H. Hasan Aroeboesman", "iata" => "ENE", "icao" => "WATE", "kota" => "Ende", "provinsi" => "Nusa Tenggara Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Soa Bajawa", "iata" => "BJW", "icao" => "WATB", "kota" => "Bajawa", "provinsi" => "Nusa Tenggara Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Frans Sales Lega", "iata" => "RTG", "icao" => "WATG", "kota" => "Ruteng", "provinsi" => "Nusa Tenggara Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Tambolaka", "iata" => "TMC", "icao" => "WATK", "kota" => "Tambolaka", "provinsi" => "Nusa Tenggara Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Lede Kalumbang", "iata" => "TJS", "icao" => "WALT", "kota" => "Tanjung Selor", "provinsi" => "Kalimantan Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Kalimarau", "iata" => "BEJ", "icao" => "WAQT", "kota" => "Berau", "provinsi" => "Kalimantan Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Aji Muhammad Sulaiman Sepinggan", "iata" => "BPN", "icao" => "WALL", "kota" => "Balikpapan", "provinsi" => "Kalimantan Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Aji Pangeran Tumenggung Pranoto", "iata" => "AAP", "icao" => "WALS", "kota" => "Samarinda", "provinsi" => "Kalimantan Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Tanjung Harapan", "iata" => "TJS", "icao" => "WALT", "kota" => "Tanjung Selor", "provinsi" => "Kalimantan Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Robert Atty Bessing", "iata" => "NNX", "icao" => "WAQN", "kota" => "Nunukan", "provinsi" => "Kalimantan Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Long Apung", "iata" => "LPU", "icao" => "WRLP", "kota" => "Long Apung", "provinsi" => "Kalimantan Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Long Bawan", "iata" => "LBW", "icao" => "WRLB", "kota" => "Long Bawan", "provinsi" => "Kalimantan Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Datah Dawai", "iata" => "DTD", "icao" => "WRLD", "kota" => "Datah Dawai", "provinsi" => "Kalimantan Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Melak", "iata" => "MLK", "icao" => "WRLM", "kota" => "Melak", "provinsi" => "Kalimantan Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Muara Wahau", "iata" => "MWW", "icao" => "WRLW", "kota" => "Muara Wahau", "provinsi" => "Kalimantan Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Muara Teweh", "iata" => "HMS", "icao" => "WRLH", "kota" => "Muara Teweh", "provinsi" => "Kalimantan Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Kuala Kurun", "iata" => "KLK", "icao" => "WRLK", "kota" => "Kuala Kurun", "provinsi" => "Kalimantan Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Kuala Pembuang", "iata" => "KLP", "icao" => "WRLP", "kota" => "Kuala Pembuang", "provinsi" => "Kalimantan Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Pangkalan Bun", "iata" => "PKN", "icao" => "WAGI", "kota" => "Pangkalan Bun", "provinsi" => "Kalimantan Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sampit", "iata" => "SMQ", "icao" => "WAGS", "kota" => "Sampit", "provinsi" => "Kalimantan Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Palangkaraya", "iata" => "PKY", "icao" => "WAGG", "kota" => "Palangkaraya", "provinsi" => "Kalimantan Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Buntok", "iata" => "BUN", "icao" => "WAGB", "kota" => "Buntok", "provinsi" => "Kalimantan Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Tumbang Samba", "iata" => "TBS", "icao" => "WAGT", "kota" => "Tumbang Samba", "provinsi" => "Kalimantan Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Puruk Cahu", "iata" => "PCU", "icao" => "WAGP", "kota" => "Puruk Cahu", "provinsi" => "Kalimantan Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Beringin", "iata" => "BRG", "icao" => "WAGB", "kota" => "Beringin", "provinsi" => "Kalimantan Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Gusti Syamsir Alam", "iata" => "KBU", "icao" => "WAOK", "kota" => "Kotabaru", "provinsi" => "Kalimantan Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Syamsudin Noor", "iata" => "BDJ", "icao" => "WAOO", "kota" => "Banjarmasin", "provinsi" => "Kalimantan Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Batu Licin", "iata" => "BTW", "icao" => "WAOB", "kota" => "Batu Licin", "provinsi" => "Kalimantan Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Warukin", "iata" => "TJG", "icao" => "WAON", "kota" => "Tanjung", "provinsi" => "Kalimantan Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Supadio", "iata" => "PNK", "icao" => "WIOO", "kota" => "Pontianak", "provinsi" => "Kalimantan Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Rahadi Osman", "iata" => "KTG", "icao" => "WIOK", "kota" => "Ketapang", "provinsi" => "Kalimantan Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Singkawang", "iata" => "SKJ", "icao" => "WIOS", "kota" => "Singkawang", "provinsi" => "Kalimantan Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sintang", "iata" => "SQG", "icao" => "WIOS", "kota" => "Sintang", "provinsi" => "Kalimantan Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Putussibau", "iata" => "PSU", "icao" => "WIOP", "kota" => "Putussibau", "provinsi" => "Kalimantan Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Kapuas Hulu", "iata" => "KHY", "icao" => "WIOH", "kota" => "Kapuas Hulu", "provinsi" => "Kalimantan Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Bengkayang", "iata" => "BKY", "icao" => "WIOB", "kota" => "Bengkayang", "provinsi" => "Kalimantan Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Landak", "iata" => "LDK", "icao" => "WIOL", "kota" => "Landak", "provinsi" => "Kalimantan Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Mempawah", "iata" => "MPW", "icao" => "WIOM", "kota" => "Mempawah", "provinsi" => "Kalimantan Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sambas", "iata" => "SBS", "icao" => "WIOS", "kota" => "Sambas", "provinsi" => "Kalimantan Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sanggau", "iata" => "SGQ", "icao" => "WIOS", "kota" => "Sanggau", "provinsi" => "Kalimantan Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sekadau", "iata" => "SKD", "icao" => "WIOS", "kota" => "Sekadau", "provinsi" => "Kalimantan Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Tayan", "iata" => "TYN", "icao" => "WIOT", "kota" => "Tayan", "provinsi" => "Kalimantan Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Kuala Tungkal", "iata" => "KTL", "icao" => "WIKT", "kota" => "Kuala Tungkal", "provinsi" => "Jambi", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Thaha", "iata" => "DJB", "icao" => "WIPA", "kota" => "Jambi", "provinsi" => "Jambi", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Muara Bungo", "iata" => "BUU", "icao" => "WIPB", "kota" => "Muara Bungo", "provinsi" => "Jambi", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Kerinci", "iata" => "KRC", "icao" => "WIPK", "kota" => "Kerinci", "provinsi" => "Jambi", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Depati Parbo", "iata" => "KRC", "icao" => "WIPK", "kota" => "Kerinci", "provinsi" => "Jambi", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Fatmawati Soekarno", "iata" => "BKS", "icao" => "WIPL", "kota" => "Bengkulu", "provinsi" => "Bengkulu", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Mukomuko", "iata" => "MPC", "icao" => "WIPM", "kota" => "Mukomuko", "provinsi" => "Bengkulu", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Enggano", "iata" => "ENG", "icao" => "WIPE", "kota" => "Enggano", "provinsi" => "Bengkulu", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Mahmud Badaruddin II", "iata" => "PLM", "icao" => "WIPP", "kota" => "Palembang", "provinsi" => "Sumatera Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Silampari", "iata" => "LLG", "icao" => "WIPL", "kota" => "Lubuk Linggau", "provinsi" => "Sumatera Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Atung Bungsu", "iata" => "PXA", "icao" => "WIPX", "kota" => "Pagar Alam", "provinsi" => "Sumatera Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Banding Agung", "iata" => "BDA", "icao" => "WIPD", "kota" => "Banding Agung", "provinsi" => "Sumatera Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Radin Inten II", "iata" => "TKG", "icao" => "WILL", "kota" => "Bandar Lampung", "provinsi" => "Lampung", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Gusti Sjamsir Alam", "iata" => "KBU", "icao" => "WAOK", "kota" => "Kotabaru", "provinsi" => "Kalimantan Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Abdul Rachman Saleh", "iata" => "MLG", "icao" => "WARA", "kota" => "Malang", "provinsi" => "Jawa Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Banyuwangi", "iata" => "BWX", "icao" => "WADY", "kota" => "Banyuwangi", "provinsi" => "Jawa Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Notohadinegoro", "iata" => "JBB", "icao" => "WARE", "kota" => "Jember", "provinsi" => "Jawa Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Iswahjudi", "iata" => "MDN", "icao" => "WARI", "kota" => "Madiun", "provinsi" => "Jawa Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Dhoho", "iata" => "DHO", "icao" => "WARD", "kota" => "Kediri", "provinsi" => "Jawa Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Juanda", "iata" => "SUB", "icao" => "WARR", "kota" => "Surabaya", "provinsi" => "Jawa Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Bawean", "iata" => "BXW", "icao" => "WARB", "kota" => "Bawean", "provinsi" => "Jawa Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Kangean", "iata" => "KGP", "icao" => "WARK", "kota" => "Kangean", "provinsi" => "Jawa Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sumenep", "iata" => "SUP", "icao" => "WARS", "kota" => "Sumenep", "provinsi" => "Jawa Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Tuban", "iata" => "TBU", "icao" => "WART", "kota" => "Tuban", "provinsi" => "Jawa Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Ahmad Yani", "iata" => "SRG", "icao" => "WAHS", "kota" => "Semarang", "provinsi" => "Jawa Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Adi Soemarmo", "iata" => "SOC", "icao" => "WARQ", "kota" => "Solo", "provinsi" => "Jawa Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Jenderal Ahmad Yani", "iata" => "SRG", "icao" => "WAHS", "kota" => "Semarang", "provinsi" => "Jawa Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Tunggul Wulung", "iata" => "CXP", "icao" => "WIHL", "kota" => "Cilacap", "provinsi" => "Jawa Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Dewadaru", "iata" => "KWB", "icao" => "WAHK", "kota" => "Karimunjawa", "provinsi" => "Jawa Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Yogyakarta", "iata" => "YIA", "icao" => "WAHI", "kota" => "Kulon Progo", "provinsi" => "DI Yogyakarta", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Adisutjipto", "iata" => "JOG", "icao" => "WARJ", "kota" => "Yogyakarta", "provinsi" => "DI Yogyakarta", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Husein Sastranegara", "iata" => "BDO", "icao" => "WICC", "kota" => "Bandung", "provinsi" => "Jawa Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Kertajati", "iata" => "KJT", "icao" => "WICA", "kota" => "Majalengka", "provinsi" => "Jawa Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Cakrabhuwana", "iata" => "CBN", "icao" => "WICD", "kota" => "Cirebon", "provinsi" => "Jawa Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Nusawiru", "iata" => "CJN", "icao" => "WICN", "kota" => "Pangandaran", "provinsi" => "Jawa Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Soekarno-Hatta", "iata" => "CGK", "icao" => "WIII", "kota" => "Tangerang", "provinsi" => "Banten", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Halim Perdanakusuma", "iata" => "HLP", "icao" => "WIHH", "kota" => "Jakarta", "provinsi" => "DKI Jakarta", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Pondok Cabe", "iata" => "PCB", "icao" => "WIHP", "kota" => "Tangerang Selatan", "provinsi" => "Banten", "jenis" => "Domestik"],
  ["nama" => "Bandar Udara Internasional Curug", "iata" => "CUR", "icao" => "WIIA", "kota" => "Tangerang", "provinsi" => "Banten", "jenis" => "Domestik"],
  ["nama" => "Bandar Udara Internasional Budiarto", "iata" => "CUR", "icao" => "WIIA", "kota" => "Tangerang", "provinsi" => "Banten", "jenis" => "Domestik"],
  ["nama" => "Bandar Udara Internasional Sultan Iskandar Muda", "iata" => "BTJ", "icao" => "WITT", "kota" => "Banda Aceh", "provinsi" => "Aceh", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Malikussaleh", "iata" => "LSW", "icao" => "WITM", "kota" => "Lhokseumawe", "provinsi" => "Aceh", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Syarif Kasim II", "iata" => "PKU", "icao" => "WIBB", "kota" => "Pekanbaru", "provinsi" => "Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Hang Nadim", "iata" => "BTH", "icao" => "WIDD", "kota" => "Batam", "provinsi" => "Kepulauan Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Raja Haji Fisabilillah", "iata" => "TNJ", "icao" => "WIDN", "kota" => "Tanjung Pinang", "provinsi" => "Kepulauan Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Minangkabau", "iata" => "PDG", "icao" => "WIPT", "kota" => "Padang", "provinsi" => "Sumatera Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Kualanamu", "iata" => "KNO", "icao" => "WIMM", "kota" => "Medan", "provinsi" => "Sumatera Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Silangit", "iata" => "DTB", "icao" => "WIMN", "kota" => "Siborong-Borong", "provinsi" => "Sumatera Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Ferdinand Lumban Tobing", "iata" => "FLZ", "icao" => "WIMS", "kota" => "Sibolga", "provinsi" => "Sumatera Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Aek Godang", "iata" => "AEG", "icao" => "WIME", "kota" => "Padang Sidempuan", "provinsi" => "Sumatera Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Binaka", "iata" => "GNS", "icao" => "WIMB", "kota" => "Gunungsitoli", "provinsi" => "Sumatera Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Lasikin", "iata" => "LKI", "icao" => "WIML", "kota" => "Lasikin", "provinsi" => "Sumatera Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sibisa", "iata" => "SIB", "icao" => "WIMS", "kota" => "Sibisa", "provinsi" => "Sumatera Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Dr. Ferdinand Lumban Tobing", "iata" => "FLZ", "icao" => "WIMS", "kota" => "Sibolga", "provinsi" => "Sumatera Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Raja Haji Fisabilillah", "iata" => "TNJ", "icao" => "WIDN", "kota" => "Tanjung Pinang", "provinsi" => "Kepulauan Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Dabo", "iata" => "SIQ", "icao" => "WIDS", "kota" => "Singkep", "provinsi" => "Kepulauan Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Letung", "iata" => "LMU", "icao" => "WIDL", "kota" => "Letung", "provinsi" => "Kepulauan Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Matak", "iata" => "MWK", "icao" => "WIOM", "kota" => "Matak", "provinsi" => "Kepulauan Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Ranai", "iata" => "NTX", "icao" => "WION", "kota" => "Ranai", "provinsi" => "Kepulauan Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Tambelan", "iata" => "TBX", "icao" => "WIDT", "kota" => "Tambelan", "provinsi" => "Kepulauan Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Jemaja", "iata" => "LMU", "icao" => "WIDL", "kota" => "Jemaja", "provinsi" => "Kepulauan Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Siantan", "iata" => "SIQ", "icao" => "WIDS", "kota" => "Siantan", "provinsi" => "Kepulauan Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Tioman", "iata" => "TOD", "icao" => "WIDT", "kota" => "Tioman", "provinsi" => "Kepulauan Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Pangkal Pinang", "iata" => "PGK", "icao" => "WIPK", "kota" => "Pangkal Pinang", "provinsi" => "Bangka Belitung", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional H.A.S. Hanandjoeddin", "iata" => "TJQ", "icao" => "WIOD", "kota" => "Tanjung Pandan", "provinsi" => "Bangka Belitung", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Depati Amir", "iata" => "PGK", "icao" => "WIPK", "kota" => "Pangkal Pinang", "provinsi" => "Bangka Belitung", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Fatmawati Soekarno", "iata" => "BKS", "icao" => "WIPL", "kota" => "Bengkulu", "provinsi" => "Bengkulu", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Thaha", "iata" => "DJB", "icao" => "WIPA", "kota" => "Jambi", "provinsi" => "Jambi", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Mahmud Badaruddin II", "iata" => "PLM", "icao" => "WIPP", "kota" => "Palembang", "provinsi" => "Sumatera Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Radin Inten II", "iata" => "TKG", "icao" => "WILL", "kota" => "Bandar Lampung", "provinsi" => "Lampung", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Soekarno-Hatta", "iata" => "CGK", "icao" => "WIII", "kota" => "Tangerang", "provinsi" => "Banten", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Ngurah Rai", "iata" => "DPS", "icao" => "WADD", "kota" => "Denpasar", "provinsi" => "Bali", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Lombok", "iata" => "LOP", "icao" => "WADL", "kota" => "Praya", "provinsi" => "Nusa Tenggara Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Muhammad Kaharuddin III", "iata" => "SWQ", "icao" => "WADS", "kota" => "Sumbawa Besar", "provinsi" => "Nusa Tenggara Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Bima", "iata" => "BMU", "icao" => "WADB", "kota" => "Bima", "provinsi" => "Nusa Tenggara Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional El Tari", "iata" => "KOE", "icao" => "WATT", "kota" => "Kupang", "provinsi" => "Nusa Tenggara Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Komodo", "iata" => "LBJ", "icao" => "WATO", "kota" => "Labuan Bajo", "provinsi" => "Nusa Tenggara Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Frans Kaisiepo", "iata" => "BIK", "icao" => "WABB", "kota" => "Biak", "provinsi" => "Papua", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sentani", "iata" => "DJJ", "icao" => "WAJJ", "kota" => "Jayapura", "provinsi" => "Papua", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Mozes Kilangin", "iata" => "TIM", "icao" => "WABP", "kota" => "Timika", "provinsi" => "Papua", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Wamena", "iata" => "WMX", "icao" => "WAJW", "kota" => "Wamena", "provinsi" => "Papua", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Merauke", "iata" => "MKQ", "icao" => "WAKK", "kota" => "Merauke", "provinsi" => "Papua", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Nabire", "iata" => "NBX", "icao" => "WABI", "kota" => "Nabire", "provinsi" => "Papua", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Fakfak", "iata" => "FKQ", "icao" => "WASF", "kota" => "Fakfak", "provinsi" => "Papua Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Kaimana", "iata" => "KNG", "icao" => "WASK", "kota" => "Kaimana", "provinsi" => "Papua Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Manokwari", "iata" => "MKW", "icao" => "WASR", "kota" => "Manokwari", "provinsi" => "Papua Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sorong", "iata" => "SOQ", "icao" => "WASS", "kota" => "Sorong", "provinsi" => "Papua Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Torea", "iata" => "FKQ", "icao" => "WASF", "kota" => "Fakfak", "provinsi" => "Papua Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Utarom", "iata" => "KNG", "icao" => "WASK", "kota" => "Kaimana", "provinsi" => "Papua Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Rendani", "iata" => "MKW", "icao" => "WASR", "kota" => "Manokwari", "provinsi" => "Papua Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Domine Eduard Osok", "iata" => "SOQ", "icao" => "WASS", "kota" => "Sorong", "provinsi" => "Papua Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Pattimura", "iata" => "AMQ", "icao" => "WAPP", "kota" => "Ambon", "provinsi" => "Maluku", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Babullah", "iata" => "TTE", "icao" => "WAMT", "kota" => "Ternate", "provinsi" => "Maluku Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sam Ratulangi", "iata" => "MDC", "icao" => "WAMM", "kota" => "Manado", "provinsi" => "Sulawesi Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Djalaluddin", "iata" => "GTO", "icao" => "WAMG", "kota" => "Gorontalo", "provinsi" => "Gorontalo", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Syukuran Aminuddin Amir", "iata" => "LUW", "icao" => "WAMW", "kota" => "Luwuk", "provinsi" => "Sulawesi Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Mutiara SIS Al-Jufrie", "iata" => "PLW", "icao" => "WAFF", "kota" => "Palu", "provinsi" => "Sulawesi Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Hasanuddin", "iata" => "UPG", "icao" => "WAAA", "kota" => "Makassar", "provinsi" => "Sulawesi Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Haluoleo", "iata" => "KDI", "icao" => "WAWW", "kota" => "Kendari", "provinsi" => "Sulawesi Tenggara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Betoambari", "iata" => "BUW", "icao" => "WAWB", "kota" => "Bau-Bau", "provinsi" => "Sulawesi Tenggara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Aji Muhammad Sulaiman Sepinggan", "iata" => "BPN", "icao" => "WALL", "kota" => "Balikpapan", "provinsi" => "Kalimantan Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Aji Pangeran Tumenggung Pranoto", "iata" => "AAP", "icao" => "WALS", "kota" => "Samarinda", "provinsi" => "Kalimantan Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Juwata", "iata" => "TRK", "icao" => "WAQQ", "kota" => "Tarakan", "provinsi" => "Kalimantan Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Kalimarau", "iata" => "BEJ", "icao" => "WAQT", "kota" => "Berau", "provinsi" => "Kalimantan Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Syarif Kasim II", "iata" => "PKU", "icao" => "WIBB", "kota" => "Pekanbaru", "provinsi" => "Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Iskandar Muda", "iata" => "BTJ", "icao" => "WITT", "kota" => "Banda Aceh", "provinsi" => "Aceh", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Minangkabau", "iata" => "PDG", "icao" => "WIPT", "kota" => "Padang", "provinsi" => "Sumatera Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Kualanamu", "iata" => "KNO", "icao" => "WIMM", "kota" => "Medan", "provinsi" => "Sumatera Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Hang Nadim", "iata" => "BTH", "icao" => "WIDD", "kota" => "Batam", "provinsi" => "Kepulauan Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Soekarno-Hatta", "iata" => "CGK", "icao" => "WIII", "kota" => "Tangerang", "provinsi" => "Banten", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Halim Perdanakusuma", "iata" => "HLP", "icao" => "WIHH", "kota" => "Jakarta", "provinsi" => "DKI Jakarta", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Juanda", "iata" => "SUB", "icao" => "WARR", "kota" => "Surabaya", "provinsi" => "Jawa Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Ngurah Rai", "iata" => "DPS", "icao" => "WADD", "kota" => "Denpasar", "provinsi" => "Bali", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Hasanuddin", "iata" => "UPG", "icao" => "WAAA", "kota" => "Makassar", "provinsi" => "Sulawesi Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Kualanamu", "iata" => "KNO", "icao" => "WIMM", "kota" => "Medan", "provinsi" => "Sumatera Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sam Ratulangi", "iata" => "MDC", "icao" => "WAMM", "kota" => "Manado", "provinsi" => "Sulawesi Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Aji Muhammad Sulaiman Sepinggan", "iata" => "BPN", "icao" => "WALL", "kota" => "Balikpapan", "provinsi" => "Kalimantan Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Yogyakarta", "iata" => "YIA", "icao" => "WAHI", "kota" => "Kulon Progo", "provinsi" => "DI Yogyakarta", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Adisutjipto", "iata" => "JOG", "icao" => "WARJ", "kota" => "Yogyakarta", "provinsi" => "DI Yogyakarta", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Ahmad Yani", "iata" => "SRG", "icao" => "WAHS", "kota" => "Semarang", "provinsi" => "Jawa Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Adi Soemarmo", "iata" => "SOC", "icao" => "WARQ", "kota" => "Solo", "provinsi" => "Jawa Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Husein Sastranegara", "iata" => "BDO", "icao" => "WICC", "kota" => "Bandung", "provinsi" => "Jawa Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Kertajati", "iata" => "KJT", "icao" => "WICA", "kota" => "Majalengka", "provinsi" => "Jawa Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Iskandar Muda", "iata" => "BTJ", "icao" => "WITT", "kota" => "Banda Aceh", "provinsi" => "Aceh", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Syarif Kasim II", "iata" => "PKU", "icao" => "WIBB", "kota" => "Pekanbaru", "provinsi" => "Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Minangkabau", "iata" => "PDG", "icao" => "WIPT", "kota" => "Padang", "provinsi" => "Sumatera Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Mahmud Badaruddin II", "iata" => "PLM", "icao" => "WIPP", "kota" => "Palembang", "provinsi" => "Sumatera Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Radin Inten II", "iata" => "TKG", "icao" => "WILL", "kota" => "Bandar Lampung", "provinsi" => "Lampung", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Depati Amir", "iata" => "PGK", "icao" => "WIPK", "kota" => "Pangkal Pinang", "provinsi" => "Bangka Belitung", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Raja Haji Fisabilillah", "iata" => "TNJ", "icao" => "WIDN", "kota" => "Tanjung Pinang", "provinsi" => "Kepulauan Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Hang Nadim", "iata" => "BTH", "icao" => "WIDD", "kota" => "Batam", "provinsi" => "Kepulauan Riau", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Supadio", "iata" => "PNK", "icao" => "WIOO", "kota" => "Pontianak", "provinsi" => "Kalimantan Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Syamsudin Noor", "iata" => "BDJ", "icao" => "WAOO", "kota" => "Banjarmasin", "provinsi" => "Kalimantan Selatan", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Aji Muhammad Sulaiman Sepinggan", "iata" => "BPN", "icao" => "WALL", "kota" => "Balikpapan", "provinsi" => "Kalimantan Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Juwata", "iata" => "TRK", "icao" => "WAQQ", "kota" => "Tarakan", "provinsi" => "Kalimantan Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Mutiara SIS Al-Jufrie", "iata" => "PLW", "icao" => "WAFF", "kota" => "Palu", "provinsi" => "Sulawesi Tengah", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Haluoleo", "iata" => "KDI", "icao" => "WAWW", "kota" => "Kendari", "provinsi" => "Sulawesi Tenggara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Betoambari", "iata" => "BUW", "icao" => "WAWB", "kota" => "Bau-Bau", "provinsi" => "Sulawesi Tenggara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Babullah", "iata" => "TTE", "icao" => "WAMT", "kota" => "Ternate", "provinsi" => "Maluku Utara", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Pattimura", "iata" => "AMQ", "icao" => "WAPP", "kota" => "Ambon", "provinsi" => "Maluku", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Frans Kaisiepo", "iata" => "BIK", "icao" => "WABB", "kota" => "Biak", "provinsi" => "Papua", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sentani", "iata" => "DJJ", "icao" => "WAJJ", "kota" => "Jayapura", "provinsi" => "Papua", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional El Tari", "iata" => "KOE", "icao" => "WATT", "kota" => "Kupang", "provinsi" => "Nusa Tenggara Timur", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Lombok", "iata" => "LOP", "icao" => "WADL", "kota" => "Praya", "provinsi" => "Nusa Tenggara Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Sultan Muhammad Kaharuddin III", "iata" => "SWQ", "icao" => "WADS", "kota" => "Sumbawa Besar", "provinsi" => "Nusa Tenggara Barat", "jenis" => "Internasional"],
  ["nama" => "Bandar Udara Internasional Komodo", "iata" => "LBJ", "icao" => "WATO", "kota" => "Labuan Bajo", "provinsi" => "Nusa Tenggara Timur", "jenis" => "Internasional"]
];

?>  