<?php

$pesawatIndonesia = [
  ["nama" => "Boeing 737-800 NG", "operator" => "Garuda Indonesia", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-800 NG (Winglet)", "operator" => "Garuda Indonesia", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737 MAX 8", "operator" => "Garuda Indonesia", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A330-200", "operator" => "Garuda Indonesia", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A330-300", "operator" => "Garuda Indonesia", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A330-900neo", "operator" => "Garuda Indonesia", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 777-300ER", "operator" => "Garuda Indonesia", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "ATR 72-600", "operator" => "Garuda Indonesia (Explore Jet)", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Bombardier CRJ1000 NextGen", "operator" => "Garuda Indonesia (Explore Jet)", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-800 NG", "operator" => "Lion Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-900ER", "operator" => "Lion Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737 MAX 8", "operator" => "Lion Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737 MAX 9", "operator" => "Lion Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A330-300", "operator" => "Lion Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A330-900neo", "operator" => "Lion Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-800 NG", "operator" => "Batik Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-900ER", "operator" => "Batik Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A320-200", "operator" => "Batik Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A320neo", "operator" => "Batik Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A321neo", "operator" => "Batik Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "ATR 72-600", "operator" => "Wings Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "ATR 72-500", "operator" => "Wings Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-800 NG", "operator" => "Malindo Air (Lion Group)", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "ATR 72-600", "operator" => "Malindo Air (Lion Group)", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-800 NG", "operator" => "Thai Lion Air (Lion Group)", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A320-200", "operator" => "Citilink", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A320neo", "operator" => "Citilink", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A330-900neo", "operator" => "Citilink", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "ATR 72-600", "operator" => "Citilink", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-800 NG", "operator" => "Sriwijaya Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-900ER", "operator" => "Sriwijaya Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-500", "operator" => "Sriwijaya Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Sriwijaya Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "ATR 72-600", "operator" => "NAM Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-500", "operator" => "NAM Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A320-200", "operator" => "AirAsia Indonesia", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A320neo", "operator" => "AirAsia Indonesia", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A321neo", "operator" => "AirAsia Indonesia", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-800 NG", "operator" => "Super Air Jet", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A320-200", "operator" => "Super Air Jet", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-800 NG", "operator" => "TransNusa", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A320-200", "operator" => "TransNusa", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "COMAC ARJ21-700", "operator" => "TransNusa", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-800 NG", "operator" => "Pelita Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-500", "operator" => "Pelita Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "ATR 72-600", "operator" => "Pelita Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Trigana Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-400", "operator" => "Trigana Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "ATR 42-300", "operator" => "Trigana Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "ATR 72-500", "operator" => "Trigana Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Kalstar Aviation", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-500", "operator" => "Kalstar Aviation", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "ATR 72-500", "operator" => "Kalstar Aviation", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Xpress Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "ATR 42-300", "operator" => "Xpress Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "ATR 72-500", "operator" => "Xpress Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-500", "operator" => "Susi Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Cessna Grand Caravan 208B", "operator" => "Susi Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6 Porter", "operator" => "Susi Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "DHC-6 Twin Otter Series 400", "operator" => "Susi Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Jayawijaya Dirgantara", "kategori" => "Kargo", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-400", "operator" => "Jayawijaya Dirgantara", "kategori" => "Kargo", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-500", "operator" => "Jayawijaya Dirgantara", "kategori" => "Kargo", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-800 NG", "operator" => "Garuda Indonesia Cargo", "kategori" => "Kargo", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-400", "operator" => "Cardig Air", "kategori" => "Kargo", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Cardig Air", "kategori" => "Kargo", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Cardig Air", "kategori" => "Kargo", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Tri-MG Intra Asia Airlines", "kategori" => "Kargo", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Tri-MG Intra Asia Airlines", "kategori" => "Kargo", "negara" => "Indonesia"],
  ["nama" => "Fokker F27 Friendship", "operator" => "Merpati Nusantara Airlines", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Fokker F28 Fellowship", "operator" => "Merpati Nusantara Airlines", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Fokker 100", "operator" => "Merpati Nusantara Airlines", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Fokker 50", "operator" => "Merpati Nusantara Airlines", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Merpati Nusantara Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Merpati Nusantara Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-400", "operator" => "Merpati Nusantara Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-500", "operator" => "Merpati Nusantara Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "CASA CN-235", "operator" => "Merpati Nusantara Airlines", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Xian MA60", "operator" => "Merpati Nusantara Airlines", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Adam Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Adam Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-400", "operator" => "Adam Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-500", "operator" => "Adam Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Mandala Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-400", "operator" => "Mandala Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A320-200", "operator" => "Mandala Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Sempati Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Sempati Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Fokker F28", "operator" => "Sempati Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Bouraq Indonesia Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Bouraq Indonesia Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-400", "operator" => "Bouraq Indonesia Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-500", "operator" => "Bouraq Indonesia Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "BAe 146-200", "operator" => "Bouraq Indonesia Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "BAe 146-300", "operator" => "Bouraq Indonesia Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Fokker F28", "operator" => "Bouraq Indonesia Airlines", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Dirgantara Air Service", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "CASA CN-235", "operator" => "Dirgantara Air Service", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "DHC-6 Twin Otter", "operator" => "Dirgantara Air Service", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Cessna Grand Caravan 208B", "operator" => "Dirgantara Air Service", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "ATR 42-300", "operator" => "Indonesia Air Transport", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "ATR 72-500", "operator" => "Indonesia Air Transport", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Fokker F27", "operator" => "Indonesia Air Transport", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "BAe 146-200", "operator" => "Indonesia Air Transport", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Indonesia Air Transport", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "CASA C-212 Aviocar", "operator" => "Indonesia Air Transport", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6 Porter", "operator" => "Indonesia Air Transport", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "ATR 42-300", "operator" => "Air Regional", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "ATR 72-500", "operator" => "Air Regional", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Air Regional", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Fokker F28", "operator" => "Air Regional", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "BAe 146-100", "operator" => "Air Regional", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "DHC-6 Twin Otter", "operator" => "Air Regional", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Airmark Indonesia", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Fokker F28", "operator" => "Airmark Indonesia", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "BAe 146-200", "operator" => "Airmark Indonesia", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Star Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Star Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Fokker F28", "operator" => "Star Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "BAe 146-200", "operator" => "Star Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Jatayu Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Jatayu Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-400", "operator" => "Jatayu Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Fokker F28", "operator" => "Jatayu Airlines", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "BAe 146-200", "operator" => "Jatayu Airlines", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Bayu Indonesia Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Bayu Indonesia Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Fokker F28", "operator" => "Bayu Indonesia Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "BAe 146-200", "operator" => "Bayu Indonesia Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Awair International", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Awair International", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Airbus A300B4", "operator" => "Awair International", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "AOM Indonesia", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "AOM Indonesia", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-400", "operator" => "AOM Indonesia", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Air Pacific", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Air Pacific", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Fokker F28", "operator" => "Air Pacific", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "BAe 146-200", "operator" => "Air Pacific", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Bali Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Bali Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Fokker F28", "operator" => "Bali Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "BAe 146-200", "operator" => "Bali Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Liputan Udara", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-300", "operator" => "Liputan Udara", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Fokker F28", "operator" => "Liputan Udara", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "BAe 146-200", "operator" => "Liputan Udara", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Deraya Air Taxi", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Cessna Grand Caravan 208B", "operator" => "Deraya Air Taxi", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6 Porter", "operator" => "Deraya Air Taxi", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "DHC-6 Twin Otter", "operator" => "Deraya Air Taxi", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "CASA C-212 Aviocar", "operator" => "Deraya Air Taxi", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Nusantara Air Charter", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Cessna Grand Caravan 208B", "operator" => "Nusantara Air Charter", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6 Porter", "operator" => "Nusantara Air Charter", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "DHC-6 Twin Otter", "operator" => "Nusantara Air Charter", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Asco Nusa Air", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Cessna Grand Caravan 208B", "operator" => "Asco Nusa Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6 Porter", "operator" => "Asco Nusa Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "DHC-6 Twin Otter", "operator" => "Asco Nusa Air", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Sabang Merauke Air Charter", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Cessna Grand Caravan 208B", "operator" => "Sabang Merauke Air Charter", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6 Porter", "operator" => "Sabang Merauke Air Charter", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "DHC-6 Twin Otter", "operator" => "Sabang Merauke Air Charter", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Transwisata Prima Aviation", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Cessna Grand Caravan 208B", "operator" => "Transwisata Prima Aviation", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6 Porter", "operator" => "Transwisata Prima Aviation", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "DHC-6 Twin Otter", "operator" => "Transwisata Prima Aviation", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Marga Mandala Sakti", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Cessna Grand Caravan 208B", "operator" => "Marga Mandala Sakti", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6 Porter", "operator" => "Marga Mandala Sakti", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "DHC-6 Twin Otter", "operator" => "Marga Mandala Sakti", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Gatari Air Service", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Cessna Grand Caravan 208B", "operator" => "Gatari Air Service", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6 Porter", "operator" => "Gatari Air Service", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "DHC-6 Twin Otter", "operator" => "Gatari Air Service", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Pura Wisata Baruna", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Cessna Grand Caravan 208B", "operator" => "Pura Wisata Baruna", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6 Porter", "operator" => "Pura Wisata Baruna", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "DHC-6 Twin Otter", "operator" => "Pura Wisata Baruna", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "Dirgantara Air Service", "kategori" => "Komersial", "negara" => "Indonesia"],
  ["nama" => "Fokker F27", "operator" => "Dirgantara Air Service", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "CASA C-212 Aviocar", "operator" => "Dirgantara Air Service", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "DHC-6 Twin Otter", "operator" => "Dirgantara Air Service", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Cessna Grand Caravan 208B", "operator" => "Dirgantara Air Service", "kategori" => "Komersial Regional", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6 Porter", "operator" => "Dirgantara Air Service", "kategori" => "Komersial Regional", "negara" => "Indonesia"],

  // ==========================================================
  // PESAWAT MILITER TNI AU
  // ==========================================================
  ["nama" => "F-16 Fighting Falcon", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "F-16 Block 15 OCU", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "F-16 Block 25", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "F-16 Block 52ID", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "F-16 C/D Block 72", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "Sukhoi Su-27SK", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "Sukhoi Su-27SKM", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "Sukhoi Su-30MK", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "Sukhoi Su-30MKK", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "Sukhoi Su-30MK2", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "Hawk 100", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "Hawk 200", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "BAe Hawk Mk 109", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "BAe Hawk Mk 209", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "EMB-314 Super Tucano", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "T-50 Golden Eagle", "operator" => "TNI AU", "kategori" => "Militer Latih/Tempur", "negara" => "Indonesia"],
  ["nama" => "KT-1B Wongbee", "operator" => "TNI AU", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "T-34C Turbo Mentor", "operator" => "TNI AU", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "Grob G 120TP", "operator" => "TNI AU", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "Socata TB-10 Tobago", "operator" => "TNI AU", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna T-41 Mescalero", "operator" => "TNI AU", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "Lockheed C-130 Hercules", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Lockheed C-130B Hercules", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Lockheed C-130H Hercules", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Lockheed C-130J Super Hercules", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Lockheed L-100-30 Hercules", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "CASA C-212 Aviocar", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "CASA CN-235", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "CASA CN-235-220", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "CASA CN-295", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Fokker F27 Friendship", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Fokker F28 Fellowship", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-400", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-500", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Airbus A400M Atlas", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Antonov An-32", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Antonov An-26", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Antonov An-12", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Ilyushin Il-76", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing 707", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing 727", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "DHC-5 Buffalo", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "NC-212 Aviocar", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Aermacchi MB-339", "operator" => "TNI AU", "kategori" => "Militer Latih/Tempur", "negara" => "Indonesia"],
  ["nama" => "BAe Hawk 53", "operator" => "TNI AU", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "Lockheed Martin C-130J-30", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Dassault Mirage 2000", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "Dassault Rafale", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "KAI KF-21 Boramae", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "Boeing AH-64E Apache", "operator" => "TNI AD", "kategori" => "Militer Helikopter Serang", "negara" => "Indonesia"],
  ["nama" => "Mil Mi-35P", "operator" => "TNI AD", "kategori" => "Militer Helikopter Serang", "negara" => "Indonesia"],
  ["nama" => "Mil Mi-17", "operator" => "TNI AD", "kategori" => "Militer Helikopter Angkut", "negara" => "Indonesia"],
  ["nama" => "Mil Mi-8", "operator" => "TNI AD", "kategori" => "Militer Helikopter Angkut", "negara" => "Indonesia"],
  ["nama" => "Bell 412", "operator" => "TNI AD", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell UH-1H Iroquois", "operator" => "TNI AD", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Boeing CH-47 Chinook", "operator" => "TNI AD", "kategori" => "Militer Helikopter Angkut", "negara" => "Indonesia"],
  ["nama" => "Eurocopter Fennec", "operator" => "TNI AD", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Hughes 269", "operator" => "TNI AD", "kategori" => "Militer Helikopter Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 172", "operator" => "TNI AD", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 182", "operator" => "TNI AD", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "CASA C-212 Aviocar", "operator" => "TNI AD", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "NC-212 Aviocar", "operator" => "TNI AD", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Antonov An-32", "operator" => "TNI AD", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "CASA CN-235", "operator" => "TNI AD", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Britten-Norman Islander", "operator" => "TNI AD", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "PAC CT/4 Airtrainer", "operator" => "TNI AU", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "SIAI-Marchetti SF.260", "operator" => "TNI AU", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "Lockheed T-33 Shooting Star", "operator" => "TNI AU", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "North American T-6 Texan", "operator" => "TNI AU", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "North American P-51 Mustang", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "CAC Sabre", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "MiG-15", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "MiG-17", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "MiG-19", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "MiG-21", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "Lockheed F-104 Starfighter", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "Northrop F-5 Tiger II", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "A-4 Skyhawk", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "OV-10 Bronco", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "Rockwell OV-10F Bronco", "operator" => "TNI AU", "kategori" => "Militer Tempur", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200 Surveiller", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "CASA CN-235 MPA", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "CASA CN-235 Persuader", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-800 MPA", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Airbus C295 MPA", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Beechcraft King Air 350i", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Britten-Norman BN-2 Islander", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "CASA C-212 MPA", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Fokker F27 Maritime", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "NC-212 MPA", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-2X9 Surveiller", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Lockheed C-130H-30 Hercules", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Lockheed C-130J-30 Super Hercules", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "CASA CN-235-100", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "CASA CN-235-220 MPA", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "CASA C-295", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "CASA C-295 MPA", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-800", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-400", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-500", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Fokker F28-1000", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Fokker F28-3000", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Fokker F27-400M", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Fokker F27-500", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Fokker F27-600", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Fokker F27-700", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Fokker F27 Maritime Enforcer", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Fokker F28-1000C", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Fokker F28-3000C", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing 707-300C", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing 727-100", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing 727-200", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Lockheed L-100-30", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Lockheed L-100-20", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Lockheed C-130B", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Lockheed C-130H", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Lockheed C-130J", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Lockheed C-130J-30", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Airbus A400M", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Antonov An-124 Ruslan", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Antonov An-225 Mriya", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Ilyushin Il-76MD", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Ilyushin Il-76TD", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Ilyushin Il-78 Midas", "operator" => "TNI AU", "kategori" => "Militer Tanker", "negara" => "Indonesia"],
  ["nama" => "Lockheed KC-130 Hercules", "operator" => "TNI AU", "kategori" => "Militer Tanker", "negara" => "Indonesia"],
  ["nama" => "Boeing KC-135 Stratotanker", "operator" => "TNI AU", "kategori" => "Militer Tanker", "negara" => "Indonesia"],
  ["nama" => "Airbus A330 MRTT", "operator" => "TNI AU", "kategori" => "Militer Tanker", "negara" => "Indonesia"],
  ["nama" => "Boeing E-7 Wedgetail", "operator" => "TNI AU", "kategori" => "Militer AEW&C", "negara" => "Indonesia"],
  ["nama" => "Embraer R-99", "operator" => "TNI AU", "kategori" => "Militer AEW&C", "negara" => "Indonesia"],
  ["nama" => "Saab 340 AEW&C", "operator" => "TNI AU", "kategori" => "Militer AEW&C", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200 AEW&C", "operator" => "TNI AU", "kategori" => "Militer AEW&C", "negara" => "Indonesia"],
  ["nama" => "CASA CN-235 AEW&C", "operator" => "TNI AU", "kategori" => "Militer AEW&C", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-800 AEW&C", "operator" => "TNI AU", "kategori" => "Militer AEW&C", "negara" => "Indonesia"],
  ["nama" => "Airbus C295 AEW&C", "operator" => "TNI AU", "kategori" => "Militer AEW&C", "negara" => "Indonesia"],
  ["nama" => "Boeing P-8 Poseidon", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-800 MPA", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "CASA CN-235 MPA", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "CASA C-295 MPA", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Beechcraft King Air 350i MPA", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Britten-Norman BN-2T Turbine Islander", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "CASA C-212 MPA", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Fokker F27 Maritime", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "NC-212 MPA", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-2X9 Surveiller", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Lockheed C-130H-30", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Lockheed C-130J-30", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "CASA CN-235-100", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "CASA CN-235-220 MPA", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "CASA C-295", "operator" => "TNI AU", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "CASA C-295 MPA", "operator" => "TNI AU", "kategori" => "Militer Patroli", "negara" => "Indonesia"],

  // ==========================================================
  // PESAWAT MILITER TNI AL (PENERBAL)
  // ==========================================================
  ["nama" => "CASA C-212 Aviocar", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "CASA CN-235", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "CASA CN-235 MPA", "operator" => "TNI AL", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "CASA C-295", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "CASA C-295 MPA", "operator" => "TNI AL", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "NC-212 Aviocar", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "NC-212 MPA", "operator" => "TNI AL", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Fokker F27 Maritime", "operator" => "TNI AL", "kategori" => "Militer Patroli", "negara" => "Indonesia"],
  ["nama" => "Fokker F28", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-200", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-400", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-500", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-800", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing 737-900ER", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Airbus A320", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Airbus A330", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Lockheed C-130 Hercules", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Lockheed C-130B Hercules", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Lockheed C-130H Hercules", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Lockheed C-130J Super Hercules", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Antonov An-26", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Antonov An-32", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Ilyushin Il-76", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "DHC-5 Buffalo", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Britten-Norman Islander", "operator" => "TNI AL", "kategori" => "Militer Angkut", "negara" => "Indonesia"],
  ["nama" => "Cessna 172", "operator" => "TNI AL", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 182", "operator" => "TNI AL", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "Socata TB-9 Tampico", "operator" => "TNI AL", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "Socata TB-10 Tobago", "operator" => "TNI AL", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "Grob G 120TP", "operator" => "TNI AL", "kategori" => "Militer Latih", "negara" => "Indonesia"],
  ["nama" => "Bell 412", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell UH-1H Iroquois", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Mil Mi-2", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Mil Mi-8", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Mil Mi-17", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Eurocopter AS565 Panther", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Eurocopter EC120 Colibri", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Eurocopter EC135", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Eurocopter EC725 Caracal", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H225M Caracal", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H145", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H155", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Leonardo AW101", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Leonardo AW139", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Leonardo AW159 Wildcat", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Sikorsky S-70B Seahawk", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Sikorsky SH-60 Seahawk", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Westland Wasp", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Westland Lynx", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "MBB Bo 105", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 206 JetRanger", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 212", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 214", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 427", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 429", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 505 Jet Ranger X", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 407", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 412EP", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 412EPI", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell UH-1Y Venom", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell AH-1Z Viper", "operator" => "TNI AL", "kategori" => "Militer Helikopter Serang", "negara" => "Indonesia"],
  ["nama" => "Boeing AH-64E Apache", "operator" => "TNI AL", "kategori" => "Militer Helikopter Serang", "negara" => "Indonesia"],
  ["nama" => "Boeing CH-47 Chinook", "operator" => "TNI AL", "kategori" => "Militer Helikopter Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing MH-47G Chinook", "operator" => "TNI AL", "kategori" => "Militer Helikopter Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing AH-6 Little Bird", "operator" => "TNI AL", "kategori" => "Militer Helikopter Serang", "negara" => "Indonesia"],
  ["nama" => "Boeing MH-6 Little Bird", "operator" => "TNI AL", "kategori" => "Militer Helikopter Serang", "negara" => "Indonesia"],
  ["nama" => "Boeing CH-46 Sea Knight", "operator" => "TNI AL", "kategori" => "Militer Helikopter Angkut", "negara" => "Indonesia"],
  ["nama" => "Boeing V-22 Osprey", "operator" => "TNI AL", "kategori" => "Militer Helikopter Angkut", "negara" => "Indonesia"],
  ["nama" => "Sikorsky CH-53 Sea Stallion", "operator" => "TNI AL", "kategori" => "Militer Helikopter Angkut", "negara" => "Indonesia"],
  ["nama" => "Sikorsky CH-53E Super Stallion", "operator" => "TNI AL", "kategori" => "Militer Helikopter Angkut", "negara" => "Indonesia"],
  ["nama" => "Sikorsky MH-53E Sea Dragon", "operator" => "TNI AL", "kategori" => "Militer Helikopter Angkut", "negara" => "Indonesia"],
  ["nama" => "Sikorsky S-92", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Sikorsky S-76", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Sikorsky S-70", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "NHIndustries NH90", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H215", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H225", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H135", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H125", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H130", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H160", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H175", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H185", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H190", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H210", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H220", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H230", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H235", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H240", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H245", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H250", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H255", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H260", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H265", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H270", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H275", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H280", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H285", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H290", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H295", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H300", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H305", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H310", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H315", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H320", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H325", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H330", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H335", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H340", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H345", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H350", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H355", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H360", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H365", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H370", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H375", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H380", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H385", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H390", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H395", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H400", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H405", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H410", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H415", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H420", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H425", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H430", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H435", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H440", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H445", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H450", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H455", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H460", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H465", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H470", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H475", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H480", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H485", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H490", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H495", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H500", "operator" => "TNI AL", "kategori" => "Militer Helikopter", "negara" => "Indonesia"],

  // ==========================================================
  // PESAWAT LATIH / SEKOLAH PENERBANGAN
  // ==========================================================
  ["nama" => "Cessna 152", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 172 Skyhawk", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 172S Skyhawk SP", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 182 Skylane", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 206 Stationair", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 208 Caravan", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 208B Grand Caravan", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Piper PA-28 Cherokee", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Piper PA-28 Warrior", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Piper PA-28 Archer", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Piper PA-34 Seneca", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Piper PA-44 Seminole", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Piper PA-18 Super Cub", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Piper PA-31 Navajo", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Piper PA-42 Cheyenne", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Piper PA-46 Malibu", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Diamond DA20 Katana", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Diamond DA40 Diamond Star", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Diamond DA42 Twin Star", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Diamond DA62", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cirrus SR20", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cirrus SR22", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cirrus SF50 Vision Jet", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Beechcraft Bonanza G36", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Beechcraft Baron G58", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Beechcraft King Air C90", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Beechcraft King Air 200", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Beechcraft King Air 350", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Socata TB-9 Tampico", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Socata TB-10 Tobago", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Socata TB-20 Trinidad", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Socata TBM 700", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Socata TBM 850", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Socata TBM 900", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Socata TBM 930", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Socata TBM 940", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Socata TBM 960", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Grob G 115", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Grob G 120", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Grob G 120TP", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Slingsby T-67 Firefly", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Scottish Aviation Bulldog", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "CASA C-101 Aviojet", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Aermacchi SF-260", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Aermacchi MB-326", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Aermacchi MB-339", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "BAe Hawk", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "BAe Jet Provost", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna T-37 Tweet", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Northrop T-38 Talon", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "KAI T-50 Golden Eagle", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "KAI KT-1 Wongbee", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Embraer EMB-312 Tucano", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Embraer EMB-314 Super Tucano", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-7 Turbo Trainer", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-9", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-21", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-12", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-24", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6 Porter", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6 Turbo Porter", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/B2-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/B2-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/A-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/A-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/B-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/B-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/C-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/C-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/D-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/D-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/E-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/E-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/F-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/F-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/G-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/G-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/H-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/H-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/I-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/I-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/J-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/J-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/K-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/K-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/L-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/L-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/M-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/M-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/N-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/N-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/O-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/O-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/P-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/P-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/Q-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/Q-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/R-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/R-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/S-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/S-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/T-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/T-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/U-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/U-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/V-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/V-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/W-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/W-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/X-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/X-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/Y-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/Y-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/Z-H2", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Pilatus PC-6/Z-H4", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 172RG Cutlass", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 177 Cardinal", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 210 Centurion", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 310", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 337 Skymaster", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 340", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 402", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 414", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 421 Golden Eagle", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 425 Conquest I", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 441 Conquest II", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 500 Citation I", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 525 CitationJet", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 550 Citation II", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 560 Citation V", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 560XL Citation Excel", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 650 Citation III", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 680 Citation Sovereign", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],
  ["nama" => "Cessna 750 Citation X", "operator" => "Sekolah Penerbangan", "kategori" => "Latih", "negara" => "Indonesia"],

  // ==========================================================
  // HELIKOPTER SIPIL
  // ==========================================================
  ["nama" => "Bell 206 JetRanger", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 206 LongRanger", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 407", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 412", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 429", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 505 Jet Ranger X", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H125", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H130", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H135", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H145", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H155", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H175", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H215", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H225", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Leonardo AW109", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Leonardo AW119", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Leonardo AW139", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Leonardo AW169", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Leonardo AW189", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Sikorsky S-76", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Sikorsky S-92", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Robinson R22", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Robinson R44", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Robinson R66", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "MD Helicopters MD 500", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "MD Helicopters MD 600", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "MD Helicopters MD 902 Explorer", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Eurocopter AS350 Écureuil", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Eurocopter AS355 TwinStar", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Eurocopter EC120 Colibri", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Eurocopter EC130", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Eurocopter EC135", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Eurocopter EC145", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Eurocopter EC155", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Eurocopter EC225", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "MBB Bo 105", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "MBB BK 117", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Kawasaki BK 117", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Agusta A109", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Agusta A119 Koala", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "AgustaWestland AW101", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "AgustaWestland AW139", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "AgustaWestland AW159", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "NHIndustries NH90", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Kamov Ka-32", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Kamov Ka-226", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Mil Mi-8", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Mil Mi-17", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Mil Mi-26", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Mil Mi-171", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Mil Mi-172", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "PZL W-3 Sokół", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "PZL SW-4 Puszczyk", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Kaman K-MAX", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Sikorsky S-64 Skycrane", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Erickson S-64 Air Crane", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Boeing CH-47 Chinook", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Boeing Vertol CH-46 Sea Knight", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Sikorsky CH-53 Sea Stallion", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Sikorsky CH-54 Tarhe", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell AH-1 Cobra", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell UH-1 Iroquois", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell UH-1H Huey", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell UH-1N Twin Huey", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell UH-1Y Venom", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell AH-1Z Viper", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 214", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 214ST", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 222", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 230", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 430", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Bell 525 Relentless", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H160", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H175", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H225M", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H225M Caracal", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H215M", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H135M", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H145M", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H125M", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H130", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H120", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H140", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H150", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H155", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H165", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H170", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H180", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H185", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H190", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H195", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H200", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H205", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H210", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H220", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H230", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H240", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H245", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H250", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H255", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H260", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H265", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H270", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H275", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H280", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H285", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H290", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H295", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H300", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H305", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H310", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H315", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H320", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H325", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H330", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H335", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H340", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H345", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H350", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H355", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H360", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H365", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H370", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H375", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H380", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H385", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H390", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H395", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H400", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H405", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H410", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H415", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H420", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H425", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H430", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H435", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H440", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H445", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H450", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H455", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H460", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H465", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H470", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H475", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H480", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H485", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H490", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H495", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"],
  ["nama" => "Airbus H500", "operator" => "Sipil", "kategori" => "Helikopter", "negara" => "Indonesia"]
];

?>