const plateCodes = [
  { code: "A", region: "Banten" },
  { code: "AA", region: "Magelang (Jawa Tengah)" },
  { code: "AB", region: "Yogyakarta (DIY)" },
  { code: "AD", region: "Surakarta (Jawa Tengah)" },
  { code: "AE", region: "Madiun (Jawa Timur)" },
  { code: "AG", region: "Kediri (Jawa Timur)" },
  { code: "B", region: "Jakarta (DKI)" },
  { code: "BA", region: "Sumatera Barat" },
  { code: "BB", region: "Sumatera Utara (Tebing Tinggi)" },
  { code: "BD", region: "Bengkulu" },
  { code: "BE", region: "Lampung" },
  { code: "BG", region: "Sumatera Selatan" },
  { code: "BH", region: "Jambi" },
  { code: "BK", region: "Sumatera Utara (Medan)" },
  { code: "BL", region: "Aceh" },
  { code: "BM", region: "Riau (Pekanbaru)" },
  { code: "BN", region: "Kepulauan Riau (Batam)" },
  { code: "BP", region: "Bangka Belitung" },
  { code: "D", region: "Bandung (Jawa Barat)" },
  { code: "DA", region: "Kalimantan Selatan" },
  { code: "DB", region: "Sulawesi Utara" },
  { code: "DC", region: "Sulawesi Barat" },
  { code: "DD", region: "Sulawesi Selatan" },
  { code: "DE", region: "Maluku" },
  { code: "DG", region: "Maluku Utara" },
  { code: "DK", region: "Bali" },
  { code: "DM", region: "Gorontalo" },
  { code: "DN", region: "Sulawesi Tengah" },
  { code: "DT", region: "Sulawesi Tenggara" },
  { code: "E", region: "Cirebon (Jawa Barat)" },
  { code: "EA", region: "Nusa Tenggara Barat" },
  { code: "EB", region: "Nusa Tenggara Timur" },
  { code: "F", region: "Bogor (Jawa Barat)" },
  { code: "G", region: "Tegal (Jawa Tengah)" },
  { code: "H", region: "Semarang (Jawa Tengah)" },
  { code: "K", region: "Pati (Jawa Tengah)" },
  { code: "KB", region: "Kalimantan Barat" },
  { code: "KH", region: "Kalimantan Tengah" },
  { code: "KT", region: "Kalimantan Timur" },
  { code: "KU", region: "Kalimantan Utara" },
  { code: "L", region: "Surabaya (Jawa Timur)" },
  { code: "M", region: "Madura (Jawa Timur)" },
  { code: "N", region: "Malang (Jawa Timur)" },
  { code: "P", region: "Jember (Jawa Timur)" },
  { code: "PA", region: "Papua" },
  { code: "PB", region: "Papua Barat" },
  { code: "R", region: "Banyumas (Jawa Tengah)" },
  { code: "S", region: "Bojonegoro (Jawa Timur)" },
  { code: "W", region: "Sidoarjo (Jawa Timur)" }
];