-- ============================================================
-- DATABASE: AI MODELS
-- File: model_ai.sql
-- Konversi lengkap dari php.txt
-- ============================================================

DROP TABLE IF EXISTS model_ai;

CREATE TABLE model_ai (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    pengembang VARCHAR(255),
    jenis VARCHAR(255),
    modalitas VARCHAR(255),
    rilis YEAR,
    lisensi VARCHAR(50),
    INDEX idx_nama (nama),
    INDEX idx_pengembang (pengembang),
    INDEX idx_jenis (jenis),
    INDEX idx_lisensi (lisensi)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==================== LARGE LANGUAGE MODEL (LLM) - PROPRIETARY ====================
INSERT INTO model_ai (nama, pengembang, jenis, modalitas, rilis, lisensi) VALUES
('GPT-4', 'OpenAI', 'LLM', 'Teks, Gambar', 2023, 'Proprietary'),
('GPT-4 Turbo', 'OpenAI', 'LLM', 'Teks, Gambar', 2023, 'Proprietary'),
('GPT-4o', 'OpenAI', 'LLM Multimodal', 'Teks, Gambar, Audio, Video', 2024, 'Proprietary'),
('GPT-4o mini', 'OpenAI', 'LLM Multimodal', 'Teks, Gambar, Audio, Video', 2024, 'Proprietary'),
('GPT-4.1', 'OpenAI', 'LLM', 'Teks, Gambar', 2025, 'Proprietary'),
('GPT-4.1 mini', 'OpenAI', 'LLM', 'Teks, Gambar', 2025, 'Proprietary'),
('GPT-4.1 nano', 'OpenAI', 'LLM', 'Teks, Gambar', 2025, 'Proprietary'),
('GPT-4.5', 'OpenAI', 'LLM', 'Teks, Gambar', 2025, 'Proprietary'),
('GPT-5', 'OpenAI', 'LLM', 'Teks, Gambar, Audio, Video', 2025, 'Proprietary'),
('GPT-5 mini', 'OpenAI', 'LLM', 'Teks, Gambar', 2025, 'Proprietary'),
('GPT-5 nano', 'OpenAI', 'LLM', 'Teks, Gambar', 2025, 'Proprietary'),
('o1', 'OpenAI', 'LLM Reasoning', 'Teks, Gambar', 2024, 'Proprietary'),
('o1-mini', 'OpenAI', 'LLM Reasoning', 'Teks', 2024, 'Proprietary'),
('o1-preview', 'OpenAI', 'LLM Reasoning', 'Teks', 2024, 'Proprietary'),
('o1-pro', 'OpenAI', 'LLM Reasoning', 'Teks, Gambar', 2025, 'Proprietary'),
('o3', 'OpenAI', 'LLM Reasoning', 'Teks, Gambar', 2025, 'Proprietary'),
('o3-mini', 'OpenAI', 'LLM Reasoning', 'Teks', 2025, 'Proprietary'),
('o3-pro', 'OpenAI', 'LLM Reasoning', 'Teks, Gambar', 2025, 'Proprietary'),
('o4-mini', 'OpenAI', 'LLM Reasoning', 'Teks, Gambar', 2025, 'Proprietary'),
('GPT-3.5 Turbo', 'OpenAI', 'LLM', 'Teks', 2023, 'Proprietary'),
('GPT-3', 'OpenAI', 'LLM', 'Teks', 2020, 'Proprietary'),
('GPT-2', 'OpenAI', 'LLM', 'Teks', 2019, 'Open Source'),
('GPT-1', 'OpenAI', 'LLM', 'Teks', 2018, 'Open Source'),
('Claude 3 Opus', 'Anthropic', 'LLM', 'Teks, Gambar', 2024, 'Proprietary'),
('Claude 3 Sonnet', 'Anthropic', 'LLM', 'Teks, Gambar', 2024, 'Proprietary'),
('Claude 3 Haiku', 'Anthropic', 'LLM', 'Teks, Gambar', 2024, 'Proprietary'),
('Claude 3.5 Sonnet', 'Anthropic', 'LLM', 'Teks, Gambar', 2024, 'Proprietary'),
('Claude 3.5 Haiku', 'Anthropic', 'LLM', 'Teks, Gambar', 2024, 'Proprietary'),
('Claude 3.7 Sonnet', 'Anthropic', 'LLM', 'Teks, Gambar', 2025, 'Proprietary'),
('Claude 4 Opus', 'Anthropic', 'LLM', 'Teks, Gambar', 2025, 'Proprietary'),
('Claude 4 Sonnet', 'Anthropic', 'LLM', 'Teks, Gambar', 2025, 'Proprietary'),
('Claude 2', 'Anthropic', 'LLM', 'Teks', 2023, 'Proprietary'),
('Claude 1', 'Anthropic', 'LLM', 'Teks', 2023, 'Proprietary'),
('Gemini 1.0 Ultra', 'Google DeepMind', 'LLM Multimodal', 'Teks, Gambar, Audio, Video', 2023, 'Proprietary'),
('Gemini 1.0 Pro', 'Google DeepMind', 'LLM Multimodal', 'Teks, Gambar, Audio, Video', 2023, 'Proprietary'),
('Gemini 1.0 Nano', 'Google DeepMind', 'LLM Multimodal', 'Teks, Gambar', 2023, 'Proprietary'),
('Gemini 1.5 Pro', 'Google DeepMind', 'LLM Multimodal', 'Teks, Gambar, Audio, Video', 2024, 'Proprietary'),
('Gemini 1.5 Flash', 'Google DeepMind', 'LLM Multimodal', 'Teks, Gambar, Audio, Video', 2024, 'Proprietary'),
('Gemini 1.5 Flash-8B', 'Google DeepMind', 'LLM Multimodal', 'Teks, Gambar, Audio, Video', 2024, 'Proprietary'),
('Gemini 2.0 Flash', 'Google DeepMind', 'LLM Multimodal', 'Teks, Gambar, Audio, Video', 2024, 'Proprietary'),
('Gemini 2.0 Flash Thinking', 'Google DeepMind', 'LLM Reasoning', 'Teks, Gambar, Audio, Video', 2024, 'Proprietary'),
('Gemini 2.5 Pro', 'Google DeepMind', 'LLM Reasoning', 'Teks, Gambar, Audio, Video', 2025, 'Proprietary'),
('Gemini 2.5 Flash', 'Google DeepMind', 'LLM Multimodal', 'Teks, Gambar, Audio, Video', 2025, 'Proprietary'),
('Gemini 2.5 Flash-Lite', 'Google DeepMind', 'LLM Multimodal', 'Teks, Gambar, Audio, Video', 2025, 'Proprietary'),
('Gemini Ultra', 'Google DeepMind', 'LLM Multimodal', 'Teks, Gambar, Audio, Video', 2023, 'Proprietary'),
('Gemini Nano', 'Google DeepMind', 'LLM On-Device', 'Teks, Gambar', 2023, 'Proprietary'),
('PaLM 2', 'Google', 'LLM', 'Teks', 2023, 'Proprietary'),
('PaLM', 'Google', 'LLM', 'Teks', 2022, 'Proprietary'),
('LaMDA', 'Google', 'LLM', 'Teks', 2021, 'Proprietary'),
('BERT', 'Google', 'LLM', 'Teks', 2018, 'Open Source'),
('T5', 'Google', 'LLM', 'Teks', 2019, 'Open Source'),
('Gemma', 'Google', 'LLM', 'Teks', 2024, 'Open Source'),
('Gemma 2', 'Google', 'LLM', 'Teks', 2024, 'Open Source'),
('Gemma 3', 'Google', 'LLM', 'Teks, Gambar', 2025, 'Open Source'),
('Gemma 3n', 'Google', 'LLM Multimodal', 'Teks, Gambar, Audio, Video', 2025, 'Open Source'),
('LLaMA', 'Meta AI', 'LLM', 'Teks', 2023, 'Open Source'),
('LLaMA 2', 'Meta AI', 'LLM', 'Teks', 2023, 'Open Source'),
('LLaMA 3', 'Meta AI', 'LLM', 'Teks', 2024, 'Open Source'),
('LLaMA 3.1', 'Meta AI', 'LLM', 'Teks', 2024, 'Open Source'),
('LLaMA 3.2', 'Meta AI', 'LLM Multimodal', 'Teks, Gambar', 2024, 'Open Source'),
('LLaMA 3.3', 'Meta AI', 'LLM', 'Teks', 2024, 'Open Source'),
('LLaMA 4', 'Meta AI', 'LLM Multimodal', 'Teks, Gambar', 2025, 'Open Source'),
('Mistral 7B', 'Mistral AI', 'LLM', 'Teks', 2023, 'Open Source'),
('Mistral 8x7B', 'Mistral AI', 'LLM MoE', 'Teks', 2023, 'Open Source'),
('Mistral 8x22B', 'Mistral AI', 'LLM MoE', 'Teks', 2024, 'Open Source'),
('Mistral Large', 'Mistral AI', 'LLM', 'Teks', 2024, 'Proprietary'),
('Mistral Large 2', 'Mistral AI', 'LLM', 'Teks', 2024, 'Proprietary'),
('Mistral Medium', 'Mistral AI', 'LLM', 'Teks', 2023, 'Proprietary'),
('Mistral Small', 'Mistral AI', 'LLM', 'Teks', 2024, 'Open Source'),
('Mixtral 8x7B', 'Mistral AI', 'LLM MoE', 'Teks', 2023, 'Open Source'),
('Mixtral 8x22B', 'Mistral AI', 'LLM MoE', 'Teks', 2024, 'Open Source'),
('Codestral', 'Mistral AI', 'LLM Coding', 'Teks', 2024, 'Proprietary'),
('Mathstral', 'Mistral AI', 'LLM Math', 'Teks', 2024, 'Open Source'),
('Pixtral 12B', 'Mistral AI', 'LLM Multimodal', 'Teks, Gambar', 2024, 'Open Source'),
('Pixtral Large', 'Mistral AI', 'LLM Multimodal', 'Teks, Gambar', 2024, 'Proprietary'),
('Mistral NeMo', 'Mistral AI, NVIDIA', 'LLM', 'Teks', 2024, 'Open Source'),
('Command R', 'Cohere', 'LLM', 'Teks', 2024, 'Open Source'),
('Command R+', 'Cohere', 'LLM', 'Teks', 2024, 'Proprietary'),
('Command', 'Cohere', 'LLM', 'Teks', 2022, 'Proprietary'),
('Command Light', 'Cohere', 'LLM', 'Teks', 2023, 'Proprietary'),
('Aya 23', 'Cohere', 'LLM Multilingual', 'Teks', 2024, 'Open Source'),
('Aya 101', 'Cohere', 'LLM Multilingual', 'Teks', 2024, 'Open Source'),
('Grok-1', 'xAI', 'LLM', 'Teks', 2023, 'Open Source'),
('Grok-1.5', 'xAI', 'LLM', 'Teks', 2024, 'Proprietary'),
('Grok-1.5V', 'xAI', 'LLM Multimodal', 'Teks, Gambar', 2024, 'Proprietary'),
('Grok-2', 'xAI', 'LLM', 'Teks, Gambar', 2024, 'Proprietary'),
('Grok-2 mini', 'xAI', 'LLM', 'Teks, Gambar', 2024, 'Proprietary'),
('Grok-3', 'xAI', 'LLM', 'Teks, Gambar', 2025, 'Proprietary'),
('Grok-3 mini', 'xAI', 'LLM', 'Teks, Gambar', 2025, 'Proprietary'),
('Grok-4', 'xAI', 'LLM', 'Teks, Gambar', 2025, 'Proprietary'),
('DeepSeek-V2', 'DeepSeek', 'LLM MoE', 'Teks', 2024, 'Open Source'),
('DeepSeek-V3', 'DeepSeek', 'LLM MoE', 'Teks', 2024, 'Open Source'),
('DeepSeek-R1', 'DeepSeek', 'LLM Reasoning', 'Teks', 2025, 'Open Source'),
('DeepSeek-R1-Zero', 'DeepSeek', 'LLM Reasoning', 'Teks', 2025, 'Open Source'),
('DeepSeek-Coder', 'DeepSeek', 'LLM Coding', 'Teks', 2023, 'Open Source'),
('DeepSeek-Coder-V2', 'DeepSeek', 'LLM Coding', 'Teks', 2024, 'Open Source'),
('DeepSeek-VL', 'DeepSeek', 'LLM Multimodal', 'Teks, Gambar', 2024, 'Open Source'),
('DeepSeek-VL2', 'DeepSeek', 'LLM Multimodal', 'Teks, Gambar', 2024, 'Open Source'),
('DeepSeek-Math', 'DeepSeek', 'LLM Math', 'Teks', 2024, 'Open Source'),
('Qwen', 'Alibaba', 'LLM', 'Teks', 2023, 'Open Source'),
('Qwen 1.5', 'Alibaba', 'LLM', 'Teks', 2024, 'Open Source'),
('Qwen 2', 'Alibaba', 'LLM', 'Teks', 2024, 'Open Source'),
('Qwen 2.5', 'Alibaba', 'LLM', 'Teks', 2024, 'Open Source'),
('Qwen 3', 'Alibaba', 'LLM', 'Teks', 2025, 'Open Source'),
('Qwen-VL', 'Alibaba', 'LLM Multimodal', 'Teks, Gambar', 2024, 'Open Source'),
('Qwen2-VL', 'Alibaba', 'LLM Multimodal', 'Teks, Gambar, Video', 2024, 'Open Source'),
('Qwen2.5-VL', 'Alibaba', 'LLM Multimodal', 'Teks, Gambar, Video', 2025, 'Open Source'),
('Qwen-Audio', 'Alibaba', 'LLM Audio', 'Teks, Audio', 2024, 'Open Source'),
('Qwen2-Audio', 'Alibaba', 'LLM Audio', 'Teks, Audio', 2024, 'Open Source'),
('Qwen-Coder', 'Alibaba', 'LLM Coding', 'Teks', 2024, 'Open Source'),
('Qwen2.5-Coder', 'Alibaba', 'LLM Coding', 'Teks', 2024, 'Open Source'),
('Qwen-Math', 'Alibaba', 'LLM Math', 'Teks', 2024, 'Open Source'),
('Qwen2.5-Math', 'Alibaba', 'LLM Math', 'Teks', 2024, 'Open Source'),
('QwQ-32B', 'Alibaba', 'LLM Reasoning', 'Teks', 2024, 'Open Source'),
('QwQ-32B-Preview', 'Alibaba', 'LLM Reasoning', 'Teks', 2024, 'Open Source'),
('Yi', '01.AI', 'LLM', 'Teks', 2023, 'Open Source'),
('Yi-1.5', '01.AI', 'LLM', 'Teks', 2024, 'Open Source'),
('Yi-Large', '01.AI', 'LLM', 'Teks', 2024, 'Proprietary'),
('Yi-VL', '01.AI', 'LLM Multimodal', 'Teks, Gambar', 2024, 'Open Source'),
('Yi-Coder', '01.AI', 'LLM Coding', 'Teks', 2024, 'Open Source'),
('Phi-1', 'Microsoft', 'LLM', 'Teks', 2023, 'Open Source'),
('Phi-1.5', 'Microsoft', 'LLM', 'Teks', 2023, 'Open Source'),
('Phi-2', 'Microsoft', 'LLM', 'Teks', 2023, 'Open Source'),
('Phi-3', 'Microsoft', 'LLM', 'Teks', 2024, 'Open Source'),
('Phi-3.5', 'Microsoft', 'LLM', 'Teks', 2024, 'Open Source'),
('Phi-4', 'Microsoft', 'LLM', 'Teks', 2024, 'Open Source'),
('Phi-3 Vision', 'Microsoft', 'LLM Multimodal', 'Teks, Gambar', 2024, 'Open Source'),
('Phi-3.5 Vision', 'Microsoft', 'LLM Multimodal', 'Teks, Gambar', 2024, 'Open Source'),
('Orca', 'Microsoft', 'LLM', 'Teks', 2023, 'Open Source'),
('Orca 2', 'Microsoft', 'LLM', 'Teks', 2023, 'Open Source'),
('WizardLM', 'Microsoft', 'LLM', 'Teks', 2023, 'Open Source'),
('WizardLM-2', 'Microsoft', 'LLM', 'Teks', 2024, 'Open Source'),
('Titan', 'Amazon', 'LLM', 'Teks', 2023, 'Proprietary'),
('Titan Text G1', 'Amazon', 'LLM', 'Teks', 2023, 'Proprietary'),
('Titan Multimodal', 'Amazon', 'LLM Multimodal', 'Teks, Gambar', 2024, 'Proprietary'),
('Nova Micro', 'Amazon', 'LLM', 'Teks', 2024, 'Proprietary'),
('Nova Lite', 'Amazon', 'LLM Multimodal', 'Teks, Gambar, Video', 2024, 'Proprietary'),
('Nova Pro', 'Amazon', 'LLM Multimodal', 'Teks, Gambar, Video', 2024, 'Proprietary'),
('Nova Premier', 'Amazon', 'LLM Multimodal', 'Teks, Gambar, Video', 2024, 'Proprietary'),
('Nova Canvas', 'Amazon', 'Image Generation', 'Teks ke Gambar', 2024, 'Proprietary'),
('Nova Reel', 'Amazon', 'Video Generation', 'Teks ke Video', 2024, 'Proprietary'),
('Nova Sonic', 'Amazon', 'Speech', 'Audio', 2024, 'Proprietary'),
('Falcon 40B', 'TII', 'LLM', 'Teks', 2023, 'Open Source'),
('Falcon 180B', 'TII', 'LLM', 'Teks', 2023, 'Open Source'),
('Falcon 2', 'TII', 'LLM', 'Teks', 2024, 'Open Source'),
('Falcon 3', 'TII', 'LLM', 'Teks', 2024, 'Open Source'),
('Falcon-VL', 'TII', 'LLM Multimodal', 'Teks, Gambar', 2024, 'Open Source'),
('Jais', 'G42', 'LLM Arabic', 'Teks', 2023, 'Open Source'),
('Jais 30B', 'G42', 'LLM Arabic', 'Teks', 2023, 'Open Source'),
('Sarvam 1', 'Sarvam AI', 'LLM Hindi', 'Teks', 2024, 'Open Source'),
('Airavata', 'AI4Bharat', 'LLM Hindi', 'Teks', 2024, 'Open Source'),
('Sahabat-AI', 'GoTo, Indosat', 'LLM Indonesia', 'Teks', 2024, 'Open Source'),
('Komodo-7B', 'Yellow.ai', 'LLM Indonesia', 'Teks', 2024, 'Open Source'),
('Cendol', 'IndoNLG', 'LLM Indonesia', 'Teks', 2023, 'Open Source'),
('Merak-7B', 'Ichsan2895', 'LLM Indonesia', 'Teks', 2024, 'Open Source'),
('SEA-LION', 'AI Singapore', 'LLM Asia Tenggara', 'Teks', 2023, 'Open Source'),
('SEA-LION v2', 'AI Singapore', 'LLM Asia Tenggara', 'Teks', 2024, 'Open Source'),
('SEA-LION v3', 'AI Singapore', 'LLM Asia Tenggara', 'Teks', 2025, 'Open Source'),
('Sailor', 'Sea AI Lab', 'LLM Asia Tenggara', 'Teks', 2024, 'Open Source'),
('Sailor2', 'Sea AI Lab', 'LLM Asia Tenggara', 'Teks', 2024, 'Open Source'),
('DBRX', 'Databricks', 'LLM MoE', 'Teks', 2024, 'Open Source'),
('Dolly', 'Databricks', 'LLM', 'Teks', 2023, 'Open Source'),
('Dolly 2.0', 'Databricks', 'LLM', 'Teks', 2023, 'Open Source'),
('MPT', 'MosaicML', 'LLM', 'Teks', 2023, 'Open Source'),
('MPT-7B', 'MosaicML', 'LLM', 'Teks', 2023, 'Open Source'),
('MPT-30B', 'MosaicML', 'LLM', 'Teks', 2023, 'Open Source'),
('RedPajama', 'Together AI', 'LLM', 'Teks', 2023, 'Open Source'),
('RedPajama-INCITE', 'Together AI', 'LLM', 'Teks', 2023, 'Open Source'),
('Vicuna', 'LMSYS', 'LLM', 'Teks', 2023, 'Open Source'),
('Vicuna-13B', 'LMSYS', 'LLM', 'Teks', 2023, 'Open Source'),
('Vicuna-33B', 'LMSYS', 'LLM', 'Teks', 2023, 'Open Source'),
('Alpaca', 'Stanford', 'LLM', 'Teks', 2023, 'Open Source'),
('Vicuna', 'Stanford', 'LLM', 'Teks', 2023, 'Open Source'),
('Llama Guard', 'Meta AI', 'LLM Safety', 'Teks', 2023, 'Open Source'),
('Llama Guard 2', 'Meta AI', 'LLM Safety', 'Teks', 2024, 'Open Source'),
('Llama Guard 3', 'Meta AI', 'LLM Safety', 'Teks, Gambar', 2024, 'Open Source'),
('Code Llama', 'Meta AI', 'LLM Coding', 'Teks', 2023, 'Open Source'),
('Code Llama 70B', 'Meta AI', 'LLM Coding', 'Teks', 2024, 'Open Source'),
('Code Llama Python', 'Meta AI', 'LLM Coding', 'Teks', 2024, 'Open Source'),
('StarCoder', 'BigCode', 'LLM Coding', 'Teks', 2023, 'Open Source'),
('StarCoder 2', 'BigCode', 'LLM Coding', 'Teks', 2024, 'Open Source'),
('StarCoderBase', 'BigCode', 'LLM Coding', 'Teks', 2023, 'Open Source'),
('SantaCoder', 'BigCode', 'LLM Coding', 'Teks', 2022, 'Open Source'),
('WizardCoder', 'WizardLM', 'LLM Coding', 'Teks', 2023, 'Open Source'),
('Phind-CodeLlama', 'Phind', 'LLM Coding', 'Teks', 2023, 'Open Source'),
('CodeGen', 'Salesforce', 'LLM Coding', 'Teks', 2022, 'Open Source'),
('CodeT5', 'Salesforce', 'LLM Coding', 'Teks', 2021, 'Open Source'),
('CodeT5+', 'Salesforce', 'LLM Coding', 'Teks', 2023, 'Open Source'),
('InstructGPT', 'OpenAI', 'LLM', 'Teks', 2022, 'Proprietary'),
('ChatGPT', 'OpenAI', 'LLM Chatbot', 'Teks, Gambar, Audio', 2022, 'Proprietary'),
('Bard', 'Google', 'LLM Chatbot', 'Teks, Gambar', 2023, 'Proprietary'),
('Copilot', 'Microsoft', 'LLM Coding', 'Teks', 2021, 'Proprietary'),
('GitHub Copilot', 'GitHub', 'LLM Coding', 'Teks', 2021, 'Proprietary'),
('Copilot Chat', 'Microsoft', 'LLM Coding', 'Teks', 2023, 'Proprietary'),
('Amazon Q', 'AWS', 'LLM Assistant', 'Teks', 2023, 'Proprietary'),
('Amazon Q Developer', 'AWS', 'LLM Coding', 'Teks', 2024, 'Proprietary'),
('Gemini Code Assist', 'Google', 'LLM Coding', 'Teks', 2024, 'Proprietary'),
('Cursor', 'Cursor', 'LLM Coding', 'Teks', 2023, 'Proprietary'),
('Devin', 'Cognition', 'AI Agent Coding', 'Teks', 2024, 'Proprietary'),
('Replit Agent', 'Replit', 'AI Agent Coding', 'Teks', 2024, 'Proprietary'),
('Claude Code', 'Anthropic', 'AI Agent Coding', 'Teks', 2025, 'Proprietary'),
('OpenAI Codex', 'OpenAI', 'LLM Coding', 'Teks', 2021, 'Proprietary'),
('Codex CLI', 'OpenAI', 'AI Agent Coding', 'Teks', 2025, 'Proprietary'),
('Ollama', 'Ollama', 'LLM Runtime', 'Teks', 2023, 'Open Source'),
('LM Studio', 'LM Studio', 'LLM Runtime', 'Teks', 2023, 'Proprietary'),
('vLLM', 'Berkeley', 'LLM Runtime', 'Teks', 2023, 'Open Source'),
('llama.cpp', 'Georgi Gerganov', 'LLM Runtime', 'Teks', 2023, 'Open Source'),
('Text Generation Inference', 'Hugging Face', 'LLM Runtime', 'Teks', 2023, 'Open Source'),
('TensorRT-LLM', 'NVIDIA', 'LLM Runtime', 'Teks', 2023, 'Open Source'),
('OpenLLM', 'BentoML', 'LLM Runtime', 'Teks', 2023, 'Open Source'),
('LocalAI', 'mudler', 'LLM Runtime', 'Teks, Gambar, Audio', 2023, 'Open Source'),

-- ==================== TEXT-TO-IMAGE ====================
('DALL-E', 'OpenAI', 'Text-to-Image', 'Teks ke Gambar', 2021, 'Proprietary'),
('DALL-E 2', 'OpenAI', 'Text-to-Image', 'Teks ke Gambar', 2022, 'Proprietary'),
('DALL-E 3', 'OpenAI', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Proprietary'),
('Stable Diffusion 1.4', 'Stability AI', 'Text-to-Image', 'Teks ke Gambar', 2022, 'Open Source'),
('Stable Diffusion 1.5', 'Stability AI', 'Text-to-Image', 'Teks ke Gambar', 2022, 'Open Source'),
('Stable Diffusion 2.0', 'Stability AI', 'Text-to-Image', 'Teks ke Gambar', 2022, 'Open Source'),
('Stable Diffusion 2.1', 'Stability AI', 'Text-to-Image', 'Teks ke Gambar', 2022, 'Open Source'),
('Stable Diffusion XL', 'Stability AI', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Open Source'),
('Stable Diffusion XL Turbo', 'Stability AI', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Open Source'),
('Stable Diffusion 3', 'Stability AI', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('Stable Diffusion 3 Medium', 'Stability AI', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('Stable Diffusion 3.5', 'Stability AI', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('Stable Diffusion 3.5 Large', 'Stability AI', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('Stable Diffusion 3.5 Medium', 'Stability AI', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('SDXL Turbo', 'Stability AI', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Open Source'),
('Stable Cascade', 'Stability AI', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('Midjourney v1', 'Midjourney', 'Text-to-Image', 'Teks ke Gambar', 2022, 'Proprietary'),
('Midjourney v2', 'Midjourney', 'Text-to-Image', 'Teks ke Gambar', 2022, 'Proprietary'),
('Midjourney v3', 'Midjourney', 'Text-to-Image', 'Teks ke Gambar', 2022, 'Proprietary'),
('Midjourney v4', 'Midjourney', 'Text-to-Image', 'Teks ke Gambar', 2022, 'Proprietary'),
('Midjourney v5', 'Midjourney', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Proprietary'),
('Midjourney v5.1', 'Midjourney', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Proprietary'),
('Midjourney v5.2', 'Midjourney', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Proprietary'),
('Midjourney v6', 'Midjourney', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Proprietary'),
('Midjourney v6.1', 'Midjourney', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Proprietary'),
('Midjourney v7', 'Midjourney', 'Text-to-Image', 'Teks ke Gambar', 2025, 'Proprietary'),
('Imagen', 'Google', 'Text-to-Image', 'Teks ke Gambar', 2022, 'Proprietary'),
('Imagen 2', 'Google', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Proprietary'),
('Imagen 3', 'Google', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Proprietary'),
('Imagen 4', 'Google', 'Text-to-Image', 'Teks ke Gambar', 2025, 'Proprietary'),
('Parti', 'Google', 'Text-to-Image', 'Teks ke Gambar', 2022, 'Proprietary'),
('Muse', 'Google', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Proprietary'),
('Firefly', 'Adobe', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Proprietary'),
('Firefly Image 2', 'Adobe', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Proprietary'),
('Firefly Image 3', 'Adobe', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Proprietary'),
('Flux.1 Pro', 'Black Forest Labs', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Proprietary'),
('Flux.1 Dev', 'Black Forest Labs', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('Flux.1 Schnell', 'Black Forest Labs', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('Flux.1.1 Pro', 'Black Forest Labs', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Proprietary'),
('Flux.1 Kontext', 'Black Forest Labs', 'Text-to-Image', 'Teks ke Gambar', 2025, 'Proprietary'),
('Ideogram', 'Ideogram', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Proprietary'),
('Ideogram 2.0', 'Ideogram', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Proprietary'),
('Ideogram 3.0', 'Ideogram', 'Text-to-Image', 'Teks ke Gambar', 2025, 'Proprietary'),
('Recraft V3', 'Recraft', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Proprietary'),
('Leonardo AI', 'Leonardo', 'Text-to-Image', 'Teks ke Gambar', 2022, 'Proprietary'),
('Playground AI', 'Playground', 'Text-to-Image', 'Teks ke Gambar', 2022, 'Proprietary'),
('Kandinsky', 'Sber AI', 'Text-to-Image', 'Teks ke Gambar', 2022, 'Open Source'),
('Kandinsky 2.1', 'Sber AI', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Open Source'),
('Kandinsky 2.2', 'Sber AI', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Open Source'),
('Kandinsky 3', 'Sber AI', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Open Source'),
('DeepFloyd IF', 'DeepFloyd', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Open Source'),
('CogView', 'Tsinghua', 'Text-to-Image', 'Teks ke Gambar', 2021, 'Open Source'),
('CogView 2', 'Tsinghua', 'Text-to-Image', 'Teks ke Gambar', 2022, 'Open Source'),
('CogView 3', 'Tsinghua', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Open Source'),
('CogView 4', 'Tsinghua', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('Wuerstchen', 'Stability AI', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Open Source'),
('PixArt-Alpha', 'Huawei', 'Text-to-Image', 'Teks ke Gambar', 2023, 'Open Source'),
('PixArt-Sigma', 'Huawei', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('SDXL Lightning', 'ByteDance', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('Hunyuan-DiT', 'Tencent', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('HunyuanImage 2.0', 'Tencent', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('HunyuanImage 3.0', 'Tencent', 'Text-to-Image', 'Teks ke Gambar', 2025, 'Open Source'),
('Lumina-T2X', 'Shanghai AI Lab', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('Lumina-Next', 'Shanghai AI Lab', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('Lumina-Image 2.0', 'Shanghai AI Lab', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('Sana', 'NVIDIA', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('Kolors', 'Kuaishou', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('Playground v2.5', 'Playground', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Open Source'),
('Playground v3', 'Playground', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Proprietary'),
('Seedream 2.0', 'ByteDance', 'Text-to-Image', 'Teks ke Gambar', 2024, 'Proprietary'),
('Seedream 3.0', 'ByteDance', 'Text-to-Image', 'Teks ke Gambar', 2025, 'Proprietary'),
('Seedream 4.0', 'ByteDance', 'Text-to-Image', 'Teks ke Gambar', 2025, 'Proprietary'),
('GPT Image 1', 'OpenAI', 'Text-to-Image', 'Teks ke Gambar', 2025, 'Proprietary'),
('GPT Image 1 Mini', 'OpenAI', 'Text-to-Image', 'Teks ke Gambar', 2025, 'Proprietary'),
('Nano Banana (Gemini 2.5 Flash Image)', 'Google', 'Image Editing', 'Teks, Gambar', 2025, 'Proprietary'),
('Qwen-Image', 'Alibaba', 'Text-to-Image', 'Teks ke Gambar', 2025, 'Open Source'),

-- ==================== TEXT-TO-VIDEO ====================
('Sora', 'OpenAI', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('Sora Turbo', 'OpenAI', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('Sora 2', 'OpenAI', 'Text-to-Video', 'Teks, Gambar, Video', 2025, 'Proprietary'),
('Veo', 'Google', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('Veo 2', 'Google', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('Veo 3', 'Google', 'Text-to-Video', 'Teks, Gambar, Audio', 2025, 'Proprietary'),
('Veo 3 Fast', 'Google', 'Text-to-Video', 'Teks, Gambar, Audio', 2025, 'Proprietary'),
('Imagen Video', 'Google', 'Text-to-Video', 'Teks ke Video', 2022, 'Proprietary'),
('Lumiere', 'Google', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('Runway Gen-1', 'Runway', 'Text-to-Video', 'Teks ke Video', 2023, 'Proprietary'),
('Runway Gen-2', 'Runway', 'Text-to-Video', 'Teks ke Video', 2023, 'Proprietary'),
('Runway Gen-3 Alpha', 'Runway', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('Runway Gen-3 Alpha Turbo', 'Runway', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('Runway Gen-4', 'Runway', 'Text-to-Video', 'Teks, Gambar, Video', 2025, 'Proprietary'),
('Pika 1.0', 'Pika Labs', 'Text-to-Video', 'Teks ke Video', 2023, 'Proprietary'),
('Pika 1.5', 'Pika Labs', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('Pika 2.0', 'Pika Labs', 'Text-to-Video', 'Teks, Gambar, Video', 2024, 'Proprietary'),
('Stable Video Diffusion', 'Stability AI', 'Image-to-Video', 'Gambar ke Video', 2023, 'Open Source'),
('Stable Video Diffusion 1.1', 'Stability AI', 'Image-to-Video', 'Gambar ke Video', 2024, 'Open Source'),
('SVD XT 1.1', 'Stability AI', 'Image-to-Video', 'Gambar ke Video', 2024, 'Open Source'),
('Stable Video 4D', 'Stability AI', 'Video-to-Video 4D', 'Video ke Video 4D', 2024, 'Open Source'),
('CogVideo', 'Tsinghua', 'Text-to-Video', 'Teks ke Video', 2022, 'Open Source'),
('CogVideoX', 'Tsinghua', 'Text-to-Video', 'Teks ke Video', 2024, 'Open Source'),
('CogVideoX-2B', 'Tsinghua', 'Text-to-Video', 'Teks ke Video', 2024, 'Open Source'),
('CogVideoX-5B', 'Tsinghua', 'Text-to-Video', 'Teks ke Video', 2024, 'Open Source'),
('CogVideoX-1.5', 'Tsinghua', 'Text-to-Video', 'Teks ke Video', 2024, 'Open Source'),
('Mochi 1', 'Genmo', 'Text-to-Video', 'Teks ke Video', 2024, 'Open Source'),
('HunyuanVideo', 'Tencent', 'Text-to-Video', 'Teks ke Video', 2024, 'Open Source'),
('HunyuanVideo-I2V', 'Tencent', 'Image-to-Video', 'Gambar ke Video', 2025, 'Open Source'),
('LTX-Video', 'Lightricks', 'Text-to-Video', 'Teks ke Video', 2024, 'Open Source'),
('LTX-Video 0.9.5', 'Lightricks', 'Text-to-Video', 'Teks ke Video', 2024, 'Open Source'),
('Wan 2.1', 'Alibaba', 'Text-to-Video', 'Teks ke Video', 2025, 'Open Source'),
('Wan 2.2', 'Alibaba', 'Text-to-Video', 'Teks ke Video', 2025, 'Open Source'),
('Kling AI 1.0', 'Kuaishou', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('Kling AI 1.5', 'Kuaishou', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('Kling AI 1.6', 'Kuaishou', 'Text-to-Video', 'Teks, Gambar', 2025, 'Proprietary'),
('Kling AI 2.0', 'Kuaishou', 'Text-to-Video', 'Teks, Gambar', 2025, 'Proprietary'),
('Kling AI 2.1', 'Kuaishou', 'Text-to-Video', 'Teks, Gambar', 2025, 'Proprietary'),
('Luma Dream Machine', 'Luma AI', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('Luma Dream Machine 1.5', 'Luma AI', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('Luma Ray 2', 'Luma AI', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('Luma Ray 3', 'Luma AI', 'Text-to-Video', 'Teks, Gambar', 2025, 'Proprietary'),
('Minimax Hailuo', 'MiniMax', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('Minimax Hailuo 02', 'MiniMax', 'Text-to-Video', 'Teks ke Video', 2025, 'Proprietary'),
('PixVerse V3', 'PixVerse', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('PixVerse V4', 'PixVerse', 'Text-to-Video', 'Teks ke Video', 2025, 'Proprietary'),
('PixVerse V4.5', 'PixVerse', 'Text-to-Video', 'Teks ke Video', 2025, 'Proprietary'),
('Seedance 1.0', 'ByteDance', 'Text-to-Video', 'Teks ke Video', 2025, 'Proprietary'),
('Seaweed-7B', 'ByteDance', 'Text-to-Video', 'Teks ke Video', 2025, 'Open Source'),
('Open-Sora', 'ColossalAI', 'Text-to-Video', 'Teks ke Video', 2024, 'Open Source'),
('Open-Sora 1.2', 'ColossalAI', 'Text-to-Video', 'Teks ke Video', 2024, 'Open Source'),
('Open-Sora 2.0', 'ColossalAI', 'Text-to-Video', 'Teks ke Video', 2025, 'Open Source'),
('Open-Sora Plan', 'PKU', 'Text-to-Video', 'Teks ke Video', 2024, 'Open Source'),
('HiDream-I1', 'HiDream', 'Text-to-Image', 'Teks ke Gambar', 2025, 'Open Source'),
('Vidu', 'Shengshu', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('Vidu 1.5', 'Shengshu', 'Text-to-Video', 'Teks ke Video', 2024, 'Proprietary'),
('Vidu Q1', 'Shengshu', 'Text-to-Video', 'Teks ke Video', 2025, 'Proprietary'),

-- ==================== TEXT-TO-SPEECH / VOICE ====================
('Tacotron', 'Google', 'TTS', 'Teks ke Audio', 2017, 'Open Source'),
('Tacotron 2', 'Google', 'TTS', 'Teks ke Audio', 2017, 'Open Source'),
('WaveNet', 'Google DeepMind', 'TTS', 'Teks ke Audio', 2016, 'Proprietary'),
('FastSpeech', 'Microsoft', 'TTS', 'Teks ke Audio', 2019, 'Open Source'),
('FastSpeech 2', 'Microsoft', 'TTS', 'Teks ke Audio', 2020, 'Open Source'),
('VITS', 'Kakao', 'TTS', 'Teks ke Audio', 2021, 'Open Source'),
('Bark', 'Suno AI', 'TTS', 'Teks ke Audio', 2023, 'Open Source'),
('XTTS', 'Coqui', 'TTS Voice Cloning', 'Teks ke Audio', 2023, 'Open Source'),
('XTTS v2', 'Coqui', 'TTS Voice Cloning', 'Teks ke Audio', 2024, 'Open Source'),
('Tortoise TTS', 'Neonbjb', 'TTS', 'Teks ke Audio', 2023, 'Open Source'),
('ElevenLabs', 'ElevenLabs', 'TTS Voice Cloning', 'Teks ke Audio', 2022, 'Proprietary'),
('ElevenLabs v2', 'ElevenLabs', 'TTS Voice Cloning', 'Teks ke Audio', 2023, 'Proprietary'),
('ElevenLabs v3', 'ElevenLabs', 'TTS Voice Cloning', 'Teks ke Audio', 2025, 'Proprietary'),
('Eleven Multilingual v2', 'ElevenLabs', 'TTS Multilingual', 'Teks ke Audio', 2023, 'Proprietary'),
('Play.ht', 'Play.ht', 'TTS', 'Teks ke Audio', 2021, 'Proprietary'),
('Resemble AI', 'Resemble', 'TTS Voice Cloning', 'Teks ke Audio', 2019, 'Proprietary'),
('Descript Overdub', 'Descript', 'TTS Voice Cloning', 'Teks ke Audio', 2019, 'Proprietary'),
('Murf AI', 'Murf', 'TTS', 'Teks ke Audio', 2020, 'Proprietary'),
('Speechify', 'Speechify', 'TTS', 'Teks ke Audio', 2017, 'Proprietary'),
('Microsoft Azure TTS', 'Microsoft', 'TTS', 'Teks ke Audio', 2018, 'Proprietary'),
('Google Cloud TTS', 'Google', 'TTS', 'Teks ke Audio', 2018, 'Proprietary'),
('Amazon Polly', 'Amazon', 'TTS', 'Teks ke Audio', 2016, 'Proprietary'),
('OpenAI TTS', 'OpenAI', 'TTS', 'Teks ke Audio', 2023, 'Proprietary'),
('OpenAI Voice Engine', 'OpenAI', 'TTS Voice Cloning', 'Teks ke Audio', 2024, 'Proprietary'),
('Gemini TTS', 'Google', 'TTS', 'Teks ke Audio', 2025, 'Proprietary'),
('Sesame CSM', 'Sesame', 'TTS', 'Teks ke Audio', 2025, 'Open Source'),
('Dia', 'Nari Labs', 'TTS', 'Teks ke Audio', 2025, 'Open Source'),
('Orpheus TTS', 'Canopy Labs', 'TTS', 'Teks ke Audio', 2025, 'Open Source'),
('Kokoro TTS', 'Hexgrad', 'TTS', 'Teks ke Audio', 2024, 'Open Source'),
('F5-TTS', 'SWivid', 'TTS Voice Cloning', 'Teks ke Audio', 2024, 'Open Source'),
('Fish Speech', 'Fish Audio', 'TTS Voice Cloning', 'Teks ke Audio', 2023, 'Open Source'),
('Fish Audio S1', 'Fish Audio', 'TTS Voice Cloning', 'Teks ke Audio', 2025, 'Open Source'),
('StyleTTS 2', 'Columbia University', 'TTS', 'Teks ke Audio', 2023, 'Open Source'),
('Piper TTS', 'Rhasspy', 'TTS', 'Teks ke Audio', 2023, 'Open Source'),
('MeloTTS', 'MyShell', 'TTS', 'Teks ke Audio', 2024, 'Open Source'),
('ChatTTS', '2noise', 'TTS', 'Teks ke Audio', 2024, 'Open Source'),
('CosyVoice', 'Alibaba', 'TTS Voice Cloning', 'Teks ke Audio', 2024, 'Open Source'),
('CosyVoice 2', 'Alibaba', 'TTS Voice Cloning', 'Teks ke Audio', 2024, 'Open Source'),
('Spark-TTS', 'SparkAudio', 'TTS', 'Teks ke Audio', 2025, 'Open Source'),
('IndexTTS', 'Bilibili', 'TTS', 'Teks ke Audio', 2025, 'Open Source'),
('Zonos', 'Zyphra', 'TTS Voice Cloning', 'Teks ke Audio', 2025, 'Open Source'),

-- ==================== SPEECH-TO-TEXT / ASR ====================
('Whisper', 'OpenAI', 'Speech-to-Text', 'Audio ke Teks', 2022, 'Open Source'),
('Whisper Large V2', 'OpenAI', 'Speech-to-Text', 'Audio ke Teks', 2023, 'Open Source'),
('Whisper Large V3', 'OpenAI', 'Speech-to-Text', 'Audio ke Teks', 2023, 'Open Source'),
('Whisper Large V3 Turbo', 'OpenAI', 'Speech-to-Text', 'Audio ke Teks', 2024, 'Open Source'),
('Whisper Tiny', 'OpenAI', 'Speech-to-Text', 'Audio ke Teks', 2022, 'Open Source'),
('Whisper Base', 'OpenAI', 'Speech-to-Text', 'Audio ke Teks', 2022, 'Open Source'),
('Whisper Small', 'OpenAI', 'Speech-to-Text', 'Audio ke Teks', 2022, 'Open Source'),
('Whisper Medium', 'OpenAI', 'Speech-to-Text', 'Audio ke Teks', 2022, 'Open Source'),
('Wav2Vec 2.0', 'Meta AI', 'Speech-to-Text', 'Audio ke Teks', 2020, 'Open Source'),
('HuBERT', 'Meta AI', 'Speech-to-Text', 'Audio ke Teks', 2021, 'Open Source'),
('DeepSpeech', 'Mozilla', 'Speech-to-Text', 'Audio ke Teks', 2017, 'Open Source'),
('DeepSpeech 2', 'Baidu', 'Speech-to-Text', 'Audio ke Teks', 2015, 'Open Source'),
('Conformer', 'Google', 'Speech-to-Text', 'Audio ke Teks', 2020, 'Open Source'),
('SpeechTransformer', 'Microsoft', 'Speech-to-Text', 'Audio ke Teks', 2018, 'Open Source'),
('RNN-T', 'Google', 'Speech-to-Text', 'Audio ke Teks', 2019, 'Proprietary'),
('AssemblyAI', 'AssemblyAI', 'Speech-to-Text', 'Audio ke Teks', 2017, 'Proprietary'),
('Deepgram Nova-2', 'Deepgram', 'Speech-to-Text', 'Audio ke Teks', 2023, 'Proprietary'),
('Deepgram Nova-3', 'Deepgram', 'Speech-to-Text', 'Audio ke Teks', 2025, 'Proprietary'),
('Rev AI', 'Rev', 'Speech-to-Text', 'Audio ke Teks', 2017, 'Proprietary'),
('Otter.ai', 'Otter', 'Speech-to-Text', 'Audio ke Teks', 2016, 'Proprietary'),
('Fireflies.ai', 'Fireflies', 'Speech-to-Text', 'Audio ke Teks', 2016, 'Proprietary'),
('Sonix', 'Sonix', 'Speech-to-Text', 'Audio ke Teks', 2016, 'Proprietary'),
('Trint', 'Trint', 'Speech-to-Text', 'Audio ke Teks', 2014, 'Proprietary'),
('Verbit', 'Verbit', 'Speech-to-Text', 'Audio ke Teks', 2017, 'Proprietary'),
('Speechmatics', 'Speechmatics', 'Speech-to-Text', 'Audio ke Teks', 2015, 'Proprietary'),
('Kaldi', 'Johns Hopkins', 'Speech-to-Text', 'Audio ke Teks', 2011, 'Open Source'),
('ESPnet', 'CMU', 'Speech-to-Text', 'Audio ke Teks', 2018, 'Open Source'),
('NeMo', 'NVIDIA', 'Speech-to-Text', 'Audio ke Teks', 2019, 'Open Source'),
('SpeechBrain', 'MILA', 'Speech-to-Text', 'Audio ke Teks', 2021, 'Open Source'),
('WeNet', 'WeNet Community', 'Speech-to-Text', 'Audio ke Teks', 2020, 'Open Source'),
('FunASR', 'Alibaba', 'Speech-to-Text', 'Audio ke Teks', 2023, 'Open Source'),

-- ==================== TEXT-TO-MUSIC / AUDIO GENERATION ====================
('MuseNet', 'OpenAI', 'Text-to-Music', 'Teks ke Audio', 2019, 'Proprietary'),
('Jukebox', 'OpenAI', 'Text-to-Music', 'Teks ke Audio', 2020, 'Open Source'),
('MusicGen', 'Meta AI', 'Text-to-Music', 'Teks ke Audio', 2023, 'Open Source'),
('MusicGen Large', 'Meta AI', 'Text-to-Music', 'Teks ke Audio', 2023, 'Open Source'),
('AudioGen', 'Meta AI', 'Text-to-Audio', 'Teks ke Audio', 2023, 'Open Source'),
('AudioLDM', 'Surrey University', 'Text-to-Audio', 'Teks ke Audio', 2023, 'Open Source'),
('AudioLDM 2', 'Surrey University', 'Text-to-Audio', 'Teks ke Audio', 2023, 'Open Source'),
('Stable Audio', 'Stability AI', 'Text-to-Music', 'Teks ke Audio', 2023, 'Open Source'),
('Stable Audio 2', 'Stability AI', 'Text-to-Music', 'Teks ke Audio', 2024, 'Open Source'),
('Stable Audio Open', 'Stability AI', 'Text-to-Music', 'Teks ke Audio', 2024, 'Open Source'),
('Suno AI', 'Suno', 'Text-to-Music', 'Teks ke Audio', 2023, 'Proprietary'),
('Suno v3', 'Suno', 'Text-to-Music', 'Teks ke Audio', 2024, 'Proprietary'),
('Suno v3.5', 'Suno', 'Text-to-Music', 'Teks ke Audio', 2024, 'Proprietary'),
('Suno v4', 'Suno', 'Text-to-Music', 'Teks ke Audio', 2024, 'Proprietary'),
('Suno v4.5', 'Suno', 'Text-to-Music', 'Teks ke Audio', 2025, 'Proprietary'),
('Udio', 'Udio', 'Text-to-Music', 'Teks ke Audio', 2024, 'Proprietary'),
('Udio v1.5', 'Udio', 'Text-to-Music', 'Teks ke Audio', 2024, 'Proprietary'),
('Udio v2', 'Udio', 'Text-to-Music', 'Teks ke Audio', 2025, 'Proprietary'),
('AIVA', 'AIVA', 'Text-to-Music', 'Teks ke Audio', 2016, 'Proprietary'),
('Amper Music', 'Amper', 'Text-to-Music', 'Teks ke Audio', 2016, 'Proprietary'),
('Boomy', 'Boomy', 'Text-to-Music', 'Teks ke Audio', 2019, 'Proprietary'),
('Soundraw', 'Soundraw', 'Text-to-Music', 'Teks ke Audio', 2020, 'Proprietary'),
('Beatoven.ai', 'Beatoven', 'Text-to-Music', 'Teks ke Audio', 2021, 'Proprietary'),
('Mubert', 'Mubert', 'Text-to-Music', 'Teks ke Audio', 2017, 'Proprietary'),
('Riffusion', 'Riffusion', 'Text-to-Music', 'Teks ke Audio', 2022, 'Open Source'),
('Magenta', 'Google', 'Text-to-Music', 'Teks ke Audio', 2016, 'Open Source'),
('MusicLM', 'Google', 'Text-to-Music', 'Teks ke Audio', 2023, 'Proprietary'),
('MusicFX', 'Google', 'Text-to-Music', 'Teks ke Audio', 2023, 'Proprietary'),
('Lyria', 'Google DeepMind', 'Text-to-Music', 'Teks ke Audio', 2023, 'Proprietary'),
('Lyria 2', 'Google DeepMind', 'Text-to-Music', 'Teks ke Audio', 2025, 'Proprietary'),

-- ==================== 3D GENERATION ====================
('DreamFusion', 'Google', 'Text-to-3D', 'Teks ke 3D', 2022, 'Open Source'),
('Magic3D', 'NVIDIA', 'Text-to-3D', 'Teks ke 3D', 2022, 'Open Source'),
('Point-E', 'OpenAI', 'Text-to-3D', 'Teks ke 3D', 2022, 'Open Source'),
('Shap-E', 'OpenAI', 'Text-to-3D', 'Teks ke 3D', 2023, 'Open Source'),
('Zero-1-to-3', 'Columbia University', 'Image-to-3D', 'Gambar ke 3D', 2023, 'Open Source'),
('One-2-3-45', 'NYU', 'Image-to-3D', 'Gambar ke 3D', 2023, 'Open Source'),
('TripoSR', 'Stability AI, Tripo', 'Image-to-3D', 'Gambar ke 3D', 2024, 'Open Source'),
('Tripo3D', 'Tripo', 'Text-to-3D', 'Teks ke 3D', 2024, 'Proprietary'),
('Meshy', 'Meshy', 'Text-to-3D', 'Teks ke 3D', 2023, 'Proprietary'),
('Luma Genie', 'Luma AI', 'Text-to-3D', 'Teks ke 3D', 2023, 'Proprietary'),
('CSM 3D', 'Common Sense Machines', 'Image-to-3D', 'Gambar ke 3D', 2024, 'Proprietary'),
('Rodin', 'Deemos', 'Text-to-3D', 'Teks ke 3D', 2024, 'Proprietary'),
('Hunyuan3D', 'Tencent', 'Text-to-3D', 'Teks ke 3D', 2024, 'Open Source'),
('Hunyuan3D 2.0', 'Tencent', 'Text-to-3D', 'Teks ke 3D', 2025, 'Open Source'),
('Trellis', 'Microsoft', 'Image-to-3D', 'Gambar ke 3D', 2024, 'Open Source'),
('GVHMR', 'Zhejiang University', 'Video-to-3D', 'Video ke 3D', 2024, 'Open Source'),

-- ==================== MULTIMODAL / VISION-LANGUAGE ====================
('CLIP', 'OpenAI', 'Vision-Language', 'Teks, Gambar', 2021, 'Open Source'),
('BLIP', 'Salesforce', 'Vision-Language', 'Teks, Gambar', 2022, 'Open Source'),
('BLIP-2', 'Salesforce', 'Vision-Language', 'Teks, Gambar', 2023, 'Open Source'),
('InstructBLIP', 'Salesforce', 'Vision-Language', 'Teks, Gambar', 2023, 'Open Source'),
('Flamingo', 'Google DeepMind', 'Vision-Language', 'Teks, Gambar, Video', 2022, 'Proprietary'),
('PaLI', 'Google', 'Vision-Language', 'Teks, Gambar', 2022, 'Proprietary'),
('PaLI-3', 'Google', 'Vision-Language', 'Teks, Gambar', 2023, 'Proprietary'),
('PaLM-E', 'Google', 'Vision-Language', 'Teks, Gambar, Robotik', 2023, 'Proprietary'),
('LLaVA', 'Microsoft', 'Vision-Language', 'Teks, Gambar', 2023, 'Open Source'),
('LLaVA 1.5', 'Microsoft', 'Vision-Language', 'Teks, Gambar', 2023, 'Open Source'),
('LLaVA 1.6 (NeXT)', 'Microsoft', 'Vision-Language', 'Teks, Gambar', 2024, 'Open Source'),
('CogVLM', 'Tsinghua', 'Vision-Language', 'Teks, Gambar', 2023, 'Open Source'),
('CogVLM2', 'Tsinghua', 'Vision-Language', 'Teks, Gambar', 2024, 'Open Source'),
('InternVL', 'Shanghai AI Lab', 'Vision-Language', 'Teks, Gambar', 2023, 'Open Source'),
('InternVL 1.5', 'Shanghai AI Lab', 'Vision-Language', 'Teks, Gambar', 2024, 'Open Source'),
('InternVL 2.0', 'Shanghai AI Lab', 'Vision-Language', 'Teks, Gambar', 2024, 'Open Source'),
('InternVL 2.5', 'Shanghai AI Lab', 'Vision-Language', 'Teks, Gambar', 2024, 'Open Source'),
('InternVL 3', 'Shanghai AI Lab', 'Vision-Language', 'Teks, Gambar', 2025, 'Open Source'),
('Qwen-VL', 'Alibaba', 'Vision-Language', 'Teks, Gambar', 2023, 'Open Source'),
('Qwen2-VL', 'Alibaba', 'Vision-Language', 'Teks, Gambar, Video', 2024, 'Open Source'),
('Qwen2.5-VL', 'Alibaba', 'Vision-Language', 'Teks, Gambar, Video', 2025, 'Open Source'),
('Qwen3-VL', 'Alibaba', 'Vision-Language', 'Teks, Gambar, Video', 2025, 'Open Source'),
('Idefics', 'Hugging Face', 'Vision-Language', 'Teks, Gambar', 2023, 'Open Source'),
('Idefics2', 'Hugging Face', 'Vision-Language', 'Teks, Gambar', 2024, 'Open Source'),
('Idefics3', 'Hugging Face', 'Vision-Language', 'Teks, Gambar', 2024, 'Open Source'),
('SmolVLM', 'Hugging Face', 'Vision-Language', 'Teks, Gambar', 2024, 'Open Source'),
('Pixtral 12B', 'Mistral AI', 'Vision-Language', 'Teks, Gambar', 2024, 'Open Source'),
('Pixtral Large', 'Mistral AI', 'Vision-Language', 'Teks, Gambar', 2024, 'Proprietary'),
('Molmo', 'Allen AI', 'Vision-Language', 'Teks, Gambar', 2024, 'Open Source'),
('PaliGemma', 'Google', 'Vision-Language', 'Teks, Gambar', 2024, 'Open Source'),
('Gemma 3', 'Google', 'Vision-Language', 'Teks, Gambar', 2025, 'Open Source'),
('Gemma 3n', 'Google', 'Vision-Language', 'Teks, Gambar, Audio, Video', 2025, 'Open Source'),

-- ==================== AI AGENTS & FRAMEWORKS ====================
('AutoGPT', 'Significant Gravitas', 'AI Agent', 'Teks', 2023, 'Open Source'),
('BabyAGI', 'Yohei Nakajima', 'AI Agent', 'Teks', 2023, 'Open Source'),
('AgentGPT', 'Reworkd', 'AI Agent', 'Teks', 2023, 'Open Source'),
('LangChain', 'LangChain', 'AI Framework', 'Teks', 2022, 'Open Source'),
('LangGraph', 'LangChain', 'AI Framework', 'Teks', 2024, 'Open Source'),
('LlamaIndex', 'LlamaIndex', 'AI Framework', 'Teks', 2022, 'Open Source'),
('CrewAI', 'CrewAI', 'AI Framework', 'Teks', 2023, 'Open Source'),
('AutoGen', 'Microsoft', 'AI Framework', 'Teks', 2023, 'Open Source'),
('Semantic Kernel', 'Microsoft', 'AI Framework', 'Teks', 2023, 'Open Source'),
('Haystack', 'deepset', 'AI Framework', 'Teks', 2019, 'Open Source'),
('DSPy', 'Stanford', 'AI Framework', 'Teks', 2023, 'Open Source'),
('Flowise', 'FlowiseAI', 'AI Framework', 'Teks', 2023, 'Open Source'),
('n8n', 'n8n', 'AI Automation', 'Teks', 2019, 'Open Source'),
('Zapier AI', 'Zapier', 'AI Automation', 'Teks', 2023, 'Proprietary'),
('Make AI', 'Make', 'AI Automation', 'Teks', 2023, 'Proprietary'),

-- ==================== AI CODING ASSISTANTS ====================
('GitHub Copilot', 'GitHub, OpenAI', 'AI Coding', 'Teks', 2021, 'Proprietary'),
('GitHub Copilot Chat', 'GitHub, OpenAI', 'AI Coding', 'Teks', 2023, 'Proprietary'),
('Amazon CodeWhisperer', 'AWS', 'AI Coding', 'Teks', 2022, 'Proprietary'),
('Amazon Q Developer', 'AWS', 'AI Coding', 'Teks', 2024, 'Proprietary'),
('Tabnine', 'Tabnine', 'AI Coding', 'Teks', 2018, 'Proprietary'),
('Codeium', 'Codeium', 'AI Coding', 'Teks', 2022, 'Proprietary'),
('Windsurf', 'Codeium', 'AI Coding', 'Teks', 2024, 'Proprietary'),
('Cursor', 'Anysphere', 'AI Coding', 'Teks', 2023, 'Proprietary'),
('Replit Ghostwriter', 'Replit', 'AI Coding', 'Teks', 2022, 'Proprietary'),
('Replit Agent', 'Replit', 'AI Coding', 'Teks', 2024, 'Proprietary'),
('Sourcegraph Cody', 'Sourcegraph', 'AI Coding', 'Teks', 2023, 'Proprietary'),
('Continue', 'Continue', 'AI Coding', 'Teks', 2023, 'Open Source'),
('Aider', 'Aider', 'AI Coding', 'Teks', 2023, 'Open Source'),
('OpenDevin', 'OpenDevin', 'AI Coding', 'Teks', 2024, 'Open Source'),
('Devin', 'Cognition', 'AI Coding', 'Teks', 2024, 'Proprietary'),
('Claude Code', 'Anthropic', 'AI Coding', 'Teks', 2025, 'Proprietary'),
('OpenAI Codex CLI', 'OpenAI', 'AI Coding', 'Teks', 2025, 'Proprietary'),
('Gemini Code Assist', 'Google', 'AI Coding', 'Teks', 2024, 'Proprietary'),
('JetBrains AI Assistant', 'JetBrains', 'AI Coding', 'Teks', 2023, 'Proprietary'),
('Visual Studio IntelliCode', 'Microsoft', 'AI Coding', 'Teks', 2018, 'Proprietary'),
('Sourcery', 'Sourcery', 'AI Coding', 'Teks', 2019, 'Proprietary'),
('Qodo (Codium)', 'Qodo', 'AI Coding', 'Teks', 2022, 'Proprietary'),
('Blackbox AI', 'Blackbox', 'AI Coding', 'Teks', 2022, 'Proprietary'),
('AskCodi', 'AskCodi', 'AI Coding', 'Teks', 2022, 'Proprietary'),
('Mutable AI', 'Mutable', 'AI Coding', 'Teks', 2022, 'Proprietary'),
('Phind', 'Phind', 'AI Coding', 'Teks', 2022, 'Proprietary'),
('Bloop', 'Bloop', 'AI Coding', 'Teks', 2023, 'Proprietary'),
('Pieces', 'Pieces', 'AI Coding', 'Teks', 2023, 'Proprietary'),
('Sweep', 'Sweep', 'AI Coding', 'Teks', 2023, 'Proprietary'),

-- ==================== AI SEARCH & RESEARCH ====================
('Perplexity AI', 'Perplexity', 'AI Search', 'Teks', 2022, 'Proprietary'),
('You.com', 'You.com', 'AI Search', 'Teks', 2021, 'Proprietary'),
('Phind', 'Phind', 'AI Search', 'Teks', 2022, 'Proprietary'),
('Consensus', 'Consensus', 'AI Search', 'Teks', 2022, 'Proprietary'),
('Elicit', 'Elicit', 'AI Research', 'Teks', 2021, 'Proprietary'),
('Semantic Scholar', 'Allen AI', 'AI Research', 'Teks', 2015, 'Open Source'),
('Scite', 'Scite', 'AI Research', 'Teks', 2018, 'Proprietary'),
('Connected Papers', 'Connected Papers', 'AI Research', 'Teks', 2019, 'Proprietary'),
('ResearchRabbit', 'ResearchRabbit', 'AI Research', 'Teks', 2021, 'Proprietary'),
('SciSpace', 'SciSpace', 'AI Research', 'Teks', 2020, 'Proprietary'),
('NotebookLM', 'Google', 'AI Research', 'Teks', 2023, 'Proprietary'),
('Glean', 'Glean', 'AI Search', 'Teks', 2019, 'Proprietary'),
('Kagi', 'Kagi', 'AI Search', 'Teks', 2022, 'Proprietary'),
('Exa', 'Exa', 'AI Search', 'Teks', 2021, 'Proprietary'),
('Tavily', 'Tavily', 'AI Search', 'Teks', 2023, 'Proprietary'),
('Brave Search API', 'Brave', 'AI Search', 'Teks', 2021, 'Proprietary'),

-- ==================== AI PRODUCTIVITY & WRITING ====================
('Notion AI', 'Notion', 'AI Writing', 'Teks', 2023, 'Proprietary'),
('Jasper', 'Jasper', 'AI Writing', 'Teks', 2021, 'Proprietary'),
('Copy.ai', 'Copy.ai', 'AI Writing', 'Teks', 2020, 'Proprietary'),
('Writesonic', 'Writesonic', 'AI Writing', 'Teks', 2021, 'Proprietary'),
('Rytr', 'Rytr', 'AI Writing', 'Teks', 2021, 'Proprietary'),
('Grammarly', 'Grammarly', 'AI Writing', 'Teks', 2009, 'Proprietary'),
('QuillBot', 'QuillBot', 'AI Writing', 'Teks', 2017, 'Proprietary'),
('Wordtune', 'AI21 Labs', 'AI Writing', 'Teks', 2020, 'Proprietary'),
('Sudowrite', 'Sudowrite', 'AI Writing', 'Teks', 2020, 'Proprietary'),
('NovelAI', 'Anlatan', 'AI Writing', 'Teks, Gambar', 2021, 'Proprietary'),
('AI Dungeon', 'Latitude', 'AI Game', 'Teks', 2019, 'Proprietary'),
('Character.AI', 'Character.AI', 'AI Chatbot', 'Teks', 2022, 'Proprietary'),
('Replika', 'Luka', 'AI Chatbot', 'Teks, Audio', 2017, 'Proprietary'),
('Pi', 'Inflection AI', 'AI Chatbot', 'Teks', 2023, 'Proprietary'),
('Claude', 'Anthropic', 'AI Chatbot', 'Teks, Gambar', 2023, 'Proprietary'),
('Gemini', 'Google', 'AI Chatbot', 'Teks, Gambar, Audio, Video', 2023, 'Proprietary'),
('Copilot', 'Microsoft', 'AI Chatbot', 'Teks, Gambar', 2023, 'Proprietary'),
('Meta AI', 'Meta', 'AI Chatbot', 'Teks, Gambar', 2023, 'Proprietary'),
('Grok', 'xAI', 'AI Chatbot', 'Teks, Gambar', 2023, 'Proprietary'),
('DeepSeek Chat', 'DeepSeek', 'AI Chatbot', 'Teks', 2024, 'Proprietary'),
('Qwen Chat', 'Alibaba', 'AI Chatbot', 'Teks, Gambar', 2024, 'Proprietary'),
('Kimi', 'Moonshot AI', 'AI Chatbot', 'Teks', 2023, 'Proprietary'),
('Doubao', 'ByteDance', 'AI Chatbot', 'Teks, Gambar', 2023, 'Proprietary'),
('Ernie Bot', 'Baidu', 'AI Chatbot', 'Teks, Gambar', 2023, 'Proprietary'),
('Spark', 'iFlytek', 'AI Chatbot', 'Teks, Audio', 2023, 'Proprietary'),
('HuggingChat', 'Hugging Face', 'AI Chatbot', 'Teks', 2023, 'Open Source'),
('Poe', 'Quora', 'AI Chatbot', 'Teks', 2023, 'Proprietary'),
('YouChat', 'You.com', 'AI Chatbot', 'Teks', 2022, 'Proprietary'),
('Andi', 'Andi', 'AI Search', 'Teks', 2022, 'Proprietary'),
('Neeva AI', 'Neeva', 'AI Search', 'Teks', 2022, 'Proprietary'),

-- ==================== AI IMAGE EDITING & ENHANCEMENT ====================
('Remove.bg', 'Canva', 'AI Image Editing', 'Gambar', 2018, 'Proprietary'),
('Cleanup.pictures', 'Clipdrop', 'AI Image Editing', 'Gambar', 2021, 'Proprietary'),
('Clipdrop', 'Stability AI', 'AI Image Editing', 'Gambar', 2021, 'Proprietary'),
('Magic Eraser', 'Google', 'AI Image Editing', 'Gambar', 2021, 'Proprietary'),
('Photoshop Generative Fill', 'Adobe', 'AI Image Editing', 'Teks, Gambar', 2023, 'Proprietary'),
('Photoshop Generative Expand', 'Adobe', 'AI Image Editing', 'Teks, Gambar', 2023, 'Proprietary'),
('Lightroom AI Enhance', 'Adobe', 'AI Image Editing', 'Gambar', 2023, 'Proprietary'),
('Topaz Photo AI', 'Topaz Labs', 'AI Image Enhancement', 'Gambar', 2022, 'Proprietary'),
('Topaz Gigapixel AI', 'Topaz Labs', 'AI Image Upscaling', 'Gambar', 2018, 'Proprietary'),
('Topaz Video AI', 'Topaz Labs', 'AI Video Enhancement', 'Video', 2020, 'Proprietary'),
('Real-ESRGAN', 'Tencent', 'AI Image Upscaling', 'Gambar', 2021, 'Open Source'),
('GFPGAN', 'Tencent', 'AI Face Restoration', 'Gambar', 2021, 'Open Source'),
('CodeFormer', 'NTU', 'AI Face Restoration', 'Gambar', 2022, 'Open Source'),
('ESRGAN', 'Tencent', 'AI Image Upscaling', 'Gambar', 2018, 'Open Source'),
('SwinIR', 'ETH Zurich', 'AI Image Restoration', 'Gambar', 2021, 'Open Source'),
('Lama Cleaner', 'Sanster', 'AI Image Inpainting', 'Gambar', 2022, 'Open Source'),
('IOPaint', 'Sanster', 'AI Image Inpainting', 'Gambar', 2023, 'Open Source'),
('ControlNet', 'Stanford', 'AI Image Control', 'Gambar', 2023, 'Open Source'),
('IP-Adapter', 'Tencent', 'AI Image Control', 'Gambar', 2023, 'Open Source'),
('T2I-Adapter', 'Tencent', 'AI Image Control', 'Gambar', 2023, 'Open Source'),
('LoRA', 'Microsoft', 'AI Fine-tuning', 'Teks, Gambar', 2021, 'Open Source'),
('DreamBooth', 'Google', 'AI Fine-tuning', 'Teks, Gambar', 2022, 'Open Source'),
('Textual Inversion', 'NVIDIA', 'AI Fine-tuning', 'Teks, Gambar', 2022, 'Open Source'),
('Custom Diffusion', 'NVIDIA', 'AI Fine-tuning', 'Teks, Gambar', 2023, 'Open Source'),

-- ==================== AI VIDEO EDITING & GENERATION ====================
('Runway', 'Runway', 'AI Video Editing', 'Video', 2018, 'Proprietary'),
('Descript', 'Descript', 'AI Video Editing', 'Teks, Audio, Video', 2017, 'Proprietary'),
('CapCut AI', 'ByteDance', 'AI Video Editing', 'Video', 2020, 'Proprietary'),
('InVideo AI', 'InVideo', 'AI Video Generation', 'Teks ke Video', 2019, 'Proprietary'),
('Synthesia', 'Synthesia', 'AI Video Generation', 'Teks ke Video', 2017, 'Proprietary'),
('HeyGen', 'HeyGen', 'AI Video Generation', 'Teks ke Video', 2020, 'Proprietary'),
('D-ID', 'D-ID', 'AI Video Generation', 'Teks ke Video', 2017, 'Proprietary'),
('Hour One', 'Hour One', 'AI Video Generation', 'Teks ke Video', 2019, 'Proprietary'),
('Colossyan', 'Colossyan', 'AI Video Generation', 'Teks ke Video', 2020, 'Proprietary'),
('Elai.io', 'Elai', 'AI Video Generation', 'Teks ke Video', 2020, 'Proprietary'),
('Pictory', 'Pictory', 'AI Video Editing', 'Teks ke Video', 2019, 'Proprietary'),
('Fliki', 'Fliki', 'AI Video Generation', 'Teks ke Video', 2021, 'Proprietary'),
('Steve AI', 'Steve AI', 'AI Video Generation', 'Teks ke Video', 2020, 'Proprietary'),
('Lumen5', 'Lumen5', 'AI Video Editing', 'Teks ke Video', 2016, 'Proprietary'),
('Kapwing AI', 'Kapwing', 'AI Video Editing', 'Video', 2018, 'Proprietary'),
('Veed AI', 'Veed', 'AI Video Editing', 'Video', 2018, 'Proprietary'),
('Clipchamp AI', 'Microsoft', 'AI Video Editing', 'Video', 2020, 'Proprietary'),
('Adobe Premiere Pro AI', 'Adobe', 'AI Video Editing', 'Video', 2023, 'Proprietary'),
('Final Cut Pro AI', 'Apple', 'AI Video Editing', 'Video', 2023, 'Proprietary'),
('DaVinci Resolve AI', 'Blackmagic Design', 'AI Video Editing', 'Video', 2023, 'Proprietary'),

-- ==================== AI AUDIO EDITING & ENHANCEMENT ====================
('Adobe Podcast Enhance', 'Adobe', 'AI Audio Enhancement', 'Audio', 2022, 'Proprietary'),
('Auphonic', 'Auphonic', 'AI Audio Enhancement', 'Audio', 2012, 'Proprietary'),
('iZotope RX', 'iZotope', 'AI Audio Enhancement', 'Audio', 2018, 'Proprietary'),
('iZotope Ozone', 'iZotope', 'AI Audio Mastering', 'Audio', 2018, 'Proprietary'),
('LANDR', 'LANDR', 'AI Audio Mastering', 'Audio', 2014, 'Proprietary'),
('eMastered', 'eMastered', 'AI Audio Mastering', 'Audio', 2015, 'Proprietary'),
('CloudBounce', 'CloudBounce', 'AI Audio Mastering', 'Audio', 2014, 'Proprietary'),
('Accusonus ERA', 'Accusonus', 'AI Audio Enhancement', 'Audio', 2017, 'Proprietary'),
('Krisp', 'Krisp', 'AI Noise Cancellation', 'Audio', 2018, 'Proprietary'),
('NVIDIA Broadcast', 'NVIDIA', 'AI Audio/Video Enhancement', 'Audio, Video', 2020, 'Proprietary'),
('Voicemod', 'Voicemod', 'AI Voice Changer', 'Audio', 2017, 'Proprietary'),
('Murf AI', 'Murf', 'AI Voiceover', 'Teks ke Audio', 2020, 'Proprietary'),
('Lovo', 'Lovo', 'AI Voiceover', 'Teks ke Audio', 2019, 'Proprietary'),
('WellSaid Labs', 'WellSaid', 'AI Voiceover', 'Teks ke Audio', 2018, 'Proprietary'),
('Respeecher', 'Respeecher', 'AI Voice Cloning', 'Audio', 2018, 'Proprietary'),
('Voice.ai', 'Voice.ai', 'AI Voice Changer', 'Audio', 2020, 'Proprietary'),
('Altered Studio', 'Altered', 'AI Voice Changer', 'Audio', 2019, 'Proprietary'),
('MorphVOX', 'Screaming Bee', 'AI Voice Changer', 'Audio', 2007, 'Proprietary'),
('Clownfish', 'Clownfish', 'AI Voice Changer', 'Audio', 2015, 'Proprietary'),

-- ==================== AI PRESENTATION & DESIGN ====================
('Gamma', 'Gamma', 'AI Presentation', 'Teks ke Slide', 2020, 'Proprietary'),
('Tome', 'Tome', 'AI Presentation', 'Teks ke Slide', 2022, 'Proprietary'),
('Beautiful.ai', 'Beautiful.ai', 'AI Presentation', 'Teks ke Slide', 2018, 'Proprietary'),
('Pitch', 'Pitch', 'AI Presentation', 'Teks ke Slide', 2018, 'Proprietary'),
('SlidesAI', 'SlidesAI', 'AI Presentation', 'Teks ke Slide', 2022, 'Proprietary'),
('Decktopus', 'Decktopus', 'AI Presentation', 'Teks ke Slide', 2021, 'Proprietary'),
('Canva Magic Design', 'Canva', 'AI Design', 'Teks ke Gambar', 2022, 'Proprietary'),
('Canva Magic Write', 'Canva', 'AI Writing', 'Teks', 2022, 'Proprietary'),
('Canva Magic Edit', 'Canva', 'AI Image Editing', 'Gambar', 2023, 'Proprietary'),
('Canva Magic Studio', 'Canva', 'AI Design', 'Teks, Gambar, Video', 2023, 'Proprietary'),
('Microsoft Designer', 'Microsoft', 'AI Design', 'Teks ke Gambar', 2022, 'Proprietary'),
('Adobe Express AI', 'Adobe', 'AI Design', 'Teks, Gambar', 2023, 'Proprietary'),
('Figma AI', 'Figma', 'AI Design', 'Teks, Gambar', 2024, 'Proprietary'),
('Uizard', 'Uizard', 'AI Design', 'Teks ke UI', 2018, 'Proprietary'),
('Galileo AI', 'Galileo', 'AI Design', 'Teks ke UI', 2022, 'Proprietary'),
('Magician for Figma', 'Magician', 'AI Design', 'Teks', 2022, 'Proprietary'),
('Diagram AI', 'Diagram', 'AI Design', 'Teks ke Diagram', 2022, 'Proprietary'),
('Whimsical AI', 'Whimsical', 'AI Design', 'Teks ke Diagram', 2023, 'Proprietary'),
('Miro AI', 'Miro', 'AI Design', 'Teks ke Diagram', 2023, 'Proprietary'),
('Lucidchart AI', 'Lucid', 'AI Design', 'Teks ke Diagram', 2023, 'Proprietary'),

-- ==================== AI DATA & ANALYTICS ====================
('Julius AI', 'Julius', 'AI Data Analysis', 'Teks, Data', 2023, 'Proprietary'),
('Rows AI', 'Rows', 'AI Spreadsheet', 'Teks, Data', 2023, 'Proprietary'),
('Formula Bot', 'Formula Bot', 'AI Spreadsheet', 'Teks, Data', 2022, 'Proprietary'),
('Sheet AI', 'Sheet AI', 'AI Spreadsheet', 'Teks, Data', 2022, 'Proprietary'),
('Numerous AI', 'Numerous', 'AI Spreadsheet', 'Teks, Data', 2022, 'Proprietary'),
('Akkio', 'Akkio', 'AI Data Analysis', 'Teks, Data', 2018, 'Proprietary'),
('Obviously AI', 'Obviously AI', 'AI Data Analysis', 'Teks, Data', 2018, 'Proprietary'),
('DataRobot', 'DataRobot', 'AI Data Analysis', 'Teks, Data', 2012, 'Proprietary'),
('H2O.ai', 'H2O.ai', 'AI Data Analysis', 'Teks, Data', 2012, 'Open Source'),
('Dataiku', 'Dataiku', 'AI Data Analysis', 'Teks, Data', 2013, 'Proprietary'),
('Alteryx', 'Alteryx', 'AI Data Analysis', 'Teks, Data', 2010, 'Proprietary'),
('KNIME', 'KNIME', 'AI Data Analysis', 'Teks, Data', 2006, 'Open Source'),
('RapidMiner', 'RapidMiner', 'AI Data Analysis', 'Teks, Data', 2006, 'Proprietary'),
('Orange', 'University of Ljubljana', 'AI Data Analysis', 'Teks, Data', 1997, 'Open Source'),
('Weka', 'University of Waikato', 'AI Data Analysis', 'Teks, Data', 1993, 'Open Source'),

-- ==================== AI ROBOTICS & EMBODIED AI ====================
('RT-1', 'Google DeepMind', 'Robotics', 'Teks, Gambar, Robotik', 2022, 'Proprietary'),
('RT-2', 'Google DeepMind', 'Robotics', 'Teks, Gambar, Robotik', 2023, 'Proprietary'),
('RT-X', 'Google DeepMind', 'Robotics', 'Teks, Gambar, Robotik', 2023, 'Proprietary'),
('Open X-Embodiment', 'Google DeepMind', 'Robotics', 'Teks, Gambar, Robotik', 2023, 'Open Source'),
('PaLM-E', 'Google', 'Robotics', 'Teks, Gambar, Robotik', 2023, 'Proprietary'),
('SayCan', 'Google', 'Robotics', 'Teks, Robotik', 2022, 'Proprietary'),
('Code as Policies', 'Google', 'Robotics', 'Teks, Robotik', 2022, 'Proprietary'),
('VoxPoser', 'Stanford', 'Robotics', 'Teks, Gambar, Robotik', 2023, 'Proprietary'),
('Figure 01', 'Figure', 'Robotics', 'Teks, Gambar, Robotik', 2024, 'Proprietary'),
('Figure 02', 'Figure', 'Robotics', 'Teks, Gambar, Robotik', 2024, 'Proprietary'),
('Tesla Optimus', 'Tesla', 'Robotics', 'Teks, Gambar, Robotik', 2022, 'Proprietary'),
('1X Neo', '1X', 'Robotics', 'Teks, Gambar, Robotik', 2024, 'Proprietary'),
('1X Eve', '1X', 'Robotics', 'Teks, Gambar, Robotik', 2024, 'Proprietary'),
('Boston Dynamics Spot', 'Boston Dynamics', 'Robotics', 'Robotik', 2015, 'Proprietary'),
('Boston Dynamics Atlas', 'Boston Dynamics', 'Robotics', 'Robotik', 2013, 'Proprietary'),
('Boston Dynamics Stretch', 'Boston Dynamics', 'Robotics', 'Robotik', 2021, 'Proprietary'),
('Agility Digit', 'Agility Robotics', 'Robotics', 'Robotik', 2019, 'Proprietary'),
('Apptronik Apollo', 'Apptronik', 'Robotics', 'Robotik', 2023, 'Proprietary'),
('Sanctuary Phoenix', 'Sanctuary AI', 'Robotics', 'Robotik', 2023, 'Proprietary'),
('Unitree H1', 'Unitree', 'Robotics', 'Robotik', 2023, 'Proprietary'),
('Unitree G1', 'Unitree', 'Robotics', 'Robotik', 2024, 'Proprietary'),

-- ==================== AI HEALTHCARE & BIOLOGY ====================
('AlphaFold', 'Google DeepMind', 'AI Biology', 'Protein', 2020, 'Open Source'),
('AlphaFold 2', 'Google DeepMind', 'AI Biology', 'Protein', 2021, 'Open Source'),
('AlphaFold 3', 'Google DeepMind', 'AI Biology', 'Protein, DNA, RNA', 2024, 'Proprietary'),
('ESMFold', 'Meta AI', 'AI Biology', 'Protein', 2022, 'Open Source'),
('ESM-2', 'Meta AI', 'AI Biology', 'Protein', 2022, 'Open Source'),
('RoseTTAFold', 'University of Washington', 'AI Biology', 'Protein', 2021, 'Open Source'),
('RoseTTAFold2', 'University of Washington', 'AI Biology', 'Protein', 2023, 'Open Source'),
('OpenFold', 'Columbia University', 'AI Biology', 'Protein', 2022, 'Open Source'),
('RFdiffusion', 'University of Washington', 'AI Biology', 'Protein', 2023, 'Open Source'),
('ProteinMPNN', 'University of Washington', 'AI Biology', 'Protein', 2022, 'Open Source'),
('AlphaMissense', 'Google DeepMind', 'AI Biology', 'Protein', 2023, 'Proprietary'),
('Enformer', 'Google DeepMind', 'AI Genomics', 'DNA', 2021, 'Proprietary'),
('Nucleotide Transformer', 'NVIDIA', 'AI Genomics', 'DNA', 2023, 'Open Source'),
('DNABERT', 'University of Illinois', 'AI Genomics', 'DNA', 2021, 'Open Source'),
('DNABERT-2', 'University of Illinois', 'AI Genomics', 'DNA', 2023, 'Open Source'),
('scBERT', 'Tencent', 'AI Genomics', 'RNA', 2022, 'Open Source'),
('scGPT', 'University of Toronto', 'AI Genomics', 'RNA', 2024, 'Open Source'),
('Geneformer', 'Broad Institute', 'AI Genomics', 'RNA', 2023, 'Open Source'),
('Med-PaLM', 'Google', 'AI Healthcare', 'Teks', 2022, 'Proprietary'),
('Med-PaLM 2', 'Google', 'AI Healthcare', 'Teks', 2023, 'Proprietary'),
('Med-Gemini', 'Google', 'AI Healthcare', 'Teks, Gambar', 2024, 'Proprietary'),
('AMIE', 'Google', 'AI Healthcare', 'Teks, Gambar', 2024, 'Proprietary'),
('BioGPT', 'Microsoft', 'AI Healthcare', 'Teks', 2022, 'Open Source'),
('PubMedBERT', 'Microsoft', 'AI Healthcare', 'Teks', 2020, 'Open Source'),
('ClinicalBERT', 'MIT', 'AI Healthcare', 'Teks', 2019, 'Open Source'),
('BioBERT', 'Korea University', 'AI Healthcare', 'Teks', 2019, 'Open Source'),
('SciBERT', 'Allen AI', 'AI Research', 'Teks', 2019, 'Open Source'),
('PathChat', 'Harvard', 'AI Pathology', 'Teks, Gambar', 2024, 'Proprietary'),
('LLaVA-Med', 'Microsoft', 'AI Healthcare', 'Teks, Gambar', 2023, 'Open Source'),
('RadImageNet', 'Mount Sinai', 'AI Radiology', 'Gambar', 2022, 'Open Source'),
('CheXNet', 'Stanford', 'AI Radiology', 'Gambar', 2017, 'Open Source'),
('CheXpert', 'Stanford', 'AI Radiology', 'Gambar', 2019, 'Open Source'),
('MONAI', 'NVIDIA', 'AI Healthcare', 'Gambar', 2019, 'Open Source'),
('OpenBioMed', 'Tsinghua', 'AI Healthcare', 'Teks, Gambar', 2022, 'Open Source'),

-- ==================== AI WEATHER & CLIMATE ====================
('GraphCast', 'Google DeepMind', 'AI Weather', 'Cuaca', 2023, 'Open Source'),
('GenCast', 'Google DeepMind', 'AI Weather', 'Cuaca', 2023, 'Proprietary'),
('Pangu-Weather', 'Huawei', 'AI Weather', 'Cuaca', 2023, 'Proprietary'),
('FourCastNet', 'NVIDIA', 'AI Weather', 'Cuaca', 2022, 'Open Source'),
('FengWu', 'Shanghai AI Lab', 'AI Weather', 'Cuaca', 2023, 'Proprietary'),
('FuXi', 'Fudan University', 'AI Weather', 'Cuaca', 2023, 'Proprietary'),
('ClimaX', 'Microsoft', 'AI Climate', 'Iklim', 2023, 'Open Source'),
('Aurora', 'Microsoft', 'AI Climate', 'Iklim', 2024, 'Open Source'),
('ClimateNet', 'NVIDIA', 'AI Climate', 'Iklim', 2021, 'Open Source'),
('Earth-2', 'NVIDIA', 'AI Climate', 'Iklim', 2023, 'Proprietary'),

-- ==================== AI MATHEMATICS & REASONING ====================
('AlphaTensor', 'Google DeepMind', 'AI Math', 'Matematika', 2022, 'Proprietary'),
('AlphaGeometry', 'Google DeepMind', 'AI Math', 'Matematika', 2024, 'Proprietary'),
('AlphaProof', 'Google DeepMind', 'AI Math', 'Matematika', 2024, 'Proprietary'),
('AlphaZero', 'Google DeepMind', 'AI Game', 'Game', 2017, 'Proprietary'),
('MuZero', 'Google DeepMind', 'AI Game', 'Game', 2019, 'Proprietary'),
('AlphaStar', 'Google DeepMind', 'AI Game', 'Game', 2019, 'Proprietary'),
('OpenAI Five', 'OpenAI', 'AI Game', 'Game', 2018, 'Proprietary'),
('Deep Blue', 'IBM', 'AI Game', 'Game', 1996, 'Proprietary'),
('Watson', 'IBM', 'AI QA', 'Teks', 2011, 'Proprietary'),
('GPT-f', 'OpenAI', 'AI Math', 'Matematika', 2020, 'Proprietary'),
('Minerva', 'Google', 'AI Math', 'Matematika', 2022, 'Proprietary'),
('Llemma', 'EleutherAI', 'AI Math', 'Matematika', 2023, 'Open Source'),
('WizardMath', 'Microsoft', 'AI Math', 'Matematika', 2023, 'Open Source'),
('MetaMath', 'Meta AI', 'AI Math', 'Matematika', 2023, 'Open Source'),
('DeepSeek-Math', 'DeepSeek', 'AI Math', 'Matematika', 2024, 'Open Source'),
('Qwen-Math', 'Alibaba', 'AI Math', 'Matematika', 2024, 'Open Source'),
('Mathstral', 'Mistral AI', 'AI Math', 'Matematika', 2024, 'Open Source'),
('ToRA', 'Microsoft', 'AI Math', 'Matematika', 2023, 'Open Source'),
('MathCoder', 'HKU', 'AI Math', 'Matematika', 2023, 'Open Source'),

-- ==================== AI SECURITY & PRIVACY ====================
('Microsoft Security Copilot', 'Microsoft', 'AI Security', 'Teks', 2023, 'Proprietary'),
('Google Sec-PaLM', 'Google', 'AI Security', 'Teks', 2023, 'Proprietary'),
('Darktrace', 'Darktrace', 'AI Security', 'Jaringan', 2013, 'Proprietary'),
('CrowdStrike Falcon', 'CrowdStrike', 'AI Security', 'Jaringan', 2011, 'Proprietary'),
('SentinelOne', 'SentinelOne', 'AI Security', 'Jaringan', 2013, 'Proprietary'),
('Vectra AI', 'Vectra', 'AI Security', 'Jaringan', 2011, 'Proprietary'),
('Abnormal Security', 'Abnormal', 'AI Security', 'Email', 2018, 'Proprietary'),
('Doppel', 'Doppel', 'AI Security', 'Teks, Gambar', 2022, 'Proprietary'),
('Robust Intelligence', 'Robust Intelligence', 'AI Security', 'Teks, Gambar', 2019, 'Proprietary'),
('Lakera', 'Lakera', 'AI Security', 'Teks', 2021, 'Proprietary'),
('HiddenLayer', 'HiddenLayer', 'AI Security', 'Teks, Gambar', 2022, 'Proprietary'),
('Protect AI', 'Protect AI', 'AI Security', 'Teks, Gambar', 2022, 'Proprietary'),
('CalypsoAI', 'CalypsoAI', 'AI Security', 'Teks', 2018, 'Proprietary'),
('Arthur AI', 'Arthur', 'AI Monitoring', 'Teks, Data', 2018, 'Proprietary'),
('Fiddler AI', 'Fiddler', 'AI Monitoring', 'Teks, Data', 2018, 'Proprietary'),
('Arize AI', 'Arize', 'AI Monitoring', 'Teks, Data', 2020, 'Proprietary'),
('WhyLabs', 'WhyLabs', 'AI Monitoring', 'Teks, Data', 2020, 'Proprietary'),
('Evidently AI', 'Evidently', 'AI Monitoring', 'Teks, Data', 2020, 'Open Source'),
('Giskard', 'Giskard', 'AI Testing', 'Teks, Data', 2022, 'Open Source'),
('Deepchecks', 'Deepchecks', 'AI Testing', 'Teks, Data', 2020, 'Open Source'),
('Great Expectations', 'Great Expectations', 'AI Testing', 'Data', 2017, 'Open Source'),
('MLflow', 'Databricks', 'MLOps', 'Data', 2018, 'Open Source'),
('Weights & Biases', 'W&B', 'MLOps', 'Data', 2018, 'Proprietary'),
('Neptune.ai', 'Neptune', 'MLOps', 'Data', 2018, 'Proprietary'),
('Comet ML', 'Comet', 'MLOps', 'Data', 2017, 'Proprietary'),
('Kubeflow', 'Google', 'MLOps', 'Data', 2018, 'Open Source'),
('ZenML', 'ZenML', 'MLOps', 'Data', 2020, 'Open Source'),
('Metaflow', 'Netflix', 'MLOps', 'Data', 2019, 'Open Source'),
('DVC', 'Iterative', 'MLOps', 'Data', 2017, 'Open Source'),
('Pachyderm', 'Pachyderm', 'MLOps', 'Data', 2015, 'Open Source'),
('Flyte', 'Lyft', 'MLOps', 'Data', 2019, 'Open Source'),
('Airflow', 'Airbnb', 'MLOps', 'Data', 2014, 'Open Source'),
('Prefect', 'Prefect', 'MLOps', 'Data', 2018, 'Open Source'),
('Dagster', 'Dagster', 'MLOps', 'Data', 2018, 'Open Source'),
('Ray', 'Anyscale', 'MLOps', 'Data', 2017, 'Open Source'),
('BentoML', 'BentoML', 'MLOps', 'Data', 2019, 'Open Source'),
('Seldon', 'Seldon', 'MLOps', 'Data', 2014, 'Open Source'),
('KServe', 'Google', 'MLOps', 'Data', 2019, 'Open Source'),
('Triton Inference Server', 'NVIDIA', 'MLOps', 'Data', 2019, 'Open Source'),
('ONNX Runtime', 'Microsoft', 'MLOps', 'Data', 2018, 'Open Source'),
('OpenVINO', 'Intel', 'MLOps', 'Data', 2018, 'Open Source'),
('TensorFlow Serving', 'Google', 'MLOps', 'Data', 2016, 'Open Source'),
('TorchServe', 'AWS, Meta', 'MLOps', 'Data', 2020, 'Open Source'),
('Hugging Face Transformers', 'Hugging Face', 'AI Framework', 'Teks, Gambar, Audio', 2018, 'Open Source'),
('Hugging Face Diffusers', 'Hugging Face', 'AI Framework', 'Gambar, Video', 2022, 'Open Source'),
('Hugging Face Datasets', 'Hugging Face', 'AI Framework', 'Data', 2020, 'Open Source'),
('Hugging Face Accelerate', 'Hugging Face', 'AI Framework', 'Data', 2021, 'Open Source'),
('Hugging Face PEFT', 'Hugging Face', 'AI Framework', 'Data', 2022, 'Open Source'),
('Hugging Face TRL', 'Hugging Face', 'AI Framework', 'Data', 2022, 'Open Source'),
('PyTorch', 'Meta AI', 'AI Framework', 'Data', 2016, 'Open Source'),
('TensorFlow', 'Google', 'AI Framework', 'Data', 2015, 'Open Source'),
('JAX', 'Google', 'AI Framework', 'Data', 2018, 'Open Source'),
('Keras', 'Google', 'AI Framework', 'Data', 2015, 'Open Source'),
('MXNet', 'Apache', 'AI Framework', 'Data', 2015, 'Open Source'),
('PaddlePaddle', 'Baidu', 'AI Framework', 'Data', 2016, 'Open Source'),
('MindSpore', 'Huawei', 'AI Framework', 'Data', 2020, 'Open Source'),
('OneFlow', 'OneFlow', 'AI Framework', 'Data', 2020, 'Open Source'),
('FastAI', 'FastAI', 'AI Framework', 'Data', 2018, 'Open Source'),
('scikit-learn', 'INRIA', 'AI Framework', 'Data', 2007, 'Open Source'),
('XGBoost', 'University of Washington', 'AI Framework', 'Data', 2014, 'Open Source'),
('LightGBM', 'Microsoft', 'AI Framework', 'Data', 2017, 'Open Source'),
('CatBoost', 'Yandex', 'AI Framework', 'Data', 2017, 'Open Source'),
('MLlib', 'Apache', 'AI Framework', 'Data', 2014, 'Open Source'),
('Vowpal Wabbit', 'Microsoft', 'AI Framework', 'Data', 2007, 'Open Source'),
('Caffe', 'Berkeley', 'AI Framework', 'Data', 2013, 'Open Source'),
('Theano', 'University of Montreal', 'AI Framework', 'Data', 2007, 'Open Source'),
('Torch', 'Ronan Collobert', 'AI Framework', 'Data', 2002, 'Open Source'),
('CNTK', 'Microsoft', 'AI Framework', 'Data', 2016, 'Open Source'),
('Chainer', 'Preferred Networks', 'AI Framework', 'Data', 2015, 'Open Source'),
('DyNet', 'CMU', 'AI Framework', 'Data', 2016, 'Open Source'),
('BigDL', 'Intel', 'AI Framework', 'Data', 2016, 'Open Source'),
('Deeplearning4j', 'Eclipse', 'AI Framework', 'Data', 2014, 'Open Source'),
('ML.NET', 'Microsoft', 'AI Framework', 'Data', 2018, 'Open Source'),
('Core ML', 'Apple', 'AI Framework', 'Data', 2017, 'Proprietary'),
('TensorFlow Lite', 'Google', 'AI Framework', 'Data', 2017, 'Open Source'),
('PyTorch Mobile', 'Meta AI', 'AI Framework', 'Data', 2019, 'Open Source'),
('ONNX', 'Microsoft, Meta', 'AI Format', 'Data', 2017, 'Open Source'),
('GGUF', 'Georgi Gerganov', 'AI Format', 'Data', 2023, 'Open Source'),
('GGML', 'Georgi Gerganov', 'AI Format', 'Data', 2022, 'Open Source'),
('Safetensors', 'Hugging Face', 'AI Format', 'Data', 2022, 'Open Source'),
('AWQ', 'MIT', 'AI Quantization', 'Data', 2023, 'Open Source'),
('GPTQ', 'IST-DASLab', 'AI Quantization', 'Data', 2022, 'Open Source'),
('bitsandbytes', 'Tim Dettmers', 'AI Quantization', 'Data', 2022, 'Open Source'),
('llama.cpp', 'Georgi Gerganov', 'LLM Runtime', 'Teks', 2023, 'Open Source'),
('llamafile', 'Mozilla', 'LLM Runtime', 'Teks', 2023, 'Open Source'),
('Ollama', 'Ollama', 'LLM Runtime', 'Teks', 2023, 'Open Source'),
('LM Studio', 'LM Studio', 'LLM Runtime', 'Teks', 2023, 'Proprietary'),
('LocalAI', 'mudler', 'LLM Runtime', 'Teks, Gambar, Audio', 2023, 'Open Source'),
('vLLM', 'Berkeley', 'LLM Runtime', 'Teks', 2023, 'Open Source'),
('TensorRT-LLM', 'NVIDIA', 'LLM Runtime', 'Teks', 2023, 'Open Source'),
('Text Generation Inference', 'Hugging Face', 'LLM Runtime', 'Teks', 2023, 'Open Source'),
('OpenLLM', 'BentoML', 'LLM Runtime', 'Teks', 2023, 'Open Source'),
('CTranslate2', 'OpenNMT', 'LLM Runtime', 'Teks', 2019, 'Open Source'),
('FasterTransformer', 'NVIDIA', 'LLM Runtime', 'Teks', 2019, 'Open Source'),
('DeepSpeed', 'Microsoft', 'LLM Training', 'Data', 2020, 'Open Source'),
('Megatron-LM', 'NVIDIA', 'LLM Training', 'Data', 2019, 'Open Source'),
('FairScale', 'Meta AI', 'LLM Training', 'Data', 2020, 'Open Source'),
('Colossal-AI', 'HPC-AI Tech', 'LLM Training', 'Data', 2021, 'Open Source'),
('Alpa', 'Berkeley', 'LLM Training', 'Data', 2022, 'Open Source'),
('JAX', 'Google', 'AI Framework', 'Data', 2018, 'Open Source'),
('Flax', 'Google', 'AI Framework', 'Data', 2020, 'Open Source'),
('Haiku', 'Google DeepMind', 'AI Framework', 'Data', 2020, 'Open Source'),
('Equinox', 'Patrick Kidger', 'AI Framework', 'Data', 2022, 'Open Source'),
('MaxText', 'Google', 'LLM Training', 'Data', 2022, 'Open Source'),
('Levanter', 'Stanford', 'LLM Training', 'Data', 2023, 'Open Source'),
('Lit-GPT', 'Lightning AI', 'LLM Training', 'Data', 2023, 'Open Source'),
('Axolotl', 'OpenAccess AI Collective', 'LLM Training', 'Data', 2023, 'Open Source'),
('Unsloth', 'Unsloth AI', 'LLM Training', 'Data', 2023, 'Open Source'),
('PEFT', 'Hugging Face', 'LLM Training', 'Data', 2022, 'Open Source'),
('LoRA', 'Microsoft', 'LLM Training', 'Data', 2021, 'Open Source'),
('QLoRA', 'University of Washington', 'LLM Training', 'Data', 2023, 'Open Source'),
('DoRA', 'NVIDIA', 'LLM Training', 'Data', 2024, 'Open Source'),
('RLHF', 'OpenAI', 'LLM Alignment', 'Data', 2017, 'Open Source'),
('DPO', 'Stanford', 'LLM Alignment', 'Data', 2023, 'Open Source'),
('PPO', 'OpenAI', 'LLM Alignment', 'Data', 2017, 'Open Source'),
('ORPO', 'KAIST', 'LLM Alignment', 'Data', 2024, 'Open Source'),
('SimPO', 'Princeton', 'LLM Alignment', 'Data', 2024, 'Open Source'),
('KTO', 'Contextual AI', 'LLM Alignment', 'Data', 2024, 'Open Source');

-- ============================================================
-- SELESAI
-- Total: seluruh entri dari php.txt telah dikonversi ke SQL
-- ============================================================