<?php

$rumahSakitIndonesia = [
  // ==================== ACEH ====================
  ["nama" => "RSUD Dr. Zainoel Abidin", "kota" => "Banda Aceh", "provinsi" => "Aceh", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSU Cut Meutia", "kota" => "Lhokseumawe", "provinsi" => "Aceh", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Meuraxa", "kota" => "Banda Aceh", "provinsi" => "Aceh", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Bunda", "kota" => "Banda Aceh", "provinsi" => "Aceh", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RS Fakinah", "kota" => "Banda Aceh", "provinsi" => "Aceh", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Tgk. Chik Ditiro", "kota" => "Sigli", "provinsi" => "Aceh", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Cut Nyak Dhien", "kota" => "Meulaboh", "provinsi" => "Aceh", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Kota Langsa", "kota" => "Langsa", "provinsi" => "Aceh", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Lhokseumawe", "kota" => "Lhokseumawe", "provinsi" => "Aceh", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Sabang", "kota" => "Sabang", "provinsi" => "Aceh", "kelas" => "D", "jenis" => "Umum"],

  // ==================== SUMATERA UTARA ====================
  ["nama" => "RSUP H. Adam Malik", "kota" => "Medan", "provinsi" => "Sumatera Utara", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Pirngadi", "kota" => "Medan", "provinsi" => "Sumatera Utara", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RS Columbia Asia", "kota" => "Medan", "provinsi" => "Sumatera Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam Dhirga Surya", "kota" => "Medan", "provinsi" => "Sumatera Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Bunda Thamrin", "kota" => "Medan", "provinsi" => "Sumatera Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Martha Friska", "kota" => "Medan", "provinsi" => "Sumatera Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Deli Serdang", "kota" => "Lubuk Pakam", "provinsi" => "Sumatera Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Kabanjahe", "kota" => "Kabanjahe", "provinsi" => "Sumatera Utara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Tarutung", "kota" => "Tarutung", "provinsi" => "Sumatera Utara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Pematangsiantar", "kota" => "Pematangsiantar", "provinsi" => "Sumatera Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Tebing Tinggi", "kota" => "Tebing Tinggi", "provinsi" => "Sumatera Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Sibolga", "kota" => "Sibolga", "provinsi" => "Sumatera Utara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Padang Sidempuan", "kota" => "Padang Sidempuan", "provinsi" => "Sumatera Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Gunungsitoli", "kota" => "Gunungsitoli", "provinsi" => "Sumatera Utara", "kelas" => "C", "jenis" => "Umum"],

  // ==================== SUMATERA BARAT ====================
  ["nama" => "RSUP Dr. M. Djamil", "kota" => "Padang", "provinsi" => "Sumatera Barat", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Rasidin", "kota" => "Padang", "provinsi" => "Sumatera Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Semen Padang", "kota" => "Padang", "provinsi" => "Sumatera Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Yos Sudarso", "kota" => "Padang", "provinsi" => "Sumatera Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RS Bunda", "kota" => "Padang", "provinsi" => "Sumatera Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Solok", "kota" => "Solok", "provinsi" => "Sumatera Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Bukittinggi", "kota" => "Bukittinggi", "provinsi" => "Sumatera Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Payakumbuh", "kota" => "Payakumbuh", "provinsi" => "Sumatera Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Pariaman", "kota" => "Pariaman", "provinsi" => "Sumatera Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Padang Panjang", "kota" => "Padang Panjang", "provinsi" => "Sumatera Barat", "kelas" => "C", "jenis" => "Umum"],

  // ==================== RIAU ====================
  ["nama" => "RSUD Arifin Achmad", "kota" => "Pekanbaru", "provinsi" => "Riau", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Petala Bumi", "kota" => "Pekanbaru", "provinsi" => "Riau", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Awal Bros", "kota" => "Pekanbaru", "provinsi" => "Riau", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Eka Hospital", "kota" => "Pekanbaru", "provinsi" => "Riau", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Syafira", "kota" => "Pekanbaru", "provinsi" => "Riau", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Dumai", "kota" => "Dumai", "provinsi" => "Riau", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Bengkalis", "kota" => "Bengkalis", "provinsi" => "Riau", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Indragiri Hulu", "kota" => "Rengat", "provinsi" => "Riau", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Indragiri Hilir", "kota" => "Tembilahan", "provinsi" => "Riau", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Pelalawan", "kota" => "Pangkalan Kerinci", "provinsi" => "Riau", "kelas" => "C", "jenis" => "Umum"],

  // ==================== KEPULAUAN RIAU ====================
  ["nama" => "RSUD Raja Ahmad Tabib", "kota" => "Tanjungpinang", "provinsi" => "Kepulauan Riau", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Muhammad Sani", "kota" => "Karimun", "provinsi" => "Kepulauan Riau", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RS Awal Bros", "kota" => "Batam", "provinsi" => "Kepulauan Riau", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Elisabeth", "kota" => "Batam", "provinsi" => "Kepulauan Riau", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Santa Elisabeth", "kota" => "Batam", "provinsi" => "Kepulauan Riau", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Tanjung Uban", "kota" => "Tanjung Uban", "provinsi" => "Kepulauan Riau", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Natuna", "kota" => "Ranai", "provinsi" => "Kepulauan Riau", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Anambas", "kota" => "Terempa", "provinsi" => "Kepulauan Riau", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Dabo", "kota" => "Singkep", "provinsi" => "Kepulauan Riau", "kelas" => "C", "jenis" => "Umum"],

  // ==================== JAMBI ====================
  ["nama" => "RSUP Dr. M. Yunus", "kota" => "Jambi", "provinsi" => "Jambi", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Raden Mattaher", "kota" => "Jambi", "provinsi" => "Jambi", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Jambi", "provinsi" => "Jambi", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Bunda", "kota" => "Jambi", "provinsi" => "Jambi", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Muara Bungo", "kota" => "Muara Bungo", "provinsi" => "Jambi", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Kerinci", "kota" => "Sungai Penuh", "provinsi" => "Jambi", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Kuala Tungkal", "kota" => "Kuala Tungkal", "provinsi" => "Jambi", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Sarolangun", "kota" => "Sarolangun", "provinsi" => "Jambi", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Batanghari", "kota" => "Muara Bulian", "provinsi" => "Jambi", "kelas" => "C", "jenis" => "Umum"],

  // ==================== SUMATERA SELATAN ====================
  ["nama" => "RSUP Dr. Mohammad Hoesin", "kota" => "Palembang", "provinsi" => "Sumatera Selatan", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Palembang Bari", "kota" => "Palembang", "provinsi" => "Sumatera Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Charitas", "kota" => "Palembang", "provinsi" => "Sumatera Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam Sriwijaya", "kota" => "Palembang", "provinsi" => "Sumatera Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Bunda", "kota" => "Palembang", "provinsi" => "Sumatera Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Kayuagung", "kota" => "Kayuagung", "provinsi" => "Sumatera Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Lubuk Linggau", "kota" => "Lubuk Linggau", "provinsi" => "Sumatera Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Prabumulih", "kota" => "Prabumulih", "provinsi" => "Sumatera Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Pagar Alam", "kota" => "Pagar Alam", "provinsi" => "Sumatera Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Lahat", "kota" => "Lahat", "provinsi" => "Sumatera Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Muara Enim", "kota" => "Muara Enim", "provinsi" => "Sumatera Selatan", "kelas" => "C", "jenis" => "Umum"],

  // ==================== BANGKA BELITUNG ====================
  ["nama" => "RSUD Dr. (H.C.) Ir. Soekarno", "kota" => "Sungailiat", "provinsi" => "Bangka Belitung", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Depati Hamzah", "kota" => "Pangkalpinang", "provinsi" => "Bangka Belitung", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Bakti Timah", "kota" => "Pangkalpinang", "provinsi" => "Bangka Belitung", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Tanjungpandan", "kota" => "Tanjungpandan", "provinsi" => "Bangka Belitung", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Belitung Timur", "kota" => "Manggar", "provinsi" => "Bangka Belitung", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Bangka Tengah", "kota" => "Koba", "provinsi" => "Bangka Belitung", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Bangka Barat", "kota" => "Mentok", "provinsi" => "Bangka Belitung", "kelas" => "C", "jenis" => "Umum"],

  // ==================== BENGKULU ====================
  ["nama" => "RSUD Dr. M. Yunus", "kota" => "Bengkulu", "provinsi" => "Bengkulu", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Rafflesia", "kota" => "Bengkulu", "provinsi" => "Bengkulu", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RS Bhayangkara", "kota" => "Bengkulu", "provinsi" => "Bengkulu", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Manna", "kota" => "Manna", "provinsi" => "Bengkulu", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Curup", "kota" => "Curup", "provinsi" => "Bengkulu", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Argamakmur", "kota" => "Argamakmur", "provinsi" => "Bengkulu", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Mukomuko", "kota" => "Mukomuko", "provinsi" => "Bengkulu", "kelas" => "C", "jenis" => "Umum"],

  // ==================== LAMPUNG ====================
  ["nama" => "RSUD Dr. H. Abdul Moeloek", "kota" => "Bandar Lampung", "provinsi" => "Lampung", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Pringsewu", "kota" => "Pringsewu", "provinsi" => "Lampung", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Bumi Waras", "kota" => "Bandar Lampung", "provinsi" => "Lampung", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Bandar Lampung", "provinsi" => "Lampung", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Advent", "kota" => "Bandar Lampung", "provinsi" => "Lampung", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Metro", "kota" => "Metro", "provinsi" => "Lampung", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Liwa", "kota" => "Liwa", "provinsi" => "Lampung", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Kalianda", "kota" => "Kalianda", "provinsi" => "Lampung", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Kota Agung", "kota" => "Kota Agung", "provinsi" => "Lampung", "kelas" => "C", "jenis" => "Umum"],

  // ==================== DKI JAKARTA ====================
  ["nama" => "RSUP Dr. Cipto Mangunkusumo", "kota" => "Jakarta Pusat", "provinsi" => "DKI Jakarta", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUP Fatmawati", "kota" => "Jakarta Selatan", "provinsi" => "DKI Jakarta", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUP Persahabatan", "kota" => "Jakarta Timur", "provinsi" => "DKI Jakarta", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUP Dr. Sulianti Saroso", "kota" => "Jakarta Utara", "provinsi" => "DKI Jakarta", "kelas" => "A", "jenis" => "Khusus Infeksi"],
  ["nama" => "RS Pusat Otak Nasional", "kota" => "Jakarta Timur", "provinsi" => "DKI Jakarta", "kelas" => "A", "jenis" => "Khusus Otak"],
  ["nama" => "RS Kanker Dharmais", "kota" => "Jakarta Barat", "provinsi" => "DKI Jakarta", "kelas" => "A", "jenis" => "Khusus Kanker"],
  ["nama" => "RS Jantung Harapan Kita", "kota" => "Jakarta Barat", "provinsi" => "DKI Jakarta", "kelas" => "A", "jenis" => "Khusus Jantung"],
  ["nama" => "RSUD Tarakan", "kota" => "Jakarta Pusat", "provinsi" => "DKI Jakarta", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Koja", "kota" => "Jakarta Utara", "provinsi" => "DKI Jakarta", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Pasar Minggu", "kota" => "Jakarta Selatan", "provinsi" => "DKI Jakarta", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Cengkareng", "kota" => "Jakarta Barat", "provinsi" => "DKI Jakarta", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Budhi Asih", "kota" => "Jakarta Timur", "provinsi" => "DKI Jakarta", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Johar Baru", "kota" => "Jakarta Pusat", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Mampang Prapatan", "kota" => "Jakarta Selatan", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam Semanggi", "kota" => "Jakarta Selatan", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Pondok Indah", "kota" => "Jakarta Selatan", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Premier Bintaro", "kota" => "Tangerang Selatan", "provinsi" => "Banten", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Mitra Keluarga", "kota" => "Jakarta", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Hermina", "kota" => "Jakarta", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS St. Carolus", "kota" => "Jakarta Pusat", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS PGI Cikini", "kota" => "Jakarta Pusat", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Gading Pluit", "kota" => "Jakarta Utara", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Royal Progress", "kota" => "Jakarta Utara", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Pluit", "kota" => "Jakarta Utara", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Medistra", "kota" => "Jakarta Selatan", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS MMC", "kota" => "Jakarta Selatan", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Gandaria", "kota" => "Jakarta Selatan", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Bunda", "kota" => "Jakarta Pusat", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS YPK", "kota" => "Jakarta Timur", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS UKI", "kota" => "Jakarta Timur", "provinsi" => "DKI Jakarta", "kelas" => "B", "jenis" => "Umum"],

  // ==================== JAWA BARAT ====================
  ["nama" => "RSUP Dr. Hasan Sadikin", "kota" => "Bandung", "provinsi" => "Jawa Barat", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Al Ihsan", "kota" => "Bandung", "provinsi" => "Jawa Barat", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RS Santo Borromeus", "kota" => "Bandung", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Advent", "kota" => "Bandung", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Hermina", "kota" => "Bandung", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam Kebon Jeruk", "kota" => "Bandung", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Premier", "kota" => "Bandung", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Cibinong", "kota" => "Cibinong", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Depok", "kota" => "Depok", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Bekasi", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Mitra Keluarga", "kota" => "Bekasi", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Hermina", "kota" => "Bekasi", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Karawang", "kota" => "Karawang", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Bogor", "kota" => "Bogor", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS PMI", "kota" => "Bogor", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Bogor", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Cimahi", "kota" => "Cimahi", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Sukabumi", "kota" => "Sukabumi", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Tasikmalaya", "kota" => "Tasikmalaya", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Cirebon", "kota" => "Cirebon", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Gunung Jati", "kota" => "Cirebon", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Garut", "kota" => "Garut", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Subang", "kota" => "Subang", "provinsi" => "Jawa Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Purwakarta", "kota" => "Purwakarta", "provinsi" => "Jawa Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Bandung", "kota" => "Bandung", "provinsi" => "Jawa Barat", "kelas" => "B", "jenis" => "Umum"],

  // ==================== BANTEN ====================
  ["nama" => "RSUD Dr. Drajat Prawiranegara", "kota" => "Serang", "provinsi" => "Banten", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Tangerang", "kota" => "Tangerang", "provinsi" => "Banten", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Kabupaten Tangerang", "kota" => "Tigaraksa", "provinsi" => "Banten", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Tangerang", "provinsi" => "Banten", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Premier", "kota" => "Tangerang", "provinsi" => "Banten", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Mitra Keluarga", "kota" => "Tangerang", "provinsi" => "Banten", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Hermina", "kota" => "Tangerang", "provinsi" => "Banten", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Cilegon", "kota" => "Cilegon", "provinsi" => "Banten", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Krakatau Medika", "kota" => "Cilegon", "provinsi" => "Banten", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Pandeglang", "kota" => "Pandeglang", "provinsi" => "Banten", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Rangkasbitung", "kota" => "Rangkasbitung", "provinsi" => "Banten", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Serang", "kota" => "Serang", "provinsi" => "Banten", "kelas" => "B", "jenis" => "Umum"],

  // ==================== JAWA TENGAH ====================
  ["nama" => "RSUP Dr. Kariadi", "kota" => "Semarang", "provinsi" => "Jawa Tengah", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Moewardi", "kota" => "Surakarta", "provinsi" => "Jawa Tengah", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RS Dr. Oen", "kota" => "Surakarta", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS PKU Muhammadiyah", "kota" => "Surakarta", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Semarang", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Elisabeth", "kota" => "Semarang", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS St. Elisabeth", "kota" => "Semarang", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Hermina", "kota" => "Semarang", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Tugurejo", "kota" => "Semarang", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Kota Semarang", "kota" => "Semarang", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Kudus", "kota" => "Kudus", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Soeselo", "kota" => "Slawi", "provinsi" => "Jawa Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Soehadi Prijonegoro", "kota" => "Sragen", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Salatiga", "kota" => "Salatiga", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Purwokerto", "kota" => "Purwokerto", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Banyumas", "kota" => "Banyumas", "provinsi" => "Jawa Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Cilacap", "kota" => "Cilacap", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Magelang", "kota" => "Magelang", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Temanggung", "kota" => "Temanggung", "provinsi" => "Jawa Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Wonosobo", "kota" => "Wonosobo", "provinsi" => "Jawa Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Kebumen", "kota" => "Kebumen", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Tegal", "kota" => "Tegal", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Pekalongan", "kota" => "Pekalongan", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Pati", "kota" => "Pati", "provinsi" => "Jawa Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Rembang", "kota" => "Rembang", "provinsi" => "Jawa Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Blora", "kota" => "Blora", "provinsi" => "Jawa Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Jepara", "kota" => "Jepara", "provinsi" => "Jawa Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Demak", "kota" => "Demak", "provinsi" => "Jawa Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Ungaran", "kota" => "Ungaran", "provinsi" => "Jawa Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Ambarawa", "kota" => "Ambarawa", "provinsi" => "Jawa Tengah", "kelas" => "C", "jenis" => "Umum"],

  // ==================== DI YOGYAKARTA ====================
  ["nama" => "RSUP Dr. Sardjito", "kota" => "Yogyakarta", "provinsi" => "DI Yogyakarta", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Kota Yogyakarta", "kota" => "Yogyakarta", "provinsi" => "DI Yogyakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Bethesda", "kota" => "Yogyakarta", "provinsi" => "DI Yogyakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Panti Rapih", "kota" => "Yogyakarta", "provinsi" => "DI Yogyakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Yogyakarta", "provinsi" => "DI Yogyakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS JIH", "kota" => "Yogyakarta", "provinsi" => "DI Yogyakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS PKU Muhammadiyah", "kota" => "Yogyakarta", "provinsi" => "DI Yogyakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Panembahan Senopati", "kota" => "Bantul", "provinsi" => "DI Yogyakarta", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Wates", "kota" => "Kulon Progo", "provinsi" => "DI Yogyakarta", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Gunungkidul", "kota" => "Wonosari", "provinsi" => "DI Yogyakarta", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Sleman", "kota" => "Sleman", "provinsi" => "DI Yogyakarta", "kelas" => "B", "jenis" => "Umum"],

  // ==================== JAWA TIMUR ====================
  ["nama" => "RSUP Dr. Soetomo", "kota" => "Surabaya", "provinsi" => "Jawa Timur", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Soetomo", "kota" => "Surabaya", "provinsi" => "Jawa Timur", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Surabaya", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Premier", "kota" => "Surabaya", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Mitra Keluarga", "kota" => "Surabaya", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Hermina", "kota" => "Surabaya", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS PHC", "kota" => "Surabaya", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS William Booth", "kota" => "Surabaya", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Katolik St. Vincentius a Paulo", "kota" => "Surabaya", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Soewandhie", "kota" => "Surabaya", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Bhakti Dharma Husada", "kota" => "Surabaya", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Iskak", "kota" => "Tulungagung", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Saiful Anwar", "kota" => "Malang", "provinsi" => "Jawa Timur", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RS Panti Waluya", "kota" => "Malang", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Lavalette", "kota" => "Malang", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Malang", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Soedono", "kota" => "Madiun", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Soekarno", "kota" => "Bangkalan", "provinsi" => "Jawa Timur", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Soegiri", "kota" => "Lamongan", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. R. Sosodoro Djatikoesoemo", "kota" => "Bojonegoro", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Soeroto", "kota" => "Ngawi", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Harjono", "kota" => "Ponorogo", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Soebandi", "kota" => "Jember", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Haryoto", "kota" => "Lumajang", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Abdoer Rahem", "kota" => "Situbondo", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Blambangan", "kota" => "Banyuwangi", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Soekarno", "kota" => "Gresik", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Mohamad Soewandhie", "kota" => "Surabaya", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Sidoarjo", "kota" => "Sidoarjo", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Pasuruan", "kota" => "Pasuruan", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Probolinggo", "kota" => "Probolinggo", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Jombang", "kota" => "Jombang", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Nganjuk", "kota" => "Nganjuk", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Kediri", "kota" => "Kediri", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Blitar", "kota" => "Blitar", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Tuban", "kota" => "Tuban", "provinsi" => "Jawa Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Sumenep", "kota" => "Sumenep", "provinsi" => "Jawa Timur", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Pamekasan", "kota" => "Pamekasan", "provinsi" => "Jawa Timur", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Sampang", "kota" => "Sampang", "provinsi" => "Jawa Timur", "kelas" => "C", "jenis" => "Umum"],

  // ==================== BALI ====================
  ["nama" => "RSUP Sanglah", "kota" => "Denpasar", "provinsi" => "Bali", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Wangaya", "kota" => "Denpasar", "provinsi" => "Bali", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Denpasar", "provinsi" => "Bali", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS BIMC", "kota" => "Denpasar", "provinsi" => "Bali", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Kasih Ibu", "kota" => "Denpasar", "provinsi" => "Bali", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Prima Medika", "kota" => "Denpasar", "provinsi" => "Bali", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Tabanan", "kota" => "Tabanan", "provinsi" => "Bali", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Gianyar", "kota" => "Gianyar", "provinsi" => "Bali", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Karangasem", "kota" => "Karangasem", "provinsi" => "Bali", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Buleleng", "kota" => "Singaraja", "provinsi" => "Bali", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Klungkung", "kota" => "Semarapura", "provinsi" => "Bali", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Bangli", "kota" => "Bangli", "provinsi" => "Bali", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Jembrana", "kota" => "Negara", "provinsi" => "Bali", "kelas" => "B", "jenis" => "Umum"],

  // ==================== NUSA TENGGARA BARAT ====================
  ["nama" => "RSUD Mataram", "kota" => "Mataram", "provinsi" => "Nusa Tenggara Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Provinsi NTB", "kota" => "Mataram", "provinsi" => "Nusa Tenggara Barat", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Mataram", "provinsi" => "Nusa Tenggara Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Harapan Keluarga", "kota" => "Mataram", "provinsi" => "Nusa Tenggara Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Bima", "kota" => "Bima", "provinsi" => "Nusa Tenggara Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Sumbawa", "kota" => "Sumbawa Besar", "provinsi" => "Nusa Tenggara Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Lombok Timur", "kota" => "Selong", "provinsi" => "Nusa Tenggara Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Lombok Barat", "kota" => "Gerung", "provinsi" => "Nusa Tenggara Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Lombok Tengah", "kota" => "Praya", "provinsi" => "Nusa Tenggara Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Lombok Utara", "kota" => "Tanjung", "provinsi" => "Nusa Tenggara Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Dompu", "kota" => "Dompu", "provinsi" => "Nusa Tenggara Barat", "kelas" => "C", "jenis" => "Umum"],

  // ==================== NUSA TENGGARA TIMUR ====================
  ["nama" => "RSUD Dr. W. Z. Johannes", "kota" => "Kupang", "provinsi" => "Nusa Tenggara Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Prof. Dr. W. Z. Johannes", "kota" => "Kupang", "provinsi" => "Nusa Tenggara Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Kupang", "provinsi" => "Nusa Tenggara Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS St. Carolus", "kota" => "Kupang", "provinsi" => "Nusa Tenggara Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Maumere", "kota" => "Maumere", "provinsi" => "Nusa Tenggara Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Ende", "kota" => "Ende", "provinsi" => "Nusa Tenggara Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Ruteng", "kota" => "Ruteng", "provinsi" => "Nusa Tenggara Timur", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Bajawa", "kota" => "Bajawa", "provinsi" => "Nusa Tenggara Timur", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Larantuka", "kota" => "Larantuka", "provinsi" => "Nusa Tenggara Timur", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Waingapu", "kota" => "Waingapu", "provinsi" => "Nusa Tenggara Timur", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Soe", "kota" => "Soe", "provinsi" => "Nusa Tenggara Timur", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Kefamenanu", "kota" => "Kefamenanu", "provinsi" => "Nusa Tenggara Timur", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Atambua", "kota" => "Atambua", "provinsi" => "Nusa Tenggara Timur", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Kalabahi", "kota" => "Kalabahi", "provinsi" => "Nusa Tenggara Timur", "kelas" => "C", "jenis" => "Umum"],

  // ==================== KALIMANTAN BARAT ====================
  ["nama" => "RSUD Dr. Soedarso", "kota" => "Pontianak", "provinsi" => "Kalimantan Barat", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Sultan Syarif Mohamad Alkadrie", "kota" => "Pontianak", "provinsi" => "Kalimantan Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Pontianak", "provinsi" => "Kalimantan Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS St. Antonius", "kota" => "Pontianak", "provinsi" => "Kalimantan Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Mitra Keluarga", "kota" => "Pontianak", "provinsi" => "Kalimantan Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Singkawang", "kota" => "Singkawang", "provinsi" => "Kalimantan Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Ketapang", "kota" => "Ketapang", "provinsi" => "Kalimantan Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Sintang", "kota" => "Sintang", "provinsi" => "Kalimantan Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Putussibau", "kota" => "Putussibau", "provinsi" => "Kalimantan Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Bengkayang", "kota" => "Bengkayang", "provinsi" => "Kalimantan Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Landak", "kota" => "Ngabang", "provinsi" => "Kalimantan Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Mempawah", "kota" => "Mempawah", "provinsi" => "Kalimantan Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Sambas", "kota" => "Sambas", "provinsi" => "Kalimantan Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Sanggau", "kota" => "Sanggau", "provinsi" => "Kalimantan Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Sekadau", "kota" => "Sekadau", "provinsi" => "Kalimantan Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Tayan", "kota" => "Tayan", "provinsi" => "Kalimantan Barat", "kelas" => "C", "jenis" => "Umum"],

  // ==================== KALIMANTAN TENGAH ====================
  ["nama" => "RSUD Dr. Doris Sylvanus", "kota" => "Palangkaraya", "provinsi" => "Kalimantan Tengah", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Palangkaraya", "kota" => "Palangkaraya", "provinsi" => "Kalimantan Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Palangkaraya", "provinsi" => "Kalimantan Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Sampit", "kota" => "Sampit", "provinsi" => "Kalimantan Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Pangkalan Bun", "kota" => "Pangkalan Bun", "provinsi" => "Kalimantan Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Muara Teweh", "kota" => "Muara Teweh", "provinsi" => "Kalimantan Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Kuala Kurun", "kota" => "Kuala Kurun", "provinsi" => "Kalimantan Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Kuala Pembuang", "kota" => "Kuala Pembuang", "provinsi" => "Kalimantan Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Buntok", "kota" => "Buntok", "provinsi" => "Kalimantan Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Tamiang Layang", "kota" => "Tamiang Layang", "provinsi" => "Kalimantan Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Puruk Cahu", "kota" => "Puruk Cahu", "provinsi" => "Kalimantan Tengah", "kelas" => "C", "jenis" => "Umum"],

  // ==================== KALIMANTAN SELATAN ====================
  ["nama" => "RSUD Ulin", "kota" => "Banjarmasin", "provinsi" => "Kalimantan Selatan", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Banjarmasin", "kota" => "Banjarmasin", "provinsi" => "Kalimantan Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Banjarmasin", "provinsi" => "Kalimantan Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Islam", "kota" => "Banjarmasin", "provinsi" => "Kalimantan Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Bhayangkara", "kota" => "Banjarmasin", "provinsi" => "Kalimantan Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Ratu Zalecha", "kota" => "Martapura", "provinsi" => "Kalimantan Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Kotabaru", "kota" => "Kotabaru", "provinsi" => "Kalimantan Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Tanjung", "kota" => "Tanjung", "provinsi" => "Kalimantan Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Batu Licin", "kota" => "Batu Licin", "provinsi" => "Kalimantan Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Barabai", "kota" => "Barabai", "provinsi" => "Kalimantan Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Kandangan", "kota" => "Kandangan", "provinsi" => "Kalimantan Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Amuntai", "kota" => "Amuntai", "provinsi" => "Kalimantan Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Pelaihari", "kota" => "Pelaihari", "provinsi" => "Kalimantan Selatan", "kelas" => "C", "jenis" => "Umum"],

  // ==================== KALIMANTAN TIMUR ====================
  ["nama" => "RSUD Dr. Kanujoso Djatiwibowo", "kota" => "Balikpapan", "provinsi" => "Kalimantan Timur", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Abdul Wahab Sjahranie", "kota" => "Samarinda", "provinsi" => "Kalimantan Timur", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Balikpapan", "provinsi" => "Kalimantan Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Samarinda", "provinsi" => "Kalimantan Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Hermina", "kota" => "Balikpapan", "provinsi" => "Kalimantan Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Pertamina", "kota" => "Balikpapan", "provinsi" => "Kalimantan Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Tarakan", "kota" => "Tarakan", "provinsi" => "Kalimantan Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Berau", "kota" => "Tanjung Redeb", "provinsi" => "Kalimantan Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Kutai", "kota" => "Sendawar", "provinsi" => "Kalimantan Timur", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Tenggarong", "kota" => "Tenggarong", "provinsi" => "Kalimantan Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Bontang", "kota" => "Bontang", "provinsi" => "Kalimantan Timur", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Penajam", "kota" => "Penajam", "provinsi" => "Kalimantan Timur", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Tanjung Selor", "kota" => "Tanjung Selor", "provinsi" => "Kalimantan Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Nunukan", "kota" => "Nunukan", "provinsi" => "Kalimantan Utara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Malinau", "kota" => "Malinau", "provinsi" => "Kalimantan Utara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Bulungan", "kota" => "Tanjung Selor", "provinsi" => "Kalimantan Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Tana Tidung", "kota" => "Tideng Pale", "provinsi" => "Kalimantan Utara", "kelas" => "C", "jenis" => "Umum"],

  // ==================== SULAWESI UTARA ====================
  ["nama" => "RSUP Prof. Dr. R. D. Kandou", "kota" => "Manado", "provinsi" => "Sulawesi Utara", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Manado", "kota" => "Manado", "provinsi" => "Sulawesi Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Manado", "provinsi" => "Sulawesi Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Advent", "kota" => "Manado", "provinsi" => "Sulawesi Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS GMIM", "kota" => "Manado", "provinsi" => "Sulawesi Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Bitung", "kota" => "Bitung", "provinsi" => "Sulawesi Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Tomohon", "kota" => "Tomohon", "provinsi" => "Sulawesi Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Kotamobagu", "kota" => "Kotamobagu", "provinsi" => "Sulawesi Utara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Amurang", "kota" => "Amurang", "provinsi" => "Sulawesi Utara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Tahuna", "kota" => "Tahuna", "provinsi" => "Sulawesi Utara", "kelas" => "C", "jenis" => "Umum"],

  // ==================== GORONTALO ====================
  ["nama" => "RSUD Prof. Dr. H. Aloei Saboe", "kota" => "Gorontalo", "provinsi" => "Gorontalo", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Gorontalo", "kota" => "Gorontalo", "provinsi" => "Gorontalo", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Gorontalo", "provinsi" => "Gorontalo", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Limboto", "kota" => "Limboto", "provinsi" => "Gorontalo", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Marisa", "kota" => "Marisa", "provinsi" => "Gorontalo", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Suwawa", "kota" => "Suwawa", "provinsi" => "Gorontalo", "kelas" => "C", "jenis" => "Umum"],

  // ==================== SULAWESI TENGAH ====================
  ["nama" => "RSUD Undata", "kota" => "Palu", "provinsi" => "Sulawesi Tengah", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Undata", "kota" => "Palu", "provinsi" => "Sulawesi Tengah", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Palu", "provinsi" => "Sulawesi Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Bhayangkara", "kota" => "Palu", "provinsi" => "Sulawesi Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Luwuk", "kota" => "Luwuk", "provinsi" => "Sulawesi Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Poso", "kota" => "Poso", "provinsi" => "Sulawesi Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Tolitoli", "kota" => "Tolitoli", "provinsi" => "Sulawesi Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Buol", "kota" => "Buol", "provinsi" => "Sulawesi Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Donggala", "kota" => "Donggala", "provinsi" => "Sulawesi Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Parigi", "kota" => "Parigi", "provinsi" => "Sulawesi Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Banggai", "kota" => "Banggai", "provinsi" => "Sulawesi Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Morowali", "kota" => "Morowali", "provinsi" => "Sulawesi Tengah", "kelas" => "C", "jenis" => "Umum"],

  // ==================== SULAWESI SELATAN ====================
  ["nama" => "RSUP Dr. Wahidin Sudirohusodo", "kota" => "Makassar", "provinsi" => "Sulawesi Selatan", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Dr. Wahidin Sudirohusodo", "kota" => "Makassar", "provinsi" => "Sulawesi Selatan", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Makassar", "provinsi" => "Sulawesi Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Premier", "kota" => "Makassar", "provinsi" => "Sulawesi Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Hermina", "kota" => "Makassar", "provinsi" => "Sulawesi Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Stella Maris", "kota" => "Makassar", "provinsi" => "Sulawesi Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Akademis", "kota" => "Makassar", "provinsi" => "Sulawesi Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Labuang Baji", "kota" => "Makassar", "provinsi" => "Sulawesi Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Daya", "kota" => "Makassar", "provinsi" => "Sulawesi Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Haji", "kota" => "Makassar", "provinsi" => "Sulawesi Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Parepare", "kota" => "Parepare", "provinsi" => "Sulawesi Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Palopo", "kota" => "Palopo", "provinsi" => "Sulawesi Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Bulukumba", "kota" => "Bulukumba", "provinsi" => "Sulawesi Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Bantaeng", "kota" => "Bantaeng", "provinsi" => "Sulawesi Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Jeneponto", "kota" => "Jeneponto", "provinsi" => "Sulawesi Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Takalar", "kota" => "Takalar", "provinsi" => "Sulawesi Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Gowa", "kota" => "Sungguminasa", "provinsi" => "Sulawesi Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Sinjai", "kota" => "Sinjai", "provinsi" => "Sulawesi Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Bone", "kota" => "Watampone", "provinsi" => "Sulawesi Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Soppeng", "kota" => "Watansoppeng", "provinsi" => "Sulawesi Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Wajo", "kota" => "Sengkang", "provinsi" => "Sulawesi Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Sidrap", "kota" => "Pangkajene", "provinsi" => "Sulawesi Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Pinrang", "kota" => "Pinrang", "provinsi" => "Sulawesi Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Enrekang", "kota" => "Enrekang", "provinsi" => "Sulawesi Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Tana Toraja", "kota" => "Makale", "provinsi" => "Sulawesi Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Luwu", "kota" => "Belopa", "provinsi" => "Sulawesi Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Luwu Utara", "kota" => "Masamba", "provinsi" => "Sulawesi Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Luwu Timur", "kota" => "Malili", "provinsi" => "Sulawesi Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Maros", "kota" => "Maros", "provinsi" => "Sulawesi Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Pangkep", "kota" => "Pangkajene", "provinsi" => "Sulawesi Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Barru", "kota" => "Barru", "provinsi" => "Sulawesi Selatan", "kelas" => "C", "jenis" => "Umum"],

  // ==================== SULAWESI TENGGARA ====================
  ["nama" => "RSUD Bahteramas", "kota" => "Kendari", "provinsi" => "Sulawesi Tenggara", "kelas" => "A", "jenis" => "Umum"],
  ["nama" => "RSUD Kota Kendari", "kota" => "Kendari", "provinsi" => "Sulawesi Tenggara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Kendari", "provinsi" => "Sulawesi Tenggara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Bhayangkara", "kota" => "Kendari", "provinsi" => "Sulawesi Tenggara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Bau-Bau", "kota" => "Bau-Bau", "provinsi" => "Sulawesi Tenggara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Kolaka", "kota" => "Kolaka", "provinsi" => "Sulawesi Tenggara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Bombana", "kota" => "Rumbia", "provinsi" => "Sulawesi Tenggara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Muna", "kota" => "Raha", "provinsi" => "Sulawesi Tenggara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Buton", "kota" => "Pasarwajo", "provinsi" => "Sulawesi Tenggara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Wakatobi", "kota" => "Wangi-Wangi", "provinsi" => "Sulawesi Tenggara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Konawe", "kota" => "Unaaha", "provinsi" => "Sulawesi Tenggara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Konawe Selatan", "kota" => "Andoolo", "provinsi" => "Sulawesi Tenggara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Kolaka Utara", "kota" => "Lasusua", "provinsi" => "Sulawesi Tenggara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Konawe Utara", "kota" => "Wanggudu", "provinsi" => "Sulawesi Tenggara", "kelas" => "C", "jenis" => "Umum"],

  // ==================== MALUKU ====================
  ["nama" => "RSUD Dr. M. Haulussy", "kota" => "Ambon", "provinsi" => "Maluku", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Provinsi Maluku", "kota" => "Ambon", "provinsi" => "Maluku", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Ambon", "provinsi" => "Maluku", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Bhayangkara", "kota" => "Ambon", "provinsi" => "Maluku", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Tual", "kota" => "Tual", "provinsi" => "Maluku", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Masohi", "kota" => "Masohi", "provinsi" => "Maluku", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Namlea", "kota" => "Namlea", "provinsi" => "Maluku", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Dobo", "kota" => "Dobo", "provinsi" => "Maluku", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Saumlaki", "kota" => "Saumlaki", "provinsi" => "Maluku", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Bula", "kota" => "Bula", "provinsi" => "Maluku", "kelas" => "C", "jenis" => "Umum"],

  // ==================== MALUKU UTARA ====================
  ["nama" => "RSUD Chasan Boesoirie", "kota" => "Ternate", "provinsi" => "Maluku Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Ternate", "kota" => "Ternate", "provinsi" => "Maluku Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Ternate", "provinsi" => "Maluku Utara", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Tobelo", "kota" => "Tobelo", "provinsi" => "Maluku Utara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Sofifi", "kota" => "Sofifi", "provinsi" => "Maluku Utara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Sanana", "kota" => "Sanana", "provinsi" => "Maluku Utara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Taliabu", "kota" => "Bobong", "provinsi" => "Maluku Utara", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Morotai", "kota" => "Daruba", "provinsi" => "Maluku Utara", "kelas" => "C", "jenis" => "Umum"],

  // ==================== PAPUA ====================
  ["nama" => "RSUD Jayapura", "kota" => "Jayapura", "provinsi" => "Papua", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Provinsi Papua", "kota" => "Jayapura", "provinsi" => "Papua", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Jayapura", "provinsi" => "Papua", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Bhayangkara", "kota" => "Jayapura", "provinsi" => "Papua", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Biak", "kota" => "Biak", "provinsi" => "Papua", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Nabire", "kota" => "Nabire", "provinsi" => "Papua", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Merauke", "kota" => "Merauke", "provinsi" => "Papua", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Timika", "kota" => "Timika", "provinsi" => "Papua", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Wamena", "kota" => "Wamena", "provinsi" => "Papua", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Paniai", "kota" => "Enarotali", "provinsi" => "Papua", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Mimika", "kota" => "Timika", "provinsi" => "Papua", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Yahukimo", "kota" => "Dekai", "provinsi" => "Papua", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Boven Digoel", "kota" => "Tanah Merah", "provinsi" => "Papua", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Mappi", "kota" => "Kepi", "provinsi" => "Papua", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Asmat", "kota" => "Agats", "provinsi" => "Papua", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Mamberamo Raya", "kota" => "Burmeso", "provinsi" => "Papua", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Sarmi", "kota" => "Sarmi", "provinsi" => "Papua", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Keerom", "kota" => "Waris", "provinsi" => "Papua", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Waropen", "kota" => "Botawa", "provinsi" => "Papua", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Supiori", "kota" => "Sorendiweri", "provinsi" => "Papua", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Yapen", "kota" => "Serui", "provinsi" => "Papua", "kelas" => "C", "jenis" => "Umum"],

  // ==================== PAPUA BARAT ====================
  ["nama" => "RSUD Sorong", "kota" => "Sorong", "provinsi" => "Papua Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Provinsi Papua Barat", "kota" => "Manokwari", "provinsi" => "Papua Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Sorong", "provinsi" => "Papua Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Bhayangkara", "kota" => "Sorong", "provinsi" => "Papua Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Manokwari", "kota" => "Manokwari", "provinsi" => "Papua Barat", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Fakfak", "kota" => "Fakfak", "provinsi" => "Papua Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Kaimana", "kota" => "Kaimana", "provinsi" => "Papua Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Teluk Bintuni", "kota" => "Bintuni", "provinsi" => "Papua Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Teluk Wondama", "kota" => "Rasiei", "provinsi" => "Papua Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Raja Ampat", "kota" => "Waisai", "provinsi" => "Papua Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Sorong Selatan", "kota" => "Teminabuan", "provinsi" => "Papua Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Maybrat", "kota" => "Kumurkek", "provinsi" => "Papua Barat", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Tambrauw", "kota" => "Fef", "provinsi" => "Papua Barat", "kelas" => "C", "jenis" => "Umum"],

  // ==================== PAPUA BARAT DAYA ====================
  ["nama" => "RSUD Sorong", "kota" => "Sorong", "provinsi" => "Papua Barat Daya", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Provinsi Papua Barat Daya", "kota" => "Sorong", "provinsi" => "Papua Barat Daya", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RS Siloam", "kota" => "Sorong", "provinsi" => "Papua Barat Daya", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Maybrat", "kota" => "Kumurkek", "provinsi" => "Papua Barat Daya", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Sorong Selatan", "kota" => "Teminabuan", "provinsi" => "Papua Barat Daya", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Raja Ampat", "kota" => "Waisai", "provinsi" => "Papua Barat Daya", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Tambrauw", "kota" => "Fef", "provinsi" => "Papua Barat Daya", "kelas" => "C", "jenis" => "Umum"],

  // ==================== PAPUA TENGAH ====================
  ["nama" => "RSUD Nabire", "kota" => "Nabire", "provinsi" => "Papua Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Timika", "kota" => "Timika", "provinsi" => "Papua Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Paniai", "kota" => "Enarotali", "provinsi" => "Papua Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Mimika", "kota" => "Timika", "provinsi" => "Papua Tengah", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Dogiyai", "kota" => "Kigamani", "provinsi" => "Papua Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Intan Jaya", "kota" => "Sugapa", "provinsi" => "Papua Tengah", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Deiyai", "kota" => "Tigi", "provinsi" => "Papua Tengah", "kelas" => "C", "jenis" => "Umum"],

  // ==================== PAPUA PEGUNUNGAN ====================
  ["nama" => "RSUD Wamena", "kota" => "Wamena", "provinsi" => "Papua Pegunungan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Yahukimo", "kota" => "Dekai", "provinsi" => "Papua Pegunungan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Boven Digoel", "kota" => "Tanah Merah", "provinsi" => "Papua Pegunungan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Mappi", "kota" => "Kepi", "provinsi" => "Papua Pegunungan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Asmat", "kota" => "Agats", "provinsi" => "Papua Pegunungan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Mamberamo Raya", "kota" => "Burmeso", "provinsi" => "Papua Pegunungan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Sarmi", "kota" => "Sarmi", "provinsi" => "Papua Pegunungan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Keerom", "kota" => "Waris", "provinsi" => "Papua Pegunungan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Waropen", "kota" => "Botawa", "provinsi" => "Papua Pegunungan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Supiori", "kota" => "Sorendiweri", "provinsi" => "Papua Pegunungan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Yapen", "kota" => "Serui", "provinsi" => "Papua Pegunungan", "kelas" => "C", "jenis" => "Umum"],

  // ==================== PAPUA SELATAN ====================
  ["nama" => "RSUD Merauke", "kota" => "Merauke", "provinsi" => "Papua Selatan", "kelas" => "B", "jenis" => "Umum"],
  ["nama" => "RSUD Boven Digoel", "kota" => "Tanah Merah", "provinsi" => "Papua Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Mappi", "kota" => "Kepi", "provinsi" => "Papua Selatan", "kelas" => "C", "jenis" => "Umum"],
  ["nama" => "RSUD Asmat", "kota" => "Agats", "provinsi" => "Papua Selatan", "kelas" => "C", "jenis" => "Umum"]
];

?>