<?php

$peralatanMedis = [
  // ==================== ALAT SUNTIK & INFUS ====================
  ["nama" => "Suntikan (Syringe) 1 ml", "kategori" => "Alat Suntik", "fungsi" => "Menyuntikkan cairan/obat", "jenis" => "Disposable"],
  ["nama" => "Suntikan (Syringe) 3 ml", "kategori" => "Alat Suntik", "fungsi" => "Menyuntikkan cairan/obat", "jenis" => "Disposable"],
  ["nama" => "Suntikan (Syringe) 5 ml", "kategori" => "Alat Suntik", "fungsi" => "Menyuntikkan cairan/obat", "jenis" => "Disposable"],
  ["nama" => "Suntikan (Syringe) 10 ml", "kategori" => "Alat Suntik", "fungsi" => "Menyuntikkan cairan/obat", "jenis" => "Disposable"],
  ["nama" => "Suntikan (Syringe) 20 ml", "kategori" => "Alat Suntik", "fungsi" => "Menyuntikkan cairan/obat", "jenis" => "Disposable"],
  ["nama" => "Suntikan (Syringe) 50 ml", "kategori" => "Alat Suntik", "fungsi" => "Menyuntikkan cairan/obat", "jenis" => "Disposable"],
  ["nama" => "Suntikan Insulin", "kategori" => "Alat Suntik", "fungsi" => "Menyuntikkan insulin", "jenis" => "Disposable"],
  ["nama" => "Suntikan Tuberculin", "kategori" => "Alat Suntik", "fungsi" => "Uji tuberkulin", "jenis" => "Disposable"],
  ["nama" => "Jarum Suntik (Needle) 18G", "kategori" => "Alat Suntik", "fungsi" => "Jarum suntik", "jenis" => "Disposable"],
  ["nama" => "Jarum Suntik (Needle) 20G", "kategori" => "Alat Suntik", "fungsi" => "Jarum suntik", "jenis" => "Disposable"],
  ["nama" => "Jarum Suntik (Needle) 21G", "kategori" => "Alat Suntik", "fungsi" => "Jarum suntik", "jenis" => "Disposable"],
  ["nama" => "Jarum Suntik (Needle) 22G", "kategori" => "Alat Suntik", "fungsi" => "Jarum suntik", "jenis" => "Disposable"],
  ["nama" => "Jarum Suntik (Needle) 23G", "kategori" => "Alat Suntik", "fungsi" => "Jarum suntik", "jenis" => "Disposable"],
  ["nama" => "Jarum Suntik (Needle) 24G", "kategori" => "Alat Suntik", "fungsi" => "Jarum suntik", "jenis" => "Disposable"],
  ["nama" => "Jarum Suntik (Needle) 25G", "kategori" => "Alat Suntik", "fungsi" => "Jarum suntik", "jenis" => "Disposable"],
  ["nama" => "Jarum Suntik (Needle) 26G", "kategori" => "Alat Suntik", "fungsi" => "Jarum suntik", "jenis" => "Disposable"],
  ["nama" => "Jarum Suntik (Needle) 27G", "kategori" => "Alat Suntik", "fungsi" => "Jarum suntik", "jenis" => "Disposable"],
  ["nama" => "Infus Set", "kategori" => "Alat Infus", "fungsi" => "Memberikan cairan infus", "jenis" => "Disposable"],
  ["nama" => "Infus Set Makro", "kategori" => "Alat Infus", "fungsi" => "Memberikan cairan infus", "jenis" => "Disposable"],
  ["nama" => "Infus Set Mikro", "kategori" => "Alat Infus", "fungsi" => "Memberikan cairan infus", "jenis" => "Disposable"],
  ["nama" => "Infus Set Blood Set", "kategori" => "Alat Infus", "fungsi" => "Transfusi darah", "jenis" => "Disposable"],
  ["nama" => "Kateter Intravena (IV Catheter) 14G", "kategori" => "Alat Infus", "fungsi" => "Akses intravena", "jenis" => "Disposable"],
  ["nama" => "Kateter Intravena (IV Catheter) 16G", "kategori" => "Alat Infus", "fungsi" => "Akses intravena", "jenis" => "Disposable"],
  ["nama" => "Kateter Intravena (IV Catheter) 18G", "kategori" => "Alat Infus", "fungsi" => "Akses intravena", "jenis" => "Disposable"],
  ["nama" => "Kateter Intravena (IV Catheter) 20G", "kategori" => "Alat Infus", "fungsi" => "Akses intravena", "jenis" => "Disposable"],
  ["nama" => "Kateter Intravena (IV Catheter) 22G", "kategori" => "Alat Infus", "fungsi" => "Akses intravena", "jenis" => "Disposable"],
  ["nama" => "Kateter Intravena (IV Catheter) 24G", "kategori" => "Alat Infus", "fungsi" => "Akses intravena", "jenis" => "Disposable"],
  ["nama" => "Kateter Intravena (IV Catheter) 26G", "kategori" => "Alat Infus", "fungsi" => "Akses intravena", "jenis" => "Disposable"],
  ["nama" => "Selang Infus", "kategori" => "Alat Infus", "fungsi" => "Menyalurkan cairan infus", "jenis" => "Disposable"],
  ["nama" => "Three Way Stopcock", "kategori" => "Alat Infus", "fungsi" => "Percabangan infus", "jenis" => "Disposable"],
  ["nama" => "Extension Tube", "kategori" => "Alat Infus", "fungsi" => "Perpanjang selang infus", "jenis" => "Disposable"],
  ["nama" => "Infusion Pump", "kategori" => "Alat Infus", "fungsi" => "Mengontrol kecepatan infus", "jenis" => "Elektrik"],
  ["nama" => "Syringe Pump", "kategori" => "Alat Infus", "fungsi" => "Mengontrol kecepatan suntikan", "jenis" => "Elektrik"],
  ["nama" => "Blood Warmer", "kategori" => "Alat Infus", "fungsi" => "Menghangatkan darah", "jenis" => "Elektrik"],
  ["nama" => "Infus Warmer", "kategori" => "Alat Infus", "fungsi" => "Menghangatkan cairan infus", "jenis" => "Elektrik"],

  // ==================== ALAT DIAGNOSIS ====================
  ["nama" => "Stetoskop", "kategori" => "Alat Diagnosis", "fungsi" => "Mendengar detak jantung & paru", "jenis" => "Reusable"],
  ["nama" => "Stetoskop Elektronik", "kategori" => "Alat Diagnosis", "fungsi" => "Mendengar detak jantung digital", "jenis" => "Elektrik"],
  ["nama" => "Tensimeter Digital", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur tekanan darah", "jenis" => "Elektrik"],
  ["nama" => "Tensimeter Manual (Sphygmomanometer)", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur tekanan darah", "jenis" => "Reusable"],
  ["nama" => "Tensimeter Air Raksa", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur tekanan darah", "jenis" => "Reusable"],
  ["nama" => "Termometer Digital", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur suhu tubuh", "jenis" => "Elektrik"],
  ["nama" => "Termometer Infrared", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur suhu tanpa kontak", "jenis" => "Elektrik"],
  ["nama" => "Termometer Air Raksa", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur suhu tubuh", "jenis" => "Reusable"],
  ["nama" => "Termometer Telinga", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur suhu telinga", "jenis" => "Elektrik"],
  ["nama" => "Termometer Rektal", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur suhu rektal", "jenis" => "Reusable"],
  ["nama" => "Pulse Oximeter", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur saturasi oksigen", "jenis" => "Elektrik"],
  ["nama" => "Fetal Doppler", "kategori" => "Alat Diagnosis", "fungsi" => "Mendengar detak jantung janin", "jenis" => "Elektrik"],
  ["nama" => "CT Scanner", "kategori" => "Alat Diagnosis", "fungsi" => "Pencitraan organ dalam", "jenis" => "Elektrik"],
  ["nama" => "MRI Scanner", "kategori" => "Alat Diagnosis", "fungsi" => "Pencitraan organ dengan magnet", "jenis" => "Elektrik"],
  ["nama" => "USG (Ultrasonografi)", "kategori" => "Alat Diagnosis", "fungsi" => "Pencitraan dengan gelombang suara", "jenis" => "Elektrik"],
  ["nama" => "USG 2D", "kategori" => "Alat Diagnosis", "fungsi" => "Pencitraan 2 dimensi", "jenis" => "Elektrik"],
  ["nama" => "USG 3D", "kategori" => "Alat Diagnosis", "fungsi" => "Pencitraan 3 dimensi", "jenis" => "Elektrik"],
  ["nama" => "USG 4D", "kategori" => "Alat Diagnosis", "fungsi" => "Pencitraan 4 dimensi real-time", "jenis" => "Elektrik"],
  ["nama" => "Doppler USG", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur aliran darah", "jenis" => "Elektrik"],
  ["nama" => "Ekokardiografi", "kategori" => "Alat Diagnosis", "fungsi" => "USG jantung", "jenis" => "Elektrik"],
  ["nama" => "X-Ray (Rontgen)", "kategori" => "Alat Diagnosis", "fungsi" => "Pencitraan tulang & organ", "jenis" => "Elektrik"],
  ["nama" => "X-Ray Portable", "kategori" => "Alat Diagnosis", "fungsi" => "Rontgen portabel", "jenis" => "Elektrik"],
  ["nama" => "X-Ray Mobile", "kategori" => "Alat Diagnosis", "fungsi" => "Rontgen bergerak", "jenis" => "Elektrik"],
  ["nama" => "CT Scan 16 Slice", "kategori" => "Alat Diagnosis", "fungsi" => "CT scan 16 irisan", "jenis" => "Elektrik"],
  ["nama" => "CT Scan 64 Slice", "kategori" => "Alat Diagnosis", "fungsi" => "CT scan 64 irisan", "jenis" => "Elektrik"],
  ["nama" => "CT Scan 128 Slice", "kategori" => "Alat Diagnosis", "fungsi" => "CT scan 128 irisan", "jenis" => "Elektrik"],
  ["nama" => "CT Scan 256 Slice", "kategori" => "Alat Diagnosis", "fungsi" => "CT scan 256 irisan", "jenis" => "Elektrik"],
  ["nama" => "MRI 1.5 Tesla", "kategori" => "Alat Diagnosis", "fungsi" => "MRI medan magnet 1.5T", "jenis" => "Elektrik"],
  ["nama" => "MRI 3 Tesla", "kategori" => "Alat Diagnosis", "fungsi" => "MRI medan magnet 3T", "jenis" => "Elektrik"],
  ["nama" => "PET Scan", "kategori" => "Alat Diagnosis", "fungsi" => "Pencitraan metabolik", "jenis" => "Elektrik"],
  ["nama" => "SPECT Scan", "kategori" => "Alat Diagnosis", "fungsi" => "Pencitraan nuklir", "jenis" => "Elektrik"],
  ["nama" => "Mammografi", "kategori" => "Alat Diagnosis", "fungsi" => "Pencitraan payudara", "jenis" => "Elektrik"],
  ["nama" => "Densitometri Tulang (BMD)", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur kepadatan tulang", "jenis" => "Elektrik"],
  ["nama" => "Panoramic X-Ray", "kategori" => "Alat Diagnosis", "fungsi" => "Rontgen gigi panoramik", "jenis" => "Elektrik"],
  ["nama" => "Cephalometric X-Ray", "kategori" => "Alat Diagnosis", "fungsi" => "Rontgen kepala lateral", "jenis" => "Elektrik"],
  ["nama" => "Dental X-Ray", "kategori" => "Alat Diagnosis", "fungsi" => "Rontgen gigi", "jenis" => "Elektrik"],
  ["nama" => "Fluoroskopi", "kategori" => "Alat Diagnosis", "fungsi" => "X-ray real-time", "jenis" => "Elektrik"],
  ["nama" => "Angiografi", "kategori" => "Alat Diagnosis", "fungsi" => "Pencitraan pembuluh darah", "jenis" => "Elektrik"],
  ["nama" => "Ophthalmoscope", "kategori" => "Alat Diagnosis", "fungsi" => "Memeriksa retina mata", "jenis" => "Reusable"],
  ["nama" => "Otoscope", "kategori" => "Alat Diagnosis", "fungsi" => "Memeriksa telinga", "jenis" => "Reusable"],
  ["nama" => "Rhinoscope", "kategori" => "Alat Diagnosis", "fungsi" => "Memeriksa hidung", "jenis" => "Reusable"],
  ["nama" => "Laringoscope", "kategori" => "Alat Diagnosis", "fungsi" => "Memeriksa laring", "jenis" => "Reusable"],
  ["nama" => "Endoscope", "kategori" => "Alat Diagnosis", "fungsi" => "Melihat organ dalam", "jenis" => "Reusable"],
  ["nama" => "Gastroscope", "kategori" => "Alat Diagnosis", "fungsi" => "Endoskopi lambung", "jenis" => "Reusable"],
  ["nama" => "Kolonoscope", "kategori" => "Alat Diagnosis", "fungsi" => "Endoskopi usus besar", "jenis" => "Reusable"],
  ["nama" => "Bronchoscope", "kategori" => "Alat Diagnosis", "fungsi" => "Endoskopi saluran napas", "jenis" => "Reusable"],
  ["nama" => "Cystoscope", "kategori" => "Alat Diagnosis", "fungsi" => "Endoskopi kandung kemih", "jenis" => "Reusable"],
  ["nama" => "Hysteroscope", "kategori" => "Alat Diagnosis", "fungsi" => "Endoskopi rahim", "jenis" => "Reusable"],
  ["nama" => "Laparoscope", "kategori" => "Alat Diagnosis", "fungsi" => "Endoskopi rongga perut", "jenis" => "Reusable"],
  ["nama" => "Arthroscope", "kategori" => "Alat Diagnosis", "fungsi" => "Endoskopi sendi", "jenis" => "Reusable"],
  ["nama" => "Thoracoscope", "kategori" => "Alat Diagnosis", "fungsi" => "Endoskopi rongga dada", "jenis" => "Reusable"],
  ["nama" => "Mediastinoscope", "kategori" => "Alat Diagnosis", "fungsi" => "Endoskopi mediastinum", "jenis" => "Reusable"],
  ["nama" => "Nephroscope", "kategori" => "Alat Diagnosis", "fungsi" => "Endoskopi ginjal", "jenis" => "Reusable"],
  ["nama" => "Choledochoscope", "kategori" => "Alat Diagnosis", "fungsi" => "Endoskopi saluran empedu", "jenis" => "Reusable"],
  ["nama" => "Duodenoscope", "kategori" => "Alat Diagnosis", "fungsi" => "Endoskopi duodenum", "jenis" => "Reusable"],
  ["nama" => "Enteroscope", "kategori" => "Alat Diagnosis", "fungsi" => "Endoskopi usus halus", "jenis" => "Reusable"],
  ["nama" => "Proctoscope", "kategori" => "Alat Diagnosis", "fungsi" => "Endoskopi rektum", "jenis" => "Reusable"],
  ["nama" => "Anoscope", "kategori" => "Alat Diagnosis", "fungsi" => "Endoskopi anus", "jenis" => "Reusable"],
  ["nama" => "Sigmoidoscope", "kategori" => "Alat Diagnosis", "fungsi" => "Endoskopi sigmoid", "jenis" => "Reusable"],
  ["nama" => "Electroencephalogram (EEG)", "kategori" => "Alat Diagnosis", "fungsi" => "Merekam aktivitas otak", "jenis" => "Elektrik"],
  ["nama" => "Electromyogram (EMG)", "kategori" => "Alat Diagnosis", "fungsi" => "Merekam aktivitas otot", "jenis" => "Elektrik"],
  ["nama" => "Electrocardiogram (ECG/EKG)", "kategori" => "Alat Diagnosis", "fungsi" => "Merekam aktivitas jantung", "jenis" => "Elektrik"],
  ["nama" => "Holter Monitor", "kategori" => "Alat Diagnosis", "fungsi" => "ECG 24 jam", "jenis" => "Elektrik"],
  ["nama" => "Event Monitor", "kategori" => "Alat Diagnosis", "fungsi" => "ECG event-based", "jenis" => "Elektrik"],
  ["nama" => "Treadmill Test", "kategori" => "Alat Diagnosis", "fungsi" => "Uji beban jantung", "jenis" => "Elektrik"],
  ["nama" => "Spirometer", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur fungsi paru", "jenis" => "Elektrik"],
  ["nama" => "Peak Flow Meter", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur aliran puncak napas", "jenis" => "Reusable"],
  ["nama" => "Pletismograf", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur volume paru", "jenis" => "Elektrik"],
  ["nama" => "Body Plethysmograph", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur resistensi saluran napas", "jenis" => "Elektrik"],
  ["nama" => "Audiometer", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur pendengaran", "jenis" => "Elektrik"],
  ["nama" => "Tympanometer", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur fungsi telinga tengah", "jenis" => "Elektrik"],
  ["nama" => "Refraktometer", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur refraksi mata", "jenis" => "Elektrik"],
  ["nama" => "Autorefraktometer", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur refraksi otomatis", "jenis" => "Elektrik"],
  ["nama" => "Keratomater", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur kornea", "jenis" => "Elektrik"],
  ["nama" => "Tonometri", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur tekanan bola mata", "jenis" => "Elektrik"],
  ["nama" => "Perimetri", "kategori" => "Alat Diagnosis", "fungsi" => "Mengukur lapang pandang", "jenis" => "Elektrik"],
  ["nama" => "Slit Lamp", "kategori" => "Alat Diagnosis", "fungsi" => "Memeriksa mata dengan slit", "jenis" => "Elektrik"],
  ["nama" => "Funduskamera", "kategori" => "Alat Diagnosis", "fungsi" => "Foto fundus mata", "jenis" => "Elektrik"],
  ["nama" => "OCT (Optical Coherence Tomography)", "kategori" => "Alat Diagnosis", "fungsi" => "Pencitraan retina", "jenis" => "Elektrik"],

  // ==================== ALAT BEDAH ====================
  ["nama" => "Scalpel (Pisau Bedah)", "kategori" => "Alat Bedah", "fungsi" => "Mengiris jaringan", "jenis" => "Reusable"],
  ["nama" => "Scalpel Handle No. 3", "kategori" => "Alat Bedah", "fungsi" => "Pegangan pisau bedah", "jenis" => "Reusable"],
  ["nama" => "Scalpel Handle No. 4", "kategori" => "Alat Bedah", "fungsi" => "Pegangan pisau bedah", "jenis" => "Reusable"],
  ["nama" => "Scalpel Blade No. 10", "kategori" => "Alat Bedah", "fungsi" => "Mata pisau bedah", "jenis" => "Disposable"],
  ["nama" => "Scalpel Blade No. 11", "kategori" => "Alat Bedah", "fungsi" => "Mata pisau bedah", "jenis" => "Disposable"],
  ["nama" => "Scalpel Blade No. 15", "kategori" => "Alat Bedah", "fungsi" => "Mata pisau bedah", "jenis" => "Disposable"],
  ["nama" => "Scalpel Blade No. 20", "kategori" => "Alat Bedah", "fungsi" => "Mata pisau bedah", "jenis" => "Disposable"],
  ["nama" => "Scalpel Blade No. 22", "kategori" => "Alat Bedah", "fungsi" => "Mata pisau bedah", "jenis" => "Disposable"],
  ["nama" => "Scalpel Blade No. 23", "kategori" => "Alat Bedah", "fungsi" => "Mata pisau bedah", "jenis" => "Disposable"],
  ["nama" => "Scalpel Blade No. 24", "kategori" => "Alat Bedah", "fungsi" => "Mata pisau bedah", "jenis" => "Disposable"],
  ["nama" => "Gunting Bedah Lurus", "kategori" => "Alat Bedah", "fungsi" => "Menggunting jaringan", "jenis" => "Reusable"],
  ["nama" => "Gunting Bedah Bengkok", "kategori" => "Alat Bedah", "fungsi" => "Menggunting jaringan", "jenis" => "Reusable"],
  ["nama" => "Gunting Metzenbaum", "kategori" => "Alat Bedah", "fungsi" => "Menggunting jaringan halus", "jenis" => "Reusable"],
  ["nama" => "Gunting Mayo", "kategori" => "Alat Bedah", "fungsi" => "Menggunting jaringan tebal", "jenis" => "Reusable"],
  ["nama" => "Gunting Bandage", "kategori" => "Alat Bedah", "fungsi" => "Menggunting perban", "jenis" => "Reusable"],
  ["nama" => "Gunting Episiotomi", "kategori" => "Alat Bedah", "fungsi" => "Menggunting perineum", "jenis" => "Reusable"],
  ["nama" => "Pinset Anatomis", "kategori" => "Alat Bedah", "fungsi" => "Menjepit jaringan halus", "jenis" => "Reusable"],
  ["nama" => "Pinset Chirurgis", "kategori" => "Alat Bedah", "fungsi" => "Menjepit jaringan", "jenis" => "Reusable"],
  ["nama" => "Pinset Sirurgis", "kategori" => "Alat Bedah", "fungsi" => "Menjepit jaringan", "jenis" => "Reusable"],
  ["nama" => "Pinset Arteri", "kategori" => "Alat Bedah", "fungsi" => "Menjepit pembuluh darah", "jenis" => "Reusable"],
  ["nama" => "Klem Arteri (Artery Forceps)", "kategori" => "Alat Bedah", "fungsi" => "Menjepit pembuluh darah", "jenis" => "Reusable"],
  ["nama" => "Klem Hemostatik Lurus", "kategori" => "Alat Bedah", "fungsi" => "Menghentikan perdarahan", "jenis" => "Reusable"],
  ["nama" => "Klem Hemostatik Bengkok", "kategori" => "Alat Bedah", "fungsi" => "Menghentikan perdarahan", "jenis" => "Reusable"],
  ["nama" => "Klem Kocher", "kategori" => "Alat Bedah", "fungsi" => "Menjepit jaringan", "jenis" => "Reusable"],
  ["nama" => "Klem Allis", "kategori" => "Alat Bedah", "fungsi" => "Menjepit jaringan", "jenis" => "Reusable"],
  ["nama" => "Klem Babcock", "kategori" => "Alat Bedah", "fungsi" => "Menjepit usus", "jenis" => "Reusable"],
  ["nama" => "Klem Kelly", "kategori" => "Alat Bedah", "fungsi" => "Menjepit pembuluh darah", "jenis" => "Reusable"],
  ["nama" => "Klem Rochester-Pean", "kategori" => "Alat Bedah", "fungsi" => "Menjepit pembuluh darah", "jenis" => "Reusable"],
  ["nama" => "Klem Rochester-Carmalt", "kategori" => "Alat Bedah", "fungsi" => "Menjepit jaringan", "jenis" => "Reusable"],
  ["nama" => "Klem Mosquito", "kategori" => "Alat Bedah", "fungsi" => "Menjepit pembuluh darah kecil", "jenis" => "Reusable"],
  ["nama" => "Klem Backhaus", "kategori" => "Alat Bedah", "fungsi" => "Menjepit kain", "jenis" => "Reusable"],
  ["nama" => "Klem Doyen", "kategori" => "Alat Bedah", "fungsi" => "Menjepit rahim", "jenis" => "Reusable"],
  ["nama" => "Klem Towel", "kategori" => "Alat Bedah", "fungsi" => "Menjepit kain operasi", "jenis" => "Reusable"],
  ["nama" => "Needle Holder (Pemegang Jarum)", "kategori" => "Alat Bedah", "fungsi" => "Memegang jarum jahit", "jenis" => "Reusable"],
  ["nama" => "Needle Holder Mayo-Hegar", "kategori" => "Alat Bedah", "fungsi" => "Memegang jarum jahit", "jenis" => "Reusable"],
  ["nama" => "Needle Holder Mathieu", "kategori" => "Alat Bedah", "fungsi" => "Memegang jarum jahit", "jenis" => "Reusable"],
  ["nama" => "Needle Holder Castroviejo", "kategori" => "Alat Bedah", "fungsi" => "Memegang jarum jahit halus", "jenis" => "Reusable"],
  ["nama" => "Jarum Jahit Bedah", "kategori" => "Alat Bedah", "fungsi" => "Menjahit luka", "jenis" => "Disposable"],
  ["nama" => "Benang Jahit Bedah", "kategori" => "Alat Bedah", "fungsi" => "Menjahit luka", "jenis" => "Disposable"],
  ["nama" => "Benang Catgut", "kategori" => "Alat Bedah", "fungsi" => "Menjahit luka", "jenis" => "Disposable"],
  ["nama" => "Benang Silk", "kategori" => "Alat Bedah", "fungsi" => "Menjahit luka", "jenis" => "Disposable"],
  ["nama" => "Benang Nylon", "kategori" => "Alat Bedah", "fungsi" => "Menjahit luka", "jenis" => "Disposable"],
  ["nama" => "Benang Vicryl", "kategori" => "Alat Bedah", "fungsi" => "Menjahit luka", "jenis" => "Disposable"],
  ["nama" => "Benang Monocryl", "kategori" => "Alat Bedah", "fungsi" => "Menjahit luka", "jenis" => "Disposable"],
  ["nama" => "Benang PDS", "kategori" => "Alat Bedah", "fungsi" => "Menjahit luka", "jenis" => "Disposable"],
  ["nama" => "Retraktor (Retractor)", "kategori" => "Alat Bedah", "fungsi" => "Menarik jaringan", "jenis" => "Reusable"],
  ["nama" => "Retraktor Langenbeck", "kategori" => "Alat Bedah", "fungsi" => "Menarik jaringan", "jenis" => "Reusable"],
  ["nama" => "Retraktor Deaver", "kategori" => "Alat Bedah", "fungsi" => "Menarik jaringan", "jenis" => "Reusable"],
  ["nama" => "Retraktor Army-Navy", "kategori" => "Alat Bedah", "fungsi" => "Menarik jaringan", "jenis" => "Reusable"],
  ["nama" => "Retraktor Richardson", "kategori" => "Alat Bedah", "fungsi" => "Menarik jaringan", "jenis" => "Reusable"],
  ["nama" => "Retraktor Weitlaner", "kategori" => "Alat Bedah", "fungsi" => "Menarik jaringan", "jenis" => "Reusable"],
  ["nama" => "Retraktor Balfour", "kategori" => "Alat Bedah", "fungsi" => "Menarik dinding perut", "jenis" => "Reusable"],
  ["nama" => "Retraktor Finochietto", "kategori" => "Alat Bedah", "fungsi" => "Menarik tulang rusuk", "jenis" => "Reusable"],
  ["nama" => "Retraktor Gelpi", "kategori" => "Alat Bedah", "fungsi" => "Menarik jaringan", "jenis" => "Reusable"],
  ["nama" => "Retraktor Volkmann", "kategori" => "Alat Bedah", "fungsi" => "Menarik jaringan", "jenis" => "Reusable"],
  ["nama" => "Retraktor Hohmann", "kategori" => "Alat Bedah", "fungsi" => "Menarik tulang", "jenis" => "Reusable"],
  ["nama" => "Bone Cutter", "kategori" => "Alat Bedah", "fungsi" => "Memotong tulang", "jenis" => "Reusable"],
  ["nama" => "Bone Saw", "kategori" => "Alat Bedah", "fungsi" => "Menggergaji tulang", "jenis" => "Reusable"],
  ["nama" => "Bone Rongeur", "kategori" => "Alat Bedah", "fungsi" => "Menggigit tulang", "jenis" => "Reusable"],
  ["nama" => "Bone Curette", "kategori" => "Alat Bedah", "fungsi" => "Mengeruk tulang", "jenis" => "Reusable"],
  ["nama" => "Bone Chisel", "kategori" => "Alat Bedah", "fungsi" => "Memahat tulang", "jenis" => "Reusable"],
  ["nama" => "Bone Mallet", "kategori" => "Alat Bedah", "fungsi" => "Memukul pahat tulang", "jenis" => "Reusable"],
  ["nama" => "Bone Drill", "kategori" => "Alat Bedah", "fungsi" => "Melubangi tulang", "jenis" => "Elektrik"],
  ["nama" => "Bone Screw", "kategori" => "Alat Bedah", "fungsi" => "Sekrup tulang", "jenis" => "Implant"],
  ["nama" => "Bone Plate", "kategori" => "Alat Bedah", "fungsi" => "Plat tulang", "jenis" => "Implant"],
  ["nama" => "Bone Wire", "kategori" => "Alat Bedah", "fungsi" => "Kawat tulang", "jenis" => "Implant"],
  ["nama" => "Bone Nail", "kategori" => "Alat Bedah", "fungsi" => "Paku tulang", "jenis" => "Implant"],
  ["nama" => "Bone Graft", "kategori" => "Alat Bedah", "fungsi" => "Cangkok tulang", "jenis" => "Implant"],
  ["nama" => "Suction Tip", "kategori" => "Alat Bedah", "fungsi" => "Menyedot cairan", "jenis" => "Reusable"],
  ["nama" => "Suction Pump", "kategori" => "Alat Bedah", "fungsi" => "Menyedot cairan", "jenis" => "Elektrik"],
  ["nama" => "Electrocautery", "kategori" => "Alat Bedah", "fungsi" => "Membakar jaringan", "jenis" => "Elektrik"],
  ["nama" => "Electrosurgical Unit (ESU)", "kategori" => "Alat Bedah", "fungsi" => "Bedah listrik", "jenis" => "Elektrik"],
  ["nama" => "Ligasure", "kategori" => "Alat Bedah", "fungsi" => "Menutup pembuluh darah", "jenis" => "Elektrik"],
  ["nama" => "Harmonic Scalpel", "kategori" => "Alat Bedah", "fungsi" => "Bedah ultrasonik", "jenis" => "Elektrik"],
  ["nama" => "Cryosurgery Unit", "kategori" => "Alat Bedah", "fungsi" => "Bedah beku", "jenis" => "Elektrik"],
  ["nama" => "Laser Surgery Unit", "kategori" => "Alat Bedah", "fungsi" => "Bedah laser", "jenis" => "Elektrik"],
  ["nama" => "Microscope Bedah", "kategori" => "Alat Bedah", "fungsi" => "Mikroskop operasi", "jenis" => "Elektrik"],
  ["nama" => "Operating Table", "kategori" => "Alat Bedah", "fungsi" => "Meja operasi", "jenis" => "Elektrik"],
  ["nama" => "Operating Lamp", "kategori" => "Alat Bedah", "fungsi" => "Lampu operasi", "jenis" => "Elektrik"],
  ["nama" => "Mayo Stand", "kategori" => "Alat Bedah", "fungsi" => "Meja alat bedah", "jenis" => "Reusable"],
  ["nama" => "Instrument Trolley", "kategori" => "Alat Bedah", "fungsi" => "Troli instrumen", "jenis" => "Reusable"],
  ["nama" => "Kidney Dish", "kategori" => "Alat Bedah", "fungsi" => "Wadah alat bedah", "jenis" => "Reusable"],
  ["nama" => "Gallipot", "kategori" => "Alat Bedah", "fungsi" => "Wadah larutan", "jenis" => "Reusable"],
  ["nama" => "Drape", "kategori" => "Alat Bedah", "fungsi" => "Kain penutup operasi", "jenis" => "Disposable"],
  ["nama" => "Sterile Gown", "kategori" => "Alat Bedah", "fungsi" => "Gaun steril", "jenis" => "Disposable"],
  ["nama" => "Sterile Gloves", "kategori" => "Alat Bedah", "fungsi" => "Sarung tangan steril", "jenis" => "Disposable"],
  ["nama" => "Surgical Mask", "kategori" => "Alat Bedah", "fungsi" => "Masker bedah", "jenis" => "Disposable"],
  ["nama" => "Surgical Cap", "kategori" => "Alat Bedah", "fungsi" => "Topi bedah", "jenis" => "Disposable"],
  ["nama" => "Shoe Cover", "kategori" => "Alat Bedah", "fungsi" => "Penutup sepatu", "jenis" => "Disposable"],

  // ==================== ALAT MONITORING ====================
  ["nama" => "Patient Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor tanda vital", "jenis" => "Elektrik"],
  ["nama" => "Vital Sign Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor tanda vital", "jenis" => "Elektrik"],
  ["nama" => "ECG Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor jantung", "jenis" => "Elektrik"],
  ["nama" => "SpO2 Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor saturasi oksigen", "jenis" => "Elektrik"],
  ["nama" => "Capnograph", "kategori" => "Alat Monitoring", "fungsi" => "Monitor CO2", "jenis" => "Elektrik"],
  ["nama" => "Anesthesia Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor anestesi", "jenis" => "Elektrik"],
  ["nama" => "Fetal Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor janin", "jenis" => "Elektrik"],
  ["nama" => "Cardiotocography (CTG)", "kategori" => "Alat Monitoring", "fungsi" => "Monitor detak jantung janin", "jenis" => "Elektrik"],
  ["nama" => "Intracranial Pressure Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor tekanan intrakranial", "jenis" => "Elektrik"],
  ["nama" => "Central Venous Pressure Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor CVP", "jenis" => "Elektrik"],
  ["nama" => "Arterial Blood Pressure Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor tekanan arteri", "jenis" => "Elektrik"],
  ["nama" => "Pulmonary Artery Catheter", "kategori" => "Alat Monitoring", "fungsi" => "Monitor arteri pulmonalis", "jenis" => "Disposable"],
  ["nama" => "Cardiac Output Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor curah jantung", "jenis" => "Elektrik"],
  ["nama" => "Bispectral Index Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor kedalaman anestesi", "jenis" => "Elektrik"],
  ["nama" => "Neuromuscular Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor blok neuromuskular", "jenis" => "Elektrik"],
  ["nama" => "Temperature Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor suhu", "jenis" => "Elektrik"],
  ["nama" => "Blood Glucose Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor gula darah", "jenis" => "Elektrik"],
  ["nama" => "Continuous Glucose Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor gula darah kontinu", "jenis" => "Elektrik"],
  ["nama" => "Holter Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor ECG 24 jam", "jenis" => "Elektrik"],
  ["nama" => "Telemetry Monitor", "kategori" => "Alat Monitoring", "fungsi" => "Monitor jarak jauh", "jenis" => "Elektrik"],

  // ==================== ALAT TERAPI ====================
  ["nama" => "Ventilator", "kategori" => "Alat Terapi", "fungsi" => "Bantuan napas", "jenis" => "Elektrik"],
  ["nama" => "Ventilator ICU", "kategori" => "Alat Terapi", "fungsi" => "Ventilasi ICU", "jenis" => "Elektrik"],
  ["nama" => "Ventilator Portable", "kategori" => "Alat Terapi", "fungsi" => "Ventilasi portabel", "jenis" => "Elektrik"],
  ["nama" => "CPAP Machine", "kategori" => "Alat Terapi", "fungsi" => "Terapi sleep apnea", "jenis" => "Elektrik"],
  ["nama" => "BiPAP Machine", "kategori" => "Alat Terapi", "fungsi" => "Terapi napas bi-level", "jenis" => "Elektrik"],
  ["nama" => "Nebulizer", "kategori" => "Alat Terapi", "fungsi" => "Terapi inhalasi", "jenis" => "Elektrik"],
  ["nama" => "Nebulizer Ultrasonik", "kategori" => "Alat Terapi", "fungsi" => "Terapi inhalasi ultrasonik", "jenis" => "Elektrik"],
  ["nama" => "Oxygen Concentrator", "kategori" => "Alat Terapi", "fungsi" => "Konsentrator oksigen", "jenis" => "Elektrik"],
  ["nama" => "Oxygen Cylinder", "kategori" => "Alat Terapi", "fungsi" => "Tabung oksigen", "jenis" => "Reusable"],
  ["nama" => "Oxygen Regulator", "kategori" => "Alat Terapi", "fungsi" => "Regulator oksigen", "jenis" => "Reusable"],
  ["nama" => "Nasal Cannula", "kategori" => "Alat Terapi", "fungsi" => "Kanul hidung oksigen", "jenis" => "Disposable"],
  ["nama" => "Oxygen Mask", "kategori" => "Alat Terapi", "fungsi" => "Masker oksigen", "jenis" => "Disposable"],
  ["nama" => "Venturi Mask", "kategori" => "Alat Terapi", "fungsi" => "Masker venturi", "jenis" => "Disposable"],
  ["nama" => "Non-Rebreathing Mask", "kategori" => "Alat Terapi", "fungsi" => "Masker non-rebreathing", "jenis" => "Disposable"],
  ["nama" => "Partial Rebreather Mask", "kategori" => "Alat Terapi", "fungsi" => "Masker partial rebreather", "jenis" => "Disposable"],
  ["nama" => "Simple Face Mask", "kategori" => "Alat Terapi", "fungsi" => "Masker oksigen sederhana", "jenis" => "Disposable"],
  ["nama" => "T-Piece", "kategori" => "Alat Terapi", "fungsi" => "Konektor oksigen", "jenis" => "Disposable"],
  ["nama" => "Ambu Bag", "kategori" => "Alat Terapi", "fungsi" => "Ventilasi manual", "jenis" => "Reusable"],
  ["nama" => "Bag Valve Mask (BVM)", "kategori" => "Alat Terapi", "fungsi" => "Ventilasi manual", "jenis" => "Disposable"],
  ["nama" => "Laryngeal Mask Airway (LMA)", "kategori" => "Alat Terapi", "fungsi" => "Jalan napas", "jenis" => "Disposable"],
  ["nama" => "Oropharyngeal Airway (OPA)", "kategori" => "Alat Terapi", "fungsi" => "Jalan napas oral", "jenis" => "Disposable"],
  ["nama" => "Nasopharyngeal Airway (NPA)", "kategori" => "Alat Terapi", "fungsi" => "Jalan napas nasal", "jenis" => "Disposable"],
  ["nama" => "Endotracheal Tube (ETT)", "kategori" => "Alat Terapi", "fungsi" => "Pipa endotrakeal", "jenis" => "Disposable"],
  ["nama" => "Tracheostomy Tube", "kategori" => "Alat Terapi", "fungsi" => "Pipa trakeostomi", "jenis" => "Disposable"],
  ["nama" => "Laryngoscope", "kategori" => "Alat Terapi", "fungsi" => "Intubasi", "jenis" => "Reusable"],
  ["nama" => "Video Laryngoscope", "kategori" => "Alat Terapi", "fungsi" => "Intubasi video", "jenis" => "Elektrik"],
  ["nama" => "Suction Machine", "kategori" => "Alat Terapi", "fungsi" => "Menyedot lendir", "jenis" => "Elektrik"],
  ["nama" => "Suction Catheter", "kategori" => "Alat Terapi", "fungsi" => "Kateter suction", "jenis" => "Disposable"],
  ["nama" => "Yankauer Suction", "kategori" => "Alat Terapi", "fungsi" => "Suction oral", "jenis" => "Disposable"],
  ["nama" => "Defibrillator", "kategori" => "Alat Terapi", "fungsi" => "Kejut listrik jantung", "jenis" => "Elektrik"],
  ["nama" => "AED (Automated External Defibrillator)", "kategori" => "Alat Terapi", "fungsi" => "Defibrilasi otomatis", "jenis" => "Elektrik"],
  ["nama" => "Cardioversion Machine", "kategori" => "Alat Terapi", "fungsi" => "Kardioversi", "jenis" => "Elektrik"],
  ["nama" => "Pacemaker", "kategori" => "Alat Terapi", "fungsi" => "Alat pacu jantung", "jenis" => "Implant"],
  ["nama" => "External Pacemaker", "kategori" => "Alat Terapi", "fungsi" => "Pacu jantung eksternal", "jenis" => "Elektrik"],
  ["nama" => "ICD (Implantable Cardioverter-Defibrillator)", "kategori" => "Alat Terapi", "fungsi" => "Defibrilator implan", "jenis" => "Implant"],
  ["nama" => "CRT (Cardiac Resynchronization Therapy)", "kategori" => "Alat Terapi", "fungsi" => "Terapi resinkronisasi jantung", "jenis" => "Implant"],
  ["nama" => "Dialysis Machine", "kategori" => "Alat Terapi", "fungsi" => "Cuci darah", "jenis" => "Elektrik"],
  ["nama" => "Hemodialisis Machine", "kategori" => "Alat Terapi", "fungsi" => "Hemodialisis", "jenis" => "Elektrik"],
  ["nama" => "Peritoneal Dialysis Set", "kategori" => "Alat Terapi", "fungsi" => "Dialisis peritoneum", "jenis" => "Disposable"],
  ["nama" => "CRRT Machine", "kategori" => "Alat Terapi", "fungsi" => "Continuous Renal Replacement Therapy", "jenis" => "Elektrik"],
  ["nama" => "Plasmapheresis Machine", "kategori" => "Alat Terapi", "fungsi" => "Plasmaferesis", "jenis" => "Elektrik"],
  ["nama" => "Phototherapy Unit", "kategori" => "Alat Terapi", "fungsi" => "Terapi cahaya", "jenis" => "Elektrik"],
  ["nama" => "UVB Therapy", "kategori" => "Alat Terapi", "fungsi" => "Terapi UVB", "jenis" => "Elektrik"],
  ["nama" => "PUVA Therapy", "kategori" => "Alat Terapi", "fungsi" => "Terapi PUVA", "jenis" => "Elektrik"],
  ["nama" => "Laser Therapy", "kategori" => "Alat Terapi", "fungsi" => "Terapi laser", "jenis" => "Elektrik"],
  ["nama" => "TENS Unit", "kategori" => "Alat Terapi", "fungsi" => "Stimulasi saraf listrik", "jenis" => "Elektrik"],
  ["nama" => "EMS Unit", "kategori" => "Alat Terapi", "fungsi" => "Stimulasi otot listrik", "jenis" => "Elektrik"],
  ["nama" => "Ultrasound Therapy", "kategori" => "Alat Terapi", "fungsi" => "Terapi ultrasonik", "jenis" => "Elektrik"],
  ["nama" => "Shortwave Diathermy", "kategori" => "Alat Terapi", "fungsi" => "Diatermi gelombang pendek", "jenis" => "Elektrik"],
  ["nama" => "Microwave Diathermy", "kategori" => "Alat Terapi", "fungsi" => "Diatermi gelombang mikro", "jenis" => "Elektrik"],
  ["nama" => "Infrared Lamp", "kategori" => "Alat Terapi", "fungsi" => "Terapi inframerah", "jenis" => "Elektrik"],
  ["nama" => "Traction Unit", "kategori" => "Alat Terapi", "fungsi" => "Traksi tulang", "jenis" => "Elektrik"],
  ["nama" => "Intermittent Pneumatic Compression", "kategori" => "Alat Terapi", "fungsi" => "Kompresi pneumatik", "jenis" => "Elektrik"],
  ["nama" => "Sequential Compression Device", "kategori" => "Alat Terapi", "fungsi" => "Kompresi sekuensial", "jenis" => "Elektrik"],
  ["nama" => "Continuous Passive Motion (CPM)", "kategori" => "Alat Terapi", "fungsi" => "Gerak pasif kontinu", "jenis" => "Elektrik"],
  ["nama" => "Hyperbaric Oxygen Chamber", "kategori" => "Alat Terapi", "fungsi" => "Terapi oksigen hiperbarik", "jenis" => "Elektrik"],
  ["nama" => "Incubator", "kategori" => "Alat Terapi", "fungsi" => "Inkubator bayi", "jenis" => "Elektrik"],
  ["nama" => "Infant Warmer", "kategori" => "Alat Terapi", "fungsi" => "Penghangat bayi", "jenis" => "Elektrik"],
  ["nama" => "Radiant Warmer", "kategori" => "Alat Terapi", "fungsi" => "Penghangat radian", "jenis" => "Elektrik"],
  ["nama" => "Phototherapy Incubator", "kategori" => "Alat Terapi", "fungsi" => "Inkubator dengan fototerapi", "jenis" => "Elektrik"],
  ["nama" => "Resuscitaire", "kategori" => "Alat Terapi", "fungsi" => "Resusitasi bayi", "jenis" => "Elektrik"],
  ["nama" => "T-Piece Resuscitator", "kategori" => "Alat Terapi", "fungsi" => "Resusitasi T-piece", "jenis" => "Reusable"],
  ["nama" => "Bag and Mask", "kategori" => "Alat Terapi", "fungsi" => "Resusitasi manual", "jenis" => "Reusable"],

  // ==================== ALAT LABORATORIUM ====================
  ["nama" => "Mikroskop Binokuler", "kategori" => "Alat Lab", "fungsi" => "Melihat mikroorganisme", "jenis" => "Elektrik"],
  ["nama" => "Mikroskop Trinokuler", "kategori" => "Alat Lab", "fungsi" => "Mikroskop dengan kamera", "jenis" => "Elektrik"],
  ["nama" => "Mikroskop Elektron", "kategori" => "Alat Lab", "fungsi" => "Mikroskop elektron", "jenis" => "Elektrik"],
  ["nama" => "Centrifuge", "kategori" => "Alat Lab", "fungsi" => "Memisahkan cairan", "jenis" => "Elektrik"],
  ["nama" => "Microcentrifuge", "kategori" => "Alat Lab", "fungsi" => "Centrifuge mikro", "jenis" => "Elektrik"],
  ["nama" => "Hematocrit Centrifuge", "kategori" => "Alat Lab", "fungsi" => "Centrifuge hematokrit", "jenis" => "Elektrik"],
  ["nama" => "Refrigerated Centrifuge", "kategori" => "Alat Lab", "fungsi" => "Centrifuge berpendingin", "jenis" => "Elektrik"],
  ["nama" => "Inkubator Laboratorium", "kategori" => "Alat Lab", "fungsi" => "Inkubasi sampel", "jenis" => "Elektrik"],
  ["nama" => "CO2 Incubator", "kategori" => "Alat Lab", "fungsi" => "Inkubasi CO2", "jenis" => "Elektrik"],
  ["nama" => "Autoclave", "kategori" => "Alat Lab", "fungsi" => "Sterilisasi uap", "jenis" => "Elektrik"],
  ["nama" => "Autoclave Vertikal", "kategori" => "Alat Lab", "fungsi" => "Sterilisasi vertikal", "jenis" => "Elektrik"],
  ["nama" => "Autoclave Horizontal", "kategori" => "Alat Lab", "fungsi" => "Sterilisasi horizontal", "jenis" => "Elektrik"],
  ["nama" => "Dry Heat Sterilizer", "kategori" => "Alat Lab", "fungsi" => "Sterilisasi panas kering", "jenis" => "Elektrik"],
  ["nama" => "Water Bath", "kategori" => "Alat Lab", "fungsi" => "Pemanas air", "jenis" => "Elektrik"],
  ["nama" => "Shaking Water Bath", "kategori" => "Alat Lab", "fungsi" => "Water bath bergoyang", "jenis" => "Elektrik"],
  ["nama" => "Hot Plate", "kategori" => "Alat Lab", "fungsi" => "Pemanas pelat", "jenis" => "Elektrik"],
  ["nama" => "Magnetic Stirrer", "kategori" => "Alat Lab", "fungsi" => "Pengaduk magnetik", "jenis" => "Elektrik"],
  ["nama" => "Vortex Mixer", "kategori" => "Alat Lab", "fungsi" => "Pencampur vortex", "jenis" => "Elektrik"],
  ["nama" => "Homogenizer", "kategori" => "Alat Lab", "fungsi" => "Homogenisasi sampel", "jenis" => "Elektrik"],
  ["nama" => "Sonicator", "kategori" => "Alat Lab", "fungsi" => "Sonikasi sampel", "jenis" => "Elektrik"],
  ["nama" => "Spectrophotometer", "kategori" => "Alat Lab", "fungsi" => "Mengukur absorbansi", "jenis" => "Elektrik"],
  ["nama" => "UV-Vis Spectrophotometer", "kategori" => "Alat Lab", "fungsi" => "Spektrofotometri UV-Vis", "jenis" => "Elektrik"],
  ["nama" => "Atomic Absorption Spectrophotometer", "kategori" => "Alat Lab", "fungsi" => "AAS", "jenis" => "Elektrik"],
  ["nama" => "Flame Photometer", "kategori" => "Alat Lab", "fungsi" => "Fotometer nyala", "jenis" => "Elektrik"],
  ["nama" => "Chromatography", "kategori" => "Alat Lab", "fungsi" => "Kromatografi", "jenis" => "Elektrik"],
  ["nama" => "HPLC", "kategori" => "Alat Lab", "fungsi" => "High Performance Liquid Chromatography", "jenis" => "Elektrik"],
  ["nama" => "Gas Chromatography", "kategori" => "Alat Lab", "fungsi" => "Kromatografi gas", "jenis" => "Elektrik"],
  ["nama" => "Mass Spectrometer", "kategori" => "Alat Lab", "fungsi" => "Spektrometri massa", "jenis" => "Elektrik"],
  ["nama" => "PCR Machine", "kategori" => "Alat Lab", "fungsi" => "Polymerase Chain Reaction", "jenis" => "Elektrik"],
  ["nama" => "Real-Time PCR", "kategori" => "Alat Lab", "fungsi" => "PCR real-time", "jenis" => "Elektrik"],
  ["nama" => "Electrophoresis", "kategori" => "Alat Lab", "fungsi" => "Elektroforesis", "jenis" => "Elektrik"],
  ["nama" => "Gel Documentation", "kategori" => "Alat Lab", "fungsi" => "Dokumentasi gel", "jenis" => "Elektrik"],
  ["nama" => "ELISA Reader", "kategori" => "Alat Lab", "fungsi" => "Pembaca ELISA", "jenis" => "Elektrik"],
  ["nama" => "ELISA Washer", "kategori" => "Alat Lab", "fungsi" => "Pencuci ELISA", "jenis" => "Elektrik"],
  ["nama" => "Flow Cytometer", "kategori" => "Alat Lab", "fungsi" => "Sitometri aliran", "jenis" => "Elektrik"],
  ["nama" => "Hematology Analyzer", "kategori" => "Alat Lab", "fungsi" => "Analisis darah", "jenis" => "Elektrik"],
  ["nama" => "Chemistry Analyzer", "kategori" => "Alat Lab", "fungsi" => "Analisis kimia darah", "jenis" => "Elektrik"],
  ["nama" => "Blood Gas Analyzer", "kategori" => "Alat Lab", "fungsi" => "Analisis gas darah", "jenis" => "Elektrik"],
  ["nama" => "Coagulation Analyzer", "kategori" => "Alat Lab", "fungsi" => "Analisis koagulasi", "jenis" => "Elektrik"],
  ["nama" => "Urine Analyzer", "kategori" => "Alat Lab", "fungsi" => "Analisis urin", "jenis" => "Elektrik"],
  ["nama" => "Microbiology Analyzer", "kategori" => "Alat Lab", "fungsi" => "Analisis mikrobiologi", "jenis" => "Elektrik"],
  ["nama" => "Blood Bank Refrigerator", "kategori" => "Alat Lab", "fungsi" => "Kulkas bank darah", "jenis" => "Elektrik"],
  ["nama" => "Plasma Freezer", "kategori" => "Alat Lab", "fungsi" => "Freezer plasma", "jenis" => "Elektrik"],
  ["nama" => "Platelet Incubator", "kategori" => "Alat Lab", "fungsi" => "Inkubator trombosit", "jenis" => "Elektrik"],
  ["nama" => "Blood Mixer", "kategori" => "Alat Lab", "fungsi" => "Pengaduk darah", "jenis" => "Elektrik"],
  ["nama" => "Cell Saver", "kategori" => "Alat Lab", "fungsi" => "Penyelamat sel darah", "jenis" => "Elektrik"],
  ["nama" => "Apheresis Machine", "kategori" => "Alat Lab", "fungsi" => "Aferesis", "jenis" => "Elektrik"],
  ["nama" => "Cryoprecipitate Bath", "kategori" => "Alat Lab", "fungsi" => "Pencairan kriopresipitat", "jenis" => "Elektrik"],
  ["nama" => "Plasma Thawing System", "kategori" => "Alat Lab", "fungsi" => "Pencairan plasma", "jenis" => "Elektrik"],
  ["nama" => "Microplate Reader", "kategori" => "Alat Lab", "fungsi" => "Pembaca microplate", "jenis" => "Elektrik"],
  ["nama" => "Microplate Washer", "kategori" => "Alat Lab", "fungsi" => "Pencuci microplate", "jenis" => "Elektrik"],
  ["nama" => "Pipette", "kategori" => "Alat Lab", "fungsi" => "Mengambil cairan", "jenis" => "Reusable"],
  ["nama" => "Micropipette", "kategori" => "Alat Lab", "fungsi" => "Mengambil cairan mikro", "jenis" => "Reusable"],
  ["nama" => "Multichannel Pipette", "kategori" => "Alat Lab", "fungsi" => "Pipet multichannel", "jenis" => "Reusable"],
  ["nama" => "Pipette Tips", "kategori" => "Alat Lab", "fungsi" => "Ujung pipet", "jenis" => "Disposable"],
  ["nama" => "Buret", "kategori" => "Alat Lab", "fungsi" => "Titrasi", "jenis" => "Reusable"],
  ["nama" => "Labu Ukur", "kategori" => "Alat Lab", "fungsi" => "Mengukur volume", "jenis" => "Reusable"],
  ["nama" => "Gelas Ukur", "kategori" => "Alat Lab", "fungsi" => "Mengukur volume", "jenis" => "Reusable"],
  ["nama" => "Erlenmeyer", "kategori" => "Alat Lab", "fungsi" => "Wadah larutan", "jenis" => "Reusable"],
  ["nama" => "Beaker Glass", "kategori" => "Alat Lab", "fungsi" => "Wadah larutan", "jenis" => "Reusable"],
  ["nama" => "Tabung Reaksi", "kategori" => "Alat Lab", "fungsi" => "Wadah reaksi", "jenis" => "Reusable"],
  ["nama" => "Tabung Sentrifuge", "kategori" => "Alat Lab", "fungsi" => "Tabung centrifuge", "jenis" => "Disposable"],
  ["nama" => "Tabung EDTA", "kategori" => "Alat Lab", "fungsi" => "Tabung darah EDTA", "jenis" => "Disposable"],
  ["nama" => "Tabung Heparin", "kategori" => "Alat Lab", "fungsi" => "Tabung darah heparin", "jenis" => "Disposable"],
  ["nama" => "Tabung Citrate", "kategori" => "Alat Lab", "fungsi" => "Tabung darah sitrat", "jenis" => "Disposable"],
  ["nama" => "Tabung Serum", "kategori" => "Alat Lab", "fungsi" => "Tabung serum", "jenis" => "Disposable"],
  ["nama" => "Petri Dish", "kategori" => "Alat Lab", "fungsi" => "Cawan petri", "jenis" => "Disposable"],
  ["nama" => "Object Glass", "kategori" => "Alat Lab", "fungsi" => "Kaca objek", "jenis" => "Disposable"],
  ["nama" => "Cover Glass", "kategori" => "Alat Lab", "fungsi" => "Kaca penutup", "jenis" => "Disposable"],
  ["nama" => "Inoculating Loop", "kategori" => "Alat Lab", "fungsi" => "Ose inokulasi", "jenis" => "Reusable"],
  ["nama" => "Bunsen Burner", "kategori" => "Alat Lab", "fungsi" => "Pembakar bunsen", "jenis" => "Reusable"],
  ["nama" => "Laminar Air Flow", "kategori" => "Alat Lab", "fungsi" => "Aliran udara laminar", "jenis" => "Elektrik"],
  ["nama" => "Biosafety Cabinet", "kategori" => "Alat Lab", "fungsi" => "Kabinet biosafety", "jenis" => "Elektrik"],
  ["nama" => "Fume Hood", "kategori" => "Alat Lab", "fungsi" => "Lemari asam", "jenis" => "Elektrik"],

  // ==================== ALAT STERILISASI ====================
  ["nama" => "Autoclave", "kategori" => "Alat Sterilisasi", "fungsi" => "Sterilisasi uap", "jenis" => "Elektrik"],
  ["nama" => "Steam Sterilizer", "kategori" => "Alat Sterilisasi", "fungsi" => "Sterilisasi uap", "jenis" => "Elektrik"],
  ["nama" => "Dry Heat Sterilizer", "kategori" => "Alat Sterilisasi", "fungsi" => "Sterilisasi panas kering", "jenis" => "Elektrik"],
  ["nama" => "Ethylene Oxide Sterilizer", "kategori" => "Alat Sterilisasi", "fungsi" => "Sterilisasi EtO", "jenis" => "Elektrik"],
  ["nama" => "Plasma Sterilizer", "kategori" => "Alat Sterilisasi", "fungsi" => "Sterilisasi plasma", "jenis" => "Elektrik"],
  ["nama" => "UV Sterilizer", "kategori" => "Alat Sterilisasi", "fungsi" => "Sterilisasi UV", "jenis" => "Elektrik"],
  ["nama" => "Formaldehyde Sterilizer", "kategori" => "Alat Sterilisasi", "fungsi" => "Sterilisasi formaldehid", "jenis" => "Elektrik"],
  ["nama" => "Glutaraldehyde Sterilizer", "kategori" => "Alat Sterilisasi", "fungsi" => "Sterilisasi glutaraldehid", "jenis" => "Reusable"],
  ["nama" => "Hydrogen Peroxide Sterilizer", "kategori" => "Alat Sterilisasi", "fungsi" => "Sterilisasi H2O2", "jenis" => "Elektrik"],
  ["nama" => "Sterilization Pouch", "kategori" => "Alat Sterilisasi", "fungsi" => "Kantong sterilisasi", "jenis" => "Disposable"],
  ["nama" => "Sterilization Indicator", "kategori" => "Alat Sterilisasi", "fungsi" => "Indikator sterilisasi", "jenis" => "Disposable"],
  ["nama" => "Biological Indicator", "kategori" => "Alat Sterilisasi", "fungsi" => "Indikator biologis", "jenis" => "Disposable"],
  ["nama" => "Chemical Indicator", "kategori" => "Alat Sterilisasi", "fungsi" => "Indikator kimia", "jenis" => "Disposable"],
  ["nama" => "Sterilization Tape", "kategori" => "Alat Sterilisasi", "fungsi" => "Pita sterilisasi", "jenis" => "Disposable"],
  ["nama" => "Sterilization Container", "kategori" => "Alat Sterilisasi", "fungsi" => "Wadah sterilisasi", "jenis" => "Reusable"],

  // ==================== ALAT BANTU ====================
  ["nama" => "Kursi Roda (Wheelchair)", "kategori" => "Alat Bantu", "fungsi" => "Mobilitas pasien", "jenis" => "Reusable"],
  ["nama" => "Kursi Roda Elektrik", "kategori" => "Alat Bantu", "fungsi" => "Mobilitas elektrik", "jenis" => "Elektrik"],
  ["nama" => "Walker", "kategori" => "Alat Bantu", "fungsi" => "Alat bantu jalan", "jenis" => "Reusable"],
  ["nama" => "Rollator", "kategori" => "Alat Bantu", "fungsi" => "Walker dengan roda", "jenis" => "Reusable"],
  ["nama" => "Kruk (Crutches)", "kategori" => "Alat Bantu", "fungsi" => "Alat bantu jalan", "jenis" => "Reusable"],
  ["nama" => "Tongkat (Cane)", "kategori" => "Alat Bantu", "fungsi" => "Alat bantu jalan", "jenis" => "Reusable"],
  ["nama" => "Stretcher", "kategori" => "Alat Bantu", "fungsi" => "Tandu pasien", "jenis" => "Reusable"],
  ["nama" => "Gurney", "kategori" => "Alat Bantu", "fungsi" => "Troli pasien", "jenis" => "Reusable"],
  ["nama" => "Bed Pasien", "kategori" => "Alat Bantu", "fungsi" => "Tempat tidur pasien", "jenis" => "Reusable"],
  ["nama" => "Bed Elektrik", "kategori" => "Alat Bantu", "fungsi" => "Tempat tidur elektrik", "jenis" => "Elektrik"],
  ["nama" => "Bed ICU", "kategori" => "Alat Bantu", "fungsi" => "Tempat tidur ICU", "jenis" => "Elektrik"],
  ["nama" => "Bed Bayi", "kategori" => "Alat Bantu", "fungsi" => "Tempat tidur bayi", "jenis" => "Reusable"],
  ["nama" => "Bassinet", "kategori" => "Alat Bantu", "fungsi" => "Tempat tidur bayi", "jenis" => "Reusable"],
  ["nama" => "Brankar", "kategori" => "Alat Bantu", "fungsi" => "Tandu pasien", "jenis" => "Reusable"],
  ["nama" => "Wheelchair Tilt", "kategori" => "Alat Bantu", "fungsi" => "Kursi roda tilt", "jenis" => "Reusable"],
  ["nama" => "Patient Lift", "kategori" => "Alat Bantu", "fungsi" => "Mengangkat pasien", "jenis" => "Elektrik"],
  ["nama" => "Transfer Board", "kategori" => "Alat Bantu", "fungsi" => "Papan transfer pasien", "jenis" => "Reusable"],
  ["nama" => "Slide Sheet", "kategori" => "Alat Bantu", "fungsi" => "Lembar geser pasien", "jenis" => "Reusable"],
  ["nama" => "Bed Rail", "kategori" => "Alat Bantu", "fungsi" => "Pagar tempat tidur", "jenis" => "Reusable"],
  ["nama" => "Overbed Table", "kategori" => "Alat Bantu", "fungsi" => "Meja atas tempat tidur", "jenis" => "Reusable"],
  ["nama" => "Bedpan", "kategori" => "Alat Bantu", "fungsi" => "Pispot", "jenis" => "Reusable"],
  ["nama" => "Urinal", "kategori" => "Alat Bantu", "fungsi" => "Wadah urin", "jenis" => "Reusable"],
  ["nama" => "Commode Chair", "kategori" => "Alat Bantu", "fungsi" => "Kursi toilet", "jenis" => "Reusable"],
  ["nama" => "Shower Chair", "kategori" => "Alat Bantu", "fungsi" => "Kursi mandi", "jenis" => "Reusable"],
  ["nama" => "Bath Lift", "kategori" => "Alat Bantu", "fungsi" => "Lift mandi", "jenis" => "Elektrik"],

  // ==================== ALAT MEDIS HABIS PAKAI ====================
  ["nama" => "Kapas Steril", "kategori" => "Habis Pakai", "fungsi" => "Membersihkan luka", "jenis" => "Disposable"],
  ["nama" => "Kasa Steril", "kategori" => "Habis Pakai", "fungsi" => "Menutup luka", "jenis" => "Disposable"],
  ["nama" => "Plester", "kategori" => "Habis Pakai", "fungsi" => "Menutup luka", "jenis" => "Disposable"],
  ["nama" => "Plester Elastis", "kategori" => "Habis Pakai", "fungsi" => "Menutup luka", "jenis" => "Disposable"],
  ["nama" => "Perban", "kategori" => "Habis Pakai", "fungsi" => "Membalut luka", "jenis" => "Disposable"],
  ["nama" => "Perban Elastis", "kategori" => "Habis Pakai", "fungsi" => "Membalut luka", "jenis" => "Disposable"],
  ["nama" => "Perban Kasa", "kategori" => "Habis Pakai", "fungsi" => "Membalut luka", "jenis" => "Disposable"],
  ["nama" => "Pembalut Gulung", "kategori" => "Habis Pakai", "fungsi" => "Membalut luka", "jenis" => "Disposable"],
  ["nama" => "Alkohol Swab", "kategori" => "Habis Pakai", "fungsi" => "Antiseptik", "jenis" => "Disposable"],
  ["nama" => "Povidone Iodine Swab", "kategori" => "Habis Pakai", "fungsi" => "Antiseptik", "jenis" => "Disposable"],
  ["nama" => "Hand Sanitizer", "kategori" => "Habis Pakai", "fungsi" => "Pembersih tangan", "jenis" => "Disposable"],
  ["nama" => "Sarung Tangan Latex", "kategori" => "Habis Pakai", "fungsi" => "Pelindung tangan", "jenis" => "Disposable"],
  ["nama" => "Sarung Tangan Nitril", "kategori" => "Habis Pakai", "fungsi" => "Pelindung tangan", "jenis" => "Disposable"],
  ["nama" => "Sarung Tangan Steril", "kategori" => "Habis Pakai", "fungsi" => "Pelindung tangan steril", "jenis" => "Disposable"],
  ["nama" => "Masker Bedah", "kategori" => "Habis Pakai", "fungsi" => "Pelindung mulut", "jenis" => "Disposable"],
  ["nama" => "Masker N95", "kategori" => "Habis Pakai", "fungsi" => "Pelindung pernapasan", "jenis" => "Disposable"],
  ["nama" => "Masker KN95", "kategori" => "Habis Pakai", "fungsi" => "Pelindung pernapasan", "jenis" => "Disposable"],
  ["nama" => "Face Shield", "kategori" => "Habis Pakai", "fungsi" => "Pelindung wajah", "jenis" => "Disposable"],
  ["nama" => "Gown", "kategori" => "Habis Pakai", "fungsi" => "Gaun pelindung", "jenis" => "Disposable"],
  ["nama" => "Apron", "kategori" => "Habis Pakai", "fungsi" => "Celemek", "jenis" => "Disposable"],
  ["nama" => "Hazmat Suit", "kategori" => "Habis Pakai", "fungsi" => "Pakaian hazmat", "jenis" => "Disposable"],
  ["nama" => "Shoe Cover", "kategori" => "Habis Pakai", "fungsi" => "Penutup sepatu", "jenis" => "Disposable"],
  ["nama" => "Hair Cap", "kategori" => "Habis Pakai", "fungsi" => "Penutup kepala", "jenis" => "Disposable"],
  ["nama" => "Underpad", "kategori" => "Habis Pakai", "fungsi" => "Alas tempat tidur", "jenis" => "Disposable"],
  ["nama" => "Diaper Dewasa", "kategori" => "Habis Pakai", "fungsi" => "Popok dewasa", "jenis" => "Disposable"],
  ["nama" => "Diaper Bayi", "kategori" => "Habis Pakai", "fungsi" => "Popok bayi", "jenis" => "Disposable"],
  ["nama" => "Kateter Urin", "kategori" => "Habis Pakai", "fungsi" => "Kateter urin", "jenis" => "Disposable"],
  ["nama" => "Foley Catheter", "kategori" => "Habis Pakai", "fungsi" => "Kateter Foley", "jenis" => "Disposable"],
  ["nama" => "Condom Catheter", "kategori" => "Habis Pakai", "fungsi" => "Kateter kondom", "jenis" => "Disposable"],
  ["nama" => "Urine Bag", "kategori" => "Habis Pakai", "fungsi" => "Kantong urin", "jenis" => "Disposable"],
  ["nama" => "Colostomy Bag", "kategori" => "Habis Pakai", "fungsi" => "Kantong kolostomi", "jenis" => "Disposable"],
  ["nama" => "Nasogastric Tube (NGT)", "kategori" => "Habis Pakai", "fungsi" => "Selang lambung", "jenis" => "Disposable"],
  ["nama" => "Orogastric Tube (OGT)", "kategori" => "Habis Pakai", "fungsi" => "Selang lambung oral", "jenis" => "Disposable"],
  ["nama" => "Feeding Tube", "kategori" => "Habis Pakai", "fungsi" => "Selang makanan", "jenis" => "Disposable"],
  ["nama" => "Chest Tube", "kategori" => "Habis Pakai", "fungsi" => "Selang dada", "jenis" => "Disposable"],
  ["nama" => "Water Seal Drainage", "kategori" => "Habis Pakai", "fungsi" => "Drainase dada", "jenis" => "Disposable"],
  ["nama" => "Jackson-Pratt Drain", "kategori" => "Habis Pakai", "fungsi" => "Drainase luka", "jenis" => "Disposable"],
  ["nama" => "Hemovac Drain", "kategori" => "Habis Pakai", "fungsi" => "Drainase luka", "jenis" => "Disposable"],
  ["nama" => "Penrose Drain", "kategori" => "Habis Pakai", "fungsi" => "Drainase luka", "jenis" => "Disposable"],
  ["nama" => "T-Drain", "kategori" => "Habis Pakai", "fungsi" => "Drainase empedu", "jenis" => "Disposable"],
  ["nama" => "Nasal Cannula", "kategori" => "Habis Pakai", "fungsi" => "Kanul hidung", "jenis" => "Disposable"],
  ["nama" => "Simple Mask", "kategori" => "Habis Pakai", "fungsi" => "Masker oksigen", "jenis" => "Disposable"],
  ["nama" => "Venturi Mask", "kategori" => "Habis Pakai", "fungsi" => "Masker venturi", "jenis" => "Disposable"],
  ["nama" => "Non-Rebreathing Mask", "kategori" => "Habis Pakai", "fungsi" => "Masker NRM", "jenis" => "Disposable"],
  ["nama" => "Nebulizer Mask", "kategori" => "Habis Pakai", "fungsi" => "Masker nebulizer", "jenis" => "Disposable"],
  ["nama" => "Nebulizer Kit", "kategori" => "Habis Pakai", "fungsi" => "Kit nebulizer", "jenis" => "Disposable"],
  ["nama" => "Tracheostomy Care Kit", "kategori" => "Habis Pakai", "fungsi" => "Kit perawatan trakeostomi", "jenis" => "Disposable"],
  ["nama" => "Suction Kit", "kategori" => "Habis Pakai", "fungsi" => "Kit suction", "jenis" => "Disposable"],
  ["nama" => "Catheter Mount", "kategori" => "Habis Pakai", "fungsi" => "Konektor kateter", "jenis" => "Disposable"],
  ["nama" => "Heat and Moisture Exchanger", "kategori" => "Habis Pakai", "fungsi" => "Pelembap napas", "jenis" => "Disposable"],
  ["nama" => "Bacterial Filter", "kategori" => "Habis Pakai", "fungsi" => "Filter bakteri", "jenis" => "Disposable"],
  ["nama" => "Circular Breathing Filter", "kategori" => "Habis Pakai", "fungsi" => "Filter napas sirkular", "jenis" => "Disposable"],
  ["nama" => "Anesthesia Breathing Circuit", "kategori" => "Habis Pakai", "fungsi" => "Sirkuit anestesi", "jenis" => "Disposable"],
  ["nama" => "Anesthesia Mask", "kategori" => "Habis Pakai", "fungsi" => "Masker anestesi", "jenis" => "Disposable"],
  ["nama" => "Laryngeal Mask", "kategori" => "Habis Pakai", "fungsi" => "LMA", "jenis" => "Disposable"],
  ["nama" => "Endotracheal Tube", "kategori" => "Habis Pakai", "fungsi" => "ETT", "jenis" => "Disposable"],
  ["nama" => "Tracheostomy Tube", "kategori" => "Habis Pakai", "fungsi" => "Pipa trakeostomi", "jenis" => "Disposable"],
  ["nama" => "Introducer", "kategori" => "Habis Pakai", "fungsi" => "Introducer", "jenis" => "Disposable"],
  ["nama" => "Guide Wire", "kategori" => "Habis Pakai", "fungsi" => "Kawat pemandu", "jenis" => "Disposable"],
  ["nama" => "Dilator", "kategori" => "Habis Pakai", "fungsi" => "Dilator", "jenis" => "Disposable"],
  ["nama" => "Sheath", "kategori" => "Habis Pakai", "fungsi" => "Sheath", "jenis" => "Disposable"],
  ["nama" => "Catheter", "kategori" => "Habis Pakai", "fungsi" => "Kateter", "jenis" => "Disposable"],
  ["nama" => "Balloon Catheter", "kategori" => "Habis Pakai", "fungsi" => "Kateter balon", "jenis" => "Disposable"],
  ["nama" => "Angiographic Catheter", "kategori" => "Habis Pakai", "fungsi" => "Kateter angiografi", "jenis" => "Disposable"],
  ["nama" => "Pigtail Catheter", "kategori" => "Habis Pakai", "fungsi" => "Kateter pigtail", "jenis" => "Disposable"],
  ["nama" => "Nelaton Catheter", "kategori" => "Habis Pakai", "fungsi" => "Kateter Nelaton", "jenis" => "Disposable"],
  ["nama" => "Robinson Catheter", "kategori" => "Habis Pakai", "fungsi" => "Kateter Robinson", "jenis" => "Disposable"],
  ["nama" => "Coude Catheter", "kategori" => "Habis Pakai", "fungsi" => "Kateter Coude", "jenis" => "Disposable"],
  ["nama" => "Malecot Catheter", "kategori" => "Habis Pakai", "fungsi" => "Kateter Malecot", "jenis" => "Disposable"],
  ["nama" => "Pezzer Catheter", "kategori" => "Habis Pakai", "fungsi" => "Kateter Pezzer", "jenis" => "Disposable"],
  ["nama" => "Sengstaken-Blakemore Tube", "kategori" => "Habis Pakai", "fungsi" => "Tabung Sengstaken-Blakemore", "jenis" => "Disposable"],
  ["nama" => "Minnesota Tube", "kategori" => "Habis Pakai", "fungsi" => "Tabung Minnesota", "jenis" => "Disposable"],
  ["nama" => "Linton-Nachlas Tube", "kategori" => "Habis Pakai", "fungsi" => "Tabung Linton-Nachlas", "jenis" => "Disposable"],

  // ==================== ALAT ORTOPEDI ====================
  ["nama" => "Bone Plate", "kategori" => "Ortopedi", "fungsi" => "Fiksasi tulang", "jenis" => "Implant"],
  ["nama" => "Bone Screw", "kategori" => "Ortopedi", "fungsi" => "Fiksasi tulang", "jenis" => "Implant"],
  ["nama" => "Bone Nail", "kategori" => "Ortopedi", "fungsi" => "Fiksasi tulang", "jenis" => "Implant"],
  ["nama" => "Bone Wire", "kategori" => "Ortopedi", "fungsi" => "Fiksasi tulang", "jenis" => "Implant"],
  ["nama" => "External Fixator", "kategori" => "Ortopedi", "fungsi" => "Fiksasi eksternal", "jenis" => "Implant"],
  ["nama" => "Internal Fixator", "kategori" => "Ortopedi", "fungsi" => "Fiksasi internal", "jenis" => "Implant"],
  ["nama" => "Intramedullary Nail", "kategori" => "Ortopedi", "fungsi" => "Paku intramedula", "jenis" => "Implant"],
  ["nama" => "Dynamic Hip Screw", "kategori" => "Ortopedi", "fungsi" => "Sekrup hip dinamis", "jenis" => "Implant"],
  ["nama" => "Dynamic Compression Plate", "kategori" => "Ortopedi", "fungsi" => "Plat kompresi dinamis", "jenis" => "Implant"],
  ["nama" => "Locking Compression Plate", "kategori" => "Ortopedi", "fungsi" => "Plat kompresi locking", "jenis" => "Implant"],
  ["nama" => "Reconstruction Plate", "kategori" => "Ortopedi", "fungsi" => "Plat rekonstruksi", "jenis" => "Implant"],
  ["nama" => "T-Plate", "kategori" => "Ortopedi", "fungsi" => "Plat T", "jenis" => "Implant"],
  ["nama" => "L-Plate", "kategori" => "Ortopedi", "fungsi" => "Plat L", "jenis" => "Implant"],
  ["nama" => "Cloverleaf Plate", "kategori" => "Ortopedi", "fungsi" => "Plat cloverleaf", "jenis" => "Implant"],
  ["nama" => "Buttress Plate", "kategori" => "Ortopedi", "fungsi" => "Plat buttress", "jenis" => "Implant"],
  ["nama" => "K-Wire", "kategori" => "Ortopedi", "fungsi" => "Kawat K", "jenis" => "Implant"],
  ["nama" => "Cerclage Wire", "kategori" => "Ortopedi", "fungsi" => "Kawat cerclage", "jenis" => "Implant"],
  ["nama" => "Tension Band Wire", "kategori" => "Ortopedi", "fungsi" => "Kawat tension band", "jenis" => "Implant"],
  ["nama" => "Bone Cement", "kategori" => "Ortopedi", "fungsi" => "Semen tulang", "jenis" => "Disposable"],
  ["nama" => "Bone Graft", "kategori" => "Ortopedi", "fungsi" => "Cangkok tulang", "jenis" => "Implant"],
  ["nama" => "Bone Substitute", "kategori" => "Ortopedi", "fungsi" => "Pengganti tulang", "jenis" => "Implant"],
  ["nama" => "Artificial Joint", "kategori" => "Ortopedi", "fungsi" => "Sendi buatan", "jenis" => "Implant"],
  ["nama" => "Hip Prosthesis", "kategori" => "Ortopedi", "fungsi" => "Prostesis hip", "jenis" => "Implant"],
  ["nama" => "Knee Prosthesis", "kategori" => "Ortopedi", "fungsi" => "Prostesis lutut", "jenis" => "Implant"],
  ["nama" => "Shoulder Prosthesis", "kategori" => "Ortopedi", "fungsi" => "Prostesis bahu", "jenis" => "Implant"],
  ["nama" => "Elbow Prosthesis", "kategori" => "Ortopedi", "fungsi" => "Prostesis siku", "jenis" => "Implant"],
  ["nama" => "Ankle Prosthesis", "kategori" => "Ortopedi", "fungsi" => "Prostesis pergelangan kaki", "jenis" => "Implant"],
  ["nama" => "Spinal Implant", "kategori" => "Ortopedi", "fungsi" => "Implan tulang belakang", "jenis" => "Implant"],
  ["nama" => "Spinal Cage", "kategori" => "Ortopedi", "fungsi" => "Cage tulang belakang", "jenis" => "Implant"],
  ["nama" => "Spinal Rod", "kategori" => "Ortopedi", "fungsi" => "Rod tulang belakang", "jenis" => "Implant"],
  ["nama" => "Spinal Screw", "kategori" => "Ortopedi", "fungsi" => "Sekrup tulang belakang", "jenis" => "Implant"],
  ["nama" => "Spinal Hook", "kategori" => "Ortopedi", "fungsi" => "Hook tulang belakang", "jenis" => "Implant"],
  ["nama" => "Cross Link", "kategori" => "Ortopedi", "fungsi" => "Cross link spinal", "jenis" => "Implant"],
  ["nama" => "Vertebroplasty Cement", "kategori" => "Ortopedi", "fungsi" => "Semen vertebroplasti", "jenis" => "Disposable"],
  ["nama" => "Kyphoplasty Balloon", "kategori" => "Ortopedi", "fungsi" => "Balon kyphoplasty", "jenis" => "Disposable"],

  // ==================== ALAT KARDIOVASKULAR ====================
  ["nama" => "Stent Koroner", "kategori" => "Kardiovaskular", "fungsi" => "Stent koroner", "jenis" => "Implant"],
  ["nama" => "Drug-Eluting Stent", "kategori" => "Kardiovaskular", "fungsi" => "Stent obat", "jenis" => "Implant"],
  ["nama" => "Bare Metal Stent", "kategori" => "Kardiovaskular", "fungsi" => "Stent logam", "jenis" => "Implant"],
  ["nama" => "Bioabsorbable Stent", "kategori" => "Kardiovaskular", "fungsi" => "Stent bioabsorbsi", "jenis" => "Implant"],
  ["nama" => "Balloon Angioplasty", "kategori" => "Kardiovaskular", "fungsi" => "Balon angioplasti", "jenis" => "Disposable"],
  ["nama" => "Cutting Balloon", "kategori" => "Kardiovaskular", "fungsi" => "Balon cutting", "jenis" => "Disposable"],
  ["nama" => "Drug-Eluting Balloon", "kategori" => "Kardiovaskular", "fungsi" => "Balon obat", "jenis" => "Disposable"],
  ["nama" => "Guide Catheter", "kategori" => "Kardiovaskular", "fungsi" => "Kateter pemandu", "jenis" => "Disposable"],
  ["nama" => "Diagnostic Catheter", "kategori" => "Kardiovaskular", "fungsi" => "Kateter diagnostik", "jenis" => "Disposable"],
  ["nama" => "Guiding Catheter", "kategori" => "Kardiovaskular", "fungsi" => "Kateter guiding", "jenis" => "Disposable"],
  ["nama" => "Guide Wire", "kategori" => "Kardiovaskular", "fungsi" => "Kawat pemandu", "jenis" => "Disposable"],
  ["nama" => "PTCA Wire", "kategori" => "Kardiovaskular", "fungsi" => "Kawat PTCA", "jenis" => "Disposable"],
  ["nama" => "Rotational Atherectomy", "kategori" => "Kardiovaskular", "fungsi" => "Aterektomi rotasional", "jenis" => "Disposable"],
  ["nama" => "Thrombectomy Catheter", "kategori" => "Kardiovaskular", "fungsi" => "Kateter trombektomi", "jenis" => "Disposable"],
  ["nama" => "Embolic Protection Device", "kategori" => "Kardiovaskular", "fungsi" => "Perangkat proteksi emboli", "jenis" => "Disposable"],
  ["nama" => "IVUS Catheter", "kategori" => "Kardiovaskular", "fungsi" => "Kateter IVUS", "jenis" => "Disposable"],
  ["nama" => "OCT Catheter", "kategori" => "Kardiovaskular", "fungsi" => "Kateter OCT", "jenis" => "Disposable"],
  ["nama" => "FFR Wire", "kategori" => "Kardiovaskular", "fungsi" => "Kawat FFR", "jenis" => "Disposable"],
  ["nama" => "Heart Valve Prosthesis", "kategori" => "Kardiovaskular", "fungsi" => "Prostesis katup jantung", "jenis" => "Implant"],
  ["nama" => "Mechanical Heart Valve", "kategori" => "Kardiovaskular", "fungsi" => "Katup jantung mekanik", "jenis" => "Implant"],
  ["nama" => "Bioprosthetic Heart Valve", "kategori" => "Kardiovaskular", "fungsi" => "Katup jantung biologis", "jenis" => "Implant"],
  ["nama" => "TAVI Valve", "kategori" => "Kardiovaskular", "fungsi" => "Katup TAVI", "jenis" => "Implant"],
  ["nama" => "Annuloplasty Ring", "kategori" => "Kardiovaskular", "fungsi" => "Cincin anuloplasti", "jenis" => "Implant"],
  ["nama" => "Cardiac Patch", "kategori" => "Kardiovaskular", "fungsi" => "Patch jantung", "jenis" => "Implant"],
  ["nama" => "Pericardial Patch", "kategori" => "Kardiovaskular", "fungsi" => "Patch perikardial", "jenis" => "Implant"],
  ["nama" => "Vascular Graft", "kategori" => "Kardiovaskular", "fungsi" => "Graft vaskular", "jenis" => "Implant"],
  ["nama" => "Dacron Graft", "kategori" => "Kardiovaskular", "fungsi" => "Graft Dacron", "jenis" => "Implant"],
  ["nama" => "PTFE Graft", "kategori" => "Kardiovaskular", "fungsi" => "Graft PTFE", "jenis" => "Implant"],
  ["nama" => "Bovine Pericardium", "kategori" => "Kardiovaskular", "fungsi" => "Perikardium sapi", "jenis" => "Implant"],
  ["nama" => "Pacemaker", "kategori" => "Kardiovaskular", "fungsi" => "Alat pacu jantung", "jenis" => "Implant"],
  ["nama" => "ICD", "kategori" => "Kardiovaskular", "fungsi" => "Defibrilator implan", "jenis" => "Implant"],
  ["nama" => "CRT Device", "kategori" => "Kardiovaskular", "fungsi" => "CRT", "jenis" => "Implant"],
  ["nama" => "Pacemaker Lead", "kategori" => "Kardiovaskular", "fungsi" => "Lead pacemaker", "jenis" => "Implant"],
  ["nama" => "Epicardial Lead", "kategori" => "Kardiovaskular", "fungsi" => "Lead epikardial", "jenis" => "Implant"],
  ["nama" => "Endocardial Lead", "kategori" => "Kardiovaskular", "fungsi" => "Lead endokardial", "jenis" => "Implant"],
  ["nama" => "Coronary Sinus Lead", "kategori" => "Kardiovaskular", "fungsi" => "Lead sinus koroner", "jenis" => "Implant"],
  ["nama" => "IABP Balloon", "kategori" => "Kardiovaskular", "fungsi" => "Balon IABP", "jenis" => "Disposable"],
  ["nama" => "ECMO Circuit", "kategori" => "Kardiovaskular", "fungsi" => "Sirkuit ECMO", "jenis" => "Disposable"],
  ["nama" => "ECMO Cannula", "kategori" => "Kardiovaskular", "fungsi" => "Kanul ECMO", "jenis" => "Disposable"],
  ["nama" => "Centrifugal Pump", "kategori" => "Kardiovaskular", "fungsi" => "Pompa sentrifugal", "jenis" => "Disposable"],
  ["nama" => "Oxygenator", "kategori" => "Kardiovaskular", "fungsi" => "Oksigenator", "jenis" => "Disposable"],
  ["nama" => "Cardioplegia Set", "kategori" => "Kardiovaskular", "fungsi" => "Set kardioplegia", "jenis" => "Disposable"],
  ["nama" => "Cardiotomy Reservoir", "kategori" => "Kardiovaskular", "fungsi" => "Reservoir kardiotomi", "jenis" => "Disposable"],
  ["nama" => "Arterial Filter", "kategori" => "Kardiovaskular", "fungsi" => "Filter arteri", "jenis" => "Disposable"],
  ["nama" => "Venous Reservoir", "kategori" => "Kardiovaskular", "fungsi" => "Reservoir vena", "jenis" => "Disposable"],
  ["nama" => "Tubing Set CPB", "kategori" => "Kardiovaskular", "fungsi" => "Set tubing CPB", "jenis" => "Disposable"],

  // ==================== ALAT DIALISIS ====================
  ["nama" => "Dialyzer", "kategori" => "Dialisis", "fungsi" => "Dialyzer", "jenis" => "Disposable"],
  ["nama" => "Blood Line Set", "kategori" => "Dialisis", "fungsi" => "Set selang darah", "jenis" => "Disposable"],
  ["nama" => "Dialysate Line", "kategori" => "Dialisis", "fungsi" => "Selang dialisat", "jenis" => "Disposable"],
  ["nama" => "Fistula Needle", "kategori" => "Dialisis", "fungsi" => "Jarum fistula", "jenis" => "Disposable"],
  ["nama" => "AV Fistula Needle", "kategori" => "Dialisis", "fungsi" => "Jarum AV fistula", "jenis" => "Disposable"],
  ["nama" => "Central Venous Catheter", "kategori" => "Dialisis", "fungsi" => "Kateter vena sentral", "jenis" => "Disposable"],
  ["nama" => "Permcath", "kategori" => "Dialisis", "fungsi" => "Kateter Permcath", "jenis" => "Disposable"],
  ["nama" => "Peritoneal Dialysis Catheter", "kategori" => "Dialisis", "fungsi" => "Kateter dialisis peritoneum", "jenis" => "Implant"],
  ["nama" => "Peritoneal Dialysis Set", "kategori" => "Dialisis", "fungsi" => "Set dialisis peritoneum", "jenis" => "Disposable"],
  ["nama" => "Transfer Set", "kategori" => "Dialisis", "fungsi" => "Set transfer", "jenis" => "Disposable"],
  ["nama" => "Dialysate Concentrate", "kategori" => "Dialisis", "fungsi" => "Konsentrat dialisat", "jenis" => "Disposable"],
  ["nama" => "Bicarbonate Cartridge", "kategori" => "Dialisis", "fungsi" => "Kartrid bikarbonat", "jenis" => "Disposable"],
  ["nama" => "Dialyzer Reprocessing Set", "kategori" => "Dialisis", "fungsi" => "Set reprocessing dialyzer", "jenis" => "Disposable"],

  // ==================== ALAT OKSIGEN ====================
  ["nama" => "Oxygen Concentrator", "kategori" => "Oksigen", "fungsi" => "Konsentrator oksigen", "jenis" => "Elektrik"],
  ["nama" => "Oxygen Cylinder", "kategori" => "Oksigen", "fungsi" => "Tabung oksigen", "jenis" => "Reusable"],
  ["nama" => "Oxygen Regulator", "kategori" => "Oksigen", "fungsi" => "Regulator oksigen", "jenis" => "Reusable"],
  ["nama" => "Oxygen Flowmeter", "kategori" => "Oksigen", "fungsi" => "Flowmeter oksigen", "jenis" => "Reusable"],
  ["nama" => "Oxygen Humidifier", "kategori" => "Oksigen", "fungsi" => "Humidifier oksigen", "jenis" => "Reusable"],
  ["nama" => "Oxygen Mask", "kategori" => "Oksigen", "fungsi" => "Masker oksigen", "jenis" => "Disposable"],
  ["nama" => "Nasal Cannula", "kategori" => "Oksigen", "fungsi" => "Kanul hidung", "jenis" => "Disposable"],
  ["nama" => "Oxygen Tubing", "kategori" => "Oksigen", "fungsi" => "Selang oksigen", "jenis" => "Disposable"],
  ["nama" => "Oxygen Tent", "kategori" => "Oksigen", "fungsi" => "Tenda oksigen", "jenis" => "Reusable"],
  ["nama" => "Oxygen Hood", "kategori" => "Oksigen", "fungsi" => "Hood oksigen bayi", "jenis" => "Reusable"],
  ["nama" => "Hyperbaric Chamber", "kategori" => "Oksigen", "fungsi" => "Ruang hiperbarik", "jenis" => "Elektrik"],
  ["nama" => "Oxygen Blender", "kategori" => "Oksigen", "fungsi" => "Blender oksigen", "jenis" => "Reusable"],
  ["nama" => "Oxygen Analyzer", "kategori" => "Oksigen", "fungsi" => "Analisis oksigen", "jenis" => "Elektrik"],
  ["nama" => "Pulse Oximeter", "kategori" => "Oksigen", "fungsi" => "Oximeter", "jenis" => "Elektrik"],

  // ==================== ALAT FISIOTERAPI ====================
  ["nama" => "TENS Unit", "kategori" => "Fisioterapi", "fungsi" => "Stimulasi saraf", "jenis" => "Elektrik"],
  ["nama" => "EMS Unit", "kategori" => "Fisioterapi", "fungsi" => "Stimulasi otot", "jenis" => "Elektrik"],
  ["nama" => "Ultrasound Therapy", "kategori" => "Fisioterapi", "fungsi" => "Terapi ultrasonik", "jenis" => "Elektrik"],
  ["nama" => "Shortwave Diathermy", "kategori" => "Fisioterapi", "fungsi" => "Diatermi gelombang pendek", "jenis" => "Elektrik"],
  ["nama" => "Microwave Diathermy", "kategori" => "Fisioterapi", "fungsi" => "Diatermi gelombang mikro", "jenis" => "Elektrik"],
  ["nama" => "Infrared Lamp", "kategori" => "Fisioterapi", "fungsi" => "Terapi inframerah", "jenis" => "Elektrik"],
  ["nama" => "Ultraviolet Lamp", "kategori" => "Fisioterapi", "fungsi" => "Terapi ultraviolet", "jenis" => "Elektrik"],
  ["nama" => "Laser Therapy", "kategori" => "Fisioterapi", "fungsi" => "Terapi laser", "jenis" => "Elektrik"],
  ["nama" => "Magnetotherapy", "kategori" => "Fisioterapi", "fungsi" => "Terapi magnet", "jenis" => "Elektrik"],
  ["nama" => "Traction Unit", "kategori" => "Fisioterapi", "fungsi" => "Traksi", "jenis" => "Elektrik"],
  ["nama" => "Cervical Traction", "kategori" => "Fisioterapi", "fungsi" => "Traksi servikal", "jenis" => "Elektrik"],
  ["nama" => "Lumbar Traction", "kategori" => "Fisioterapi", "fungsi" => "Traksi lumbal", "jenis" => "Elektrik"],
  ["nama" => "Continuous Passive Motion (CPM)", "kategori" => "Fisioterapi", "fungsi" => "CPM", "jenis" => "Elektrik"],
  ["nama" => "Exercise Equipment", "kategori" => "Fisioterapi", "fungsi" => "Alat latihan", "jenis" => "Reusable"],
  ["nama" => "Theraband", "kategori" => "Fisioterapi", "fungsi" => "Band latihan", "jenis" => "Reusable"],
  ["nama" => "Exercise Ball", "kategori" => "Fisioterapi", "fungsi" => "Bola latihan", "jenis" => "Reusable"],
  ["nama" => "Balance Board", "kategori" => "Fisioterapi", "fungsi" => "Papan keseimbangan", "jenis" => "Reusable"],
  ["nama" => "Wobble Board", "kategori" => "Fisioterapi", "fungsi" => "Papan wobble", "jenis" => "Reusable"],
  ["nama" => "Parallel Bars", "kategori" => "Fisioterapi", "fungsi" => "Palang paralel", "jenis" => "Reusable"],
  ["nama" => "Walking Belt", "kategori" => "Fisioterapi", "fungsi" => "Sabuk jalan", "jenis" => "Reusable"],
  ["nama" => "Gait Trainer", "kategori" => "Fisioterapi", "fungsi" => "Alat latihan jalan", "jenis" => "Elektrik"],
  ["nama" => "Treadmill Rehab", "kategori" => "Fisioterapi", "fungsi" => "Treadmill rehabilitasi", "jenis" => "Elektrik"],
  ["nama" => "Stationary Bike", "kategori" => "Fisioterapi", "fungsi" => "Sepeda statis", "jenis" => "Elektrik"],
  ["nama" => "Arm Ergometer", "kategori" => "Fisioterapi", "fungsi" => "Ergometer lengan", "jenis" => "Elektrik"],
  ["nama" => "Leg Press", "kategori" => "Fisioterapi", "fungsi" => "Leg press", "jenis" => "Reusable"],
  ["nama" => "Shoulder Wheel", "kategori" => "Fisioterapi", "fungsi" => "Roda bahu", "jenis" => "Reusable"],
  ["nama" => "Finger Ladder", "kategori" => "Fisioterapi", "fungsi" => "Tangga jari", "jenis" => "Reusable"],
  ["nama" => "Pulley System", "kategori" => "Fisioterapi", "fungsi" => "Sistem katrol", "jenis" => "Reusable"],
  ["nama" => "Hot Pack", "kategori" => "Fisioterapi", "fungsi" => "Kompres panas", "jenis" => "Reusable"],
  ["nama" => "Cold Pack", "kategori" => "Fisioterapi", "fungsi" => "Kompres dingin", "jenis" => "Reusable"],
  ["nama" => "Paraffin Bath", "kategori" => "Fisioterapi", "fungsi" => "Mandian parafin", "jenis" => "Elektrik"],
  ["nama" => "Whirlpool Bath", "kategori" => "Fisioterapi", "fungsi" => "Mandian whirlpool", "jenis" => "Elektrik"],
  ["nama" => "Hydrotherapy Pool", "kategori" => "Fisioterapi", "fungsi" => "Kolam hidroterapi", "jenis" => "Elektrik"],
  ["nama" => "Massage Table", "kategori" => "Fisioterapi", "fungsi" => "Meja pijat", "jenis" => "Reusable"],
  ["nama" => "Massage Chair", "kategori" => "Fisioterapi", "fungsi" => "Kursi pijat", "jenis" => "Elektrik"],
  ["nama" => "Massage Gun", "kategori" => "Fisioterapi", "fungsi" => "Pistol pijat", "jenis" => "Elektrik"],
  ["nama" => "Foam Roller", "kategori" => "Fisioterapi", "fungsi" => "Foam roller", "jenis" => "Reusable"],
  ["nama" => "Massage Ball", "kategori" => "Fisioterapi", "fungsi" => "Bola pijat", "jenis" => "Reusable"],
  ["nama" => "Kinesio Tape", "kategori" => "Fisioterapi", "fungsi" => "Pita kinesio", "jenis" => "Disposable"],
  ["nama" => "Athletic Tape", "kategori" => "Fisioterapi", "fungsi" => "Pita atletik", "jenis" => "Disposable"],

  // ==================== ALAT RADIOLOGI ====================
  ["nama" => "X-Ray Machine", "kategori" => "Radiologi", "fungsi" => "Rontgen", "jenis" => "Elektrik"],
  ["nama" => "X-Ray Mobile", "kategori" => "Radiologi", "fungsi" => "Rontgen mobile", "jenis" => "Elektrik"],
  ["nama" => "X-Ray Portable", "kategori" => "Radiologi", "fungsi" => "Rontgen portable", "jenis" => "Elektrik"],
  ["nama" => "X-Ray C-Arm", "kategori" => "Radiologi", "fungsi" => "Rontgen C-Arm", "jenis" => "Elektrik"],
  ["nama" => "X-Ray Fluoroscopy", "kategori" => "Radiologi", "fungsi" => "Rontgen fluoroskopi", "jenis" => "Elektrik"],
  ["nama" => "CT Scanner", "kategori" => "Radiologi", "fungsi" => "CT scan", "jenis" => "Elektrik"],
  ["nama" => "MRI Scanner", "kategori" => "Radiologi", "fungsi" => "MRI", "jenis" => "Elektrik"],
  ["nama" => "USG Machine", "kategori" => "Radiologi", "fungsi" => "USG", "jenis" => "Elektrik"],
  ["nama" => "Doppler USG", "kategori" => "Radiologi", "fungsi" => "USG Doppler", "jenis" => "Elektrik"],
  ["nama" => "Mammography", "kategori" => "Radiologi", "fungsi" => "Mammografi", "jenis" => "Elektrik"],
  ["nama" => "Bone Densitometry", "kategori" => "Radiologi", "fungsi" => "Densitometri tulang", "jenis" => "Elektrik"],
  ["nama" => "Panoramic X-Ray", "kategori" => "Radiologi", "fungsi" => "Rontgen panoramik", "jenis" => "Elektrik"],
  ["nama" => "Cephalometric X-Ray", "kategori" => "Radiologi", "fungsi" => "Rontgen cephalometri", "jenis" => "Elektrik"],
  ["nama" => "Dental X-Ray", "kategori" => "Radiologi", "fungsi" => "Rontgen gigi", "jenis" => "Elektrik"],
  ["nama" => "PET Scan", "kategori" => "Radiologi", "fungsi" => "PET scan", "jenis" => "Elektrik"],
  ["nama" => "SPECT Scan", "kategori" => "Radiologi", "fungsi" => "SPECT scan", "jenis" => "Elektrik"],
  ["nama" => "Gamma Camera", "kategori" => "Radiologi", "fungsi" => "Kamera gamma", "jenis" => "Elektrik"],
  ["nama" => "Angiography Machine", "kategori" => "Radiologi", "fungsi" => "Angiografi", "jenis" => "Elektrik"],
  ["nama" => "Cath Lab", "kategori" => "Radiologi", "fungsi" => "Laboratorium kateterisasi", "jenis" => "Elektrik"],
  ["nama" => "Radiotherapy Machine", "kategori" => "Radiologi", "fungsi" => "Radioterapi", "jenis" => "Elektrik"],
  ["nama" => "Linear Accelerator", "kategori" => "Radiologi", "fungsi" => "Linear accelerator", "jenis" => "Elektrik"],
  ["nama" => "Brachytherapy", "kategori" => "Radiologi", "fungsi" => "Brakiterapi", "jenis" => "Elektrik"],
  ["nama" => "Gamma Knife", "kategori" => "Radiologi", "fungsi" => "Gamma knife", "jenis" => "Elektrik"],
  ["nama" => "CyberKnife", "kategori" => "Radiologi", "fungsi" => "CyberKnife", "jenis" => "Elektrik"],
  ["nama" => "Proton Therapy", "kategori" => "Radiologi", "fungsi" => "Terapi proton", "jenis" => "Elektrik"],
  ["nama" => "Radiation Dosimeter", "kategori" => "Radiologi", "fungsi" => "Dosimeter radiasi", "jenis" => "Reusable"],
  ["nama" => "Lead Apron", "kategori" => "Radiologi", "fungsi" => "Apron timbal", "jenis" => "Reusable"],
  ["nama" => "Thyroid Shield", "kategori" => "Radiologi", "fungsi" => "Perisai tiroid", "jenis" => "Reusable"],
  ["nama" => "Gonad Shield", "kategori" => "Radiologi", "fungsi" => "Perisai gonad", "jenis" => "Reusable"],
  ["nama" => "Mobile Barrier", "kategori" => "Radiologi", "fungsi" => "Barrier mobile", "jenis" => "Reusable"],
  ["nama" => "View Box", "kategori" => "Radiologi", "fungsi" => "Kotak baca film", "jenis" => "Elektrik"],
  ["nama" => "PACS System", "kategori" => "Radiologi", "fungsi" => "Sistem PACS", "jenis" => "Elektrik"],
  ["nama" => "DICOM Viewer", "kategori" => "Radiologi", "fungsi" => "Viewer DICOM", "jenis" => "Elektrik"],
  ["nama" => "Film Processor", "kategori" => "Radiologi", "fungsi" => "Prosesor film", "jenis" => "Elektrik"],
  ["nama" => "CR Reader", "kategori" => "Radiologi", "fungsi" => "Pembaca CR", "jenis" => "Elektrik"],
  ["nama" => "DR Detector", "kategori" => "Radiologi", "fungsi" => "Detektor DR", "jenis" => "Elektrik"],
  ["nama" => "Grid", "kategori" => "Radiologi", "fungsi" => "Grid radiologi", "jenis" => "Reusable"],
  ["nama" => "Collimator", "kategori" => "Radiologi", "fungsi" => "Kollimator", "jenis" => "Reusable"],
  ["nama" => "Cassette", "kategori" => "Radiologi", "fungsi" => "Kaset radiologi", "jenis" => "Reusable"],
  ["nama" => "Intensifying Screen", "kategori" => "Radiologi", "fungsi" => "Layar intensifikasi", "jenis" => "Reusable"],
  ["nama" => "X-Ray Film", "kategori" => "Radiologi", "fungsi" => "Film rontgen", "jenis" => "Disposable"],
  ["nama" => "Contrast Media", "kategori" => "Radiologi", "fungsi" => "Media kontras", "jenis" => "Disposable"],
  ["nama" => "Barium Sulfate", "kategori" => "Radiologi", "fungsi" => "Barium sulfat", "jenis" => "Disposable"],
  ["nama" => "Iodinated Contrast", "kategori" => "Radiologi", "fungsi" => "Kontras iodin", "jenis" => "Disposable"],
  ["nama" => "Gadolinium Contrast", "kategori" => "Radiologi", "fungsi" => "Kontras gadolinium", "jenis" => "Disposable"],
  ["nama" => "Injector Contrast", "kategori" => "Radiologi", "fungsi" => "Injector kontras", "jenis" => "Elektrik"],
  ["nama" => "Pressure Injector", "kategori" => "Radiologi", "fungsi" => "Injector tekanan", "jenis" => "Elektrik"]
];

?>