<?php

$tenagaKesehatan = [
  // ==================== TENAGA MEDIS ====================
  ["nama" => "Dokter Umum", "kategori" => "Tenaga Medis", "pendidikan" => "S1 Kedokteran + Profesi Dokter", "tugas" => "Melakukan pemeriksaan, diagnosis, pengobatan pasien umum, merujuk ke spesialis, menjaga rekam medis"],
  ["nama" => "Dokter Spesialis Penyakit Dalam", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Penyakit Dalam", "tugas" => "Menangani penyakit organ dalam, diabetes, hipertensi, infeksi, autoimun"],
  ["nama" => "Dokter Spesialis Anak", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Anak", "tugas" => "Menangani kesehatan bayi, anak, imunisasi, tumbuh kembang"],
  ["nama" => "Dokter Spesialis Bedah", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Bedah", "tugas" => "Melakukan operasi umum, bedah digestif, bedah onkologi"],
  ["nama" => "Dokter Spesialis Bedah Orthopedi", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Orthopedi", "tugas" => "Menangani cedera tulang, sendi, fraktur, sports injury"],
  ["nama" => "Dokter Spesialis Bedah Saraf", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Bedah Saraf", "tugas" => "Operasi otak, sumsum tulang belakang, saraf"],
  ["nama" => "Dokter Spesialis Bedah Plastik", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Bedah Plastik", "tugas" => "Rekonstruksi, estetika, luka bakar, cangkok kulit"],
  ["nama" => "Dokter Spesialis Bedah Toraks Kardiovaskular", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Bedah Toraks Kardiovaskular", "tugas" => "Operasi jantung, paru, pembuluh darah"],
  ["nama" => "Dokter Spesialis Bedah Digestif", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Bedah Digestif", "tugas" => "Operasi saluran cerna, hati, empedu"],
  ["nama" => "Dokter Spesialis Bedah Urologi", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Urologi", "tugas" => "Menangani saluran kemih, ginjal, prostat"],
  ["nama" => "Dokter Spesialis Obstetri & Ginekologi", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Obstetri & Ginekologi", "tugas" => "Menangani kehamilan, persalinan, kandungan, operasi caesar"],
  ["nama" => "Dokter Spesialis Mata", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Mata", "tugas" => "Menangani gangguan mata, operasi katarak, glaukoma, retina"],
  ["nama" => "Dokter Spesialis THT-KL", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis THT-KL", "tugas" => "Menangani telinga, hidung, tenggorokan, kepala leher"],
  ["nama" => "Dokter Spesialis Kulit & Kelamin", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Dermatologi & Venereologi", "tugas" => "Menangani penyakit kulit, kelamin, estetika"],
  ["nama" => "Dokter Spesialis Saraf", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Neurologi", "tugas" => "Menangani stroke, epilepsi, Parkinson, nyeri saraf"],
  ["nama" => "Dokter Spesialis Jiwa", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Psikiatri", "tugas" => "Menangani gangguan mental, depresi, skizofrenia, adiksi"],
  ["nama" => "Dokter Spesialis Jantung", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Jantung & Pembuluh Darah", "tugas" => "Menangani penyakit jantung, hipertensi, aritmia, kateterisasi"],
  ["nama" => "Dokter Spesialis Paru", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Pulmonologi", "tugas" => "Menangani asma, TBC, PPOK, kanker paru"],
  ["nama" => "Dokter Spesialis Radiologi", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Radiologi", "tugas" => "Membaca hasil rontgen, CT scan, MRI, USG"],
  ["nama" => "Dokter Spesialis Patologi Klinik", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Patologi Klinik", "tugas" => "Menganalisis hasil laboratorium, diagnosis penyakit"],
  ["nama" => "Dokter Spesialis Patologi Anatomi", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Patologi Anatomi", "tugas" => "Menganalisis jaringan biopsi, diagnosis kanker"],
  ["nama" => "Dokter Spesialis Anestesi", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Anestesiologi", "tugas" => "Melakukan anestesi operasi, manajemen nyeri, ICU"],
  ["nama" => "Dokter Spesialis Rehabilitasi Medik", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Kedokteran Fisik & Rehabilitasi", "tugas" => "Rehabilitasi pasien stroke, cedera, disabilitas"],
  ["nama" => "Dokter Spesialis Forensik", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Forensik & Medikolegal", "tugas" => "Autopsi, visum et repertum, forensik"],
  ["nama" => "Dokter Spesialis Gizi Klinik", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Gizi Klinik", "tugas" => "Menangani gizi pasien, diet khusus, obesitas"],
  ["nama" => "Dokter Spesialis Mikrobiologi Klinik", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Mikrobiologi Klinik", "tugas" => "Menganalisis infeksi, resistensi antibiotik"],
  ["nama" => "Dokter Spesialis Kedokteran Olahraga", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Kedokteran Olahraga", "tugas" => "Menangani cedera olahraga, performa atlet"],
  ["nama" => "Dokter Spesialis Kedokteran Nuklir", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Kedokteran Nuklir", "tugas" => "Diagnosis dan terapi dengan radioisotop"],
  ["nama" => "Dokter Spesialis Onkologi Radiasi", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Onkologi Radiasi", "tugas" => "Radioterapi kanker"],
  ["nama" => "Dokter Spesialis Onkologi Medik", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Onkologi Medik", "tugas" => "Kemoterapi, imunoterapi kanker"],
  ["nama" => "Dokter Gigi", "kategori" => "Tenaga Medis", "pendidikan" => "S1 Kedokteran Gigi + Profesi Dokter Gigi", "tugas" => "Memeriksa gigi, menambal, mencabut, membersihkan karang gigi"],
  ["nama" => "Dokter Gigi Spesialis Orthodonti", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Ortodonti", "tugas" => "Merapikan gigi dengan behel, ortodonti"],
  ["nama" => "Dokter Gigi Spesialis Bedah Mulut", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Bedah Mulut & Maksilofasial", "tugas" => "Operasi mulut, rahang, wajah"],
  ["nama" => "Dokter Gigi Spesialis Konservasi Gigi", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Konservasi Gigi", "tugas" => "Perawatan saluran akar, restorasi gigi"],
  ["nama" => "Dokter Gigi Spesialis Periodonsi", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Periodonsi", "tugas" => "Menangani penyakit gusi, jaringan pendukung gigi"],
  ["nama" => "Dokter Gigi Spesialis Prosthodonsi", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Prosthodonsi", "tugas" => "Membuat gigi palsu, mahkota, jembatan"],
  ["nama" => "Dokter Gigi Spesialis Pedodonti", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Kedokteran Gigi Anak", "tugas" => "Menangani gigi anak"],
  ["nama" => "Dokter Gigi Spesialis Radiologi Kedokteran Gigi", "kategori" => "Tenaga Medis", "pendidikan" => "Spesialis Radiologi Kedokteran Gigi", "tugas" => "Rontgen gigi, panoramik, CBCT"],

  // ==================== TENAGA KEPERAWATAN ====================
  ["nama" => "Perawat", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan + Profesi Ners", "tugas" => "Merawat pasien, memberikan obat, monitoring tanda vital, asuhan keperawatan"],
  ["nama" => "Perawat ICU", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan + Pelatihan ICU", "tugas" => "Merawat pasien kritis, ventilator, monitoring intensif"],
  ["nama" => "Perawat Bedah", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan + Pelatihan Bedah", "tugas" => "Membantu operasi, instrumen bedah, perawatan luka"],
  ["nama" => "Perawat Anak", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan + Pelatihan Anak", "tugas" => "Merawat bayi dan anak, imunisasi, tumbuh kembang"],
  ["nama" => "Perawat Maternitas", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan + Pelatihan Maternitas", "tugas" => "Merawat ibu hamil, bersalin, nifas, bayi baru lahir"],
  ["nama" => "Perawat Jiwa", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan + Pelatihan Jiwa", "tugas" => "Merawat pasien gangguan jiwa, terapi aktivitas kelompok"],
  ["nama" => "Perawat Komunitas", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan + Pelatihan Komunitas", "tugas" => "Perawatan kesehatan masyarakat, puskesmas, home care"],
  ["nama" => "Perawat Gerontik", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan + Pelatihan Gerontik", "tugas" => "Merawat lansia, panti jompo, home care lansia"],
  ["nama" => "Perawat Medikal Bedah", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan + Pelatihan Medikal Bedah", "tugas" => "Merawat pasien dewasa dengan penyakit medis dan bedah"],
  ["nama" => "Perawat Gawat Darurat", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan + Pelatihan Emergency", "tugas" => "Menangani pasien gawat darurat, triase, resusitasi"],
  ["nama" => "Perawat Hemodialisis", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan + Pelatihan Hemodialisis", "tugas" => "Menangani pasien cuci darah, mesin dialisis"],
  ["nama" => "Perawat Kamar Operasi", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan + Pelatihan OK", "tugas" => "Menyiapkan instrumen operasi, membantu dokter bedah"],
  ["nama" => "Perawat Recovery Room", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan + Pelatihan RR", "tugas" => "Merawat pasien pasca operasi"],
  ["nama" => "Perawat Poliklinik", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan", "tugas" => "Melayani pasien rawat jalan, asisten dokter"],
  ["nama" => "Perawat Home Care", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan", "tugas" => "Merawat pasien di rumah, perawatan luka, kateter"],
  ["nama" => "Perawat Sekolah", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan", "tugas" => "UKS, kesehatan sekolah, pertolongan pertama"],
  ["nama" => "Perawat Perusahaan", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan", "tugas" => "Klinik perusahaan, kesehatan kerja, P3K"],
  ["nama" => "Bidan", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Kebidanan + Profesi Bidan", "tugas" => "Menangani kehamilan, persalinan normal, nifas, bayi baru lahir, KB"],
  ["nama" => "Bidan Delima", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3 Kebidanan + Sertifikasi", "tugas" => "Praktik mandiri bidan, pelayanan KB, ANC, PNC"],
  ["nama" => "Bidan Desa", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3 Kebidanan", "tugas" => "Melayani kesehatan ibu dan anak di desa, posyandu"],
  ["nama" => "Bidan Puskesmas", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4 Kebidanan", "tugas" => "KIA di puskesmas, imunisasi, KB, persalinan"],
  ["nama" => "Bidan Rumah Sakit", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4 Kebidanan", "tugas" => "Persalinan di RS, kamar bersalin, perawatan maternitas"],
  ["nama" => "Bidan Klinik", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3 Kebidanan", "tugas" => "Pelayanan KB, ANC, PNC, imunisasi"],
  ["nama" => "Bidan Komunitas", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4 Kebidanan", "tugas" => "Pelayanan kesehatan ibu dan anak di komunitas"],
  ["nama" => "Perawat Anestesi", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D4 Keperawatan Anestesi", "tugas" => "Membantu anestesi, monitoring pasien operasi"],
  ["nama" => "Perawat Penanggung Jawab Asuhan", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan", "tugas" => "Mengelola asuhan keperawatan pasien"],
  ["nama" => "Kepala Ruangan", "kategori" => "Tenaga Keperawatan", "pendidikan" => "D3/D4/S1 Keperawatan + Manajemen", "tugas" => "Mengelola ruangan, jadwal perawat, mutu asuhan"],
  ["nama" => "Perawat Pendidikan", "kategori" => "Tenaga Keperawatan", "pendidikan" => "S1/S2 Keperawatan", "tugas" => "Mengajar, melatih perawat, pendidikan keperawatan"],
  ["nama" => "Perawat Peneliti", "kategori" => "Tenaga Keperawatan", "pendidikan" => "S2/S3 Keperawatan", "tugas" => "Penelitian keperawatan, publikasi ilmiah"],
  ["nama" => "Perawat Konsultan", "kategori" => "Tenaga Keperawatan", "pendidikan" => "S2/S3 Keperawatan", "tugas" => "Konsultasi keperawatan, manajemen kasus"],

  // ==================== TENAGA KEFARMASIAN ====================
  ["nama" => "Apoteker", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "S1 Farmasi + Profesi Apoteker", "tugas" => "Menyiapkan obat, pelayanan resep, konseling obat, manajemen apotek"],
  ["nama" => "Apoteker Penanggung Jawab", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "S1 Farmasi + Profesi Apoteker", "tugas" => "Penanggung jawab apotek, legalitas, mutu obat"],
  ["nama" => "Apoteker Industri", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "S1 Farmasi + Profesi Apoteker", "tugas" => "Produksi obat, QC, QA, registrasi obat"],
  ["nama" => "Apoteker Rumah Sakit", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "S1 Farmasi + Profesi Apoteker", "tugas" => "Pelayanan farmasi RS, PFT, steril, obat kanker"],
  ["nama" => "Apoteker Puskesmas", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "S1 Farmasi + Profesi Apoteker", "tugas" => "Pengelolaan obat puskesmas, pelayanan resep"],
  ["nama" => "Apoteker Klinik", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "S1 Farmasi + Profesi Apoteker", "tugas" => "Pelayanan farmasi klinik, konseling pasien"],
  ["nama" => "Tenaga Teknis Kefarmasian", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "D3 Farmasi", "tugas" => "Menyiapkan obat, meracik, melayani resep"],
  ["nama" => "Asisten Apoteker", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "D3 Farmasi", "tugas" => "Membantu apoteker, menyiapkan obat, melayani resep"],
  ["nama" => "Farmasis", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "S1 Farmasi", "tugas" => "Penelitian, pengembangan obat, QC"],
  ["nama" => "Apoteker Komunitas", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "S1 Farmasi + Profesi Apoteker", "tugas" => "Apotek komunitas, pelayanan swamedikasi"],
  ["nama" => "Apoteker Regulatory", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "S1 Farmasi + Profesi Apoteker", "tugas" => "Registrasi obat, izin edar, BPOM"],
  ["nama" => "Apoteker Quality Control", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "S1 Farmasi + Profesi Apoteker", "tugas" => "Kontrol kualitas obat, uji laboratorium"],
  ["nama" => "Apoteker Quality Assurance", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "S1 Farmasi + Profesi Apoteker", "tugas" => "Jaminan mutu obat, audit, dokumentasi"],
  ["nama" => "Apoteker Produksi", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "S1 Farmasi + Profesi Apoteker", "tugas" => "Produksi obat, formulasi, scale-up"],
  ["nama" => "Apoteker Riset", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "S1 Farmasi + Profesi Apoteker", "tugas" => "Riset obat baru, formulasi, uji klinis"],
  ["nama" => "Apoteker Kosmetik", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "S1 Farmasi + Profesi Apoteker", "tugas" => "Formulasi kosmetik, uji stabilitas, registrasi"],
  ["nama" => "Apoteker Makanan", "kategori" => "Tenaga Kefarmasian", "pendidikan" => "S1 Farmasi + Profesi Apoteker", "tugas" => "Pengawasan makanan, BPOM, keamanan pangan"],

  // ==================== TENAGA KESEHATAN MASYARAKAT ====================
  ["nama" => "Epidemiolog", "kategori" => "Kesehatan Masyarakat", "pendidikan" => "S1/S2 Epidemiologi", "tugas" => "Investigasi wabah, surveilans penyakit, analisis data kesehatan"],
  ["nama" => "Ahli Kesehatan Masyarakat", "kategori" => "Kesehatan Masyarakat", "pendidikan" => "S1/S2 Kesehatan Masyarakat", "tugas" => "Program kesehatan, promosi kesehatan, pemberdayaan masyarakat"],
  ["nama" => "Penyuluh Kesehatan", "kategori" => "Kesehatan Masyarakat", "pendidikan" => "D3/S1 Kesehatan Masyarakat", "tugas" => "Penyuluhan kesehatan, edukasi masyarakat, kampanye kesehatan"],
  ["nama" => "Administrator Kesehatan", "kategori" => "Kesehatan Masyarakat", "pendidikan" => "S1 Administrasi Kesehatan", "tugas" => "Manajemen RS, puskesmas, klaim BPJS, administrasi"],
  ["nama" => "Ahli Gizi", "kategori" => "Kesehatan Masyarakat", "pendidikan" => "D3/D4/S1 Gizi", "tugas" => "Menyusun diet pasien, konseling gizi, asuhan gizi"],
  ["nama" => "Dietisien", "kategori" => "Kesehatan Masyarakat", "pendidikan" => "D3/D4/S1 Gizi + Profesi Dietisien", "tugas" => "Terapi diet, asuhan gizi klinik, monitoring gizi"],
  ["nama" => "Nutrisionis", "kategori" => "Kesehatan Masyarakat", "pendidikan" => "D3 Gizi", "tugas" => "Menyiapkan makanan pasien, penyuluhan gizi"],
  ["nama" => "Ahli Kesehatan Lingkungan", "kategori" => "Kesehatan Lingkungan", "pendidikan" => "D3/D4/S1 Kesehatan Lingkungan", "tugas" => "Sanitasi, pengendalian vektor, kualitas air, limbah"],
  ["nama" => "Sanitarian", "kategori" => "Kesehatan Lingkungan", "pendidikan" => "D3 Kesehatan Lingkungan", "tugas" => "Inspeksi sanitasi, pengendalian vektor, penyuluhan lingkungan"],
  ["nama" => "Ahli Kesehatan Kerja", "kategori" => "Kesehatan Kerja", "pendidikan" => "S1/S2 Kesehatan Kerja", "tugas" => "Kesehatan kerja, ergonomi, keselamatan kerja, higiene industri"],
  ["nama" => "Ahli Keselamatan Kerja", "kategori" => "Kesehatan Kerja", "pendidikan" => "S1/S2 K3", "tugas" => "Manajemen K3, audit keselamatan, investigasi kecelakaan"],
  ["nama" => "Hygienist Industri", "kategori" => "Kesehatan Kerja", "pendidikan" => "S1/S2 Higiene Industri", "tugas" => "Pengukuran paparan, monitoring lingkungan kerja"],
  ["nama" => "Ergonom", "kategori" => "Kesehatan Kerja", "pendidikan" => "S1/S2 Ergonomi", "tugas" => "Desain kerja, postur, pencegahan cedera kerja"],
  ["nama" => "Ahli Promosi Kesehatan", "kategori" => "Kesehatan Masyarakat", "pendidikan" => "S1/S2 Promosi Kesehatan", "tugas" => "Kampanye kesehatan, media edukasi, pemberdayaan"],
  ["nama" => "Ahli Biostatistik", "kategori" => "Kesehatan Masyarakat", "pendidikan" => "S1/S2 Biostatistik", "tugas" => "Analisis data kesehatan, penelitian, statistik"],
  ["nama" => "Ahli Kesehatan Reproduksi", "kategori" => "Kesehatan Masyarakat", "pendidikan" => "S1/S2 Kesehatan Reproduksi", "tugas" => "Program KB, kesehatan ibu, kespro remaja"],
  ["nama" => "Ahli Kesehatan Ibu dan Anak", "kategori" => "Kesehatan Masyarakat", "pendidikan" => "S1/S2 KIA", "tugas" => "Program KIA, posyandu, imunisasi, gizi ibu anak"],
  ["nama" => "Ahli Surveilans", "kategori" => "Kesehatan Masyarakat", "pendidikan" => "S1/S2 Surveilans", "tugas" => "Pemantauan penyakit, deteksi dini wabah, pelaporan"],
  ["nama" => "Ahli Kesehatan Global", "kategori" => "Kesehatan Masyarakat", "pendidikan" => "S1/S2 Kesehatan Global", "tugas" => "Kerjasama internasional, kebijakan kesehatan global"],
  ["nama" => "Ahli Kebijakan Kesehatan", "kategori" => "Kesehatan Masyarakat", "pendidikan" => "S1/S2 Kebijakan Kesehatan", "tugas" => "Analisis kebijakan, advokasi, regulasi kesehatan"],

  // ==================== TENAGA KETERAPIAN FISIK ====================
  ["nama" => "Fisioterapis", "kategori" => "Keterapian Fisik", "pendidikan" => "D3/D4/S1 Fisioterapi + Profesi", "tugas" => "Rehabilitasi gerak, terapi latihan, modalitas fisik"],
  ["nama" => "Okupasi Terapis", "kategori" => "Keterapian Fisik", "pendidikan" => "D3/D4/S1 Okupasi Terapi + Profesi", "tugas" => "Terapi aktivitas sehari-hari, rehabilitasi vokasional"],
  ["nama" => "Terapis Wicara", "kategori" => "Keterapian Fisik", "pendidikan" => "D3/D4/S1 Terapi Wicara + Profesi", "tugas" => "Terapi bicara, bahasa, menelan, komunikasi"],
  ["nama" => "Ortotis Prostetis", "kategori" => "Keterapian Fisik", "pendidikan" => "D3/D4/S1 Ortotik Prostetik + Profesi", "tugas" => "Membuat alat bantu ortotik, prostetik, sepatu orthopedi"],
  ["nama" => "Terapis Okupasi", "kategori" => "Keterapian Fisik", "pendidikan" => "D3/D4/S1 Okupasi Terapi", "tugas" => "Rehabilitasi pasien stroke, cedera, disabilitas"],
  ["nama" => "Terapis Fisik Olahraga", "kategori" => "Keterapian Fisik", "pendidikan" => "S1 Fisioterapi + Spesialisasi", "tugas" => "Rehabilitasi atlet, cedera olahraga, performa"],
  ["nama" => "Terapis Pediatri", "kategori" => "Keterapian Fisik", "pendidikan" => "S1 Fisioterapi + Spesialisasi", "tugas" => "Fisioterapi anak, tumbuh kembang, cerebral palsy"],
  ["nama" => "Terapis Geriatri", "kategori" => "Keterapian Fisik", "pendidikan" => "S1 Fisioterapi + Spesialisasi", "tugas" => "Fisioterapi lansia, jatuh, mobilitas"],
  ["nama" => "Terapis Kardiovaskular", "kategori" => "Keterapian Fisik", "pendidikan" => "S1 Fisioterapi + Spesialisasi", "tugas" => "Rehabilitasi jantung, pasca operasi jantung"],
  ["nama" => "Terapis Pernapasan", "kategori" => "Keterapian Fisik", "pendidikan" => "S1 Fisioterapi + Spesialisasi", "tugas" => "Fisioterapi dada, bersih jalan napas, ventilator"],
  ["nama" => "Terapis Neurologi", "kategori" => "Keterapian Fisik", "pendidikan" => "S1 Fisioterapi + Spesialisasi", "tugas" => "Rehabilitasi stroke, saraf, keseimbangan"],

  // ==================== TENAGA KETEKNISIAN MEDIS ====================
  ["nama" => "Radiografer", "kategori" => "Keteknisian Medis", "pendidikan" => "D3/D4 Radiologi", "tugas" => "Mengoperasikan X-Ray, CT, MRI, USG, mammografi"],
  ["nama" => "Teknisi Radiologi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknik Radiologi", "tugas" => "Pencitraan medis, processing film, QC alat"],
  ["nama" => "Terapis Radiasi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3/D4 Radioterapi", "tugas" => "Radioterapi kanker, linear accelerator"],
  ["nama" => "Teknisi Laboratorium Medis", "kategori" => "Keteknisian Medis", "pendidikan" => "D3/D4 Teknologi Laboratorium Medis", "tugas" => "Pemeriksaan laboratorium, sampling, analisis"],
  ["nama" => "Analis Laboratorium", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Analis Kesehatan", "tugas" => "Analisis darah, urin, mikrobiologi, kimia"],
  ["nama" => "Teknisi Bank Darah", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Bank Darah", "tugas" => "Pengelolaan darah, crossmatch, penyimpanan"],
  ["nama" => "Teknisi Elektromedik", "kategori" => "Keteknisian Medis", "pendidikan" => "D3/D4 Teknik Elektromedik", "tugas" => "Pemeliharaan alat medis, kalibrasi, perbaikan"],
  ["nama" => "Teknisi Gigi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknik Gigi", "tugas" => "Membuat gigi palsu, mahkota, jembatan, ortodonti"],
  ["nama" => "Teknisi Ortodonti", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknik Ortodonti", "tugas" => "Membuat alat ortodonti, retainer, behel"],
  ["nama" => "Teknisi Kardiovaskular", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Kardiovaskular", "tugas" => "EKG, treadmill, holter, echokardiografi"],
  ["nama" => "Perfusionist", "kategori" => "Keteknisian Medis", "pendidikan" => "D3/D4 Perfusion", "tugas" => "Mengoperasikan mesin heart-lung bypass operasi jantung"],
  ["nama" => "Teknisi Nuklir Medis", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Nuklir Medis", "tugas" => "Pencitraan nuklir, PET, SPECT, radioisotop"],
  ["nama" => "Teknisi Ortotik Prostetik", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Ortotik Prostetik", "tugas" => "Membuat dan memasang alat bantu ortotik prostetik"],
  ["nama" => "Teknisi Anestesi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknik Anestesi", "tugas" => "Membantu anestesi, mesin anestesi, monitoring"],
  ["nama" => "Teknisi Elektrokardiografi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknik EKG", "tugas" => "Perekaman EKG, treadmill, holter"],
  ["nama" => "Teknisi Endoskopi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknik Endoskopi", "tugas" => "Mengoperasikan endoskop, sterilisasi, perawatan alat"],
  ["nama" => "Teknisi Dialisis", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknik Dialisis", "tugas" => "Mengoperasikan mesin dialisis, perawatan akses vaskular"],
  ["nama" => "Teknisi Rekam Medis", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Rekam Medis & Informasi Kesehatan", "tugas" => "Mengelola rekam medis, koding ICD, statistik RS"],
  ["nama" => "Perekam Medis", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Rekam Medis", "tugas" => "Rekam medis, koding, klaim BPJS, arsip"],
  ["nama" => "Koder Medis", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Rekam Medis + Sertifikasi Koder", "tugas" => "Koding diagnosis ICD-10, prosedur ICD-9-CM, klaim"],
  ["nama" => "Teknisi Sterilisasi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknik Sterilisasi", "tugas" => "Sterilisasi alat medis, autoclave, CSSD"],
  ["nama" => "Teknisi Forensik", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknik Forensik", "tugas" => "Membantu autopsi, pengambilan sampel forensik"],
  ["nama" => "Teknisi Histologi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Histologi", "tugas" => "Membuat sediaan jaringan, pewarnaan, mikroskop"],
  ["nama" => "Teknisi Sitologi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Sitologi", "tugas" => "Pemeriksaan sel, Pap smear, sitologi"],
  ["nama" => "Teknisi Imunologi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Imunologi", "tugas" => "Pemeriksaan imunologi, ELISA, flow cytometry"],
  ["nama" => "Teknisi Mikrobiologi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Mikrobiologi", "tugas" => "Kultur bakteri, identifikasi, uji resistensi"],
  ["nama" => "Teknisi Biologi Molekuler", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Biologi Molekuler", "tugas" => "PCR, DNA sequencing, diagnostik molekuler"],
  ["nama" => "Teknisi Toksikologi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Toksikologi", "tugas" => "Pemeriksaan toksikologi, deteksi racun, doping"],
  ["nama" => "Teknisi Genetika", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Genetika", "tugas" => "Pemeriksaan genetik, kromosom, DNA"],
  ["nama" => "Teknisi Patologi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Patologi", "tugas" => "Pemeriksaan patologi klinik dan anatomi"],
  ["nama" => "Teknisi Parasitologi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Parasitologi", "tugas" => "Pemeriksaan parasit, malaria, cacing"],
  ["nama" => "Teknisi Hematologi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Hematologi", "tugas" => "Pemeriksaan darah, koagulasi, hematologi"],
  ["nama" => "Teknisi Kimia Klinik", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Kimia Klinik", "tugas" => "Pemeriksaan kimia darah, enzim, elektrolit"],
  ["nama" => "Teknisi Urinalisis", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Urinalisis", "tugas" => "Pemeriksaan urin, sedimen, kimia urin"],
  ["nama" => "Teknisi Serologi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Serologi", "tugas" => "Pemeriksaan serologi, antibodi, antigen"],
  ["nama" => "Teknisi Virologi", "kategori" => "Keteknisian Medis", "pendidikan" => "D3 Teknologi Virologi", "tugas" => "Pemeriksaan virus, kultur virus, PCR virus"],

  // ==================== TENAGA KESEHATAN TRADISIONAL ====================
  ["nama" => "Pengobat Tradisional", "kategori" => "Kesehatan Tradisional", "pendidikan" => "Pelatihan/Kursus", "tugas" => "Pengobatan tradisional, jamu, akupunktur"],
  ["nama" => "Akupunkturis", "kategori" => "Kesehatan Tradisional", "pendidikan" => "Pendidikan Akupunktur", "tugas" => "Terapi akupunktur, titik meridian, jarum"],
  ["nama" => "Terapis Pijat", "kategori" => "Kesehatan Tradisional", "pendidikan" => "Pelatihan Pijat", "tugas" => "Pijat terapi, refleksi, relaksasi"],
  ["nama" => "Refleksi", "kategori" => "Kesehatan Tradisional", "pendidikan" => "Pelatihan Refleksi", "tugas" => "Terapi refleksi kaki, tangan, telinga"],
  ["nama" => "Herbalis", "kategori" => "Kesehatan Tradisional", "pendidikan" => "Pelatihan Herbal", "tugas" => "Meracik jamu, herbal, pengobatan alami"],
  ["nama" => "Tabib", "kategori" => "Kesehatan Tradisional", "pendidikan" => "Pengalaman/Tradisi", "tugas" => "Pengobatan tradisional, spiritual, herbal"],
  ["nama" => "Dukun Bayi", "kategori" => "Kesehatan Tradisional", "pendidikan" => "Pengalaman/Tradisi", "tugas" => "Menolong persalinan tradisional, perawatan bayi"],
  ["nama" => "Sinse", "kategori" => "Kesehatan Tradisional", "pendidikan" => "Pendidikan Sinse", "tugas" => "Pengobatan tradisional Tionghoa, akupunktur, herbal"],
  ["nama" => "Terapis Bekam", "kategori" => "Kesehatan Tradisional", "pendidikan" => "Pelatihan Bekam", "tugas" => "Terapi bekam, hijamah, detoksifikasi"],
  ["nama" => "Terapis Gua Sha", "kategori" => "Kesehatan Tradisional", "pendidikan" => "Pelatihan Gua Sha", "tugas" => "Terapi gua sha, kerokan, sirkulasi darah"],
  ["nama" => "Terapis Chiropractic", "kategori" => "Kesehatan Tradisional", "pendidikan" => "Pendidikan Chiropractic", "tugas" => "Manipulasi tulang belakang, sendi, nyeri punggung"],
  ["nama" => "Terapis Osteopati", "kategori" => "Kesehatan Tradisional", "pendidikan" => "Pendidikan Osteopati", "tugas" => "Manipulasi osteopati, mobilitas sendi, nyeri"],
  ["nama" => "Terapis Shiatsu", "kategori" => "Kesehatan Tradisional", "pendidikan" => "Pelatihan Shiatsu", "tugas" => "Tekanan jari shiatsu, meridian, relaksasi"],
  ["nama" => "Terapis Aromaterapi", "kategori" => "Kesehatan Tradisional", "pendidikan" => "Pelatihan Aromaterapi", "tugas" => "Terapi minyak esensial, relaksasi, pijat aroma"],
  ["nama" => "Terapis Hidroterapi", "kategori" => "Kesehatan Tradisional", "pendidikan" => "Pelatihan Hidroterapi", "tugas" => "Terapi air, hidroterapi, kolam, sauna"],

  // ==================== TENAGA PSIKOLOGI KLINIS ====================
  ["nama" => "Psikolog Klinis", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + S2 Psikologi Klinis + Profesi", "tugas" => "Asesmen psikologi, terapi psikologi, konseling"],
  ["nama" => "Psikolog Anak", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + S2 Psikologi Klinis Anak", "tugas" => "Asesmen dan terapi anak, tumbuh kembang, autisme"],
  ["nama" => "Psikolog Pendidikan", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + S2 Psikologi Pendidikan", "tugas" => "Asesmen belajar, konseling pendidikan, kesulitan belajar"],
  ["nama" => "Psikolog Industri", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + S2 Psikologi Industri", "tugas" => "Asesmen karyawan, rekrutmen, pengembangan SDM"],
  ["nama" => "Psikolog Forensik", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + S2 Psikologi Forensik", "tugas" => "Asesmen forensik, psikologi hukum, saksi ahli"],
  ["nama" => "Psikolog Olahraga", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + S2 Psikologi Olahraga", "tugas" => "Psikologi atlet, motivasi, performa mental"],
  ["nama" => "Psikolog Kesehatan", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + S2 Psikologi Kesehatan", "tugas" => "Psikologi kesehatan, perilaku sehat, penyakit kronis"],
  ["nama" => "Psikolog Neuropsikologi", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + S2 Neuropsikologi", "tugas" => "Asesmen fungsi otak, rehabilitasi kognitif"],
  ["nama" => "Konselor", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 Bimbingan Konseling", "tugas" => "Konseling individu, kelompok, keluarga"],
  ["nama" => "Konselor Adiksi", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + Pelatihan Adiksi", "tugas" => "Konseling pecandu narkoba, alkohol, rokok"],
  ["nama" => "Konselor HIV/AIDS", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + Pelatihan HIV", "tugas" => "Konseling HIV, tes, dukungan psikososial"],
  ["nama" => "Konselor Genetik", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + Pelatihan Genetik", "tugas" => "Konseling genetik, risiko penyakit, keluarga"],
  ["nama" => "Terapis Perilaku", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + Pelatihan CBT", "tugas" => "Terapi perilaku kognitif, fobia, OCD"],
  ["nama" => "Terapis Keluarga", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + Pelatihan Terapi Keluarga", "tugas" => "Terapi keluarga, komunikasi, konflik"],
  ["nama" => "Terapis Anak", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + Pelatihan Terapi Anak", "tugas" => "Terapi bermain, anak, autisme, ADHD"],
  ["nama" => "Terapis Trauma", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + Pelatihan Trauma", "tugas" => "Terapi trauma, PTSD, EMDR"],
  ["nama" => "Hipnoterapis", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + Pelatihan Hipnoterapi", "tugas" => "Hipnoterapi, sugesti, relaksasi, nyeri"],
  ["nama" => "Psikoterapis", "kategori" => "Psikologi Klinis", "pendidikan" => "S1 + S2 Psikoterapi", "tugas" => "Psikoterapi, psikoanalisis, humanistik"],

  // ==================== TENAGA KESEHATAN LAINNYA ====================
  ["nama" => "Administrator Rumah Sakit", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Administrasi RS", "tugas" => "Manajemen RS, keuangan, SDM, mutu, akreditasi"],
  ["nama" => "Manajer Klinik", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Manajemen Kesehatan", "tugas" => "Mengelola klinik, operasional, keuangan, SDM"],
  ["nama" => "Manajer Puskesmas", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Masyarakat", "tugas" => "Mengelola puskesmas, program kesehatan, SDM"],
  ["nama" => "Kepala Dinas Kesehatan", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Masyarakat", "tugas" => "Kebijakan kesehatan daerah, program, anggaran"],
  ["nama" => "Menteri Kesehatan", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2/S3 Kesehatan", "tugas" => "Kebijakan kesehatan nasional, regulasi, program"],
  ["nama" => "Direktur Rumah Sakit", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Manajemen RS", "tugas" => "Memimpin RS, kebijakan, mutu, akreditasi"],
  ["nama" => "Konsultan Kesehatan", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan", "tugas" => "Konsultasi manajemen kesehatan, mutu, akreditasi"],
  ["nama" => "Auditor Kesehatan", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan", "tugas" => "Audit mutu, audit klaim, audit keuangan kesehatan"],
  ["nama" => "Asuransi Kesehatan", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Asuransi/Kesehatan", "tugas" => "Verifikasi klaim, underwriting, manajemen risiko"],
  ["nama" => "Case Manager", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Keperawatan/Kesehatan", "tugas" => "Manajemen kasus pasien, koordinasi perawatan, discharge planning"],
  ["nama" => "Community Health Worker", "kategori" => "Manajemen Kesehatan", "pendidikan" => "Pelatihan Kader", "tugas" => "Kader kesehatan, posyandu, penyuluhan, rujukan"],
  ["nama" => "Kader Posyandu", "kategori" => "Manajemen Kesehatan", "pendidikan" => "Pelatihan Kader", "tugas" => "Penimbangan balita, imunisasi, penyuluhan gizi"],
  ["nama" => "Kader Kesehatan", "kategori" => "Manajemen Kesehatan", "pendidikan" => "Pelatihan Kader", "tugas" => "Pemberdayaan masyarakat, penyuluhan, deteksi dini"],
  ["nama" => "Pemandu Kesehatan", "kategori" => "Manajemen Kesehatan", "pendidikan" => "Pelatihan", "tugas" => "Pemandu program kesehatan, edukasi, motivasi"],
  ["nama" => "Health Coach", "kategori" => "Manajemen Kesehatan", "pendidikan" => "Sertifikasi Health Coach", "tugas" => "Coaching kesehatan, gaya hidup, motivasi pasien"],
  ["nama" => "Health Educator", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Kesehatan Masyarakat", "tugas" => "Edukasi kesehatan, pengembangan media, pelatihan"],
  ["nama" => "Patient Navigator", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Kesehatan", "tugas" => "Membantu pasien navigasi sistem kesehatan, akses layanan"],
  ["nama" => "Medical Scribe", "kategori" => "Manajemen Kesehatan", "pendidikan" => "D3/S1 Kesehatan", "tugas" => "Dokumentasi medis, mencatat dokter, rekam medis"],
  ["nama" => "Medical Translator", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Bahasa + Kesehatan", "tugas" => "Menerjemahkan medis, komunikasi pasien asing"],
  ["nama" => "Medical Interpreter", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Bahasa + Kesehatan", "tugas" => "Interpretasi medis, komunikasi dokter-pasien"],
  ["nama" => "Medical Writer", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Kesehatan + Menulis", "tugas" => "Menulis artikel medis, edukasi, publikasi"],
  ["nama" => "Medical Representative", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Kesehatan/Farmasi", "tugas" => "Pemasaran obat, edukasi dokter, produk farmasi"],
  ["nama" => "Product Specialist", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Kesehatan/Farmasi", "tugas" => "Spesialis produk medis, alat kesehatan, edukasi"],
  ["nama" => "Clinical Research Associate", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Kesehatan", "tugas" => "Monitoring uji klinis, data, kepatuhan protokol"],
  ["nama" => "Clinical Research Coordinator", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Kesehatan", "tugas" => "Koordinasi uji klinis, rekrutmen subjek, data"],
  ["nama" => "Regulatory Affairs", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Farmasi/Kesehatan", "tugas" => "Registrasi obat/alat kesehatan, BPOM, izin edar"],
  ["nama" => "Pharmacovigilance", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Farmasi/Kesehatan", "tugas" => "Monitoring efek samping obat, pelaporan, keamanan obat"],
  ["nama" => "Medical Affairs", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan", "tugas" => "Edukasi medis, hubungan dokter, strategi medis"],
  ["nama" => "Market Access", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan", "tugas" => "Akses pasar obat, reimbursement, BPJS"],
  ["nama" => "Health Economist", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Ekonomi Kesehatan", "tugas" => "Analisis ekonomi kesehatan, cost-effectiveness, anggaran"],
  ["nama" => "Health Policy Analyst", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kebijakan Kesehatan", "tugas" => "Analisis kebijakan kesehatan, advokasi, rekomendasi"],
  ["nama" => "Health Informatics", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Informatika Kesehatan", "tugas" => "Sistem informasi kesehatan, rekam medis elektronik, data"],
  ["nama" => "Health Data Analyst", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Data Kesehatan", "tugas" => "Analisis data kesehatan, big data, visualisasi"],
  ["nama" => "Telemedicine Specialist", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Kesehatan + Teknologi", "tugas" => "Layanan telemedicine, konsultasi online, monitoring jarak jauh"],
  ["nama" => "Digital Health Specialist", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Kesehatan + Teknologi", "tugas" => "Pengembangan aplikasi kesehatan, wearable, IoT kesehatan"],
  ["nama" => "Artificial Intelligence in Health", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 AI + Kesehatan", "tugas" => "AI diagnosis, machine learning, imaging AI"],
  ["nama" => "Bioinformatika", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Bioinformatika", "tugas" => "Analisis data genom, sekuensing, biologi komputasi"],
  ["nama" => "Genetika Klinis", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Genetika Klinis", "tugas" => "Konseling genetik, diagnosis genetik, tes DNA"],
  ["nama" => "Konselor Genetik", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Konseling Genetik", "tugas" => "Konseling genetik, risiko keluarga, tes genetik"],
  ["nama" => "Ahli Gizi Olahraga", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Gizi Olahraga", "tugas" => "Gizi atlet, performa, suplemen, hidrasi"],
  ["nama" => "Ahli Gizi Klinik", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Gizi Klinik", "tugas" => "Terapi gizi pasien, diabetes, ginjal, kanker"],
  ["nama" => "Ahli Gizi Masyarakat", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Gizi Masyarakat", "tugas" => "Program gizi masyarakat, stunting, anemia, posyandu"],
  ["nama" => "Ahli Gizi Industri", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Gizi Industri", "tugas" => "Gizi karyawan, katering industri, produktivitas"],
  ["nama" => "Ahli Gizi Food Service", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Gizi", "tugas" => "Manajemen penyelenggaraan makanan, menu, mutu"],
  ["nama" => "Ahli Teknologi Pangan", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Teknologi Pangan", "tugas" => "Pengembangan produk pangan, keamanan pangan, gizi"],
  ["nama" => "Ahli Keamanan Pangan", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Keamanan Pangan", "tugas" => "Pengawasan pangan, HACCP, BPOM, keamanan konsumen"],
  ["nama" => "Ahli Kesehatan Hewan", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Kedokteran Hewan", "tugas" => "Kesehatan hewan, zoonosis, vaksin hewan, karantina"],
  ["nama" => "Dokter Hewan", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1 Kedokteran Hewan + Profesi", "tugas" => "Mengobati hewan, operasi hewan, vaksinasi, zoonosis"],
  ["nama" => "Paramedik Veteriner", "kategori" => "Manajemen Kesehatan", "pendidikan" => "D3 Kesehatan Hewan", "tugas" => "Membantu dokter hewan, perawatan hewan, laboratorium"],
  ["nama" => "Ahli Kesehatan Masyarakat Veteriner", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Masyarakat Veteriner", "tugas" => "Zoonosis, keamanan pangan asal hewan, surveilans"],
  ["nama" => "Ahli Kesehatan Tumbuhan", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Tumbuhan", "tugas" => "Kesehatan tanaman, hama, penyakit tanaman, karantina"],
  ["nama" => "Ahli Kesehatan Lingkungan Industri", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Lingkungan", "tugas" => "Limbah industri, pencemaran, AMDAL, kesehatan lingkungan"],
  ["nama" => "Ahli Kesehatan Radiasi", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Fisika Medis", "tugas" => "Proteksi radiasi, dosimetri, keselamatan radiasi"],
  ["nama" => "Fisikawan Medis", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Fisika Medis", "tugas" => "Radioterapi, dosimetri, kalibrasi alat radiasi, QC"],
  ["nama" => "Ahli Kesehatan Nuklir", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Nuklir", "tugas" => "Kedokteran nuklir, radiofarmasi, proteksi radiasi"],
  ["nama" => "Ahli Kesehatan Penerbangan", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Penerbangan", "tugas" => "Kesehatan pilot, awak kabin, aviation medicine"],
  ["nama" => "Ahli Kesehatan Kelautan", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Kelautan", "tugas" => "Kesehatan pelaut, hiperbarik, diving medicine"],
  ["nama" => "Ahli Kesehatan Bencana", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Bencana", "tugas" => "Manajemen bencana, triase, bantuan darurat, logistik"],
  ["nama" => "Ahli Kesehatan Militer", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Militer", "tugas" => "Kesehatan tentara, medan perang, evakuasi, trauma"],
  ["nama" => "Ahli Kesehatan Olahraga", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Olahraga", "tugas" => "Kesehatan atlet, cedera olahraga, doping, performa"],
  ["nama" => "Ahli Kesehatan Reproduksi", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Reproduksi", "tugas" => "Kesehatan reproduksi, KB, kespro remaja, infertilitas"],
  ["nama" => "Ahli Kesehatan Seksual", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Seksual", "tugas" => "Kesehatan seksual, IMS, HIV, konseling"],
  ["nama" => "Ahli Kesehatan Lansia", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Gerontologi", "tugas" => "Kesehatan lansia, panti, home care, penyakit degeneratif"],
  ["nama" => "Ahli Kesehatan Anak", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Anak", "tugas" => "Kesehatan anak, tumbuh kembang, imunisasi, gizi anak"],
  ["nama" => "Ahli Kesehatan Remaja", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Remaja", "tugas" => "Kesehatan remaja, kespro, NAPZA, mental health"],
  ["nama" => "Ahli Kesehatan Perempuan", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Perempuan", "tugas" => "Kesehatan perempuan, menopause, kanker serviks, payudara"],
  ["nama" => "Ahli Kesehatan Pria", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Pria", "tugas" => "Kesehatan pria, prostat, disfungsi ereksi, testosteron"],
  ["nama" => "Ahli Kesehatan Keluarga", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Keluarga", "tugas" => "Kesehatan keluarga, dokter keluarga, home care"],
  ["nama" => "Ahli Kesehatan Komunitas", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Komunitas", "tugas" => "Kesehatan komunitas, puskesmas, posyandu, UKBM"],
  ["nama" => "Ahli Kesehatan Sekolah", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Sekolah", "tugas" => "UKS, kesehatan sekolah, skrining, penyuluhan"],
  ["nama" => "Ahli Kesehatan Kerja", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Kerja", "tugas" => "Kesehatan kerja, ergonomi, K3, penyakit akibat kerja"],
  ["nama" => "Ahli Kesehatan Lingkungan", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Lingkungan", "tugas" => "Sanitasi, air bersih, limbah, vektor, pencemaran"],
  ["nama" => "Ahli Kesehatan Global", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Global", "tugas" => "Kesehatan global, pandemi, kerjasama internasional, WHO"],
  ["nama" => "Ahli Kesehatan Digital", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Digital", "tugas" => "Kesehatan digital, telemedicine, AI, wearable, big data"],
  ["nama" => "Ahli Kesehatan Presisi", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Presisi", "tugas" => "Kedokteran presisi, genomik, personalized medicine"],
  ["nama" => "Ahli Kesehatan Regeneratif", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Regeneratif", "tugas" => "Kedokteran regeneratif, stem cell, tissue engineering"],
  ["nama" => "Ahli Kesehatan Anti-Aging", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Anti-Aging", "tugas" => "Anti-aging, longevity, hormon, nutrisi, estetika"],
  ["nama" => "Ahli Kesehatan Estetika", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Estetika", "tugas" => "Estetika medis, botox, filler, laser, skincare"],
  ["nama" => "Ahli Kesehatan Kulit", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Dermatologi", "tugas" => "Kesehatan kulit, kosmetik, dermatologi estetika"],
  ["nama" => "Ahli Kesehatan Rambut", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Trichology", "tugas" => "Kesehatan rambut, kerontokan, transplantasi rambut"],
  ["nama" => "Ahli Kesehatan Kuku", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Podiatri", "tugas" => "Kesehatan kuku, kaki, podiatri, diabetes foot care"],
  ["nama" => "Ahli Kesehatan Kaki", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Podiatri", "tugas" => "Kesehatan kaki, sepatu orthopedi, diabetes foot"],
  ["nama" => "Ahli Kesehatan Mulut", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kedokteran Gigi", "tugas" => "Kesehatan mulut, gigi, gusi, preventif, promotif"],
  ["nama" => "Ahli Kesehatan Gigi Masyarakat", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kesehatan Gigi Masyarakat", "tugas" => "Kesehatan gigi masyarakat, sikat gigi massal, fluoridasi"],
  ["nama" => "Ahli Kesehatan Gigi Anak", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kedokteran Gigi Anak", "tugas" => "Kesehatan gigi anak, pencegahan karies, edukasi"],
  ["nama" => "Ahli Kesehatan Gigi Keluarga", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kedokteran Gigi Keluarga", "tugas" => "Kesehatan gigi keluarga, preventif, promotif"],
  ["nama" => "Ahli Kesehatan Gigi Lansia", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kedokteran Gigi Lansia", "tugas" => "Kesehatan gigi lansia, gigi palsu, perawatan mulut"],
  ["nama" => "Ahli Kesehatan Gigi Disabilitas", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kedokteran Gigi Disabilitas", "tugas" => "Kesehatan gigi disabilitas, perawatan khusus, sedasi"],
  ["nama" => "Ahli Kesehatan Gigi Ibu Hamil", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kedokteran Gigi", "tugas" => "Kesehatan gigi ibu hamil, gingivitis kehamilan, edukasi"],
  ["nama" => "Ahli Kesehatan Gigi Diabetes", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kedokteran Gigi", "tugas" => "Kesehatan gigi diabetes, periodontitis, penyembuhan luka"],
  ["nama" => "Ahli Kesehatan Gigi Kanker", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kedokteran Gigi", "tugas" => "Kesehatan gigi pasien kanker, mukositis, xerostomia"],
  ["nama" => "Ahli Kesehatan Gigi Kardiovaskular", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kedokteran Gigi", "tugas" => "Kesehatan gigi pasien jantung, endokarditis, antikoagulan"],
  ["nama" => "Ahli Kesehatan Gigi HIV", "kategori" => "Manajemen Kesehatan", "pendidikan" => "S1/S2 Kedokteran Gigi", "tugas" => "Kesehatan gigi pasien HIV, kandidiasis, infeksi oportunistik"]
];

?>