<?php

$virusDunia = [
  // ==================== VIRUS DNA ====================
  // ===== Adenoviridae =====
  ["nama" => "Adenovirus", "famili" => "Adenoviridae", "materi" => "DNA", "penyakit" => "Infeksi Saluran Napas, Konjungtivitis, Gastroenteritis"],
  ["nama" => "Adenovirus Tipe 1", "famili" => "Adenoviridae", "materi" => "DNA", "penyakit" => "Infeksi Saluran Napas"],
  ["nama" => "Adenovirus Tipe 2", "famili" => "Adenoviridae", "materi" => "DNA", "penyakit" => "Infeksi Saluran Napas"],
  ["nama" => "Adenovirus Tipe 3", "famili" => "Adenoviridae", "materi" => "DNA", "penyakit" => "Demam Faringokonjungtival"],
  ["nama" => "Adenovirus Tipe 4", "famili" => "Adenoviridae", "materi" => "DNA", "penyakit" => "Infeksi Saluran Napas"],
  ["nama" => "Adenovirus Tipe 5", "famili" => "Adenoviridae", "materi" => "DNA", "penyakit" => "Infeksi Saluran Napas"],
  ["nama" => "Adenovirus Tipe 7", "famili" => "Adenoviridae", "materi" => "DNA", "penyakit" => "Infeksi Saluran Napas"],
  ["nama" => "Adenovirus Tipe 14", "famili" => "Adenoviridae", "materi" => "DNA", "penyakit" => "Infeksi Saluran Napas"],
  ["nama" => "Adenovirus Tipe 40", "famili" => "Adenoviridae", "materi" => "DNA", "penyakit" => "Gastroenteritis"],
  ["nama" => "Adenovirus Tipe 41", "famili" => "Adenoviridae", "materi" => "DNA", "penyakit" => "Gastroenteritis"],

  // ===== Herpesviridae =====
  ["nama" => "Herpes Simplex Virus 1 (HSV-1)", "famili" => "Herpesviridae", "materi" => "DNA", "penyakit" => "Herpes Oral, Keratitis"],
  ["nama" => "Herpes Simplex Virus 2 (HSV-2)", "famili" => "Herpesviridae", "materi" => "DNA", "penyakit" => "Herpes Genital"],
  ["nama" => "Varicella Zoster Virus (VZV)", "famili" => "Herpesviridae", "materi" => "DNA", "penyakit" => "Cacar Air, Herpes Zoster"],
  ["nama" => "Epstein-Barr Virus (EBV)", "famili" => "Herpesviridae", "materi" => "DNA", "penyakit" => "Mononukleosis Infeksiosa, Limfoma Burkitt"],
  ["nama" => "Cytomegalovirus (CMV)", "famili" => "Herpesviridae", "materi" => "DNA", "penyakit" => "Sitomegalovirus, Retinitis"],
  ["nama" => "Human Herpesvirus 6 (HHV-6)", "famili" => "Herpesviridae", "materi" => "DNA", "penyakit" => "Roseola Infantum"],
  ["nama" => "Human Herpesvirus 7 (HHV-7)", "famili" => "Herpesviridae", "materi" => "DNA", "penyakit" => "Roseola Infantum"],
  ["nama" => "Human Herpesvirus 8 (HHV-8)", "famili" => "Herpesviridae", "materi" => "DNA", "penyakit" => "Sarkoma Kaposi"],
  ["nama" => "Herpesvirus Simiae (B Virus)", "famili" => "Herpesviridae", "materi" => "DNA", "penyakit" => "Ensefalitis"],
  ["nama" => "Herpesvirus Cercopithecine", "famili" => "Herpesviridae", "materi" => "DNA", "penyakit" => "Infeksi Herpes"],
  ["nama" => "Pseudorabies Virus", "famili" => "Herpesviridae", "materi" => "DNA", "penyakit" => "Penyakit Aujeszky"],
  ["nama" => "Equine Herpesvirus 1", "famili" => "Herpesviridae", "materi" => "DNA", "penyakit" => "Aborsi Kuda"],
  ["nama" => "Bovine Herpesvirus 1", "famili" => "Herpesviridae", "materi" => "DNA", "penyakit" => "Rhinotrakeitis Infeksiosa"],
  ["nama" => "Feline Herpesvirus 1", "famili" => "Herpesviridae", "materi" => "DNA", "penyakit" => "Rhinotrakeitis Kucing"],
  ["nama" => "Canine Herpesvirus 1", "famili" => "Herpesviridae", "materi" => "DNA", "penyakit" => "Infeksi Herpes Anjing"],

  // ===== Poxviridae =====
  ["nama" => "Variola Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Cacar (Smallpox)"],
  ["nama" => "Vaccinia Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Vaksin Cacar"],
  ["nama" => "Monkeypox Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Mpox (Cacar Monyet)"],
  ["nama" => "Cowpox Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Cacar Sapi"],
  ["nama" => "Buffalopox Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Cacar Kerbau"],
  ["nama" => "Camelpox Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Cacar Unta"],
  ["nama" => "Ectromelia Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Cacar Tikus"],
  ["nama" => "Myxoma Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Miksomatosis Kelinci"],
  ["nama" => "Molluscum Contagiosum Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Molluscum Contagiosum"],
  ["nama" => "Tanapox Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Tanapox"],
  ["nama" => "Yaba Monkey Tumor Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Tumor Monyet Yaba"],
  ["nama" => "Orf Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Ecthyma Contagiosum"],
  ["nama" => "Pseudocowpox Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Pseudocowpox"],
  ["nama" => "Bovine Papular Stomatitis Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Stomatitis Papular Sapi"],
  ["nama" => "Fowlpox Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Cacar Unggas"],
  ["nama" => "Sheeppox Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Cacar Domba"],
  ["nama" => "Goatpox Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Cacar Kambing"],
  ["nama" => "Lumpy Skin Disease Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Penyakit Kulit Nodular Sapi"],
  ["nama" => "Swinepox Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Cacar Babi"],
  ["nama" => "Myxomatosis Virus", "famili" => "Poxviridae", "materi" => "DNA", "penyakit" => "Miksomatosis"],

  // ===== Papillomaviridae =====
  ["nama" => "Human Papillomavirus (HPV) Tipe 6", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Kutil Genital"],
  ["nama" => "Human Papillomavirus (HPV) Tipe 11", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Kutil Genital"],
  ["nama" => "Human Papillomavirus (HPV) Tipe 16", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Kanker Serviks"],
  ["nama" => "Human Papillomavirus (HPV) Tipe 18", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Kanker Serviks"],
  ["nama" => "Human Papillomavirus (HPV) Tipe 31", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Kanker Serviks"],
  ["nama" => "Human Papillomavirus (HPV) Tipe 33", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Kanker Serviks"],
  ["nama" => "Human Papillomavirus (HPV) Tipe 35", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Kanker Serviks"],
  ["nama" => "Human Papillomavirus (HPV) Tipe 39", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Kanker Serviks"],
  ["nama" => "Human Papillomavirus (HPV) Tipe 45", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Kanker Serviks"],
  ["nama" => "Human Papillomavirus (HPV) Tipe 51", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Kanker Serviks"],
  ["nama" => "Human Papillomavirus (HPV) Tipe 52", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Kanker Serviks"],
  ["nama" => "Human Papillomavirus (HPV) Tipe 56", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Kanker Serviks"],
  ["nama" => "Human Papillomavirus (HPV) Tipe 58", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Kanker Serviks"],
  ["nama" => "Human Papillomavirus (HPV) Tipe 59", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Kanker Serviks"],
  ["nama" => "Bovine Papillomavirus", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Papillomatosis Sapi"],
  ["nama" => "Canine Papillomavirus", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Papillomatosis Anjing"],
  ["nama" => "Equine Papillomavirus", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Papillomatosis Kuda"],
  ["nama" => "Rabbit Papillomavirus", "famili" => "Papillomaviridae", "materi" => "DNA", "penyakit" => "Papillomatosis Kelinci"],

  // ===== Polyomaviridae =====
  ["nama" => "JC Polyomavirus", "famili" => "Polyomaviridae", "materi" => "DNA", "penyakit" => "Leukoensefalopati Multifokal Progresif"],
  ["nama" => "BK Polyomavirus", "famili" => "Polyomaviridae", "materi" => "DNA", "penyakit" => "Nefropati, Stenosis Ureter"],
  ["nama" => "Simian Virus 40 (SV40)", "famili" => "Polyomaviridae", "materi" => "DNA", "penyakit" => "Tumor"],
  ["nama" => "Merkel Cell Polyomavirus", "famili" => "Polyomaviridae", "materi" => "DNA", "penyakit" => "Karsinoma Sel Merkel"],
  ["nama" => "KI Polyomavirus", "famili" => "Polyomaviridae", "materi" => "DNA", "penyakit" => "Infeksi Pernapasan"],
  ["nama" => "WU Polyomavirus", "famili" => "Polyomaviridae", "materi" => "DNA", "penyakit" => "Infeksi Pernapasan"],
  ["nama" => "Murine Polyomavirus", "famili" => "Polyomaviridae", "materi" => "DNA", "penyakit" => "Tumor Tikus"],
  ["nama" => "Hamster Polyomavirus", "famili" => "Polyomaviridae", "materi" => "DNA", "penyakit" => "Tumor Hamster"],

  // ===== Hepadnaviridae =====
  ["nama" => "Hepatitis B Virus (HBV)", "famili" => "Hepadnaviridae", "materi" => "DNA", "penyakit" => "Hepatitis B"],
  ["nama" => "Hepatitis B Virus Genotipe A", "famili" => "Hepadnaviridae", "materi" => "DNA", "penyakit" => "Hepatitis B"],
  ["nama" => "Hepatitis B Virus Genotipe B", "famili" => "Hepadnaviridae", "materi" => "DNA", "penyakit" => "Hepatitis B"],
  ["nama" => "Hepatitis B Virus Genotipe C", "famili" => "Hepadnaviridae", "materi" => "DNA", "penyakit" => "Hepatitis B"],
  ["nama" => "Hepatitis B Virus Genotipe D", "famili" => "Hepadnaviridae", "materi" => "DNA", "penyakit" => "Hepatitis B"],
  ["nama" => "Hepatitis B Virus Genotipe E", "famili" => "Hepadnaviridae", "materi" => "DNA", "penyakit" => "Hepatitis B"],
  ["nama" => "Hepatitis B Virus Genotipe F", "famili" => "Hepadnaviridae", "materi" => "DNA", "penyakit" => "Hepatitis B"],
  ["nama" => "Hepatitis B Virus Genotipe G", "famili" => "Hepadnaviridae", "materi" => "DNA", "penyakit" => "Hepatitis B"],
  ["nama" => "Hepatitis B Virus Genotipe H", "famili" => "Hepadnaviridae", "materi" => "DNA", "penyakit" => "Hepatitis B"],
  ["nama" => "Hepatitis B Virus Genotipe I", "famili" => "Hepadnaviridae", "materi" => "DNA", "penyakit" => "Hepatitis B"],
  ["nama" => "Hepatitis B Virus Genotipe J", "famili" => "Hepadnaviridae", "materi" => "DNA", "penyakit" => "Hepatitis B"],
  ["nama" => "Duck Hepatitis B Virus", "famili" => "Hepadnaviridae", "materi" => "DNA", "penyakit" => "Hepatitis B Bebek"],
  ["nama" => "Woodchuck Hepatitis Virus", "famili" => "Hepadnaviridae", "materi" => "DNA", "penyakit" => "Hepatitis B Marmot"],
  ["nama" => "Ground Squirrel Hepatitis Virus", "famili" => "Hepadnaviridae", "materi" => "DNA", "penyakit" => "Hepatitis B Tupai"],

  // ===== Parvoviridae =====
  ["nama" => "Parvovirus B19", "famili" => "Parvoviridae", "materi" => "DNA", "penyakit" => "Erythema Infectiosum (Fifth Disease)"],
  ["nama" => "Canine Parvovirus", "famili" => "Parvoviridae", "materi" => "DNA", "penyakit" => "Parvovirus Anjing"],
  ["nama" => "Feline Panleukopenia Virus", "famili" => "Parvoviridae", "materi" => "DNA", "penyakit" => "Panleukopenia Kucing"],
  ["nama" => "Porcine Parvovirus", "famili" => "Parvoviridae", "materi" => "DNA", "penyakit" => "Parvovirus Babi"],
  ["nama" => "Bovine Parvovirus", "famili" => "Parvoviridae", "materi" => "DNA", "penyakit" => "Parvovirus Sapi"],
  ["nama" => "Adeno-associated Virus (AAV)", "famili" => "Parvoviridae", "materi" => "DNA", "penyakit" => "Tidak Menyebabkan Penyakit"],
  ["nama" => "Human Bocavirus", "famili" => "Parvoviridae", "materi" => "DNA", "penyakit" => "Infeksi Saluran Napas"],
  ["nama" => "Mink Enteritis Virus", "famili" => "Parvoviridae", "materi" => "DNA", "penyakit" => "Enteritis Mink"],

  // ==================== VIRUS RNA ====================
  // ===== Coronaviridae =====
  ["nama" => "SARS-CoV", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "SARS"],
  ["nama" => "MERS-CoV", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "MERS"],
  ["nama" => "SARS-CoV-2", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "COVID-19"],
  ["nama" => "SARS-CoV-2 Varian Alpha", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "COVID-19"],
  ["nama" => "SARS-CoV-2 Varian Beta", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "COVID-19"],
  ["nama" => "SARS-CoV-2 Varian Gamma", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "COVID-19"],
  ["nama" => "SARS-CoV-2 Varian Delta", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "COVID-19"],
  ["nama" => "SARS-CoV-2 Varian Omicron", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "COVID-19"],
  ["nama" => "Human Coronavirus 229E", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "Flu Biasa"],
  ["nama" => "Human Coronavirus OC43", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "Flu Biasa"],
  ["nama" => "Human Coronavirus NL63", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "Flu Biasa"],
  ["nama" => "Human Coronavirus HKU1", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "Flu Biasa"],
  ["nama" => "Feline Coronavirus", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "Peritonitis Infeksiosa Kucing"],
  ["nama" => "Canine Coronavirus", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "Enteritis Anjing"],
  ["nama" => "Bovine Coronavirus", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "Enteritis Sapi"],
  ["nama" => "Porcine Epidemic Diarrhea Virus", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "Diare Epidemi Babi"],
  ["nama" => "Transmissible Gastroenteritis Virus", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "Gastroenteritis Babi"],
  ["nama" => "Avian Infectious Bronchitis Virus", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "Bronkitis Infeksiosa Unggas"],
  ["nama" => "Mouse Hepatitis Virus", "famili" => "Coronaviridae", "materi" => "RNA", "penyakit" => "Hepatitis Tikus"],

  // ===== Orthomyxoviridae =====
  ["nama" => "Influenza A Virus", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu"],
  ["nama" => "Influenza A H1N1", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu Babi"],
  ["nama" => "Influenza A H1N1 (1918)", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu Spanyol"],
  ["nama" => "Influenza A H2N2", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu Asia"],
  ["nama" => "Influenza A H3N2", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu Hong Kong"],
  ["nama" => "Influenza A H5N1", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu Burung"],
  ["nama" => "Influenza A H5N2", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu Burung"],
  ["nama" => "Influenza A H5N6", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu Burung"],
  ["nama" => "Influenza A H5N8", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu Burung"],
  ["nama" => "Influenza A H7N1", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu Burung"],
  ["nama" => "Influenza A H7N2", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu Burung"],
  ["nama" => "Influenza A H7N3", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu Burung"],
  ["nama" => "Influenza A H7N7", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu Burung"],
  ["nama" => "Influenza A H7N9", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu Burung"],
  ["nama" => "Influenza A H9N2", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu Burung"],
  ["nama" => "Influenza A H10N8", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu Burung"],
  ["nama" => "Influenza B Virus", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu"],
  ["nama" => "Influenza B/Yamagata", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu"],
  ["nama" => "Influenza B/Victoria", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu"],
  ["nama" => "Influenza C Virus", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Flu Ringan"],
  ["nama" => "Influenza D Virus", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Infeksi Sapi"],
  ["nama" => "Thogoto Virus", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Demam Tick-Borne"],
  ["nama" => "Dhori Virus", "famili" => "Orthomyxoviridae", "materi" => "RNA", "penyakit" => "Demam Tick-Borne"],

  // ===== Paramyxoviridae =====
  ["nama" => "Measles Virus (Rubeola)", "famili" => "Paramyxoviridae", "materi" => "RNA", "penyakit" => "Campak"],
  ["nama" => "Mumps Virus", "famili" => "Paramyxoviridae", "materi" => "RNA", "penyakit" => "Gondongan"],
  ["nama" => "Rubella Virus", "famili" => "Matonaviridae", "materi" => "RNA", "penyakit" => "Rubella (Campak Jerman)"],
  ["nama" => "Parainfluenza Virus 1", "famili" => "Paramyxoviridae", "materi" => "RNA", "penyakit" => "Croup"],
  ["nama" => "Parainfluenza Virus 2", "famili" => "Paramyxoviridae", "materi" => "RNA", "penyakit" => "Infeksi Saluran Napas"],
  ["nama" => "Parainfluenza Virus 3", "famili" => "Paramyxoviridae", "materi" => "RNA", "penyakit" => "Bronkiolitis"],
  ["nama" => "Parainfluenza Virus 4", "famili" => "Paramyxoviridae", "materi" => "RNA", "penyakit" => "Infeksi Saluran Napas"],
  ["nama" => "Respiratory Syncytial Virus (RSV)", "famili" => "Pneumoviridae", "materi" => "RNA", "penyakit" => "Bronkiolitis, Pneumonia"],
  ["nama" => "Human Metapneumovirus (hMPV)", "famili" => "Pneumoviridae", "materi" => "RNA", "penyakit" => "Infeksi Saluran Napas"],
  ["nama" => "Nipah Virus", "famili" => "Paramyxoviridae", "materi" => "RNA", "penyakit" => "Ensefalitis Nipah"],
  ["nama" => "Hendra Virus", "famili" => "Paramyxoviridae", "materi" => "RNA", "penyakit" => "Infeksi Hendra"],
  ["nama" => "Newcastle Disease Virus", "famili" => "Paramyxoviridae", "materi" => "RNA", "penyakit" => "Penyakit Newcastle Unggas"],
  ["nama" => "Canine Distemper Virus", "famili" => "Paramyxoviridae", "materi" => "RNA", "penyakit" => "Distemper Anjing"],
  ["nama" => "Rinderpest Virus", "famili" => "Paramyxoviridae", "materi" => "RNA", "penyakit" => "Rinderpest"],
  ["nama" => "Peste-des-Petits-Ruminants Virus", "famili" => "Paramyxoviridae", "materi" => "RNA", "penyakit" => "PPR"],
  ["nama" => "Sendai Virus", "famili" => "Paramyxoviridae", "materi" => "RNA", "penyakit" => "Infeksi Tikus"],
  ["nama" => "Simian Virus 5", "famili" => "Paramyxoviridae", "materi" => "RNA", "penyakit" => "Infeksi Monyet"],
  ["nama" => "Simian Virus 41", "famili" => "Paramyxoviridae", "materi" => "RNA", "penyakit" => "Infeksi Monyet"],

  // ===== Rhabdoviridae =====
  ["nama" => "Rabies Virus", "famili" => "Rhabdoviridae", "materi" => "RNA", "penyakit" => "Rabies"],
  ["nama" => "Vesicular Stomatitis Virus", "famili" => "Rhabdoviridae", "materi" => "RNA", "penyakit" => "Stomatitis Vesikular"],
  ["nama" => "Chandipura Virus", "famili" => "Rhabdoviridae", "materi" => "RNA", "penyakit" => "Ensefalitis"],
  ["nama" => "Lyssavirus Australia", "famili" => "Rhabdoviridae", "materi" => "RNA", "penyakit" => "Rabies"],
  ["nama" => "Lagos Bat Virus", "famili" => "Rhabdoviridae", "materi" => "RNA", "penyakit" => "Rabies"],
  ["nama" => "Mokola Virus", "famili" => "Rhabdoviridae", "materi" => "RNA", "penyakit" => "Rabies"],
  ["nama" => "Duvenhage Virus", "famili" => "Rhabdoviridae", "materi" => "RNA", "penyakit" => "Rabies"],
  ["nama" => "European Bat Lyssavirus 1", "famili" => "Rhabdoviridae", "materi" => "RNA", "penyakit" => "Rabies"],
  ["nama" => "European Bat Lyssavirus 2", "famili" => "Rhabdoviridae", "materi" => "RNA", "penyakit" => "Rabies"],
  ["nama" => "Bovine Ephemeral Fever Virus", "famili" => "Rhabdoviridae", "materi" => "RNA", "penyakit" => "Demam Ephemeral Sapi"],
  ["nama" => "Infectious Hematopoietic Necrosis Virus", "famili" => "Rhabdoviridae", "materi" => "RNA", "penyakit" => "Nekrosis Hematopoietik Ikan"],
  ["nama" => "Viral Hemorrhagic Septicemia Virus", "famili" => "Rhabdoviridae", "materi" => "RNA", "penyakit" => "Septicemia Hemoragik Ikan"],
  ["nama" => "Snakehead Rhabdovirus", "famili" => "Rhabdoviridae", "materi" => "RNA", "penyakit" => "Infeksi Ikan Gabus"],

  // ===== Filoviridae =====
  ["nama" => "Ebola Virus", "famili" => "Filoviridae", "materi" => "RNA", "penyakit" => "Ebola"],
  ["nama" => "Ebola Virus Zaire", "famili" => "Filoviridae", "materi" => "RNA", "penyakit" => "Ebola"],
  ["nama" => "Ebola Virus Sudan", "famili" => "Filoviridae", "materi" => "RNA", "penyakit" => "Ebola"],
  ["nama" => "Ebola Virus Bundibugyo", "famili" => "Filoviridae", "materi" => "RNA", "penyakit" => "Ebola"],
  ["nama" => "Ebola Virus Tai Forest", "famili" => "Filoviridae", "materi" => "RNA", "penyakit" => "Ebola"],
  ["nama" => "Ebola Virus Reston", "famili" => "Filoviridae", "materi" => "RNA", "penyakit" => "Ebola"],
  ["nama" => "Marburg Virus", "famili" => "Filoviridae", "materi" => "RNA", "penyakit" => "Marburg"],
  ["nama" => "Lloviu Virus", "famili" => "Filoviridae", "materi" => "RNA", "penyakit" => "Infeksi Kelelawar"],

  // ===== Flaviviridae =====
  ["nama" => "Dengue Virus Tipe 1", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Demam Berdarah Dengue"],
  ["nama" => "Dengue Virus Tipe 2", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Demam Berdarah Dengue"],
  ["nama" => "Dengue Virus Tipe 3", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Demam Berdarah Dengue"],
  ["nama" => "Dengue Virus Tipe 4", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Demam Berdarah Dengue"],
  ["nama" => "Zika Virus", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Zika"],
  ["nama" => "Yellow Fever Virus", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Demam Kuning"],
  ["nama" => "West Nile Virus", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Demam West Nile"],
  ["nama" => "Japanese Encephalitis Virus", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Ensefalitis Jepang"],
  ["nama" => "St. Louis Encephalitis Virus", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Ensefalitis St. Louis"],
  ["nama" => "Murray Valley Encephalitis Virus", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Ensefalitis Murray Valley"],
  ["nama" => "Tick-Borne Encephalitis Virus", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Ensefalitis Tick-Borne"],
  ["nama" => "Kyasanur Forest Disease Virus", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Penyakit Kyasanur"],
  ["nama" => "Omsk Hemorrhagic Fever Virus", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Demam Hemoragik Omsk"],
  ["nama" => "Powassan Virus", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Ensefalitis Powassan"],
  ["nama" => "Hepatitis C Virus (HCV)", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Hepatitis C"],
  ["nama" => "Hepatitis C Virus Genotipe 1", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Hepatitis C"],
  ["nama" => "Hepatitis C Virus Genotipe 2", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Hepatitis C"],
  ["nama" => "Hepatitis C Virus Genotipe 3", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Hepatitis C"],
  ["nama" => "Hepatitis C Virus Genotipe 4", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Hepatitis C"],
  ["nama" => "Hepatitis C Virus Genotipe 5", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Hepatitis C"],
  ["nama" => "Hepatitis C Virus Genotipe 6", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Hepatitis C"],
  ["nama" => "Hepatitis C Virus Genotipe 7", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Hepatitis C"],
  ["nama" => "Hepatitis G Virus (GBV-C)", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Hepatitis G"],
  ["nama" => "Bovine Viral Diarrhea Virus", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Diare Viral Sapi"],
  ["nama" => "Classical Swine Fever Virus", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Demam Babi Klasik"],
  ["nama" => "Border Disease Virus", "famili" => "Flaviviridae", "materi" => "RNA", "penyakit" => "Border Disease Domba"],

  // ===== Togaviridae =====
  ["nama" => "Chikungunya Virus", "famili" => "Togaviridae", "materi" => "RNA", "penyakit" => "Chikungunya"],
  ["nama" => "Eastern Equine Encephalitis Virus", "famili" => "Togaviridae", "materi" => "RNA", "penyakit" => "Ensefalitis Kuda Timur"],
  ["nama" => "Western Equine Encephalitis Virus", "famili" => "Togaviridae", "materi" => "RNA", "penyakit" => "Ensefalitis Kuda Barat"],
  ["nama" => "Venezuelan Equine Encephalitis Virus", "famili" => "Togaviridae", "materi" => "RNA", "penyakit" => "Ensefalitis Kuda Venezuela"],
  ["nama" => "Sindbis Virus", "famili" => "Togaviridae", "materi" => "RNA", "penyakit" => "Demam Sindbis"],
  ["nama" => "Semliki Forest Virus", "famili" => "Togaviridae", "materi" => "RNA", "penyakit" => "Ensefalitis"],
  ["nama" => "O'nyong-nyong Virus", "famili" => "Togaviridae", "materi" => "RNA", "penyakit" => "Demam O'nyong-nyong"],
  ["nama" => "Ross River Virus", "famili" => "Togaviridae", "materi" => "RNA", "penyakit" => "Demam Ross River"],
  ["nama" => "Barmah Forest Virus", "famili" => "Togaviridae", "materi" => "RNA", "penyakit" => "Demam Barmah Forest"],
  ["nama" => "Mayaro Virus", "famili" => "Togaviridae", "materi" => "RNA", "penyakit" => "Demam Mayaro"],
  ["nama" => "Rubella Virus", "famili" => "Matonaviridae", "materi" => "RNA", "penyakit" => "Rubella"],

  // ===== Arenaviridae =====
  ["nama" => "Lassa Virus", "famili" => "Arenaviridae", "materi" => "RNA", "penyakit" => "Demam Lassa"],
  ["nama" => "Junin Virus", "famili" => "Arenaviridae", "materi" => "RNA", "penyakit" => "Demam Hemoragik Argentina"],
  ["nama" => "Machupo Virus", "famili" => "Arenaviridae", "materi" => "RNA", "penyakit" => "Demam Hemoragik Bolivia"],
  ["nama" => "Guanarito Virus", "famili" => "Arenaviridae", "materi" => "RNA", "penyakit" => "Demam Hemoragik Venezuela"],
  ["nama" => "Sabiá Virus", "famili" => "Arenaviridae", "materi" => "RNA", "penyakit" => "Demam Hemoragik Brasil"],
  ["nama" => "Chapare Virus", "famili" => "Arenaviridae", "materi" => "RNA", "penyakit" => "Demam Hemoragik Chapare"],
  ["nama" => "Lujo Virus", "famili" => "Arenaviridae", "materi" => "RNA", "penyakit" => "Demam Hemoragik Lujo"],
  ["nama" => "Lymphocytic Choriomeningitis Virus", "famili" => "Arenaviridae", "materi" => "RNA", "penyakit" => "Koriomeningitis Limfositik"],
  ["nama" => "Whitewater Arroyo Virus", "famili" => "Arenaviridae", "materi" => "RNA", "penyakit" => "Demam Hemoragik"],
  ["nama" => "Bear Canyon Virus", "famili" => "Arenaviridae", "materi" => "RNA", "penyakit" => "Infeksi Arenavirus"],
  ["nama" => "Tamiami Virus", "famili" => "Arenaviridae", "materi" => "RNA", "penyakit" => "Infeksi Arenavirus"],

  // ===== Bunyaviridae =====
  ["nama" => "Hantavirus", "famili" => "Hantaviridae", "materi" => "RNA", "penyakit" => "Hantavirus Pulmonary Syndrome"],
  ["nama" => "Sin Nombre Virus", "famili" => "Hantaviridae", "materi" => "RNA", "penyakit" => "Hantavirus Pulmonary Syndrome"],
  ["nama" => "Andes Virus", "famili" => "Hantaviridae", "materi" => "RNA", "penyakit" => "Hantavirus Pulmonary Syndrome"],
  ["nama" => "Puumala Virus", "famili" => "Hantaviridae", "materi" => "RNA", "penyakit" => "Nephropathia Epidemica"],
  ["nama" => "Hantaan Virus", "famili" => "Hantaviridae", "materi" => "RNA", "penyakit" => "Demam Hemoragik dengan Sindrom Renal"],
  ["nama" => "Seoul Virus", "famili" => "Hantaviridae", "materi" => "RNA", "penyakit" => "Demam Hemoragik dengan Sindrom Renal"],
  ["nama" => "Dobrava-Belgrade Virus", "famili" => "Hantaviridae", "materi" => "RNA", "penyakit" => "Demam Hemoragik dengan Sindrom Renal"],
  ["nama" => "Rift Valley Fever Virus", "famili" => "Phenuiviridae", "materi" => "RNA", "penyakit" => "Demam Rift Valley"],
  ["nama" => "Crimean-Congo Hemorrhagic Fever Virus", "famili" => "Nairoviridae", "materi" => "RNA", "penyakit" => "Demam Hemoragik Krimea-Kongo"],
  ["nama" => "Dugbe Virus", "famili" => "Nairoviridae", "materi" => "RNA", "penyakit" => "Demam Dugbe"],
  ["nama" => "Nairobi Sheep Disease Virus", "famili" => "Nairoviridae", "materi" => "RNA", "penyakit" => "Penyakit Domba Nairobi"],
  ["nama" => "La Crosse Virus", "famili" => "Peribunyaviridae", "materi" => "RNA", "penyakit" => "Ensefalitis La Crosse"],
  ["nama" => "California Encephalitis Virus", "famili" => "Peribunyaviridae", "materi" => "RNA", "penyakit" => "Ensefalitis California"],
  ["nama" => "Oropouche Virus", "famili" => "Peribunyaviridae", "materi" => "RNA", "penyakit" => "Demam Oropouche"],
  ["nama" => "Bunyavirus Bunyamwera", "famili" => "Peribunyaviridae", "materi" => "RNA", "penyakit" => "Demam Bunyamwera"],
  ["nama" => "Schmallenberg Virus", "famili" => "Peribunyaviridae", "materi" => "RNA", "penyakit" => "Schmallenberg"],
  ["nama" => "Akabane Virus", "famili" => "Peribunyaviridae", "materi" => "RNA", "penyakit" => "Akabane"],
  ["nama" => "Toscana Virus", "famili" => "Phenuiviridae", "materi" => "RNA", "penyakit" => "Meningitis Toscana"],
  ["nama" => "Severe Fever with Thrombocytopenia Syndrome Virus", "famili" => "Phenuiviridae", "materi" => "RNA", "penyakit" => "SFTS"],
  ["nama" => "Heartland Virus", "famili" => "Phenuiviridae", "materi" => "RNA", "penyakit" => "Infeksi Heartland"],

  // ===== Reoviridae =====
  ["nama" => "Rotavirus", "famili" => "Reoviridae", "materi" => "RNA", "penyakit" => "Diare Rotavirus"],
  ["nama" => "Rotavirus Grup A", "famili" => "Reoviridae", "materi" => "RNA", "penyakit" => "Diare Anak"],
  ["nama" => "Rotavirus Grup B", "famili" => "Reoviridae", "materi" => "RNA", "penyakit" => "Diare Dewasa"],
  ["nama" => "Rotavirus Grup C", "famili" => "Reoviridae", "materi" => "RNA", "penyakit" => "Diare"],
  ["nama" => "Reovirus", "famili" => "Reoviridae", "materi" => "RNA", "penyakit" => "Infeksi Saluran Napas"],
  ["nama" => "Orbivirus", "famili" => "Reoviridae", "materi" => "RNA", "penyakit" => "Demam Orbivirus"],
  ["nama" => "Bluetongue Virus", "famili" => "Reoviridae", "materi" => "RNA", "penyakit" => "Bluetongue"],
  ["nama" => "African Horse Sickness Virus", "famili" => "Reoviridae", "materi" => "RNA", "penyakit" => "Penyakit Kuda Afrika"],
  ["nama" => "Colorado Tick Fever Virus", "famili" => "Reoviridae", "materi" => "RNA", "penyakit" => "Demam Tick Colorado"],
  ["nama" => "Kemerovo Virus", "famili" => "Reoviridae", "materi" => "RNA", "penyakit" => "Demam Kemerovo"],
  ["nama" => "Banna Virus", "famili" => "Reoviridae", "materi" => "RNA", "penyakit" => "Ensefalitis Banna"],

  // ===== Picornaviridae =====
  ["nama" => "Poliovirus Tipe 1", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Polio"],
  ["nama" => "Poliovirus Tipe 2", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Polio"],
  ["nama" => "Poliovirus Tipe 3", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Polio"],
  ["nama" => "Coxsackievirus A", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Herpangina, Penyakit Tangan-Kaki-Mulut"],
  ["nama" => "Coxsackievirus B", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Miokarditis, Pleurodinia"],
  ["nama" => "Echovirus", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Meningitis Aseptik"],
  ["nama" => "Enterovirus 68", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Infeksi Saluran Napas"],
  ["nama" => "Enterovirus 70", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Konjungtivitis Hemoragik Akut"],
  ["nama" => "Enterovirus 71", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Penyakit Tangan-Kaki-Mulut, Ensefalitis"],
  ["nama" => "Enterovirus D68", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Infeksi Saluran Napas"],
  ["nama" => "Rhinovirus A", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Flu Biasa"],
  ["nama" => "Rhinovirus B", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Flu Biasa"],
  ["nama" => "Rhinovirus C", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Flu Biasa"],
  ["nama" => "Hepatitis A Virus (HAV)", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Hepatitis A"],
  ["nama" => "Foot-and-Mouth Disease Virus", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Penyakit Mulut dan Kuku"],
  ["nama" => "Encephalomyocarditis Virus", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Ensefalomiokarditis"],
  ["nama" => "Theiler's Murine Encephalomyelitis Virus", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Ensefalomielitis Tikus"],
  ["nama" => "Avian Encephalomyelitis Virus", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Ensefalomielitis Unggas"],
  ["nama" => "Duck Hepatitis Virus", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Hepatitis Bebek"],
  ["nama" => "Equine Rhinitis A Virus", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Rinitis Kuda"],
  ["nama" => "Equine Rhinitis B Virus", "famili" => "Picornaviridae", "materi" => "RNA", "penyakit" => "Rinitis Kuda"],

  // ===== Caliciviridae =====
  ["nama" => "Norovirus", "famili" => "Caliciviridae", "materi" => "RNA", "penyakit" => "Gastroenteritis Norovirus"],
  ["nama" => "Norovirus Genogrup I", "famili" => "Caliciviridae", "materi" => "RNA", "penyakit" => "Gastroenteritis"],
  ["nama" => "Norovirus Genogrup II", "famili" => "Caliciviridae", "materi" => "RNA", "penyakit" => "Gastroenteritis"],
  ["nama" => "Norovirus Genogrup III", "famili" => "Caliciviridae", "materi" => "RNA", "penyakit" => "Gastroenteritis Hewan"],
  ["nama" => "Norovirus Genogrup IV", "famili" => "Caliciviridae", "materi" => "RNA", "penyakit" => "Gastroenteritis"],
  ["nama" => "Sapporo Virus", "famili" => "Caliciviridae", "materi" => "RNA", "penyakit" => "Gastroenteritis"],
  ["nama" => "Feline Calicivirus", "famili" => "Caliciviridae", "materi" => "RNA", "penyakit" => "Infeksi Saluran Napas Kucing"],
  ["nama" => "Vesicular Exanthema of Swine Virus", "famili" => "Caliciviridae", "materi" => "RNA", "penyakit" => "Eksantema Vesikular Babi"],
  ["nama" => "Rabbit Hemorrhagic Disease Virus", "famili" => "Caliciviridae", "materi" => "RNA", "penyakit" => "Penyakit Hemoragik Kelinci"],
  ["nama" => "Tulane Virus", "famili" => "Caliciviridae", "materi" => "RNA", "penyakit" => "Gastroenteritis"],

  // ===== Astroviridae =====
  ["nama" => "Human Astrovirus", "famili" => "Astroviridae", "materi" => "RNA", "penyakit" => "Gastroenteritis"],
  ["nama" => "Astrovirus Tipe 1", "famili" => "Astroviridae", "materi" => "RNA", "penyakit" => "Diare"],
  ["nama" => "Astrovirus Tipe 2", "famili" => "Astroviridae", "materi" => "RNA", "penyakit" => "Diare"],
  ["nama" => "Astrovirus Tipe 3", "famili" => "Astroviridae", "materi" => "RNA", "penyakit" => "Diare"],
  ["nama" => "Astrovirus Tipe 4", "famili" => "Astroviridae", "materi" => "RNA", "penyakit" => "Diare"],
  ["nama" => "Astrovirus Tipe 5", "famili" => "Astroviridae", "materi" => "RNA", "penyakit" => "Diare"],
  ["nama" => "Astrovirus Tipe 6", "famili" => "Astroviridae", "materi" => "RNA", "penyakit" => "Diare"],
  ["nama" => "Astrovirus Tipe 7", "famili" => "Astroviridae", "materi" => "RNA", "penyakit" => "Diare"],
  ["nama" => "Astrovirus Tipe 8", "famili" => "Astroviridae", "materi" => "RNA", "penyakit" => "Diare"],
  ["nama" => "Avian Astrovirus", "famili" => "Astroviridae", "materi" => "RNA", "penyakit" => "Enteritis Unggas"],
  ["nama" => "Porcine Astrovirus", "famili" => "Astroviridae", "materi" => "RNA", "penyakit" => "Diare Babi"],

  // ===== Retroviridae =====
  ["nama" => "Human Immunodeficiency Virus 1 (HIV-1)", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "AIDS"],
  ["nama" => "Human Immunodeficiency Virus 2 (HIV-2)", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "AIDS"],
  ["nama" => "Human T-Lymphotropic Virus 1 (HTLV-1)", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Leukemia Sel T Dewasa"],
  ["nama" => "Human T-Lymphotropic Virus 2 (HTLV-2)", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Leukemia"],
  ["nama" => "Human T-Lymphotropic Virus 3 (HTLV-3)", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Infeksi HTLV"],
  ["nama" => "Human T-Lymphotropic Virus 4 (HTLV-4)", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Infeksi HTLV"],
  ["nama" => "Simian Immunodeficiency Virus (SIV)", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "AIDS Monyet"],
  ["nama" => "Feline Immunodeficiency Virus (FIV)", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "AIDS Kucing"],
  ["nama" => "Feline Leukemia Virus (FeLV)", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Leukemia Kucing"],
  ["nama" => "Bovine Immunodeficiency Virus", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Imunodefisiensi Sapi"],
  ["nama" => "Bovine Leukemia Virus", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Leukemia Sapi"],
  ["nama" => "Equine Infectious Anemia Virus", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Anemia Infeksiosa Kuda"],
  ["nama" => "Caprine Arthritis Encephalitis Virus", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Artritis-Ensefalitis Kambing"],
  ["nama" => "Maedi-Visna Virus", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Maedi-Visna Domba"],
  ["nama" => "Jaagsiekte Sheep Retrovirus", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Adenomatosis Paru Domba"],
  ["nama" => "Avian Leukosis Virus", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Leukosis Unggas"],
  ["nama" => "Rous Sarcoma Virus", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Sarkoma Rous"],
  ["nama" => "Murine Leukemia Virus", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Leukemia Tikus"],
  ["nama" => "Mouse Mammary Tumor Virus", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Tumor Payudara Tikus"],
  ["nama" => "Woolly Monkey Sarcoma Virus", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Sarkoma Monyet"],
  ["nama" => "Gibbon Ape Leukemia Virus", "famili" => "Retroviridae", "materi" => "RNA", "penyakit" => "Leukemia Gibbon"],

  // ===== Orthohepeviridae =====
  ["nama" => "Hepatitis E Virus (HEV)", "famili" => "Hepeviridae", "materi" => "RNA", "penyakit" => "Hepatitis E"],
  ["nama" => "Hepatitis E Virus Genotipe 1", "famili" => "Hepeviridae", "materi" => "RNA", "penyakit" => "Hepatitis E"],
  ["nama" => "Hepatitis E Virus Genotipe 2", "famili" => "Hepeviridae", "materi" => "RNA", "penyakit" => "Hepatitis E"],
  ["nama" => "Hepatitis E Virus Genotipe 3", "famili" => "Hepeviridae", "materi" => "RNA", "penyakit" => "Hepatitis E"],
  ["nama" => "Hepatitis E Virus Genotipe 4", "famili" => "Hepeviridae", "materi" => "RNA", "penyakit" => "Hepatitis E"],
  ["nama" => "Hepatitis E Virus Genotipe 5", "famili" => "Hepeviridae", "materi" => "RNA", "penyakit" => "Hepatitis E"],
  ["nama" => "Hepatitis E Virus Genotipe 6", "famili" => "Hepeviridae", "materi" => "RNA", "penyakit" => "Hepatitis E"],
  ["nama" => "Hepatitis E Virus Genotipe 7", "famili" => "Hepeviridae", "materi" => "RNA", "penyakit" => "Hepatitis E"],
  ["nama" => "Avian Hepatitis E Virus", "famili" => "Hepeviridae", "materi" => "RNA", "penyakit" => "Hepatitis Unggas"],

  // ===== Deltavirus =====
  ["nama" => "Hepatitis D Virus (HDV)", "famili" => "Kolmioviridae", "materi" => "RNA", "penyakit" => "Hepatitis D"],

  // ===== Bornaviridae =====
  ["nama" => "Borna Disease Virus", "famili" => "Bornaviridae", "materi" => "RNA", "penyakit" => "Penyakit Borna"],
  ["nama" => "Avian Bornavirus", "famili" => "Bornaviridae", "materi" => "RNA", "penyakit" => "Proventricular Dilatation Disease"],
  ["nama" => "Variegated Squirrel Bornavirus 1", "famili" => "Bornaviridae", "materi" => "RNA", "penyakit" => "Ensefalitis"],

  // ===== Arteriviridae =====
  ["nama" => "Equine Arteritis Virus", "famili" => "Arteriviridae", "materi" => "RNA", "penyakit" => "Arteritis Kuda"],
  ["nama" => "Porcine Reproductive and Respiratory Syndrome Virus", "famili" => "Arteriviridae", "materi" => "RNA", "penyakit" => "PRRS"],
  ["nama" => "Simian Hemorrhagic Fever Virus", "famili" => "Arteriviridae", "materi" => "RNA", "penyakit" => "Demam Hemoragik Monyet"],
  ["nama" => "Lactate Dehydrogenase Elevating Virus", "famili" => "Arteriviridae", "materi" => "RNA", "penyakit" => "Elevasi LDH Tikus"],

  // ===== Togaviridae (lanjutan) =====
  ["nama" => "Aura Virus", "famili" => "Togaviridae", "materi" => "RNA", "penyakit" => "Demam Aura"],
  ["nama" => "Una Virus", "famili" => "Togaviridae", "materi" => "RNA", "penyakit" => "Demam Una"],
  ["nama" => "Pixuna Virus", "famili" => "Togaviridae", "materi" => "RNA", "penyakit" => "Demam Pixuna"],
  ["nama" => "Highlands J Virus", "famili" => "Togaviridae", "materi" => "RNA", "penyakit" => "Ensefalitis"],

  // ==================== VIRUS DNA/RNA (Unclassified & Lainnya) ====================
  // ===== Anelloviridae =====
  ["nama" => "Torque Teno Virus (TTV)", "famili" => "Anelloviridae", "materi" => "DNA", "penyakit" => "Tidak Menyebabkan Penyakit"],
  ["nama" => "Torque Teno Mini Virus", "famili" => "Anelloviridae", "materi" => "DNA", "penyakit" => "Tidak Menyebabkan Penyakit"],
  ["nama" => "Torque Teno Midi Virus", "famili" => "Anelloviridae", "materi" => "DNA", "penyakit" => "Tidak Menyebabkan Penyakit"],

  // ===== Circoviridae =====
  ["nama" => "Porcine Circovirus 1", "famili" => "Circoviridae", "materi" => "DNA", "penyakit" => "Infeksi Babi"],
  ["nama" => "Porcine Circovirus 2", "famili" => "Circoviridae", "materi" => "DNA", "penyakit" => "Postweaning Multisystemic Wasting Syndrome"],
  ["nama" => "Porcine Circovirus 3", "famili" => "Circoviridae", "materi" => "DNA", "penyakit" => "Infeksi Babi"],
  ["nama" => "Beak and Feather Disease Virus", "famili" => "Circoviridae", "materi" => "DNA", "penyakit" => "Penyakit Paruh dan Bulu Burung"],
  ["nama" => "Chicken Anemia Virus", "famili" => "Circoviridae", "materi" => "DNA", "penyakit" => "Anemia Unggas"],
  ["nama" => "Canine Circovirus", "famili" => "Circoviridae", "materi" => "DNA", "penyakit" => "Infeksi Anjing"],

  // ===== Geminiviridae =====
  ["nama" => "Maize Streak Virus", "famili" => "Geminiviridae", "materi" => "DNA", "penyakit" => "Penyakit Jagung"],
  ["nama" => "Tomato Yellow Leaf Curl Virus", "famili" => "Geminiviridae", "materi" => "DNA", "penyakit" => "Penyakit Tomat"],
  ["nama" => "Cassava Mosaic Virus", "famili" => "Geminiviridae", "materi" => "DNA", "penyakit" => "Penyakit Singkong"],
  ["nama" => "Bean Golden Mosaic Virus", "famili" => "Geminiviridae", "materi" => "DNA", "penyakit" => "Penyakit Kacang"],

  // ===== Caulimoviridae =====
  ["nama" => "Cauliflower Mosaic Virus", "famili" => "Caulimoviridae", "materi" => "DNA", "penyakit" => "Penyakit Kubis Bunga"],
  ["nama" => "Rice Tungro Bacilliform Virus", "famili" => "Caulimoviridae", "materi" => "DNA", "penyakit" => "Penyakit Padi"],

  // ===== Virgaviridae =====
  ["nama" => "Tobacco Mosaic Virus", "famili" => "Virgaviridae", "materi" => "RNA", "penyakit" => "Penyakit Tembakau"],
  ["nama" => "Tomato Mosaic Virus", "famili" => "Virgaviridae", "materi" => "RNA", "penyakit" => "Penyakit Tomat"],
  ["nama" => "Cucumber Green Mottle Mosaic Virus", "famili" => "Virgaviridae", "materi" => "RNA", "penyakit" => "Penyakit Timun"],

  // ===== Bromoviridae =====
  ["nama" => "Cucumber Mosaic Virus", "famili" => "Bromoviridae", "materi" => "RNA", "penyakit" => "Penyakit Timun"],
  ["nama" => "Brome Mosaic Virus", "famili" => "Bromoviridae", "materi" => "RNA", "penyakit" => "Penyakit Rumput"],

  // ===== Potyviridae =====
  ["nama" => "Potato Virus Y", "famili" => "Potyviridae", "materi" => "RNA", "penyakit" => "Penyakit Kentang"],
  ["nama" => "Tobacco Etch Virus", "famili" => "Potyviridae", "materi" => "RNA", "penyakit" => "Penyakit Tembakau"],
  ["nama" => "Plum Pox Virus", "famili" => "Potyviridae", "materi" => "RNA", "penyakit" => "Penyakit Plum"],
  ["nama" => "Soybean Mosaic Virus", "famili" => "Potyviridae", "materi" => "RNA", "penyakit" => "Penyakit Kedelai"],

  // ===== Luteoviridae =====
  ["nama" => "Barley Yellow Dwarf Virus", "famili" => "Luteoviridae", "materi" => "RNA", "penyakit" => "Penyakit Barley"],
  ["nama" => "Potato Leafroll Virus", "famili" => "Luteoviridae", "materi" => "RNA", "penyakit" => "Penyakit Kentang"],

  // ==================== BACTERIOPHAGE ====================
  ["nama" => "Bacteriophage T4", "famili" => "Myoviridae", "materi" => "DNA", "penyakit" => "Infeksi Bakteri E. coli"],
  ["nama" => "Bacteriophage T7", "famili" => "Podoviridae", "materi" => "DNA", "penyakit" => "Infeksi Bakteri E. coli"],
  ["nama" => "Bacteriophage Lambda", "famili" => "Siphoviridae", "materi" => "DNA", "penyakit" => "Infeksi Bakteri E. coli"],
  ["nama" => "Bacteriophage M13", "famili" => "Inoviridae", "materi" => "DNA", "penyakit" => "Infeksi Bakteri E. coli"],
  ["nama" => "Bacteriophage MS2", "famili" => "Leviviridae", "materi" => "RNA", "penyakit" => "Infeksi Bakteri E. coli"],
  ["nama" => "Bacteriophage Phi X 174", "famili" => "Microviridae", "materi" => "DNA", "penyakit" => "Infeksi Bakteri E. coli"],
  ["nama" => "Bacteriophage P1", "famili" => "Myoviridae", "materi" => "DNA", "penyakit" => "Infeksi Bakteri E. coli"],
  ["nama" => "Bacteriophage P2", "famili" => "Myoviridae", "materi" => "DNA", "penyakit" => "Infeksi Bakteri E. coli"],
  ["nama" => "Bacteriophage Mu", "famili" => "Myoviridae", "materi" => "DNA", "penyakit" => "Infeksi Bakteri E. coli"],
  ["nama" => "Bacteriophage T5", "famili" => "Siphoviridae", "materi" => "DNA", "penyakit" => "Infeksi Bakteri E. coli"],

  // ==================== VIRUS ARKEA ====================
  ["nama" => "Sulfolobus Spindle-shaped Virus 1", "famili" => "Fuselloviridae", "materi" => "DNA", "penyakit" => "Infeksi Arkea"],
  ["nama" => "Acidianus Filamentous Virus 1", "famili" => "Lipothrixviridae", "materi" => "DNA", "penyakit" => "Infeksi Arkea"],
  ["nama" => "Pyrobaculum Spherical Virus", "famili" => "Globuloviridae", "materi" => "DNA", "penyakit" => "Infeksi Arkea"],
  ["nama" => "Halovirus", "famili" => "Haloviridae", "materi" => "DNA", "penyakit" => "Infeksi Arkea"],

  // ==================== PRION (BUKAN VIRUS, TAPI SERING DIBAHAS BERSAMA) ====================
  ["nama" => "Prion Protein (PrPSc)", "famili" => "Tidak Ada", "materi" => "Protein", "penyakit" => "Creutzfeldt-Jakob Disease"],
  ["nama" => "Prion Bovine Spongiform Encephalopathy", "famili" => "Tidak Ada", "materi" => "Protein", "penyakit" => "BSE"],
  ["nama" => "Prion Scrapie", "famili" => "Tidak Ada", "materi" => "Protein", "penyakit" => "Scrapie"],
  ["nama" => "Prion Kuru", "famili" => "Tidak Ada", "materi" => "Protein", "penyakit" => "Kuru"],
  ["nama" => "Prion Fatal Familial Insomnia", "famili" => "Tidak Ada", "materi" => "Protein", "penyakit" => "FFI"],
  ["nama" => "Prion Gerstmann-Sträussler-Scheinker", "famili" => "Tidak Ada", "materi" => "Protein", "penyakit" => "GSS"],
  ["nama" => "Prion Chronic Wasting Disease", "famili" => "Tidak Ada", "materi" => "Protein", "penyakit" => "CWD"],

  // ==================== VIROID ====================
  ["nama" => "Potato Spindle Tuber Viroid", "famili" => "Pospiviroidae", "materi" => "RNA", "penyakit" => "Penyakit Kentang"],
  ["nama" => "Coconut Cadang-Cadang Viroid", "famili" => "Pospiviroidae", "materi" => "RNA", "penyakit" => "Penyakit Kelapa"],
  ["nama" => "Avocado Sunblotch Viroid", "famili" => "Avsunviroidae", "materi" => "RNA", "penyakit" => "Penyakit Alpukat"],
  ["nama" => "Peach Latent Mosaic Viroid", "famili" => "Avsunviroidae", "materi" => "RNA", "penyakit" => "Penyakit Persik"],
  ["nama" => "Hop Stunt Viroid", "famili" => "Pospiviroidae", "materi" => "RNA", "penyakit" => "Penyakit Hop"],
  ["nama" => "Chrysanthemum Stunt Viroid", "famili" => "Pospiviroidae", "materi" => "RNA", "penyakit" => "Penyakit Krisan"],
  ["nama" => "Citrus Exocortis Viroid", "famili" => "Pospiviroidae", "materi" => "RNA", "penyakit" => "Penyakit Jeruk"],
  ["nama" => "Tomato Plant Macho Viroid", "famili" => "Pospiviroidae", "materi" => "RNA", "penyakit" => "Penyakit Tomat"]
];

?>